### ISSUE TITLE
JSONWP session handling?

### ISSUE THREAD

**Issue by jlipps** [facebook/WebDriverAgent#1]
Hi @mmmulani, @shs96c et al! Thanks for this. I'm starting to play around with it a bit. Having trouble starting a session:

```
~/C/l/webdriveragent git:master ❯❯❯ curl -X POST http://localhost:8100/wd/hub/session -d '{"desiredCapabilities": {"app": "com.apple.mobilesafari"}}'
{
  "value" : "Unhandled endpoint: \/wd\/hub\/session -- http:\/\/localhost:8100\/ with arguments {\n    desiredCapabilities =     {\n        app = \"com.apple.mobilesafari\";\n    };\n}",
  "status" : 1
}%
```

I can get the details for an imaginary session that doesn't exist:

```
~/C/l/webdriveragent git:master ❯❯❯ curl http://localhost:8100/session/foo
{
  "value" : {
    "CFBundleVersion" : "50",
    "device" : "iphone",
    "CFBundleIdentifier" : "com.apple.springboard",
    "sdkVersion" : "8.4",
    "browserName" : "SpringBoard"
  },
  "status" : 0
}%
```

I can even delete this session:

```
~/C/l/webdriveragent git:master ❮❮❮ curl -X DELETE http://localhost:8100/session/foo
{
  "value" : "",
  "status" : 0
}%
```

I can, apparently, get buttons!

```
~/C/l/webdriveragent git:master ❯❯❯ curl -X POST http://localhost:8100/session/foo/element -d '{"using": "class name", "value": "UIAButton"}'
{
  "value" : {
    "ELEMENT" : 4,
    "type" : "UIAButton"
  },
  "status" : 0
}%
```

But I can neither click it nor retrieve its text.

Just wondering if I'm missing something or if these endpoints haven't been implemented yet.

**Comment by mmmulani** [comment]
so WebDriverAgent doesn't really have an idea of a session. Because it lives in the Simulator, the "session" needs to be created by something else and then WDA inserted (that's what we use FBSimulatorControl for). You could also use simctl instead

for that reason, WDA responds to any sessionID

the last command should have worked though, let's try looking at it sometime today

**Comment by jlipps** [comment]
great, want to find a place to hack on it after lunch?

**Comment by mmmulani** [comment]
yea sounds good to me :)

**Comment by j0tunn** [comment]
Hey guys. I see you've implemented session support and some JSONWP methods. And what about other methods? Like `/session/:sessionId/url`, `/session/:sessionId/execute`, or [other](https://code.google.com/p/selenium/wiki/JsonWireProtocol)

I'm trying to launch unit tests for client JS in Mobile Safari using [karma](https://github.com/karma-runner/karma) and [wd](https://github.com/admc/wd) but I'm getting `Unhandled endpoint` error for the `/session/:sessionId/url` request. Is it possible at all right now?

**Comment by lawrencelomax** [comment]
@j0tunn I only implemented a few of the session endpoints. It looks like there are a [bunch more that need implementing](https://w3c.github.io/webdriver/webdriver-spec.html#list-of-endpoints), but I haven't gotten round to implementing them yet, we should probably have a task to track them.

**Comment by j0tunn** [comment]
@lawrencelomax What do you mean? Bunch of tasks for each method?

**Comment by marekcirkos** [comment]
@j0tunn If you are missing any endpoints you can either create PR for it or create an issue. Doesn't really matter if as one on grouped.
