### ISSUE TITLE
tap/:reference not respected

### ISSUE THREAD

**Issue by jaredly** [facebook/WebDriverAgent#10]
The tap endpoint [accepts a `reference` argument](https://github.com/facebook/WebDriverAgent/blob/c6c4ebdf664731145dee4f2738bd35529ee06d8f/WebDriverAgentLib/WebDriverCommands/FBElementCommands.m#L35), but does nothing with it. I assume the idea is to have that be an element id, and to tap relative to that.

**Comment by mmmulani** [comment]
yea we copied the behaviour from ios-driver https://github.com/ios-driver/ios-driver/search?utf8=%E2%9C%93&q=TARGET_TAP which also does nothing with it. I'm open to that behaviour though, can you make a PR?

**Comment by jaredly** [comment]
Oh interesting, I hadn't seen ios-driver. How is WebDriverAgent different/better?

**Comment by mmmulani** [comment]
we used to maintain ios-driver but it's basically deprecated now.

ios-driver is much slower, it uses a run loop, in an UIAutomation.js
script, made of curl whereas WebDriverAgent runs in the simulator natively.
when combined with FBSimulatorControl, you have way more insight into the
startup path and where it fails (whereas with ios-driver you only get
errors from instruments that are pretty opaque)
