### ISSUE TITLE
swipe or dragfromtoforduration takes too much time

### ISSUE THREAD

**Issue by ZhaoxuepingSwag** [facebook/WebDriverAgent#1023]
hi,
I was using the newest wda to control iphone real device.
xcode version9.3
iPhone 6s, iOS 11.2.6
Launched wda by xcode and control command was send out by my python client.
`data = dict(fromX=x1, fromY=y1, toX=x2, toY=y2, duration=duration)
  self.http.post('/wda/dragfromtoforduration', data=data)`
and for example swipe from left to right takes about 5 seconds. Is this time reasonable or is there anything wrong?
Here is the xcode log of one single swipe anction:

> t =  1431.73s Find the Application "com.apple.springboard" 0x10561bd50
    t =  1431.73s     Snapshot accessibility hierarchy for app with pid 56
    t =  1431.95s Snapshot accessibility hierarchy for app with pid 56
    t =  1432.05s Snapshot accessibility hierarchy for app with pid 56
    t =  1432.18s Find the Window
    t =  1432.18s     Snapshot accessibility hierarchy for app with pid 56
    t =  1432.33s Find the Window
    t =  1432.33s     Snapshot accessibility hierarchy for app with pid 56
    t =  1432.48s Snapshot accessibility hierarchy for app with pid 56
    t =  1432.60s Find the Window
    t =  1432.60s     Snapshot accessibility hierarchy for app with pid 56
    t =  1432.74s Find the Window
    t =  1432.74s     Snapshot accessibility hierarchy for app with pid 56
    t =  1432.92s Press and drag from Window[0.00, 0.00] -> (0.0, 333.0) to Window[0.00, 0.00] -> (375.0, 333.0)
    t =  1432.92s     Wait for com.apple.springboard to idle
    t =  1432.94s     Find the Window
    t =  1432.94s         Snapshot accessibility hierarchy for app with pid 56
    t =  1433.18s     Synthesize event
    t =  1433.21s         Find the Window
    t =  1433.21s             Snapshot accessibility hierarchy for app with pid 56
    t =  1433.38s         Find the Window
    t =  1433.39s             Snapshot accessibility hierarchy for app with pid 56
    t =  1435.08s     Wait for com.apple.springboard to idle

**Comment by wsndy163** [comment]
https://github.com/wsndy163/WebDriverAgent
修复swipe引起的列表卡顿问题

**Comment by brian-leidos** [comment]
Did you solve this? How?
