### ISSUE TITLE
Appium server 1.9.1, Mac OS 10.14, Xcode 10, iOS (real device) 12.0 - WDA hangs after installation on real device

### ISSUE THREAD

**Issue by cdnyoung** [facebook/WebDriverAgent#1026]
I recently updated Appium from 1.8.1 to 1.9.1. along with updates to Xcode and the Mac OS (since I was receiving errors about the xcode version when using Appium 1.8.1). It all looks correctly updated and I was able to successfully build the WDA onto our real devices (using iOS 12.0), but things appear to hang when trying to run our test suites (we run test suites through bamboo). 

It's having an effect on all our real devices and I'm new to managing appium and these devices, so I'm unsure as to what could be causing this. The Webdriver agent is successfully installed on the device, and it launches the app, but then just hangs there sending requests without interacting with the app. 

I let the test suites run for over four hours before I killed them, and I'm hoping someone can help point me in the right direction. Here is one of the appium logs. Please let me know what additional information might be needed for this. Thanks!

`[Appium] Welcome to Appium v1.9.1
[Appium] Non-default server args:
[Appium]   port: 4742
[Appium]   nodeconfig: ./nodes/radagastiphone7.json
[Appium]   tmpDir: /tmp/appium/radagastiphone7
[debug] [Appium] Starting auto register thread for grid. Will try to register every 5000 ms.
[Appium] Appium REST http interface listener started on 0.0.0.0:4742
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 5 ms - 151
[HTTP] 
[debug] [Appium] Appium successfully registered with the grid on http://xxxxx:4450
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/user/appium/appLocation/app.ipa","automationName":"XCUITEST","browserName":"Radagast iPhone7","deviceName":"Radagast iPhone7","platform":"MAC","platformName":"ios","platformVersion":"12.0","server:CONFIG_UUID":"serverUDID","udid":"UDID","wdaLocalPort":8110,"xcodeOrgId":"ORGID","xcodeSigningId":"iPhone Developer"},"capabilities":{"desiredCapabilities":{"app":"/Users/user/appium/appLocation/app.ipa","automationName":"XCUITEST","browserName":"Radagast iPhone7","deviceName":"Radagast iPhone7","platform":"MAC","platformName":"ios","platformVersion":"12.0","server:CONFIG_UUID":"serverUDID","udid":"UDID","wdaLocalPort":8110,"xcodeOrgId":"ORGID","xcodeSigningId":"iPhone Developer"},"firstMatch":[{"browserName":"Radagast iP
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"/Users/user/appium/appLocation/app.ipa","automationName":"XCUITEST","browserName":"Radagast iPhone7","deviceName":"Radagast iPhone7","platform":"MAC","platformName":"ios","platformVersion":"12.0","server:CONFIG_UUID":"serverUDID","udid":"UDID","wdaLocalPort":8110,"xcodeOrgId":"ORGID","xcodeSigningId":"iPhone Developer"},null,{"desiredCapabilities":{"app":"/Users/user/appium/appLocation/app.ipa","automationName":"XCUITEST","browserName":"Radagast iPhone7","deviceName":"Radagast iPhone7","platform":"MAC","platformName":"ios","platformVersion":"12.0","server:CONFIG_UUID":"serverUDID","udid":"UDID","wdaLocalPort":8110,"xcodeOrgId":"OrgID","xcodeSigningId":"iPhone Developer"},"firstMatch":[{"browserName":"Radagast iPhone7","platformName":"ios","server:CONFIG_UUID":"...
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1540826880675 (10:28:00 GMT-0500 (CDT))
[Appium] Could not parse W3C capabilities: 'deviceName' can't be blank
[Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[BaseDriver] The capabilities ["app","automationName","deviceName","platform","platformVersion","udid","wdaLocalPort","xcodeOrgId","xcodeSigningId"] are not standard capabilities and should have an extension prefix
[Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   app: /Users/user/appium/appLocation/app.ipa
[Appium]   automationName: XCUITEST
[Appium]   deviceName: Radagast iPhone7
[Appium]   platform: MAC
[Appium]   platformVersion: 12.0
[Appium]   udid: UDID
[Appium]   wdaLocalPort: 8110
[Appium]   xcodeOrgId: OrgId
[Appium]   xcodeSigningId: iPhone Developer
[Appium]   browserName: Radagast iPhone7
[Appium]   platformName: ios
[Appium]   server:CONFIG_UUID: serverUDID
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"appium:app... and MJSONWP desired capabilities {"app":"/Users/user/appium... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"appium:app...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: server:CONFIG_UUID, platform.
[XCUITest] The capabilities should generally not include both an 'app' and a 'browserName'
[BaseDriver] Session created with session id: b10a4239-faa4-49ec-bbb5-506ba0770fdb
[debug] [XCUITest] Current user: 'svctest'
[debug] [XCUITest] Xcode version set to '10.0' (tools v10.0.0.0.1.1535735448)
[debug] [XCUITest] iOS SDK Version set to '12.0'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1540826880845 (10:28:00 GMT-0500 (CDT))
[debug] [XCUITest] Available devices: deviceList
[debug] [XCUITest] Creating iDevice object with udid 'UDID'
[XCUITest] Determining device to run tests on: udid: 'UDID', real device: true
[BaseDriver] Using local app '/Users/user/appium/appLocation/app.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[BaseDriver] Unzipping local app '/var/folders/1l/f0sprm8j02q2wjc91svkcdn46dr36v/T/2018929-89594-1ufr9n5.9fbh/appium-app.zip'...
[debug] [BaseDriver] Unzipping /var/folders/1l/f0sprm8j02q2wjc91svkcdn46dr36v/T/2018929-89594-1ufr9n5.9fbh/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/1l/f0sprm8j02q2wjc91svkcdn46dr36v/T/2018929-89594-1ufr9n5.9fbh/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/1l/f0sprm8j02q2wjc91svkcdn46dr36v/T/2018929-89594-1ufr9n5.9fbh/Payload/APP.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1540826882544 (10:28:02 GMT-0500 (CDT))
[debug] [XCUITest] Checking whether app '/var/folders/1l/f0sprm8j02q2wjc91svkcdn46dr36v/T/2018929-89594-1ufr9n5.9fbh/Payload/APP.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/1l/f0sprm8j02q2wjc91svkcdn46dr36v/T/2018929-89594-1ufr9n5.9fbh/Payload/APP.app': 'com.ourfamilywizard.ofwinternal'
[debug] [BaseDriver] Event 'resetStarted' logged at 1540826882556 (10:28:02 GMT-0500 (CDT))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1540826882556 (10:28:02 GMT-0500 (CDT))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [XCUITest] Crash reports root '.../CrashReporter/MobileDevice/Radagast iPhone7' does not exist. Got nothing to gather.
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1540826882750 (10:28:02 GMT-0500 (CDT))
[XCUITest] Setting up real device
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] [XCUITest] Reset requested. Removing app with id 'com.appID' from the device
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[debug] [XCUITest] Installing '/var/folders/1l/f0sprm8j02q2wjc91svkcdn46dr36v/T/2018929-89594-1ufr9n5.9fbh/Payload/APP.app' on device with UUID '88153e130154876994e7e3e5b3049a512e1d419f'...
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1540826889658 (10:28:09 GMT-0500 (CDT))
[XCUITest] Using WDA path: '/Users/user/appium/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/user/appium/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8110 have been found
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8110/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.0.1\",\n      \"sdkVersion\" : \"12.0\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.0.1\",\n      \"ip\" : \"ipAddress\"\n    },\n    \"build\" : {\n      \"time\" : \"Oct 29 2018 10:26:53\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"166C4B0F-2E15-4F86-80F5-3679E1347628\",\n  \"status\" : 0\n}"
[debug] [XCUITest] Upgrade timestamp of the currently bundled WDA: 1540587088700
[debug] [XCUITest] Upgrade timestamp of the WDA on the device: undefined
[XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8110/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8110 if this is an undesired behavior.
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1540826889776 (10:28:09 GMT-0500 (CDT))
[XCUITest] Using provided WebdriverAgent at 'http://localhost:8110/'
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1540826889777 (10:28:09 GMT-0500 (CDT))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Matched '/status' to command name 'getStatus'
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8110/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"12.0.1\",\n      \"sdkVersion\" : \"12.0\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"12.0.1\",\n      \"ip\" : \"ipAddress"\n    },\n    \"build\" : {\n      \"time\" : \"Oct 29 2018 10:26:53\",\n      \"productBundleIdentifier\" : \"com.facebook.WebDriverAgentRunner\"\n    }\n  },\n  \"sessionId\" : \"166C4B0F-2E15-4F86-80F5-3679E1347628\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Matched '/session' to command name 'createSession'
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8110/session] with body: {"desiredCapabilities":{"bundleId":"com.bundleID","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"6678853B-E42E-42EC-AF41-D3AB44C64898","capabilities":{"device":"iphone","browserName":"APPName","sdkVersion":"12.0.1","CFBundleIdentifier":"com.bundleID"}},"sessionId":"6678853B-E42E-42EC-AF41-D3AB44C64898","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1540826892647 (10:28:12 GMT-0500 (CDT))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1540826892647 (10:28:12 GMT-0500 (CDT))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1540826892647 (10:28:12 GMT-0500 (CDT))
[Appium] New XCUITestDriver session created successfully, session b10a4239-faa4-49ec-bbb5-506ba0770fdb added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1540826892649 (10:28:12 GMT-0500 (CDT))
[debug] [W3C] Cached the protocol value 'W3C' for the new session b10a4239-faa4-49ec-bbb5-506ba0770fdb
[debug] [W3C] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"Radagast iPhone7","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"ios","server:CONFIG_UUID":"serverUDID","app":"/Users/user/appium/appLocation/app.ipa","automationName":"XCUITEST","deviceName":"Radagast iPhone7","platformVersion":"12.0","udid":"UDID","wdaLocalPort":8110,"xcodeOrgId":"OrgId","xcodeSigningId":"iPhone Developer"}}
[HTTP] <-- POST /wd/hub/session 200 11976 ms - 688
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 2 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session b10a4239-faa4-49ec-bbb5-506ba0770fdb from our master session list
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1","git-sha":"f9ee7d068e14f10729f88ebd85db802c2e8ac21a","built":"2018-09-20T18:14:29Z"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 151
[HTTP] 

etc etc etc
`

**Comment by JasWoolieX** [comment]
I also faced the issue when I upgraded to Appium 1.9.1 with Xcode 10. In my case scenario worked fine if ran individually but however in suite the test were failing because of error "Unable to install Web Driver agent"
The solution for now was to revert back to Appium - 1.8.2@beta and it has been working fine now.
However still facing issue with Appium Desktop @ 1.9.1

**Comment by cdnyoung** [comment]
OOK, thank you. I'll try the beta.. What iOS version were you running on? It seems to be an issue with iOS 12+.

**Comment by cdnyoung** [comment]
Using the 1.8.2beta allowed me to run the tests on a real iOS device! Thank you @JasWoolieX !
