### ISSUE TITLE
Error during Webdriver installation

### ISSUE THREAD

**Issue by ngbrito** [facebook/WebDriverAgent#1029]
Hello,

when I try to execute the command  "sh ./Scripts/build-socket.sh" I get the following

uilding Inspector for socket...

> web-driver-inspector@1.0.0 build /Users/bnatali/Documents/git/WebDriverAgent/Inspector
> webpack --progress --colors

sh: webpack: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! web-driver-inspector@1.0.0 build: `webpack --progress --colors`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the web-driver-inspector@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-11-14T16_33_33_130Z-debug.log
Done

Can you help?

Tx

**Comment by estefafdez** [comment]
Hey @ngbrito , 
I fix all the problem I had with the instalation of WDA using:
`cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
mkdir -p Resources/WebDriverAgent.bundle
./Scripts/bootstrap.sh -d`

Try this one and let me know ;) good luck!
