### ISSUE TITLE
WDA was installed and showing ServerURLHere->http://10.20.26.29:8100 but unable to launch on device

### ISSUE THREAD

**Issue by vecadithya** [facebook/WebDriverAgent#1035]
Hi Team,

I am getting weird issue while installing WDA on the following envirorment.
Xcode version : 10.1
iOS version: 12.1
Appium version: 1.9.1

I have followed all necessary steps to configure WDA in my xcode and running the following command from terminal
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=4986e8e5d7fe75b806e3549c700242a3e9446d34' test

WDA was successfully installed on my device but it was not launching on device.

Log from terminal is :

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/v4/bbyrl3nn2cd6dl533wfv4lb80000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/c44d24878fd41c2717818d1e48f9b06b/4986e8e5d7fe75b806e3549c700242a3e9446d34/ManifestCache.plist
2018-11-27 15:02:34.228272+0530 WebDriverAgentRunner-Runner[297:9586] +[CATransaction synchronize] called within transaction
2018-11-27 15:02:34.243758+0530 WebDriverAgentRunner-Runner[297:9586] Running tests...
**objc[297]: Class GCDAsyncSocketPreBuffer is implemented in both /private/var/containers/Bundle/Application/21882BED-56E3-4B9E-9789-C850C74C8607/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x104f58578) and /private/var/containers/Bundle/Application/21882BED-56E3-4B9E-9789-C850C74C8607/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x104ec5330). One of the two will be used. Which one is undefined.
objc[297]: Class GCDAsyncReadPacket is implemented in both /private/var/containers/Bundle/Application/21882BED-56E3-4B9E-9789-C850C74C8607/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x104f585c8) and /private/var/containers/Bundle/Application/21882BED-56E3-4B9E-9789-C850C74C8607/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x104ec5380). One of the two will be used. Which one is undefined.
objc[297]: Class GCDAsyncWritePacket is implemented in both /private/var/containers/Bundle/Application/21882BED-56E3-4B9E-9789-C850C74C8607/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x104f58618) and /private/var/containers/Bundle/Application/21882BED-56E3-4B9E-9789-C850C74C8607/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x104ec53d0). One of the two will be used. Which one is undefined.
objc[297]: Class GCDAsyncSpecialPacket is implemented in both /private/var/containers/Bundle/Application/21882BED-56E3-4B9E-9789-C850C74C8607/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x104f58668) and /private/var/containers/Bundle/Application/21882BED-56E3-4B9E-9789-C850C74C8607/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x104ec5420). One of the two will be used. Which one is undefined.
objc[297]: Class GCDAsyncSocket is implemented in both /private/var/containers/Bundle/Application/21882BED-56E3-4B9E-9789-C850C74C8607/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/CocoaAsyncSocket.framework/CocoaAsyncSocket (0x104f586b8) and /private/var/containers/Bundle/Application/21882BED-56E3-4B9E-9789-C850C74C8607/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer (0x104ec5470). One of the two will be used. Which one is undefined.**
Test Suite 'All tests' started at 2018-11-27 15:02:34.908
Test Suite 'WebDriverAgentRunner.xctest' started at 2018-11-27 15:02:34.910
Test Suite 'UITestingUITests' started at 2018-11-27 15:02:34.911
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2018-11-27 15:02:34.926
    t =     0.00s Set Up
2018-11-27 15:02:34.936770+0530 WebDriverAgentRunner-Runner[297:9586] Built at Nov 27 2018 14:40:24
2018-11-27 15:02:34.971360+0530 WebDriverAgentRunner-Runner[297:9586] ServerURLHere->http://10.20.26.29:8100<-ServerURLHere
2018-11-27 15:02:34.971559+0530 WebDriverAgentRunner-Runner[297:9586] Using singleton test manager

**Comment by loveharuhi** [comment]
need 'iproxy 8100 8100' then visit 'http://localhost:8100'

**Comment by khc20041** [comment]
Hi loveharuhi,
Can you please elaborate the answer as i am seeing this issue only after upgrading to Xcode 10. what is mean by need iproxy 8100 8100 ?

**Comment by khc20041** [comment]
I have installed iproxy and run the following command
**iproxy 8100 8100 <device_udid>**

The response is, **waiting for connection**

**Comment by loveharuhi** [comment]
> I have installed iproxy and run the following command
> **iproxy 8100 8100 <device_udid>**
> 
> The response is, **waiting for connection**

WDA's HTTPServer cannot be accessed by external devices
need iproxy 
sorry for my poor English

**Comment by Ritikawesome** [comment]
Hi Can someone help me I am getting same issue

**Comment by gurender1983** [comment]
Hi Can someone help me I am getting same issue

**Comment by 13409795771** [comment]
when my phone is ios10 , it work well , and http://192.168.xx.xx:8100 can visit, but when i change phone (ios 11) , i have same issue。

Can someone help me I am getting same issue in ios11 , my environment is following
1. macOS High Sierra 10.13.4
2. xcode 9.3.1
3. ios 11.1.1
