### ISSUE TITLE
./Scripts/bootstrap.sh Error: Command "bootstrap" does not exist.

### ISSUE THREAD

**Issue by liyinchigithub** [facebook/WebDriverAgent#1058]
![image](https://user-images.githubusercontent.com/19643260/50763203-1bb38180-12aa-11e9-9358-ade4d0cda5ce.png)

![image](https://user-images.githubusercontent.com/19643260/50763185-11918300-12aa-11e9-80f9-917544198d21.png)

please help me

**Comment by marekcirkos** [comment]
Is this Appium's checkout of WDA or this repo?

**Comment by liyinchigithub** [comment]
@marekcirkos 
Thank you for your message

I solved the problem

Uninstall Carthage

Reshipment Carthage
