### ISSUE TITLE
Can wda support Tangram-iOS UI framework?

### ISSUE THREAD

**Issue by andrewleo** [facebook/WebDriverAgent#1068]
[Tangram-iOS](https://github.com/alibaba/Tangram-iOS):alibaba UI framework, can wda support it ? or what should I do

**Comment by marekcirkos** [comment]
WDA depends on XCUITest, so if you cover accessibility of elements, you are good to go. :)

**Comment by andrewleo** [comment]
I am absolutely new to Tangram-iOS, what does "cover accessibility of elements" mean? Can you give some suggestions to support Tangram-iOS?
Much thanks!
