### ISSUE TITLE
Could not find any available simulators for tvOS

### ISSUE THREAD

**Issue by Johnny987** [facebook/WebDriverAgent#1113]
I'm running Scripts/bootstrap.sh, but always ended with error: Could not find any available simulators for tvOS, 
`Fetching dependencies
*** Checking out YYCache at "1.1.0"
*** Checking out RoutingHTTPServer at "v1.0.2"
*** Checking out CocoaAsyncSocket at "7.6.3"
*** xcodebuild output can be found in /var/folders/k6/6wv0khx96jd2j2z_tvtr575c0000gn/T/carthage-xcodebuild.kxCRnR.log
*** Downloading CocoaAsyncSocket.framework binary at "Version 7.6.3"
*** Building scheme "RoutingHTTPServer tvOS" in RoutingHTTPServer.xcodeproj
Could not find any available simulators for tvOS`
I don't know why webDriverAgent project specifically looking for the tvOS simulator?  However I tried installed one but still has the same issue.
![image](https://user-images.githubusercontent.com/15043148/57274222-243b8d80-70cd-11e9-9350-324e2ac987b0.png)

**Comment by jakajacky** [comment]
Hi How did you solve this problem?

**Comment by Stylar66** [comment]
Having the same issue. How was the problem solved.

**Comment by KazuCocoa** [comment]
If it is Appium related, have you upgrade your carthage to the latest one as the release note?
or creating a tvOS instance in your simulator list. (because carthage requires it)
