### ISSUE TITLE
Recommended bindings?

### ISSUE THREAD

**Issue by bootstraponline** [facebook/WebDriverAgent#115]
What WebDriver bindings does Facebook use with WebDriverAgent?

**Comment by Jonahss** [comment]
We're working to have WebDriverAgent fully support the webdriver spec, so all the usual bindings will work. If you notice any discrepancies please create an issue.

**Comment by bootstraponline** [comment]
Swift apparently doesn't have bindings. Objective C [seems broken](https://github.com/appium/selenium-objective-c/issues/73). Standard WebDriver bindings don't work for mobile. I guess the only ones expected to work would be appium's bindings.

Still interested in finding out what Facebook is using since that might be the path of least resistance.

**Comment by Jonahss** [comment]
I think what facebook is using doesnt adhere exactly to the mobile json
wire protocol spec, which is why we still need to work to get it there.

Appium bindings are good.

There's also this, under construction:
https://github.com/appium/selenium-swift

**Comment by bootstraponline** [comment]
I know Facebook's binding isn't spec compliant but I'm assuming it's actively updated to track WebDriverAgent. 

`selenium-swift` can't make http requests. New bindings are a lot of work so I don't expect that to be completed.

**Comment by Jonahss** [comment]
New bindings aren't a lot of work ;)

**Comment by bootstraponline** [comment]
I think we both know from appium that a ton of work goes into bindings (java/ruby) and that's with the benefit of the upstream bindings already existing. Testing them is also painful so most projects like WebDriverAgent don't even bother with E2E tests.

**Comment by Jonahss** [comment]
Selenium bindings are only a lot of work when one tries to add a ton of
features, or has to integrate with a rigid upstream project.

Otherwise you're just looking at a simple html api wrapper, and the
protocol is completely documented.

**Comment by bootstraponline** [comment]
It's a lot of work because:

- No mobile automation tech is fully standards compliant 
- MJSONWP spec is a work in progress and isn't sufficient for production automation
- Ever increasing amount of driver specific extensions
- Android/iOS in CI for testing is incredibly painful so there's no way to check PRs don't cause issues
- Moving target as features are added/removed
- Very few companies are willing to invest dev resources working on standards based automation so it's mostly up to volunteers

If there was a team paid to maintain the bindings then yeah it'd be easy. Instead there's a collection of bindings in various states of completeness often with no one actively working on them.

**Comment by marekcirkos** [comment]
In a nutshell, we use our own binding with WDA, same we used with ios-driver. As @Jonahss I don't think developing new binding is a lot of work. If you don't want to do it, you got Appium ;)

**Comment by bootstraponline** [comment]
It'd be cool if Facebook would consider open sourcing their bindings as the community ones leave much to be desired.

**Comment by Kitty2014** [comment]
@bootstraponline @marekcirkos I'm glad you guys do this integration.New era for iOS automation.
