### ISSUE TITLE
WebDriver Tests on Real Devices?

### ISSUE THREAD

**Issue by progressnerd** [facebook/WebDriverAgent#116]
I think I've fundamentally misunderstood something about what XCTWebDriverAgent is for. Is it possible to run a WebDriver test on a real device using XCTWebDriverAgent? I'm somewhat confused that an invocation of /session requires a bundle ID and an app, because I'm just expecting to launch Safari on the device before running a WebDriver test. If I do provide my own app, what exactly does XCTWebDriverAgent allow me to do with it that I can't already do with xcodebuild? The docs don't really say. Thanks for your help!

**Comment by Jonahss** [comment]
Yes it works on real devices.

There is a fake app called the TestRunner. It's a blank app that does nothing.
We have a set of XCUITests, tests that run to test our fake app.

The test suite is only a single test. That test runs a server from the device/simulator and that server adheres to the JSON Wire Protocol, the same protocol used by Selenium and Appium. When you send a the createSession command, the test loads up the app you supplied and now you can run more test commands on that.

The whole point is to get xcodebuild to start the XCUITest process, then we run everything from our server.

**Comment by progressnerd** [comment]
To clarify, are you using the WebDriver protocol to drive mobile safari or drive your app?

**Comment by Jonahss** [comment]
oh right right

ok so mobile safari is different.

The appium xcuitest driver just launches safari on the simulator, then appium connects to the remote debugger port that safari has. It's the same way that the safari developer tools connect to the browser.

So appium-xcuitest-driver doesn't even use WebDriverAgent for mobile tests.

On a real device, we can't start Safari ourselves, so we use an app called SafariLauncher. Webdriveragent starts SafariLauncher, and SafariLauncher starts safari. Then we connect to the safari remote debugger and automate from there.

**Comment by progressnerd** [comment]
Thanks, Jonah. Sorry for all the questions. Once you launch Safari and connect to the remote debugger, are you just using raw devtools commands from there, or are you using an actual WebDriver implementation of some kind? I'm asking, because we're currently using ios-driver to drive mobile safari on real devices, but it's pretty buggy, and I was hoping that WebDriverAgent would provide a more solid implementation of the WebDriver protocol to drive mobile safari on real devices.

**Comment by Jonahss** [comment]
So, we're using the same webdriver implementation, where we turn your webdriver commands into devtools commands for the Safari Debug port.

Have you tried Appium version 1.5? It has a much much imrorved flow, and is less buggy.

Both appium-ios-driver and appium-xcuitest-driver use the same code for sending instructions to safari, the only difference is how Safari is launched. So some bugs might still be present.

That said, appium 1.5 is much less error-prone that previous versions of appium.

**Comment by progressnerd** [comment]
Ok, so you're using XCTWebDriverAgent for the sole purpose of launching an app on a physical device. That app happens to launch Safari, after which, you're just using Appium. If that is true, I may just use idevicedebug (from libimobiledevice) to launch Safari, and leave XCTWebDriverAgent out of the mix altogether.

**Comment by marekcirkos** [comment]
@Jonahss You should be able to launch Safari with XCTWebDriverAgent just by using bundleID
@progressnerd XCTWebDriverAgent is for launching an app and automating it (in a nutshell ;0).

**Comment by Jonahss** [comment]
@marekcirkos non developer-signed apps can be run on real devices?

**Comment by marekcirkos** [comment]
@Jonahss depends what you mean. 
You can't run unsigned app on device, but you can run system app (which is not developer signed app).

**Comment by marekcirkos** [comment]
@Jonahss by system app I mean any application already installed on device. ;)

**Comment by Jonahss** [comment]
Oh I see. I'll have to play with that, sounds really useful.

**Comment by marekcirkos** [comment]
@progressnerd Are you ok to close this issue?
