### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by chris1248** [facebook/WebDriverAgent#118]
I cloned this project to my mac and followed the build instructions exactly. Right after opening xcode I immediately built, and got two build errors (Plus a build warning which I fixed).

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: -  dynamic not specified the following flags are invalid: -ObjC 
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lxml2
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lxml2 is not an object file (not allowed in a library)`

**Comment by chris1248** [comment]
Perhaps something to with KissXML?

**Comment by marekcirkos** [comment]
Hey, I just tried to build ever target and everything is fine. Did you try  to run `pod install` before building?

**Comment by chris1248** [comment]
Yes I ran `pod install`. Where am I supposed to get libxml2? I have a version but using lipo to inspect it, I found it only had code for x86_x64, and i386 architecture. Nothing for targeting IOS.

**Comment by marekcirkos** [comment]
Which target are you building, and what device are you targeting?

**Comment by chris1248** [comment]
I'm not targeting anything specific. I just select project settings on the left and hit build. The only device I'm targeting is ipad 9.2 or ipad 8.4 (But that's just the simulator type).

**Comment by marekcirkos** [comment]
Ok, what application are you building "WebDriverAgent" or "XCUITestRunner"?

**Comment by chris1248** [comment]
WebDriverAgent > ipad 8.4 for instance.
But I have tried all 4 of them, and nothing works. Didn't you read the original post though? It's missing -lxml2 or something.

**Comment by marekcirkos** [comment]
Are you sure you open workspace not project?

**Comment by chris1248** [comment]
Yes, I opened the *.xcworkspace file, not the *.xcodeproj file.

**Comment by bootstraponline** [comment]
The problem was an out of date cocoapods. I updated cocoapods to the latest stable version (0.39) and that resolved the build failure.

**Comment by chris1248** [comment]
Yep, that was it. Thanks!
