### ISSUE TITLE
Support xcode 7.3

### ISSUE THREAD

**Issue by xudafeng** [facebook/WebDriverAgent#123]
We met error like this:

```
/WebDriverAgent/XCTWebDriverAgentLib/Commands/FBCustomCommands.m:41:43: error: implicit conversion increases floating-point precision: 'float' to 'CGFloat' (aka 'double') [-Werror,-Wdouble-promotion]
  CGFloat duration = (requestedDuration ? requestedDuration.floatValue : 3.f);
          ~~~~~~~~                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Now we fixed this error, but could not get any elements instead due to some reason I can not understand.

**Comment by xudafeng** [comment]
@maiergre After ` -Wno-double-promotion` flag added, I can not get elements.

**Comment by marekcirkos** [comment]
Can you elaborate on what are you doing and how are you requesting elements?

**Comment by xudafeng** [comment]
this is my steps:
1. run `xcodebuild -workspace WebDriverAgent.xcworkspace -scheme XCTUITestRunner -destination id='<DEVICE_UDID>' test`
2. Dist app was launched [app package](https://github.com/xudafeng/macaca-test-sample/blob/master/app/ios-app-bootstrap.zip), [source code](https://github.com/xudafeng/ios-app-bootstrap)
3.create session was successed with sessionId, but when `{"using":"xpath","value":"//UIATextField[1]"}` sent to `http://localhost:8100/session/XXXXXXXXXXXXXXXXXXX/elements`, nothing got with `value:[]`. 

![image](https://cloud.githubusercontent.com/assets/1011681/14166643/c6e4e4ee-f747-11e5-9c3d-c42f418fcec3.png)

**Comment by xudafeng** [comment]
@marekcirkos By the way `UIAWebDriverAgent ` is ok, `XCTWebDriverAgent ` has problem.

**Comment by marekcirkos** [comment]
I checked it out and seems there is a bug in 7.3 which causes XCUIApplication not to be resolved properly. By that I mean it will not create 'lastSnapshot' property that we use almost everywhere since it is faster. I created a HACK that fixes this issue (check https://github.com/facebook/WebDriverAgent/tree/resolveIssue branch), but I need to investigate it further to create proper solution.

**Comment by marekcirkos** [comment]
Good news is it fixes other issue I had with inspector when I was attaching to app with PID. I thought Apple changed that on purpose :).

**Comment by xudafeng** [comment]
@marekcirkos Thanks, it's work for me, sit around and wait for the reply.

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/80f14fa9ed8ca88c55a65e0b49d429c46ad3b890
