### ISSUE TITLE
Is it possible to Run UIAWebDriverAgent on real device?

### ISSUE THREAD

**Issue by NSFish** [facebook/WebDriverAgent#153]
### Is it even possible to run UIAWebDriverAgent on real device?
Hello guys, I've been playing with WebDriverAgent for a while. The one base on XCUITest works smooth on both simulators and real devices. But when I try to run the older one that build on top of AccessibilityUtilities.framework and UIAutomation.framework on **real device**,  I ran into some problems. 

The README inside **UIAWebDriverAgent** project dir seems to be the older version of the WebDriverAgent' README, which did't mention much about real device, which make sense since it's just a blank XCUITest.bundle. 
So I'm not sure if this is possible to run UIAWebDriverAgent on real device. If it does, could you shed some light about how you guys manage to do it?  I would be really appreciated :)

The problems I've encountered are descirbed below.

### Problems
First off,  the UIAWebDriverAgent project can't  be linked because the 2 private frameworks mention above are missing.
I managed to find AccessibilityUtilities.framework at 
```powershell
~/Library/Developer/Xcode/iOS DeviceSupport/7.1.2 (11D257)/Symbols/System/Library/PrivateFrameworks/AccessibilityUtilities.framework
~/Library/Developer/Xcode/iOS DeviceSupport/8.3 (12F70)/Symbols/System/Library/PrivateFrameworks/AccessibilityUtilities.framework
~/Library/Developer/Xcode/iOS DeviceSupport/9.0.2 (13A452)/Symbols/System/Library/PrivateFrameworks/AccessibilityUtilities.framework
~/Library/Developer/Xcode/iOS DeviceSupport/9.3.1 (13E238)/Symbols/System/Library/PrivateFrameworks/AccessibilityUtilities.framework
```

The UIAutomation.framework is a bit tricky, I found it at 
```powershell
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/9.3\
```

By manually add two framework search path to the UIAWebDriverAgent project, the app was successfully loaded and ran on my devices, but it keep stuck in 
![UIAWebDriverAgent run failed](http://cl.ly/023q322z1d0N/UIAWebDriverAgent.png)
and the warning in console
```powershell
2016-05-09 15:03:36.947 WebDriverAgent[7652:681225] UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings.
2016-05-09 15:03:36.948 WebDriverAgent[7652:681225] *** Terminating app due to uncaught exception 'kUIAExceptionUIAutomationNotEnabled', reason: 'UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings.'
```

I tried to turn the UIAutomation setting on, the same warning still shows.

**Comment by marekcirkos** [comment]
UIAWebDriverAgent does not work with devices and is deprecated.
