### ISSUE TITLE
Code coverage?

### ISSUE THREAD

**Issue by bootstraponline** [facebook/WebDriverAgent#154]
Is it possible to get code coverage data from WebDriverAgent runs?

**Comment by marekcirkos** [comment]
Not really, WDA just executes commands over HTTP, so it has no way of knowing even which test it is executing.

**Comment by lawrencelomax** [comment]
I think the question is about Test coverage of the WebDriverAgent Framework itself, which can be tested directly by getting coverage data when running Unit & Integration tests over the Framework.

I'm a bit skeptical of the benefit of doing this however, especially at the boundary of `WebDriverAgent` and the Private Frameworks that are called. I could see it being useful in determining that the routing and transport of data works.
