### ISSUE TITLE
Click command does not scroll to element 

### ISSUE THREAD

**Issue by marekcirkos** [facebook/WebDriverAgent#157]
According to [WD spec](http://www.w3.org/TR/webdriver/#dfn-element-click) we should scroll to element before tapping it.

**Comment by marekcirkos** [comment]
This happens, because during scroll element "under" XCUIElement may change and we might end up tapping wrong element. I suspect that this has something to do with cell reusability.

**Comment by upasnapandey** [comment]
Is this issue fixed? I am trying to select a cell within a table, that doesn't show up on the app till we do a scroll. The inspector does show that element though. I pulled the latest master of WebDriverAgent, but it still doesn't work. Thanks.

**Comment by marekcirkos** [comment]
Not yet, but there is simple workaround. I have to explicitly call scrollToVisible beforehand.

**Comment by upasnapandey** [comment]
Could you please tell me how to call scrollToVisible.
I tried something like this.
driver.elementById("text").scrollToVisible()
driver.elementByXPath("//XCUIElementTypeTable[1]/XCUIElementTypeCell[5]").scrollToVisible()
and both did not work.

**Comment by marekcirkos** [comment]
Not sure what client are you using, but WDA has custom endpoint for handling that [here](https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L59). After we resolve Xcode 8 support we plan to make WDA more WD spec compliant. I'll create an issue for that.

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/issues/179

**Comment by marekcirkos** [comment]
Merging to https://github.com/facebook/WebDriverAgent/issues/179

**Comment by phoebusliang** [comment]
@marekcirkos  I found the code [[FBRoute POST:@"/deactivateApp"] respondWithTarget:self action:@selector(handleDeactivateAppCommand:)],

We can deactive the app, can we re-active the app again?

**Comment by marekcirkos** [comment]
It should reactive the application after given duration. Do you deactivate it in landscape mode?

**Comment by phoebusliang** [comment]
Sorry for the misunderstanding. I mean deactivate the app and then call it back by curl command manually without duration time setting or default value.
