### ISSUE TITLE
WebDriverAgentLib umbrella header almost empty?

### ISSUE THREAD

**Issue by bootstraponline** [facebook/WebDriverAgent#177]
[`WebDriverAgentLib.h`](https://github.com/facebook/WebDriverAgent/blob/30bc9e29ce3d034165af4d8dbad185e92b57208c/WebDriverAgentLib/WebDriverAgentLib.h) only has a single WebDriverAgentLib import (for `FBAlert`), is that intentional?

The lib is pretty awesome. Thanks for refactoring out the methods.

**Comment by marekcirkos** [comment]
I am still extracting stuff and writing tests for them ;)
