### ISSUE TITLE
Xcode 8 support

### ISSUE THREAD

**Issue by marekcirkos** [facebook/WebDriverAgent#181]
Project compiles however some integration tests are failing.

- [x] Tapping seems to be broken for accepting and dismissing alerts
- [x] Springboard tests are broken 
- [x] 'fb_isVisible' is broken

**Comment by linkin-xiao** [comment]
Hi,@marekcirkos .
When I try to use xcode 8 to run WDA in ios 10.0，it reminder me as below:

_2016-08-05 14:00:01.555276 XCTRunner[856:224611] [User Defaults] Failed to write value for key AutomationDisableFauxCollectionCells in CFPrefsPlistSource<0x1740f4400> (Domain: com.apple.Accessibility, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null)): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access, switching to read-only_

at the end it return a ServerURL as usual , but the URL return nothing in browser. 
So I want to ask whether the WDA support ios 10.0 now ？ or how can I fix this error ？

Thanks a lot !

**Comment by marekcirkos** [comment]
If you run on simulator:
- try replacing IP with `localhost`
- check your firewall settings, it might be blocking incoming connections

If you run on device:
- make sure device and host are connected to same network
- make sure network is not blocking connections.

**Comment by linkin-xiao** [comment]
@marekcirkos , thank you for replying.
I run on device, and I'm sure I have done the two points you said.
Have you run WebDriverAgent on device ios 10 device successfully ?

**Comment by marekcirkos** [comment]
Just tried latest beta and it works. As crazy as it sounds try rebooting phone and host, sometimes Xcode can get stuck for sum reason only restart helps

**Comment by marekcirkos** [comment]
@linkin-xiao Did you resolve this issue?

**Comment by candialala** [comment]
@marekcirkos I have the same issue.
2016-09-30 14:03:58.086921 XCTRunner[3301:462017] [User Defaults] Failed to write value for key AutomationDisableFauxCollectionCells in CFPrefsPlistSource<0x1740ede80> (Domain: com.apple.Accessibility, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null)): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access, switching to read-only
2016-09-30 14:03:58.096731 XCTRunner[3301:461911] Built at Sep 30 2016 14:03:39
2016-09-30 14:03:58.130604 XCTRunner[3301:461911] ServerURLHere->http://172.17.6.136:0<-ServerURLHere
2016-09-30 14:03:58.132625 XCTRunner[3301:461911] Listening on USB

Xcode8, real device: ios10.0.1

**Comment by marekcirkos** [comment]
@candialala Everything seems fine. `ServerURLHere->` indicates that WDA has booted and is ready to use

**Comment by BigWavelet** [comment]
@candialala  have you ever solved this issue, please help.

**Comment by PandaWX** [comment]
Do you have solved it？ help me，please！

**Comment by BigWavelet** [comment]
@PandaWX  maybe u can try iproxy to forward the device port by usb.  works for me!

**Comment by MarStarck** [comment]
I met the same problem. Do I need to config permissions like user-preference-write and file-write-data?
