### ISSUE TITLE
applicationAlertWithApplication queries application for XCUIElementTypeAlert and XCUIElementTypeSheet. 

### ISSUE THREAD

**Issue by rafael-chavez** [facebook/WebDriverAgent#183]
alert = application.sheets.element;

Not all XCUIElementTypeSheet are alerts. Therefore when checking if an alert is obstructing the view, if there is a popover sheet in the view that can be dismissed by clicking anywhere in the window, we cannot dismiss this sheet since we return a response saying "Alert is obstructing view".

Im suggesting removing line 200 in FBAlertViewCommands.m:
+ (XCUIElement *)applicationAlertWithApplication:(FBApplication *)application
{
  XCUIElement *alert = application.alerts.element;
  if (!alert.exists) {
    alert = application.sheets.element;
  }
  return alert;
}

 to ensure we only return this response if the element is a XCUIElementTypeAlert.

@marekcirkos I can fix real quick if you give me green light.

**Comment by marekcirkos** [comment]
Could you add integration test that covers this problem? 
Maybe we could add some additional checks for XCUIElementTypeSheet to distinguish this case?
