### ISSUE TITLE
WebDriverAgentRunner crashes when installed on real iOS 9.3.2 iPhone 6

### ISSUE THREAD

**Issue by kodayashi** [facebook/WebDriverAgent#192]
After bootstrapping the project, I selected the WebDriverAgentRunner then selected Project -> Test. The app is installed on an iPhone 6 running 9.3.2, but crashes on launch. iOS console logs show the following:

Jul  2 19:51:49 iPhone6 SpringBoard[58] <Warning>: Installed apps did change.
	Added: {(
	)}
	Removed: {(
	)}
	Modified: {(
	    "com.apple.test.WebDriverAgentRunner-Runner"
	)}
Jul  2 19:51:50 iPhone6 kernel[0] <Notice>: AppleKeyStore:Sending lock change 0 for handle 0
Jul  2 19:51:50 iPhone6 UserEventAgent[26] <Error>:  LockStateNotifier aksNotificationCallback posting notification: com.apple.mobile.keybagd.lock_status
Jul  2 19:51:50 iPhone6 UserEventAgent[26] <Notice>: (Note ) PIH: Lock status changed.
Jul  2 19:51:50 iPhone6 MobileMail[388] <Warning>: Ignoring lock state change from disabled to disabled
Jul  2 19:51:50 iPhone6 mobile_house_arrest[975] <Error>: vend_afc: Could not set SO_NOSIGPIPE: Bad file descriptor
Jul  2 19:51:50 iPhone6 com.apple.xpc.launchd[1] (lockdown.2647319278605.com.apple.mobile.house_arrest[975]) <Warning>: Service exited with abnormal code: 1
Jul  2 19:51:51 iPhone6 syncdefaultsd[968] <Notice>: (Note ) marked "com.me.keyvalueservice" topic as "enabled" on <APSConnection: 0x126e2bbc0>
Jul  2 19:51:51 iPhone6 kernel[0] <Notice>: AppleKeyStore:Sending lock change 0 for handle 0
Jul  2 19:51:51 iPhone6 UserEventAgent[26] <Error>:  LockStateNotifier aksNotificationCallback posting notification: com.apple.mobile.keybagd.lock_status
Jul  2 19:51:51 iPhone6 UserEventAgent[26] <Notice>: (Note ) PIH: Lock status changed.
Jul  2 19:51:51 iPhone6 MobileMail[388] <Warning>: Ignoring lock state change from disabled to disabled
Jul  2 19:51:52 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	 for arm64.
Jul  2 19:51:52 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: Connecting to com.apple.debugserver service...
Jul  2 19:51:52 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: Got a connection, waiting for process information for launching or attaching.
Jul  2 19:51:52 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: Sending AppProxy info: sequence no: 156, GUID: 993A9B8E-650B-4F55-A075-7A03E2FE49A9.
Jul  2 19:51:52 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Error>: error: Unrecognized event type: .  Ignoring.
Jul  2 19:51:52 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: About to launch process for bundle ID: com.apple.test.WebDriverAgentRunner-Runner
Jul  2 19:51:52 iPhone6 SpringBoard[58] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Jul  2 19:51:52 iPhone6 com.apple.xpc.launchd[1] (UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0xa7f3]) <Error>: The DisableASLR key is no longer respected. Please remove it.
Jul  2 19:51:52 iPhone6 securityd[93] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Jul  2 19:51:52 iPhone6 amfid[225] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Jul  2 19:51:52 iPhone6 kernel[0] <Notice>: xpcproxy[979] Container: /private/var/mobile/Containers/Data/Application/90839F27-B3FE-4BF3-AF75-EE9755B330A1 (sandbox)
Jul  2 19:51:52 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: In completion handler, got pid for bundle id, pid: 979.
Jul  2 19:51:52 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: Got a connection, launched process /private/var/containers/Bundle/Application/6A4098C5-4538-4F67-A7C2-9688D369A880/WebDriverAgentRunner-Runner.app (pid = 979).
Jul  2 19:51:52 iPhone6 SpringBoard[58] <Warning>: LICreateIconForImage passed NULL CGImageRef image
Jul  2 19:51:53 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: 1 +0.000000 sec [03d2/0c07]: error: ::mach_vm_region_recurse ( task = 0x1a13, address => 0x636a626f62696c2f, size => 0, nesting_depth => 1024, info => 0x16fd02ccc, infoCnt => 12) addr = 0x636a626f62696c2f  err = (os/kern) invalid address (0x00000001)
Jul  2 19:51:53 iPhone6 com.apple.xpc.launchd[1] <Error>: assertion failed: 13F69: launchd + 116796 [9F6284CF-8A17-36CC-9DB5-85D510A21F14]: 0x3
Jul  2 19:51:53 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: 2 +0.069258 sec [03d2/0c07]: error: ::mach_vm_region_recurse ( task = 0x1a13, address => 0xf098de5b00e2a45a, size => 0, nesting_depth => 1024, info => 0x16fd02ccc, infoCnt => 12) addr = 0xf098de5b00e2a45a  err = (os/kern) invalid address (0x00000001)
Jul  2 19:51:54 iPhone6 XCTRunner[979] <Warning>: Running tests...
Jul  2 19:51:54 iPhone6 securityd[93] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Jul  2 19:51:54 iPhone6 amfid[225] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Jul  2 19:51:54 iPhone6 kernel[0] <Notice>: AMFI: XCTRunner(pid 979) - [deny-mmap] mapped file does not the same team identifier as main process: /private/var/containers/Bundle/Application/6A4098C5-4538-4F67-A7C2-9688D369A880/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML
Jul  2 19:51:54 iPhone6 kernel[0] <Notice>: AMFI: XCTRunner(pid 979) - [deny-mmap] process has team identifier K3C3J3YZRH: /private/var/containers/Bundle/Application/6A4098C5-4538-4F67-A7C2-9688D369A880/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML
Jul  2 19:51:54 iPhone6 kernel[0] <Notice>: AMFI: XCTRunner(pid 979) - [deny-mmap] mapped file has team identifier 8C96M9YR8S: /private/var/containers/Bundle/Application/6A4098C5-4538-4F67-A7C2-9688D369A880/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML
Jul  2 19:51:54 iPhone6 XCTRunner[979] <Warning>: The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
Jul  2 19:51:54 iPhone6 XCTRunner[979] <Warning>: (dlopen_preflight(/var/containers/Bundle/Application/6A4098C5-4538-4F67-A7C2-9688D369A880/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/KissXML.framework/KissXML
	  Referenced from: /private/var/containers/Bundle/Application/6A4098C5-4538-4F67-A7C2-9688D369A880/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
	  Reason: no suitable image found.  Did find:
		/private/var/containers/Bundle/Application/6A4098C5-4538-4F67-A7C2-9688D369A880/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/6A4098C5-4538-4F67-A7C2-9688D369A880/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML')
Jul  2 19:51:54 iPhone6 SpringBoard[58] <Warning>: BSXPCMessage received error for message: Connection invalid
Jul  2 19:51:54 iPhone6 SpringBoard[58] <Warning>: HW kbd: Failed to set (null) as keyboard focus
Jul  2 19:51:54 iPhone6 com.apple.xpc.launchd[1] (UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0xa7f3][979]) <Warning>: Service exited with abnormal code: 82
Jul  2 19:51:54 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: 3 +0.235305 sec [03d2/1b0b]: error: ::read ( -1, 0x16e246a38, 1024 ) => -1 err = Bad file descriptor (0x00000009)
Jul  2 19:51:54 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[978] <Warning>: Exiting.
Jul  2 19:51:54 iPhone6 testmanagerd[974] <Warning>: testmanagerd exiting, idle with no test activity.
Jul  2 19:51:54 iPhone6 SpringBoard[58] <Warning>: Application 'UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0xa7f3]' exited voluntarily.

Running the exact same project targeting a simulator works fine. Are there additional steps to getting this working on a real device that I'm missing?

**Comment by lawrencelomax** [comment]
`deny-mmap` is showing that failing to `mmap` Frameworks due to a Code Signing issue. @marekcirkos what are your thoughts on statically linking `WebDriverAgentLib` and it's dependencies into the `xctest` target.

**Comment by marekcirkos** [comment]
Can you try removing `WebDriverAgentRunner-Runner.app` application from device your device and cleaning the project?

**Comment by kodayashi** [comment]
No dice @marekcirkos. I tried a few things:

1. Your recommendation above.
2. Blowing away the project, re-cloning/bootstrapping, and rerunning.
3. Setting the Team to my Apple Developer Account for the WebDriverAgentLib framework (just shooting in the dark here).

**Comment by marekcirkos** [comment]
It is code signing issue. Make sure you have valid team / provisioning profile that can sign any bundle id. I had same issue when I was working on different machine and explicitly selecting team solved it for me. For you it might be picking wrong prov profile. Checking which one is used on code sign step might be a go idea.

**Comment by kodayashi** [comment]
Shoot, yeah found the issue. My new Apple Developer account didn't have a Wildcard App ID and Provisioning Profile created. Once I created one and explicity set Code Signing to use this account, installs on real devices started working.

Thanks for the help @marekcirkos!

**Comment by shaynl** [comment]
@marekcirkos i have the same issue with the code signing. It seems that I can only sign apps with bundle id that start with "com.myCompanyName". Can I alternatively change all WebDriver bundle ids from "com.facebook" to this one?

**Comment by marekcirkos** [comment]
Do whatever you need to do :). WDA does not depend on bundle id having any particular value.

**Comment by alter-al** [comment]
Hi, I've same issue.
These methods not helped me:
- rebooting ios/mac
- re-cloning/bootstrapping and rerunning
- changing certificate

From another host WDA working good with these certificates.

**Comment by alter-al** [comment]
I fixed issue by re-downloading the WWDR (Apple Worldwide Developer Relations Certification Authority) and set its trust: 'use system default'.
Download from here: http://developer.apple.com/certificationauthority/AppleWWDRCA.cer
