### ISSUE TITLE
Native apps on real devices

### ISSUE THREAD

**Issue by hugomcconnell** [facebook/WebDriverAgent#193]
Hi guys,

Is it possible to launch native apps and inspect/automate them (e.g. the Settings app) on real devices with this - or just the simulator? Struggling with real device.

**Comment by marekcirkos** [comment]
It should work on devices as well. What does not work for you?

**Comment by hugomcconnell** [comment]
@marekcirkos thanks for quick reply. My colleague who logged this:
https://github.com/facebook/WebDriverAgent/issues/192
will post more information shortly about what he's been facing

**Comment by kodayashi** [comment]
Hi @marekcirkos,

We can't seem to open a native iOS app and perform actions. For example, the below cURL commands work great on a simulator, but the call to open com.apple.Preferences on hardware fails with an "unrecognized selector sent to instance" response:


DEVICE_URL=http://92.168.1.207:8100
JSON_HEADER='-H "Content-Type: application/json”'
curl -X GET $JSON_HEADER $DEVICE_URL/status
{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iPhone OS",
      "version" : "9.3.2"
    },
    "ios" : {
      "simulatorVersion" : "9.3.2"
    },
    "build" : {
      "time" : "Jul  5 2016 09:05:58"
    }
  },
  "sessionId" : null,
  "status" : 0
}
curl -X POST $JSON_HEADER -d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.Preferences\"}}" $DEVICE_URL/session
{
  "value" : "-[FBApplicationProcessProxy setApplicationImplementation:]: unrecognized selector sent to instance 0x146e30cd0\n\n(\n\t0   CoreFoundation                      0x000000018349adc8 <redacted> + 148\n\t1   libobjc.A.dylib                     0x0000000182afff80 objc_exception_throw + 56\n\t2   CoreFoundation                      0x00000001834a1c4c <redacted> + 0\n\t3   CoreFoundation                      0x000000018349ebec <redacted> + 872\n\t4   CoreFoundation                      0x000000018339cc5c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x0000000102279a68 -[FBApplication fb_placeApplicationProxy] + 300\n\t6   WebDriverAgentLib                   0x0000000102279894 -[FBApplication launch] + 76\n\t7   WebDriverAgentLib                   0x000000010226fa08 +[FBSessionCommands handleCreateSession:] + 780\n\t8   WebDriverAgentLib                   0x00000001022610a8 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208\n\t9   WebDriverAgentLib                   0x000000010225a3c8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 432\n\t10  RoutingHTTPServer                   0x00000001023323cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t11  RoutingHTTPServer                   0x0000000102332b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44\n\t12  libdispatch.dylib                   0x0000000182ee547c <redacted> + 16\n\t13  libdispatch.dylib                   0x0000000182ef4ae8 <redacted> + 644\n\t14  libdispatch.dylib                   0x0000000182ee547c <redacted> + 16\n\t15  libdispatch.dylib                   0x0000000182eeab84 _dispatch_main_queue_callback_4CF + 1844\n\t16  CoreFoundation                      0x0000000183450d50 <redacted> + 12\n\t17  CoreFoundation                      0x000000018344ebb8 <redacted> + 1628\n\t18  CoreFoundation                      0x0000000183378c50 CFRunLoopRunSpecific + 384\n\t19  Foundation                          0x0000000183d88cfc <redacted> + 308\n\t20  Foundation                          0x0000000183dde030 <redacted> + 88\n\t21  WebDriverAgentLib                   0x0000000102259460 -[FBWebServer startServing] + 284\n\t22  WebDriverAgentRunner                0x000000010202bed0 -[UITestingUITests testRunner] + 120\n\t23  CoreFoundation                      0x00000001834a0a60 <redacted> + 144\n\t24  CoreFoundation                      0x0000000183398488 <redacted> + 284\n\t25  XCTest                              0x0000000100065300 __24-[XCTestCase invokeTest]_block_invoke_2 + 364\n\t26  XCTest                              0x00000001000976ec -[XCTestContext performInScope:] + 208\n\t27  XCTest                              0x0000000100065180 -[XCTestCase invokeTest] + 164\n\t28  XCTest                              0x000000010006576c -[XCTestCase performTest:] + 460\n\t29  XCTest                              0x00000001000631d0 -[XCTestSuite performTest:] + 384\n\t30  XCTest                              0x00000001000631d0 -[XCTestSuite performTest:] + 384\n\t31  XCTest                              0x00000001000631d0 -[XCTestSuite performTest:] + 384\n\t32  XCTest                              0x00000001000703fc -[XCTestObservationCenter _observeTestExecutionForBlock:] + 596\n\t33  XCTest                              0x0000000100098d2c _XCTestMain + 1056\n\t34  CoreFoundation                      0x0000000183450f84 <redacted> + 20\n\t35  CoreFoundation                      0x00000001834508bc <redacted> + 308\n\t36  CoreFoundation                      0x000000018344e820 <redacted> + 708\n\t37  CoreFoundation                      0x0000000183378c50 CFRunLoopRunSpecific + 384\n\t38  GraphicsServices                    0x0000000184c60088 GSEventRunModal + 180\n\t39  UIKit                               0x0000000188662088 UIApplicationMain + 204\n\t40  XCTRunner                           0x0000000100024438 XCTRunner + 33848\n\t41  libdyld.dylib                       0x0000000182f168b8 <redacted> + 4\n)",
  "sessionId" : null,
  "status" : 13
}

**Comment by marekcirkos** [comment]
This is bug I found recently. Easy workaround should be placing breakpoint right before fb_placeApplicationProxy is called and wait till application is launched.

**Comment by kodayashi** [comment]
Thanks @marekcirkos, I'll try that out. Is there a github issue we can track on that bug so our team knows when it's been fixed in source?

**Comment by marekcirkos** [comment]
We can use this issue to track it.

**Comment by marekcirkos** [comment]
Landed diff that should fix your issue https://github.com/facebook/WebDriverAgent/commit/2ed10a77cea79c99056554224a5ac4a9d59e3150. Could you confirm?

**Comment by kodayashi** [comment]
@marekcirkos - Nice, yeah it's working. I was able to open up the settings app on a real iPhone 6 and inspect/click around. Thanks!
