### ISSUE TITLE
Any ETA for ios 10 support?

### ISSUE THREAD

**Issue by YatinP** [facebook/WebDriverAgent#194]

**Comment by marekcirkos** [comment]
You can run WDA on iOS already. Major change we noticed is fact that XCTest does not report not visible elements. Most likely we will not 'fight' against it. Do you have any other issues?

**Comment by YatinP** [comment]
It doesn't even start server 

2016-07-06 12:22:56.632837 XCTRunner[2920:4130833] bundleid: com.apple.test.WebDriverAgentRunner-Runner, enable_level: 0, persist_level: 0, propagate_with_activity: 0
2016-07-06 12:22:56.637408 XCTRunner[2920:4130833] Created DB, header sequence number = 272
2016-07-06 12:22:56.646706 XCTRunner[2920:4130838] subsystem: com.apple.UIKit, category: HIDEvents, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0
2016-07-06 12:22:56.665020 XCTRunner[2920:4130833] Created DB, header sequence number = 272
2016-07-06 12:22:56.762672 XCTRunner[2920:4130833] subsystem: com.apple.BaseBoard, category: MachPort, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0
2016-07-06 12:22:56.789178 XCTRunner[2920:4130833] subsystem: com.apple.FrontBoard, category: Common, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0
12:22:57.040 XCTRunner[2920:4130840] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
12:22:57.049 XCTRunner[2920:4130840] _IDE_startExecutingTestPlanWithProtocolVersion:21
libc++abi.dylib: terminating with uncaught exception of type NSException
2016-07-06 12:23:28.072 xcodebuild[2793:4130488] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
** TEST FAILED **

And when I tried to build it from Xcode itself, it failed build for iOSTarget - 10.0 on this line 
  OSAtomicOr32Barrier(1, &didFinish); As this one is deprecated

This is sim log 
Jul  6 12:34:54 OlympusMacHost-X CoreSimulatorBridge[2144]: Requesting installation of file:///Users/olympusteam/Library/Developer/Xcode/DerivedData/WebDriverAgent-gsiqwqbeifvspihfcivlmkisgrlv/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/ with options: {
	    CFBundleIdentifier = "com.apple.test.WebDriverAgentRunner-Runner";
	    PackageType = Developer;
	    SimulatorRootPath = "/Users/olympusteam/Downloads/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
	    SimulatorUserPath = "/Users/olympusteam/Library/Developer/CoreSimulator/Devices/4ED22326-D6AA-4EA5-89C9-C8DCA91192C3/data";
	}
Jul  6 12:34:54 OlympusMacHost-X installd[2130]: 0x700000094000 -[MIClientConnection _doInstallationForPath:withOptions:completion:]: Install of "/Users/olympusteam/Library/Developer/Xcode/DerivedData/WebDriverAgent-gsiqwqbeifvspihfcivlmkisgrlv/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app" type Developer (LSInstallType = (null)) requested by CoreSimulatorBridge (pid 2144)
Jul  6 12:34:54 OlympusMacHost-X installd[2130]: 0x700000094000 MDMCreateDeltaDirectory: calling MDMDirectoryDiff with:
	state->old_bundle: /Users/olympusteam/Library/Developer/CoreSimulator/Devices/4ED22326-D6AA-4EA5-89C9-C8DCA91192C3/data/Containers/Bundle/Application/4947E8EC-5ACD-4A4E-8F12-15FD5DC4278A/WebDriverAgentRunner-Runner.app
	state->new_bundle: /Users/olympusteam/Library/Developer/Xcode/DerivedData/WebDriverAgent-gsiqwqbeifvspihfcivlmkisgrlv/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app
	state->dst_bundle: /Users/olympusteam/Library/Developer/CoreSimulator/Devices/4ED22326-D6AA-4EA5-89C9-C8DCA91192C3/data/Library/Caches/com.apple.mobile.installd.staging/temp.mILEGR/extracted/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
		dst_ipa: /Users/olympusteam/Library/Developer/CoreSimulator/Devices/4ED22326-D6AA-4EA5-89C9-C8DCA91192C3/data/Library/Caches/com.apple.mobile.installd.staging/temp.mILEGR/extracted
Jul  6 12:34:54 OlympusMacHost-X installd[2130]: 0x700000117000 __MDMDirectoryDiff_block_invoke.37: calling writeDictToFile with: /Users/olympusteam/Library/Developer/CoreSimulator/Devices/4ED22326-D6AA-4EA5-89C9-C8DCA91192C3/data/Library/Caches/com.apple.mobile.installd.staging/temp.mILEGR/extracted/ManifestCache.plist
Jul  6 12:34:54 OlympusMacHost-X installd[2130]: 0x700000117000 writeDictToFile: ==== Successfully wrote Manifest cache to /Users/olympusteam/Library/Developer/CoreSimulator/Devices/4ED22326-D6AA-4EA5-89C9-C8DCA91192C3/data/Library/Caches/com.apple.mobile.installd.staging/temp.mILEGR/extracted/ManifestCache.plist
Jul  6 12:34:54 OlympusMacHost-X installd[2130]: 0x700000094000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundlePatch ID=com.apple.test.WebDriverAgentRunner-Runner; Version=1, ShortVersion=1.0>
Jul  6 12:34:54 OlympusMacHost-X installd[2130]: 0x700000094000 -[MIInstallableBundlePatch applyPatchWithError:]: Attempting patch update of com.apple.test.WebDriverAgentRunner-Runner from 1 (1.0) to 1 (1.0)
Jul  6 12:34:55 OlympusMacHost-X installd[2130]: 0x700000094000 -[MIInstallableBundle _refreshUUIDForContainer:withError:]: Data container for com.apple.test.WebDriverAgentRunner-Runner is now at /Users/olympusteam/Library/Developer/CoreSimulator/Devices/4ED22326-D6AA-4EA5-89C9-C8DCA91192C3/data/Containers/Data/Application/3C675DE5-EE2E-4F1B-937B-19C842FEFCEE
Jul  6 12:34:55 OlympusMacHost-X installd[2130]: 0x700000094000 -[MIContainer makeContainerLiveReplacingContainer:reason:withError:]: Made container live for com.apple.test.WebDriverAgentRunner-Runner at /Users/olympusteam/Library/Developer/CoreSimulator/Devices/4ED22326-D6AA-4EA5-89C9-C8DCA91192C3/data/Containers/Bundle/Application/0DBB4312-6F3F-4D06-BE89-948B5E3252BB
Jul  6 12:34:55 OlympusMacHost-X installd[2130]: 0x700000094000 -[MIInstaller performInstallationWithError:]: Install Successful; Staging: 0.05s; Waiting: 0.00s; Preflight/Patch: 0.04s, Verifying: 0.00s; Overall: 0.15s
Jul  6 12:34:55 OlympusMacHost-X pkd[2176]: releasing plug-in hold FB9CC0FE-C28E-4325-BAFD-FC3D08F1732C at client's request
Jul  6 12:34:55 OlympusMacHost-X com.apple.CallKit.CallDirectory[2296]: [Default] Unable to initialize CXCallDirectoryStore for reading and writing: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “CallDirectory” in the folder “Library”." UserInfo={NSFilePath=/var/mobile/Library/CallDirectory, NSUnderlyingError=0x7fd349c01750 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
Jul  6 12:34:55 OlympusMacHost-X callservicesd[2290]: [Default] Error synchronizing call directory extensions: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “CallDirectory” in the folder “Library”." UserInfo={NSFilePath=/var/mobile/Library/CallDirectory, NSUnderlyingError=0x7fd953411fc0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] throwing out icon because it isn't visible in the model : node=<SBApplicationIcon: 0x6000001d6170; nodeID: "com.apple.camera"> com.apple.camera
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.weather
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.mobiletimer
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.mobilenotes
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.stocks
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.videos
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.iBooks
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.MobileStore
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.AppStore
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.Home
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.facetime
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.calculator
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.podcasts
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: [Common] could not find icon for representation -> com.apple.compass
Jul  6 12:34:55 OlympusMacHost-X SpringBoard[2135]: Data provider finalized with retained byte pointer
Jul  6 12:34:57 OlympusMacHost-X CoreSimulatorBridge[2144]: Requesting launch of com.apple.test.WebDriverAgentRunner-Runner with options: {
	    arguments =     (
	        "-NSTreatUnknownArgumentsAsOpen",
	        NO,
	        "-ApplePersistenceIgnoreState",
	        YES
	    );
	    environment =     {
	        "DTX_CONNECTION_SERVICES_PATH" = "/Users/olympusteam/Downloads/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/Developer/Library/PrivateFrameworks/DTXConnectionServices.framework";
	        "DYLD_FRAMEWORK_PATH" = "/Users/olympusteam/Library/Developer/Xcode/DerivedData/WebDriverAgent-gsiqwqbeifvspihfcivlmkisgrlv/Build/Products/Debug-iphonesimulator:/Users/olympusteam/Library/Developer/Xcode/DerivedData/WebDriverAgent-gsiqwqbeifvspihfcivlmkisgrlv/Build/Products/Debug-iphonesimulator:/Users/olympusteam/Downloads/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks";
	        "DYLD_LIBRARY_PATH" = "/Users/olympusteam/Library/Developer/Xcode/DerivedData/WebDriverAgent-gsiqwqbeifvspihfcivlmkisgrlv/Build/Products/Debug-iphonesimulator:/Users/olympusteam/Library/Developer/Xcode/DerivedData/WebDriverAgent-gsiqwqbeifvspihfcivlmkisgrlv/Build/Products/Debug-iphonesimulator:/Users/olympusteam/Downloads/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks";
	        NSUnbufferedIO = YES;
	        "OS_ACTIVITY_DT_MODE" = YES;
	        "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
	        XCTestConfigurationFilePath = "/var/folders/yv/fzct1hl55rs_vp6lklt8rbfm0000gn/T/com.apple.dt.XCTest/7E017DF4-AAE6-4C86-BC59-86035B4B2133/remote-container/tmp/WebDriverAgentRunner-7E017DF4-AAE6-4C86-BC59-86035B4B2133.xctestconfiguration";
	        "__XCODE_BUILT_PRODUCTS_DIR_PATHS" = "/Users/olympusteam/Library/Developer/Xcode/DerivedData/WebDriverAgent-gsiqwqbeifvspihfcivlmkisgrlv/Build/Products/Debug-iphonesimulator";
	        "__XPC_DYLD_FRAMEWORK_PATH" = "/Users/olympusteam/Library/Developer/Xcode/DerivedData/WebDriverAgent-gsiqwqbeifvspihfcivlmkisgrlv/Build/Products/Debug-iphonesimulator";
	        "__XPC_DYLD_LIBRARY_PATH" = "/Users/olympusteam/Library/Developer/Xcode/DerivedData/WebDriverAgent-gsiqwqbeifvspihfcivlmkisgrlv/Build/Products/Debug-iphonesimulator";
	    };
	    stderr = "/dev/ttys004";
	    stdout = "/dev/ttys004";
	    "wait_for_debugger" = 0;
	}
Jul  6 12:34:57 OlympusMacHost-X CoreSimulatorBridge[2144]: [Common] [FBSSystemService][0x15f2] Sending request to open "com.apple.test.WebDriverAgentRunner-Runner"
Jul  6 12:34:57 OlympusMacHost-X assertiond[2139]: assertion failed: 15F34 14A5261u: assertiond + 14824 [80A1AEAB-946F-3471-8399-4746D2CF100E]: 0x1
Jul  6 12:34:57 OlympusMacHost-X CoreSimulatorBridge[2144]: [Common] [FBSSystemService][0x15f2] Request successful: <FBSProcessHandle: 0x7fc961e1d1d0; XCTRunner:3129; valid: YES>
Jul  6 12:34:58 OlympusMacHost-X logd[2129]: metadata shared cached uuid is null (using logd's shared cache info) XCTRunner (3129)
Jul  6 12:34:58 OlympusMacHost-X logd[2129]: Failed to harvest strings for pathless uuid '8E5FA402-CA43-3F17-B9B5-80DD7587395D'
Jul  6 12:34:58 OlympusMacHost-X logd[2129]: assertion failed: 15F34 14A5261u: logd + 66639 [D24D711F-5327-3FBE-8E31-98E71DA1A704]: 0x2
Jul  6 12:34:58 OlympusMacHost-X logd[2129]: assertion failed: 15F34 14A5261u: logd + 67521 [D24D711F-5327-3FBE-8E31-98E71DA1A704]: 0x2
Jul  6 12:34:58 OlympusMacHost-X logd[2129]: assertion failed: 15F34 14A5261u: logd + 66639 [D24D711F-5327-3FBE-8E31-98E71DA1A704]: 0x2
Jul  6 12:34:58 OlympusMacHost-X logd[2129]: assertion failed: 15F34 14A5261u: logd + 67521 [D24D711F-5327-3FBE-8E31-98E71DA1A704]: 0x2

Jul  6 12:34:58 OlympusMacHost-X logd[2129]: assertion failed: 15F34 14A5261u: logd + 66639 [D24D711F-5327-3FBE-8E31-98E71DA1A704]: 0x2
Jul  6 12:34:58 OlympusMacHost-X logd[2129]: assertion failed: 15F34 14A5261u: logd + 67521 [D24D711F-5327-3FBE-8E31-98E71DA1A704]: 0x2
Jul  6 12:34:58 OlympusMacHost-X XCTRunner[3129]: Failed to map preferences shmem named apple.sim.cfprefsd.daemon
Jul  6 12:34:58 OlympusMacHost-X XCTRunner[3129]: assertion failed: 15F34 14A5261u: libxpc.dylib + 62705 [9E804D38-5980-393F-8067-E5F900341CC8]: 0x7d
Jul  6 12:34:58 OlympusMacHost-X assertiond[2139]: assertion failed: 15F34 14A5261u: assertiond + 14824 [80A1AEAB-946F-3471-8399-4746D2CF100E]: 0x1
Jul  6 12:34:58 --- last message repeated 1 time ---
Jul  6 12:34:58 OlympusMacHost-X com.apple.CoreSimulator.SimDevice.4ED22326-D6AA-4EA5-89C9-C8DCA91192C3.launchd_sim[2112] (com.apple.accessibility.heard): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Jul  6 12:34:58 OlympusMacHost-X XCTRunner[3129]: Running tests...
Jul  6 12:34:58 OlympusMacHost-X assertiond[2139]: assertion failed: 15F34 14A5261u: assertiond + 14824 [80A1AEAB-946F-3471-8399-4746D2CF100E]: 0x1
Jul  6 12:34:58 --- last message repeated 1 time ---
Jul  6 12:34:58 OlympusMacHost-X assertiond[2139]: Could not create or rename power assertion for <BKNewProcess: 0x7feff0c1de10; com.apple.test.WebDriverAgentRunner-Runner; pid: 3129; hostpid: -1>: 0xe00002c9
Jul  6 12:34:58 OlympusMacHost-X SpringBoard[2135]: Unbalanced calls to begin/end appearance transitions for <SBLeafIconViewController: 0x7ff74b5989e0>.
Jul  6 12:35:28 OlympusMacHost-X XCTRunner[3129]: *** Assertion failure in void _XCTFailInCurrentTest(NSString *, ...)(), /Library/Caches/com.apple.xbs/Sources/XCTest_Sim/XCTest-11078.3/XCTestFramework/Classes/XCTestCase.m:65
Jul  6 12:35:28 OlympusMacHost-X XCTRunner[3129]: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '_XCTFailInCurrentTest should only be called while a test is running.
	Failure description: Failed to receive completion for <XCDeviceEvent:0x7f9d09610ce0 page 12 usage 64 duration 0.01s within 30.0s'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x000000010308ddeb __exceptionPreprocess + 171
		1   libobjc.A.dylib                     0x0000000102ae931e objc_exception_throw + 48
		2   CoreFoundation                      0x0000000103091ec2 +[NSException raise:format:arguments:] + 98
		3   Foundation                          0x000000010267c8d6 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
		4   XCTest                              0x0000000102487618 _XCTFailInCurrentTest + 375
		5   XCTest                              0x00000001024aa4d9 -[XCUIDevice _dispatchEventWithPage:usage:duration:] + 879
		6   XCTest                              0x00000001024d9b65 XCInitializeForUITesting + 575
		7   XCTest                              0x0000000102472c0c -[XCTestDriver _runSuite] + 141
		8   XCTest                              0x0000000102473958 -[XCTestDriver _checkForTestManager] + 287
		9   XCTest                              0x00000001024c29a3 _XCTestMain + 628
		10  CoreFoundation                      0x0000000103033bfc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
		11  CoreFoundation                      0x00000001030189d4 __CFRunLoopDoBlocks + 356
		12  CoreFoundation                      0x0000000103018145 __CFRunLoopRun + 901
		13  CoreFoundation                      0x0000000103017b5d CFRunLoopRunSpecific + 285
		14  GraphicsServices                    0x000000010575fa48 GSEventRunModal + 161
		15  UIKit                               0x00000001034dde8b UIApplicationMain + 159
		16  XCTRunner                           0x00000001023f1820 XCTRunner + 6176
		17  libdyld.dylib                       0x00000001060fe6bd start + 1
		18  ???                                 0x0000000000000005 0x0 + 5
	)
Jul  6 12:35:28 OlympusMacHost-X SpringBoard[2135]: HW kbd: Failed to set (null) as keyboard focus
Jul  6 12:35:28 OlympusMacHost-X logd[2129]: assertion failed: 15F34 14A5261u: logd + 66639 [D24D711F-5327-3FBE-8E31-98E71DA1A704]: 0x2
Jul  6 12:35:28 OlympusMacHost-X com.apple.CoreSimulator.SimDevice.4ED22326-D6AA-4EA5-89C9-C8DCA91192C3.launchd_sim[2112] (UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0x74ec][3129]): Service exited due to Abort trap: 6
Jul  6 12:35:28 OlympusMacHost-X logd[2129]: assertion failed: 15F34 14A5261u: logd + 67521 [D24D711F-5327-3FBE-8E31-98E71DA1A704]: 0x2
Jul  6 12:35:28 OlympusMacHost-X logd[2129]: assertion failed: 15F34 14A5261u: logd + 66639 [D24D711F-5327-3FBE-8E31-98E71DA1A704]: 0x2
Jul  6 12:35:28 OlympusMacHost-X logd[2129]: assertion failed: 15F34 14A5261u: logd + 67521 [D24D711F-5327-3FBE-8E31-98E71DA1A704]: 0x2
Jul  6 12:35:29 OlympusMacHost-X SpringBoard[2135]: [Common] Application 'UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0x74ec]' crashed.
Jul  6 12:35:29 OlympusMacHost-X assertiond[2139]: assertion failed: 15F34 14A5261u: assertiond + 14824 [80A1AEAB-946F-3471-8399-4746D2CF100E]: 0x1
Jul  6 12:35:29 --- last message repeated 1 time ---
Jul  6 12:35:29 OlympusMacHost-X assertiond[2139]: Could not create or rename power assertion for <BKNewProcess: 0x7feff0c1de10; com.apple.test.WebDriverAgentRunner-Runner; pid: 3129; hostpid: -1>: 0xe00002c9

**Comment by marekcirkos** [comment]
This is Xcode beta issue. Make sure that `xcode-select` points to Xcode beta and reboot your mac (yes, I am super serious here).

**Comment by YatinP** [comment]
Of course it does point to beta. I will try reboot option

**Comment by YatinP** [comment]
Thanks. reboot did a trick. Sorry to bother..
