### ISSUE TITLE
Apple TV support 

### ISSUE THREAD

**Issue by patotskiy** [facebook/WebDriverAgent#195]
Unable to launch WebRiverAgent for Apple tv. 
` xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'platform=tvOS Simulator,name=Apple TV 1080p' test `

Output: 
` xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:tvOS Simulator, name:Apple TV 1080p }
	Available destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS Simulator, id:E72FA047-A6D3-4022-8ECE-B0A8D5E87239, OS:9.3, name:iPad 2 }
		{ platform:iOS Simulator, id:382BF112-B13F-409D-9536-EB2057B89C68, OS:9.3, name:iPad Air }
		{ platform:iOS Simulator, id:D90BE5FF-652F-436A-8183-2980BC869A90, OS:9.3, name:iPad Air 2 }
		{ platform:iOS Simulator, id:06D34327-7C77-4E31-8D6C-E0EC1CCC0D82, OS:9.3, name:iPad Pro }
		{ platform:iOS Simulator, id:382CEBEE-6988-48C5-A96E-0161B106F826, OS:9.3, name:iPad Retina }
		{ platform:iOS Simulator, id:CD9716D3-BF32-4B15-85DF-E507989F3A84, OS:9.3, name:iPhone 4s }
		{ platform:iOS Simulator, id:D729D43C-FD98-4AFC-9F28-F838EB13F376, OS:9.3, name:iPhone 4s }
		{ platform:iOS Simulator, id:74EAAD21-F586-4320-9222-759CEA8131D4, OS:9.3, name:iPhone 5 }
		{ platform:iOS Simulator, id:7DB6E165-D9CD-4648-9D46-0C0A32FA30B5, OS:9.3, name:iPhone 5 }
		{ platform:iOS Simulator, id:DAE4A0AE-42E9-4BD3-8B70-CF6CFB44DA7C, OS:9.3, name:iPhone 5s }
		{ platform:iOS Simulator, id:06543375-0828-4879-A5C5-18021099EAF9, OS:9.3, name:iPhone 6 }
		{ platform:iOS Simulator, id:240F1E30-5C0D-4CBB-AA01-0B613732DF32, OS:9.3, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:02EFA4DA-B5DA-4666-903E-45963D9A7FAE, OS:9.3, name:iPhone 6s }
		{ platform:iOS Simulator, id:147BF49F-49BA-40B1-A5F3-87A478A32D61, OS:9.3, name:iPhone 6s }
		{ platform:iOS Simulator, id:C608567B-57B8-4741-B631-D9F7A792EB32, OS:9.3, name:iPhone 6s Plus }`

Does WebDriverAgent support Applet TV os?

**Comment by marekcirkos** [comment]
As stated in `Features` we do not support OSX and tvOS yet. We don't have any plans to work on them soon as there are a lot of other things we want to do beforehand. However support for tvOS should be pretty straightforward. Only tricky part is navigation through elements when tap command is requested as you need to explicitly navigate to element before activating it. I would be happy to review diff if you want to work on it ;)
