### ISSUE TITLE
Perform tap with arguments X, Y

### ISSUE THREAD

**Issue by codeskyblue** [facebook/WebDriverAgent#198]
Will be used in mobile game test.

## Expect
Like

```
curl -X POST -d '{"x": 20, "y": 55}' $DEVICE_URL/tap
```

Can it be possible? Thanks for your awesome work.

**Comment by marekcirkos** [comment]
We already support it have a look at https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L62. Just pass 0 as UUID. Also keep in mind we will change this endpoint soonish to be more WD spec compliant.

**Comment by codeskyblue** [comment]
How to use? I am not very familiar with OC, just guess the usage, but not working this way.

```
SESSION_ID=<my_session_id>
curl -X POST -F x=50 -F y=70 $DEVICE_URL/session/$SESSION_ID/tap/0
```

Nothing happends.

**Comment by codeskyblue** [comment]
Finally with help of other, figure out the usage.

```
curl -X POST $JSON_HEADER \
-d "{\"x\":\"10\",\"y\":\"20\"}" \
$DEVICE_URL/session/$SESSION_ID/tap/0
```

**Comment by butterflyingdog** [comment]
according to  the latest code 
 [https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L66]
you should use as this:

`curl -X POST $JSON_HEADER \
-d "{\"x\":\"10\",\"y\":\"20\"}" \
$DEVICE_URL/session/$SESSION_ID/wda/tap/0`
