### ISSUE TITLE
Python client for wda, want to know who have already write this lib?

### ISSUE THREAD

**Issue by codeskyblue** [facebook/WebDriverAgent#199]
Even through I can write it myself, but I think it is better to known who have already write it.

**Comment by xudafeng** [comment]
@codeskyblue try to binding like this [webdriveragent](https://github.com/xudafeng/webdriveragent)

**Comment by codeskyblue** [comment]
em... @xudafeng where is the doc?

**Comment by lawrencelomax** [comment]
Appium have a WebDriver client in Python https://github.com/appium/python-client/blob/master/README.md

**Comment by codeskyblue** [comment]
Thanks @lawrencelomax, but I donot want to relay on appium.

**Comment by codeskyblue** [comment]
I created a python lib in <https://github.com/codeskyblue/python-wda>

But i meet a problem, queried strange element id(not int), and when I follow the steps in README.

```
curl -X POST -d "" $DEVICE_URL/session/$SESSION_ID/element/FDFA10CA-4E13-431A-8199-8AD1ADDB4AF2/click
```

not click action seems performed.

Want some help.

**Comment by marekcirkos** [comment]
This is UUID and is expected as described in [WebDriver Spec](https://w3c.github.io/webdriver/webdriver-spec.html).

It used to be different (we had ints) be we are making WDA more WebDriver Spec compliant.

**Comment by codeskyblue** [comment]
I see, but still dont know, why

```
url -X POST -d "" $DEVICE_URL/session/$SESSION_ID/element/FDFA10CA-4E13-431A-8199-8AD1ADDB4AF2/click
```

not working?

**Comment by marekcirkos** [comment]
Could you elaborate on what is not working? What is the error, any response, etc?

**Comment by chenhengjie123** [comment]
@codeskyblue Maybe you could attach all the requests and response during the whole launch->find->click process? It's wired that you send string like session id as element id.

**Comment by codeskyblue** [comment]
1. First I create a session with POST, open app `com.apple.Health`, get session ID $SESSION_ID
2. Find element with POST $DEVICE_URL/session/$SESSION_ID/elements

    ```
    curl -x POST '{"using": "link test", "value": "name=Dashboard"}' $DEVICE_URL/session/$SESSION_ID/elements
    ```

    Got the return value like

    ```
    [
            {u'label': u'Dashboard', u'type': u'XCUIElementTypeStaticText', u'ELEMENT': u'E60237CB-5FD8-4D60-A6E4-F54B583931DF'},
            {u'label': None, u'type': u'XCUIElementTypeNavigationBar', u'ELEMENT': u'786F9BB6-7734-4B52-B341-09030256C3A6'},
            {u'label': u'Dashboard', u'type': u'XCUIElementTypeButton', u'ELEMENT': u'B294344C-6316-450D-88AE-CE6B1E375E02'}
        ]
    ```

    So I got the Button ELEMENT ID `B294344C-6316-450D-88AE-CE6B1E375E02`

3. The next step is send click with POST

    ```
    curl -X POST -d "" $DEVICE_URL/session/$SESSION_ID/element/B294344C-6316-450D-88AE-CE6B1E375E02/click
    ```

    Wow, It works.   !_!  Thanks guys.
