### ISSUE TITLE
Question about WebDriverAgentUSBClient 

### ISSUE THREAD

**Issue by YatinP** [facebook/WebDriverAgent#200]
Only way out to use this is to have http proxy and translate all calls to format so that we can call WebDriverAgentUSBClient.dispatchMethod or I am missing something.

**Comment by marekcirkos** [comment]
If you have HTTP client that can talk to WDA, you can use this class to send HTTP request to WDA via USB.

**Comment by lawrencelomax** [comment]
The rationale here is that Wifi on iOS Devices can be flaky, so running a HTTP Server on the host and pushing the request over USB can be much more reliable.

**Comment by yaphatak** [comment]
ok got it. I was working on integrating this with appium. It does look like we need to have one more http objective-c/swift server on host that will further translate logic to USB call

**Comment by marekcirkos** [comment]
Also if you can talk to USB, you could just use same ports, tags and wrap HTTP requests in same manner as [FBHTTPOverUSBClient.m ](https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentUSBClient/FBHTTPOverUSBClient.m) does.

**Comment by yaphatak** [comment]
Thanks this helps a lot. Can you aslo elaborate on https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentUSBClient/FBHTTPOverUSBClient.m#L108 what is this completion:(WDHTTPOverUSBResponse)completion parameter?

**Comment by marekcirkos** [comment]
It is callback block for request response.

**Comment by marekcirkos** [comment]
Do you have anymore questions?

**Comment by yaphatak** [comment]
Thanks you can close this

**Comment by codeskyblue** [comment]
Still don't know how to send HTTP Request over USB, Not very familiar with OC. Is this same with <http://iphonedevwiki.net/index.php/SSH_Over_USB>

**Comment by yaphatak** [comment]
install libimobiledevice and then use iproxy https://github.com/libimobiledevice/libusbmuxd/blob/4397b3376dc4e4cb1c991d0aed61ce6482614196/tools/iproxy.c
iproxy LOCAL_TCP_PORT DEVICE_TCP_PORT [UDID]
