### ISSUE TITLE
Device rotation is limited.

### ISSUE THREAD

**Issue by rafael-chavez** [facebook/WebDriverAgent#203]
Hi @marekcirkos, currently WebDriverAgent implementation of rotation api is limited to 4 orientations:

```
  .portrait = @"PORTRAIT",
  .landscapeLeft = @"LANDSCAPE",
  .landscapeRight = @"UIA_DEVICE_ORIENTATION_LANDSCAPERIGHT",
  .portraitUpsideDown = @"UIA_DEVICE_ORIENTATION_PORTRAIT_UPSIDEDOWN",
```

Are you willing to accept a pull request that would implement something like this? 
https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#devicerotation

**Comment by marekcirkos** [comment]
Definitely we want to make WDA more WD spec compliant.

**Comment by marekcirkos** [comment]
Closing and waiting for your PR ;)
