### ISSUE TITLE
Error on Click Element even thought click was performed 

### ISSUE THREAD

**Issue by yaphatak** [facebook/WebDriverAgent#204]
This is response we get 
"value":"\n<XCSynthesizedEventRecord:0x1742262a0 name:'tap'> paths:\nPath 1:\n\t<XCPointerEvent:0x174244770 type:1 coordinate:(160,170) offset:0.00s>\n\t<XCPointerEvent:0x174249990 type:3 coordinate:(160,170) offset:0.20s>","sessionId":"123181F8-5253-4568-AB1B-79DBBB589E77","status":13}

ios 10 beta and real device. xcode beta2

**Comment by marekcirkos** [comment]
Is is consisted? Which iOS beta are you using?

**Comment by yaphatak** [comment]
This is iOS version : 10.0(14A5297c). This is consistent 

I also see this for setting text. This is When I commented code where it checks for hasKeyboardFocus. Because even though keyboard is in focus it tries to click at random location to  launch keyboard. So following error actually comes from 
 if (![FBKeyboard typeText:textToType error:&error]) {
    return FBResponseWithError(error);
  }
 Got response with status 200: {"value":"-[_NSXPCDistantObject _XCT_sendString:completion:]: unrecognized selector sent to instance 0x17167f000\n\n(\n\t0   CoreFoundation                      0x000000019368fec8 <redacted> + 148\n\t1   libobjc.A.dylib                     0x0000000192c884a8 objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000193696e98 <redacted> + 0\n\t3   CoreFoundation                      0x0000000193693e98 <redacted> + 916\n\t4   CoreFoundation                      0x0000000193591afc _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x00000001023aff7c __29+[FBKeyboard typeText:error:]_block_invoke + 272\n\t6   WebDriverAgentLib                   0x00000001023b32c0 +[FBRunLoopSpinner spinUntilCompletion:] + 172\n\t7   WebDriverAgentLib                   0x00000001023afcdc +[FBKeyboard typeText:error:] + 372\n\t8   WebDriverAgentLib                   0x00000001023c56b8 +[FBElementCommands handleGetValue:] + 332\n\t9   WebDriverAgentLib                   0x00000001023b22b4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208\n\t10  WebDriverAgentLib                   0x00000001023ab764 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 432\n\t11  RoutingHTTPServer                   0x000000010245e3cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t12  RoutingHTTPServer                   0x000000010245eb80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44\n\t13  libdispatch.dylib                   0x00000001930d9018 <redacted> + 16\n\t14  libdispatch.dylib                   0x00000001930eda54 <redacted> + 320\n\t15  libdispatch.dylib                   0x00000001930d9018 <redacted> + 16\n\t16  libdispatch.dylib                   0x00000001930ddbcc _dispatch_main_queue_callback_4CF + 1000\n\t17  CoreFoundation                      0x000000019363fc48 <redacted> + 12\n\t18  CoreFoundation                      0x000000019363d834 <redacted> + 1660\n\t19  CoreFoundation                      0x000000019356d764 CFRunLoopRunSpecific + 292\n\t20  Foundation                          0x0000000194008dcc <redacted> + 304\n\t21  Foundation                          0x000000019405d474 <redacted> + 88\n\t22  WebDriverAgentLib                   0x00000001023aa824 -[FBWebServer startServing] + 284\n\t23  WebDriverAgentRunner                0x000000010209bed0 -[UITestingUITests testRunner] + 120\n\t24  CoreFoundation                      0x0000000193695d80 <redacted> + 144\n\t25  CoreFoundation                      0x000000019358d1c4 <redacted> + 284\n\t26  XCTest                              0x0000000100209914 __24-[XCTestCase invokeTest]_block_invoke_2 + 388\n\t27  XCTest                              0x000000010023db6c -[XCTestContext performInScope:] + 208\n\t28  XCTest                              0x0000000100209778 -[XCTestCase invokeTest] + 268\n\t29  XCTest                              0x0000000100209e4c -[XCTestCase performTest:] + 460\n\t30  XCTest                              0x00000001002072f8 -[XCTestSuite performTest:] + 468\n\t31  XCTest                              0x00000001002072f8 -[XCTestSuite performTest:] + 468\n\t32  XCTest                              0x00000001002072f8 -[XCTestSuite performTest:] + 468\n\t33  XCTest                              0x00000001001f32a4 __25-[XCTestDriver _runSuite]_block_invoke + 56\n\t34  XCTest                              0x00000001002141a8 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 528\n\t35  XCTest                              0x00000001001f31dc -[XCTestDriver _runSuite] + 424\n\t36  XCTest                              0x00000001001f3d94 -[XCTestDriver _checkForTestManager] + 296\n\t37  XCTest                              0x000000010023f038 _XCTestMain + 628\n\t38  CoreFoundation                      0x000000019363fe7c <redacted> + 20\n\t39  CoreFoundation                      0x000000019363f678 <redacted> + 288\n\t40  CoreFoundation                      0x000000019363d4cc <redacted> + 788\n\t41  CoreFoundation                      0x000000019356d764 CFRunLoopRunSpecific + 292\n\t42  GraphicsServices                    0x0000000194f70198 GSEventRunModal + 180\n\t43  UIKit                               0x00000001994e68d0 <redacted> + 664\n\t44  UIKit                               0x00000001994e163c UIApplicationMain + 208\n\t45  XCTRunner                           0x00000001000b83d8 XCTRunner + 33752\n\t46  libdyld.dylib                       0x00000001931105b8 <redacted> + 4\n)","sessionId":"8DD88C52-093D-429C-933B-1AC1ECC21B39","status":13}

**Comment by marekcirkos** [comment]
According typing issue try master as I fixed it recently.

**Comment by yaphatak** [comment]
Thanks that works with latest master. :). You can close this
