### ISSUE TITLE
use fbsimctl, webDriverAgent cannot launch app

### ISSUE THREAD

**Issue by noshuai** [facebook/WebDriverAgent#212]
1. ./fbsimctl xxxxx launch_xctest /Users/xxxx/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest com.xxxx.test --port 8100 --listen

2. curl -X POST '-H "Content-Type: application/json"' -d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.mobilesafari\"}}"  http://172.xx.xxx.xxx:8100/session

Result: 
{
  "value" : "Application is not running, possibly crashed",
  "sessionId" : "A6F46856-4A94-4C2A-8E9E-5A8845672084",
  "status" : 10
}%

Other Info:
Before input "curl ..." ,  http://172.xx.xxx.xxx:8100/inspector can be open, but the Screen&Tree of Elements is blank.

**Comment by noshuai** [comment]
note:  **-- listen**

**Comment by phoebusliang** [comment]
Even add the blank, I still cannot start the app, cloud you give some help?
after run the fbsimctl the console is:

Listen Started: empty
Test Plan Started
Started initilizing for UI testing.

But the app launch and quit, I can't execute curl like:curl -X POST '-H "Content-Type: application/json"' -d "{\"desiredCapabilities\":{\"bundleId\":\"xxxx\"}}" http://localhost:8100/session
