### ISSUE TITLE
WebDriverAgent can support  "operated upon"?

### ISSUE THREAD

**Issue by diaojunxian** [facebook/WebDriverAgent#224]
In appium，there is a "click" ,it is called "perform", it can click the "operated upon".
It is meaning It can tap the element around places as "prompt critical".
Sorry,my English is poor.......

**Comment by diaojunxian** [comment]
Do you know my means?

**Comment by marekcirkos** [comment]
I am not sure what do you mean. What is an issue here? WDA does support tapping elements.

**Comment by diaojunxian** [comment]
I think I can't elaborate my meanings ,sorry.
