### ISSUE TITLE
use the same locate way

### ISSUE THREAD

**Issue by diaojunxian** [facebook/WebDriverAgent#225]
Similar elements, use the same locate way, one can locate, but cannot locate to another。
I use the `/inspector`  to  view elements.
it can locate like this:
```
Class:
StaticText
Name:
长按暂停
Value:
长按暂停
Label:
长按暂停
Rect:
{{118, 403}, {84, 20}}
isEnabled:
Yes
isVisible:
No
```
but this cannt locate:
```
Class:
StaticText
Name:
结束
Value:
结束
Label:
结束
Rect:
{{77.050000000000011, 424.55000000000001}, {26, 16}}
isEnabled:
Yes
isVisible:
No
```

**Comment by marekcirkos** [comment]
Could you elaborate on how you try to locate them? Which endpoint are you using and what parameters are you passing?

**Comment by diaojunxian** [comment]
I use the link text,and respectively, one  by label = '长按暂停' , another label = '结束', and when I passing the label = '长按暂停',returned value is not [ ],but another returned value is [].

**Comment by marekcirkos** [comment]
Do you use strict or partial link text? Maybe this is some UTF8 string matching issue.

**Comment by marekcirkos** [comment]
If you could supply your app and query samples you make that would be much easier for me to investigate.

**Comment by diaojunxian** [comment]
My iphone is 9.3.3，and I am sure it's not because of UTF8,anyway, can I ask a problem,that's if the element "isVisible" is "NO"，In what way can I find the element? @marekcirkos

**Comment by marekcirkos** [comment]
With iOS 9.x WDA will also return invisible elements.

**Comment by diaojunxian** [comment]
yes,I found it's my error，sorry，I close the issue.
