### ISSUE TITLE
Cannot Launch WebDriverAgent on Xcode 8 Beta 4

### ISSUE THREAD

**Issue by derekhoops** [facebook/WebDriverAgent#227]
tested on iPhone 6 plus on Xcode beta 4 and iOS 10 beta 4.  The latest WebDriverAgent code works fine in iOS 9.3.3

**Comment by marekcirkos** [comment]
Do you got any error?

**Comment by derekhoops** [comment]
Aug  2 11:14:08 ioss-iPhone symptomsd(SymptomEvaluator)[123] <Error>: Can't get most elevated app state from dictionary <private>
Aug  2 11:14:08 ioss-iPhone symptomsd(SymptomEvaluator)[123] <Notice>: 378 com.apple.test.WebDriverAgentRunner-Runner: Unknown (most elevated: Unknown)
Aug  2 11:14:08 ioss-iPhone symptomsd(SymptomEvaluator)[123] <Notice>: 378 com.apple.test.WebDriverAgentRunner-Runner: Terminated (most elevated: Terminated)

**Comment by derekhoops** [comment]
Here's the whole log

[ios8Crash.txt](https://github.com/facebook/WebDriverAgent/files/398460/ios8Crash.txt)

**Comment by marekcirkos** [comment]
Did you try to run it on device? From your logs it is clear that WDA didn't start. Most likely this is code signing issue. 
Try: 
- Removing WDA app from phone
- Clear Xcode data
- Check code sign settings
- Reboot device 

Logs entry I am referring to:
`Aug  2 11:14:08 ioss-iPhone XCTRunner(XCTest)[378] <Notice>: (dlopen_preflight(/var/containers/Bundle/Application/BE647A81-678D-485D-94E2-587E4326B62F/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/KissXML.framework/KissXML
  Referenced from: /private/var/containers/Bundle/Application/BE647A81-678D-485D-94E2-587E4326B62F/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/BE647A81-678D-485D-94E2-587E4326B62F/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML: required code signature missing for '/private/var/containers/Bundle/Application/BE647A81-678D-485D-94E2-587E4326B62F/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML'`

**Comment by derekhoops** [comment]
Yup, that was it!  Rechecked the code sign settings and it's working!  Thanks for pointing it out!
