### ISSUE TITLE
issue with Scrolling 

### ISSUE THREAD

**Issue by yaphatak** [facebook/WebDriverAgent#228]
I see there are 2 issues with this particular code 

https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement%2BFBScrolling.m#L83-L85

1. First we should look for either CollectionView or Table  (Preferably CollectionView as I have seen CollectionView is placed in Table) and then should go for ScrollView as ScrollView is superclass of CollectionView and Table.

This causes scroll fail  in scenarios where parent is child of scrollview (say CollectionView or Table)
 
2. How do we handle situation situation where scrollview object here is not visible itself.I think there should be recursive call 
something like this 
   if(![scrollView fb_isVisible]) {
      [scrollView fb_scrollToVisibleWithNormalizedScrollDistance:FBScrollToVisibleNormalizedDistance error:error];
  }

I cant really do this as scrollview is XCElementSnapshot and not XCUIElement object.

We are facing issue because of these as we cant scroll to element whose parent is not visible.

I am willing to fix this. First one is easy fix. I am not sure how can I fix second one unless we implement scrolling logic on XCElementSnapshot object itself. Hope you guys can guide.

**Comment by marekcirkos** [comment]
Fact that CollectionView and TableView inherits from Scrollview doesn't matter in XCTest. Every element has a type and collectionView is type of `XCUIElementTypeCollectionView` not `XCUIElementTypeScrollView`. Only simple scrollview has type of `XCUIElementTypeScrollView`.

Anyway, If you consider view hierarchy with nested scrollviews, there isn't a golden general solution for scrolling.

Best approach would be to scroll in steps. E.g. request scroll to make nested scrollview visible, than scroll to inner element.

**Comment by yaphatak** [comment]
> Best approach would be to scroll in steps. E.g. request scroll to make nested scrollview visible, than scroll to inner element.

Don't you think this will be crazy because you need to know all your parents and then their visibility.  One will end up writing lots of test code just to scroll one target element. Again I am talking from Appium point of view here. Whenever we did scrollintoview or rather click it always brought that element into view. So we dont have to do write that extra code at test side.

I can give  one more shot to implement this nested scroll in WebDriverAgent itself. But will you guys accept that change? or we can keep that as separate endpoint

**Comment by yaphatak** [comment]
Can we do bare minimum like this ?
` const NSUInteger maxScrollCountParent = 5;

  NSUInteger scrollCountParent = 0;
 
 while (![scrollView fb_isVisible] && scrollCountParent < maxScrollCountParent) {
      [[self application] fb_scrollDown];
      scrollCountParent++;
  }
`

**Comment by yaphatak** [comment]
@marekcirkos : Can you comment on this?

**Comment by marekcirkos** [comment]
Most common issues with scrolling you need to consider are:
- xctest is misreporting elements by reporting duplicates, reporting bad frames or not reporting views,
- client timeouts due to slow scroll. 
- iOS 10 stopped reporting invisible elements. It still reports cells, but from my experience it probably only works on simple view hierarchies.

If you plan to add complex scrolling handling it becomes exponential harder to handle all cases correctly while handling all xctest bugs. This will make testing WDA much much harder and less reliable. Also keep in mind longer response times due to slow scrolling.

I think much better approach would be to keep WDA endpoints as simple as possible and make client handle this the way it wants as client/test knows best which view should be scrolled.

Ideally I would like to kill `scrollToVisisble` as It causes to much trouble now and with iOS 10 it will be even worse.

**Comment by yaphatak** [comment]
Thanks for explanation. We can always increase client timeout. I dont see that as major issue because if someone is writing selenium test then,writing 3 scroll actions with http call is way slower than doing all 3 scrolls in one call. What we can do is we can wrap `fb_scrollToVisibleWithError` function in other function and whenever it throws error indicating parent is not visible then we can do scroll down. Will this still be not stable? IF we cant do this in WDA, we will do this on appium side.

**Comment by marekcirkos** [comment]
Commented on https://github.com/facebook/WebDriverAgent/pull/231#issuecomment-238490340 and https://github.com/facebook/WebDriverAgent/pull/230#issuecomment-238491693

**Comment by marekcirkos** [comment]
Are you happy to close it?

**Comment by yaphatak** [comment]
Yes. Can you please look at this https://github.com/facebook/WebDriverAgent/pull/246?

**Comment by marekcirkos** [comment]
Dropping. If you want to restart please re-open PR or/and issue.
