### ISSUE TITLE
Fix "Switch" status in inspector

### ISSUE THREAD

**Issue by diaojunxian** [facebook/WebDriverAgent#232]
![Like the picture](https://cloud.githubusercontent.com/assets/19700467/17352359/9fcb7f02-5968-11e6-8d0b-fe02532cbbe1.jpg)
When I open or close the picture,  I get the swtich element attributes "accessible, enalbed,displayed" both are "True".
So,my issue is how can I judge the element's status by element's attribue?

**Comment by marekcirkos** [comment]
'Value' attribute is true/false depending on switch state. Looks like inspector does not parse bool values properly so you can't see it here, but you can try /source command to confirm that.

**Comment by diaojunxian** [comment]
Yes ,I can do it .Thanks

**Comment by diaojunxian** [comment]
@marekcirkos Then I wish to ask you a question,possible，it is very simple。The question is that the relations between  WebDriverAgent  and Uiautomation?

**Comment by diaojunxian** [comment]
@marekcirkos thanks a lot.

**Comment by marekcirkos** [comment]
I am proud to say, that there is NO relation with UIAutomation. We only use XCTest

**Comment by diaojunxian** [comment]
@marekcirkos OK，I saw the code,and also thought that,you are  really awful.Thanks a lot.

**Comment by marekcirkos** [comment]
awful?

**Comment by diaojunxian** [comment]
haha,probable my English is very very poor,I mean you are especially excellent and fantastic.

**Comment by diaojunxian** [comment]
@marekcirkos  Can I ask you a question?When I want to achieve from right slip to left， I lanched request like this`curl -X POST -H "Content-Type: application/json" -d "{fromX:120,fromY:180,toX:50,toY:180,duration:0.8}"  http:192.168.1.101/8100/session/$SESSION_ID/uiaTarget/0/dragfromtoforduration`  
But it can't realize my goal,and turn into likes "tap" not "swipe"

**Comment by diaojunxian** [comment]
@marekcirkos help....help......

**Comment by codeskyblue** [comment]
Everything goes fine on my iPhone6P.

**Comment by diaojunxian** [comment]
But my iphone is 5S

**Comment by marekcirkos** [comment]
Moved drageanddrop issue to https://github.com/facebook/WebDriverAgent/issues/239
