### ISSUE TITLE
Deployment of WDAR

### ISSUE THREAD

**Issue by michaelgallacher** [facebook/WebDriverAgent#234]
I'm trying to integrate WDA into my CI workflow.   Right now, I use the 'xcodebuild ... test' approach, but this does a full build of WebDriverAgentRunner before pushing to the (physical) device.  I want instead to keep a pre-built WDAR on the target device and launch it as needed.  

Obviously just launching the app won't work, as it needs to be launched in the context of a test.  Is there a command (xcodebuild or otherwise) that will do this, or do I have to build WDAR every time I start a new test?

**Comment by marekcirkos** [comment]
So with Xcode 8 you can use xcodebuild to only execute exiting xctest.
You can also have a look at tool we use for devices https://github.com/facebook/FBSimulatorControl/tree/master/FBDeviceControl.
