### ISSUE TITLE
Question about how to get top app bundle_id

### ISSUE THREAD

**Issue by codeskyblue** [facebook/WebDriverAgent#238]
I dont known if there is such api?

**Comment by marekcirkos** [comment]
Just add `bundleId` to `desiredCapabilities`

https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBSessionCommands.m#L39

**Comment by codeskyblue** [comment]
@marekcirkos You may misunderstood my means. What you provide is when start a new session(app), But when app crash, how can I know if the app crashed, My idea now is to get a current top app, to judge if app is still running.

**Comment by marekcirkos** [comment]
Assuming you started the application that crashes, next request you make should respond with error "Application is not running, possibly crashed"

**Comment by codeskyblue** [comment]
soga
