### ISSUE TITLE
Issues with dragfromtoforduration

### ISSUE THREAD

**Issue by marekcirkos** [facebook/WebDriverAgent#239]
Moved from https://github.com/facebook/WebDriverAgent/issues/232

@diaojunxian 

> @marekcirkos Can I ask you a question?When I want to achieve from right slip to left， I lanched request like thiscurl -X POST -H "Content-Type: application/json" -d "{fromX:120,fromY:180,toX:50,toY:180,duration:0.8}" http:192.168.1.101/8100/session/$SESSION_ID/uiaTarget/0/dragfromtoforduration
But it can't realize my goal,and turn into likes "tap" not "swipe"

**Comment by marekcirkos** [comment]
@diaojunxian What iOS version are you running?

**Comment by diaojunxian** [comment]
Now I found when I lanched request 
```
curl -X POST -H "Content-Type: application/json" -d "{fromX:300,fromY:180,toX:0,toY:180,duration:0.8}" http:192.168.1.101/8100/session/$SESSION_ID/uiaTarget/0/dragfromtoforduration
```
I found it works.Thanks a lot.

**Comment by diaojunxian** [comment]
And my iOS version is 9.3.3

**Comment by marekcirkos** [comment]
Closing since it works for you
