### ISSUE TITLE
Feature request: API to get current test device info

### ISSUE THREAD

**Issue by codeskyblue** [facebook/WebDriverAgent#240]
For example: to get device name, udid, width x height

**Comment by marekcirkos** [comment]
That should be easy to implement. Have a look here https://github.com/facebook/WebDriverAgent/blob/17af6bc08884e0e10f944e3ea6ae6e47c2652944/WebDriverAgentLib/Commands/FBSessionCommands.m#L58

**Comment by codeskyblue** [comment]
Can WDA add udid and screen size to status?

**Comment by marekcirkos** [comment]
You can use `UIKit` for that.

**Comment by codeskyblue** [comment]
Is UIKit part of WDA?

**Comment by marekcirkos** [comment]
You definitely can use `UIKit` as we already do. Unfortunately getting UDID is more tricky as Apple removed all APIs to get UDID.

**Comment by codeskyblue** [comment]
Thanks @marekcirkos , I think I can write a http proxy on the mac, to patch uuid to it.
