### ISSUE TITLE
pagesource endpoint is extremely slow on certain pages 

### ISSUE THREAD

**Issue by yaphatak** [facebook/WebDriverAgent#241]
I believe this is probably because ios reports duplicate elements. But I observed that `application debugDescription` returns pretty fast. We have user scenario where we verify there existance certain text  rather than finding element. And since pagesource call is slow we are blocked. Is it fine if we have separate endpoint that returns `debugDescription` or you think we should do that in our own extension to WDA?

**Comment by marekcirkos** [comment]
Not sure if I understand your case correctly. Why you can't search for element with given value? What `/source` endpoint gives you that you can't find with element query?

**Comment by yaphatak** [comment]
text and element both are dynamic. So we used to just do `driver.Pagesource.contians("expected dynamic text")`. But now since Pagesource is kinda slow, i was looking for alternatives. And I see that debugDescription is faster. But we cant get this as its not supported by any endpoint. So i was wondering if we can add some endpoint that can return debugDescription.

**Comment by marekcirkos** [comment]
You should be able to search for element with given text. Even if it changes you can keep queuing it same way you use `/source`

**Comment by marekcirkos** [comment]
@yaphatak If you have other questions, please reopen this issue
