### ISSUE TITLE
Add system alerts to tree command and inspector

### ISSUE THREAD

**Issue by linkin-xiao** [facebook/WebDriverAgent#247]
When I try to use WDA to control Safari to install an ipa through OTA，but the WDA can not get any element in the window below:
![image](https://cloud.githubusercontent.com/assets/20454146/17654049/12af10da-62d1-11e6-9d1a-368d8fa51a60.png)

How can I get the elements in this window?
Thanks!

**Comment by marekcirkos** [comment]
It might be system alert. Try using alert command https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBAlertViewCommands.m

**Comment by linkin-xiao** [comment]
The iphone upside is iphone 6 with ios 9.1 .
I use another device (iphone SE) with ios 9.3.2 to run this testcase , and it works .
So I think it the problem of ios firmware version compatibility.

**Comment by marekcirkos** [comment]
Inspector only shows alerts created by inspected application. I think it would make sense to also detect system alerts and inject them to tree command. This way inspector will show them to and mark appropriately.

**Comment by marekcirkos** [comment]
@linkin-xiao I played with it on device, and actually inspector does show any alerts on AppStore and Safari.

**Comment by marekcirkos** [comment]
@linkin-xiao can you check if iOS 10 works?

**Comment by marekcirkos** [comment]
If it is still an issue please reopen.
