### ISSUE TITLE
can building inspector not happen by default?

### ISSUE THREAD

**Issue by jlipps** [facebook/WebDriverAgent#248]
Hi @marekcirkos,

We are now bundling WebDriverAgent with Appium via appium-xcuitest-driver. We don't need to use the inspector at all for this purpose, and it is causing problems given that when WebDriverAgent is published as part of the Appium bundle, its committed `node_moduels` directory is omitted. Thus WebDriverAgent fails to build since `npm install` has not happened in the Inspector dir.

It would greatly simplify things if building the inspector was opt-in instead of opt-out. Are you open to a PR to this effect?

**Comment by jlipps** [comment]
Nevermind, looks like we found an easy way to set the appropriate env var to not build the inspector.

**Comment by marekcirkos** [comment]
Only time we build inspector is when you call `./Scripts/bootstrap.sh`. Calling it without any parameters will fetch dependencies and build inspector. However you can request only dependency fetch by adding `-d` or only inspector build by adding `-i`. So it should be easy for you to adjust it.
