### ISSUE TITLE
Output message when server is ready to accept requests

### ISSUE THREAD

**Issue by Jonahss** [facebook/WebDriverAgent#25]
I have a test which programmatically launches WebDriverAgent on a simulator and hits the /tree endpoint after the WebDriverAgent process outputs its first message (`Built at XX:XX:XX`). This test fails.

But if I wait for 3 seconds before issuing the http request, it passes.

I think we should output a message when the http server is ready. I suggest something similar to appium like:
`WebDriverAgent REST http interface listener started on 0.0.0.0:8100`

**Comment by lawrencelomax** [comment]
This makes a bunch of sense. I'd also suggest that you can do this from the client without needing to tail stdout of `WebDriverAgent` by using a wait-loop to poll for [an active `/status/`](https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/WebDriverCommands/FBSessionCommands.m#L26) endpoint.
