### ISSUE TITLE
can't click element

### ISSUE THREAD

**Issue by diaojunxian** [facebook/WebDriverAgent#250]
when I update WDA version number to '14820677342fc035bb1df29a206d613542dc5c13' ，I found Xcode console log told me it can found the element but not click it ， and then I made the version number to '723a0284da7ed9259552666813e328fe3247ed29'，it worked，that is the same element and the same page.
Can you help me?

**Comment by marekcirkos** [comment]
Do you mean that tapping is not working or logging is missing?

**Comment by diaojunxian** [comment]
@marekcirkos Yes,so now I'm afraid to update WDA version.

**Comment by marekcirkos** [comment]
Can you provide more information? Maybe screenshot from inspector or best would be PR with failing test case

**Comment by diaojunxian** [comment]
@marekcirkos Sorry,it's my fault.My iphone is iphone5s,and its version is 9.3.3,then my problems is I found when I update the WDA to the commit version number  to "14820677342fc035bb1df29a206d613542dc5c13" , I found there were some elements coun't execute "tap", and there were no errors, so I checked over the log, I found the log had found the element,but "tap" coun't work.Then I made the version number to '723a0284da7ed9259552666813e328fe3247ed29',the same app page and the same element it could work and "tap".

**Comment by marekcirkos** [comment]
Hmm taping works for us, so probably you hit some edge case. Can you please provide application sample? Otherwise it would be hard for me to help you.

**Comment by marekcirkos** [comment]
We can't help you if you don't provide more information. Please reopen ticket if it still doesn't work for you and you have some more information
