### ISSUE TITLE
Changing Element IDs

### ISSUE THREAD

**Issue by mirkara** [facebook/WebDriverAgent#259]
Are the element IDs suppose to change every run?

EDIT: It seems to generate a new element ID every time I query the element.

**Comment by marekcirkos** [comment]
Every query potentially can return different items, depending on context so it will always return different IDs. Even if underneath they refer to the same element. Why this is an issue for you?

**Comment by mirkara** [comment]
I was hoping to use this for automation but it looks like that's not possible.

Let me clarify a bit, every time I query the elements on the landing page of an app -- those element IDs changes every time even though the page is the same.

**Comment by jlipps** [comment]
@mirkara element ids are variable and not guaranteed to be the same. But the only purpose of an element id is to use as a handle for subsequent action. Why do you care about element ids anyway?

**Comment by marekcirkos** [comment]
Also, fact that you get new objectIDs doesn't mean that old ones are invalid. They simply point to the same element.

**Comment by marekcirkos** [comment]
@mirkara are you happy to close it?
