### ISSUE TITLE
Carthage Github API Rate Limiting

### ISSUE THREAD

**Issue by ssynix** [facebook/WebDriverAgent#260]
## Problem
When running the bootstrap.sh script, carthage failed to install dependencies due to reaching the github API rate limit (probably due to how our company manages its traffic to the external network).

>"API rate limit exceeded for 'ip address'. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"

## Solution
I modified the script to run `carthage bootstrap `**`--use-ssh`**.

**Comment by codeskyblue** [comment]
github ssh usally blocked in China. orz

**Comment by ssynix** [comment]
We can perhaps pass it as a flag to the script? It could also be documented somewhere in case more people run into the same problem.

**Comment by marekcirkos** [comment]
Yeah, switch might be a good idea.

**Comment by marekcirkos** [comment]
@ssynix, @codeskyblue feel free to create an PR. :)

**Comment by marekcirkos** [comment]
Landed
