### ISSUE TITLE
Do we need to signature webdriveragent when running test on real device?

### ISSUE THREAD

**Issue by caizhenxing** [facebook/WebDriverAgent#261]
Dear all,

when i run test on real device with webdriveragent, i got the following error:

The following build commands failed:
	CodeSign /Users/ucar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ecncypxshfwjehdvedwmpomonice/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework
	CodeSign /Users/ucar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ecncypxshfwjehdvedwmpomonice/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Frameworks/KissXML.framework
	CodeSign /Users/ucar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ecncypxshfwjehdvedwmpomonice/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Frameworks/Peertalk.framework
(3 failures)

I real need your help!

**Comment by marekcirkos** [comment]
Anything you run on device has to be code signed ;).

**Comment by caizhenxing** [comment]
Thx, got it.
