### ISSUE TITLE
Can't click/tap on keyboard search button when device in landscape mode

### ISSUE THREAD

**Issue by wfanforever** [facebook/WebDriverAgent#262]
I originally post this issue in here: https://github.com/appium/appium-xcuitest-driver/issues/107, but later I noticed this is the better place to ask this question. 

I'm seeing issue that having trouble to click on the search button when device is on landscape mode.

I followed the wiki here:
https://github.com/facebook/WebDriverAgent/wiki/Queries#tapping-element

And here are the steps to reproduce:
- I launch the app, for example:
  `curl -X POST '-H "Content-Type: application/json"' -d "{\"desiredCapabilities\":{\"bundleId\":\"com.facebook.IntegrationApp\"}}" http://localhost:8100/session`
- Background the app, on the spotlight search I tried to get the search button element id: 
  `curl -X POST '-H "Content-Type: application/json"' -d "{\"using\":\"predicate string\",\"value\":\" elementType == 9 and label == 'Search' \"}" http://localhost:8100/session/03303656-C5D9-4AAB-A0A6-D1802F733C4F/elements`
  Returned result: 

```
"value" : [
    {
      "ELEMENT" : "25421503-61B3-48A6-A39D-6670C87F1BAF",
      "type" : "XCUIElementTypeButton",
      "label" : "Search"
    }
  ],
  "sessionId" : "03303656-C5D9-4AAB-A0A6-D1802F733C4F",
  "status" : 0
```
- Try to click on it using the curl 
  `curl -X POST '-H "Content-Type: application/json"' -d "" http://localhost:8100/session/03303656-C5D9-4AAB-A0A6-D1802F733C4F/element/25421503-61B3-48A6-A39D-6670C87F1BAF/click`

So instead of click on the search button, it click on the whitespace.
<img width="759" alt="screen shot 2016-08-26 at 10 11 15 am" src="https://cloud.githubusercontent.com/assets/21108234/18015982/eb5439aa-6b7e-11e6-8712-3ddb39444286.png">

**Comment by marekcirkos** [comment]
I noticed that as well. From what I have seen it happens only on iOS 10.x so most likely it is system bug.

**Comment by wfanforever** [comment]
This is also happens on 9.3 devices.

**Comment by mykola-mokhnach** [comment]
@wfanforever Could it be because of https://github.com/facebook/WebDriverAgent/issues/300 ? Can you try to rotate to portrait, click the button and then rotate back to landscape as a workaround?

**Comment by marekcirkos** [comment]
@mykola-mokhnach I think rotating does not "transfer" coordinates. It might be because of XCTest issue or we are rotating device in a wrong way.

**Comment by marekcirkos** [comment]
@wfanforever  Can you check if it happens with new Xcode version?

**Comment by mykola-mokhnach** [comment]
@marekcirkos Unfortunately changing rotation/orientation does not help - I've tried all available API calls and this is still broken. 9.3 works properly though. It is only broken in 9.3 if NSAlert dialog is shown. In this case I have to rotate back to portrait temporarily to workaround alert/accept and alert/dismiss functionality.

**Comment by marekcirkos** [comment]
@mykola-mokhnach this is sad. That means we need to patch it on WDA side. I hoped Apple would fix it by now.

**Comment by AliNL** [comment]
Hi, has it been fixed? I'm facing the same bug. Does the latest version works?

**Comment by marekcirkos** [comment]
Not yet, sorry

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/dc0a655094ef739bf8cd6217a740397b8c9cf7c3
