### ISSUE TITLE
Application background/foreground failed when device in landscape mode

### ISSUE THREAD

**Issue by wfanforever** [facebook/WebDriverAgent#264]
A quick try on IntegrationApp:

`curl -X POST '-H "Content-Type: application/json"' -d "{\"duration\":3}" http://localhost:8100/session/DBA1E8D0-0099-4754-9188-BBD1851C7FE/deactivateApp`
```
{
  "value" : "Error Domain=com.facebook.WebDriverAgent Code=1 \"Timeout waiting for application to activate\" UserInfo={NSLocalizedDescription=Timeout waiting for application to activate}",
  "sessionId" : "DBA1E8D0-0099-4754-9188-BBD1851C57FE",
  "status" : 13
}
```

**Comment by marekcirkos** [comment]
Is this same issue as here https://github.com/facebook/WebDriverAgent/issues/269?

**Comment by wfanforever** [comment]
yeaa looks like the same issue. @marekcirkos

**Comment by marekcirkos** [comment]
Closing duplicate of #269
