### ISSUE TITLE
How to setup and use USB support?

### ISSUE THREAD

**Issue by lambourn** [facebook/WebDriverAgent#265]
When testing on a physical iOS device it seems as if it's required that the OS X machine running tests and the iOS device are on the same network. In the [docs](https://github.com/facebook/WebDriverAgent/wiki/USB-support) it says that USB support is an option when access to Wifi is restricted.

Any hints on how to setup and use the USB support?

**Comment by yaphatak** [comment]
install libimobiledevice and then use iproxy https://github.com/libimobiledevice/libusbmuxd/blob/4397b3376dc4e4cb1c991d0aed61ce6482614196/tools/iproxy.c
iproxy LOCAL_TCP_PORT DEVICE_TCP_PORT [UDID]

**Comment by marekcirkos** [comment]
Or have a look here https://github.com/facebook/WebDriverAgent/wiki/USB-support.

**Comment by skytraveler** [comment]
I changed  testRunner  of  UITestingUITests.m as below
`
- (void)testRunner
{
  [FBConfiguration shouldShowFakeCollectionViewCells:YES];
   //[[FBWebServer new] startServing];
    [[FBHTTPOverUSBServer new] startServing];  
  
}`

but after the  app I installed in the real device  using xcodebuild I got the information below.

Test Suite 'All tests' started at 2017-03-07 16:24:21.703
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-03-07 16:24:21.704
Test Suite 'UITestingUITests' started at 2017-03-07 16:24:21.704
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-03-07 16:24:21.706
    t =     0.00s     Set Up
    t =     0.01s     Tear Down
Test Case '-[UITestingUITests testRunner]' passed (0.007 seconds).
Test Suite 'UITestingUITests' passed at 2017-03-07 16:24:21.713.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.007 (0.009) seconds
Test Suite 'WebDriverAgentRunner.xctest' passed at 2017-03-07 16:24:21.713.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.007 (0.009) seconds
Test Suite 'WebDriverAgentLib.framework' started at 2017-03-07 16:24:21.714
Test Suite 'WebDriverAgentLib.framework' passed at 2017-03-07 16:24:21.714.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'All tests' passed at 2017-03-07 16:24:21.715.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.007 (0.012) seconds
** TEST SUCCEEDED **

I think I can no longer connect to it anymore 

and I think if  I want to use USBServer ,I have to Write some code to Use the  FBHTTPOverUSBClient.

Could you provide some example about how to use it ?

**Comment by marekcirkos** [comment]
@skytraveler If you run WDA out of the box on device, it will listen on USB.
