### ISSUE TITLE
only show "test succeeded" on my iPhone 5C

### ISSUE THREAD

**Issue by sherlockZ** [facebook/WebDriverAgent#266]
usually, by command + U it will install an WebDriverAgent app in iPhone.But when I do it on my iPhone 5C (9.3.5) ,Xcode would show an alertView with message:"test succeeded" .The app will not install in my 5C

**Comment by codeskyblue** [comment]
Close Xcode and relaunch it. Or you can restart you iPhone. Anyway I fixed this problem by this steps.

**Comment by sherlockZ** [comment]
thanks, it work
