### ISSUE TITLE
Typin fails sometimes with this error

### ISSUE THREAD

**Issue by yaphatak** [facebook/WebDriverAgent#267]
Error Domain=com.facebook.WebDriverAgent Code=1 "Timeout waiting for keybord to stop animating" UserInfo={NSLocalizedDescription=Timeout waiting for keybord to stop animating}

**Comment by marekcirkos** [comment]
Can you be more descriptive on that issue? What iOS are you using? Did you have any thoughts why or when it might be failing?

**Comment by marekcirkos** [comment]
@yaphatak ?

**Comment by yaphatak** [comment]
Sorry for late reply. Got busy with other things. This was happening because we were doing `textbox.clear` and when I looked at WDA code , it is literally doing backspace for each character. This issue went away as soon I removed `clear` call. But now we are getting this error at different times `Error Domain=XCTestManagerErrorDomain Code=14 "Timed out waiting for key event to complete" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete}`

This is all on real device ios 10 beta 8, xcode beta 6

**Comment by marekcirkos** [comment]
Does it happen on released iOS?

**Comment by yaphatak** [comment]
Yes this is still continue to happen on ios 10.0.1

**Comment by marekcirkos** [comment]
Is this persistent or random? 
I have seen this issue on slower host machines. This is why Integration tests are flaky as well,due to XCTest flakiness (not much that we can do).
You can try special handle this issue as error message is distinct.

**Comment by marekcirkos** [comment]
You added "FBInvisibleParentScrollingTests" to be compiled as part of "WebDriverAgentRunner". It should only be compiled into IntegrationTests

**Comment by yaphatak** [comment]
okay Thanks!. Its not persistent but once it happens it is persistent. Only way out is kill `WDA` I am closing this as we cant do anything until Apple does something about it

**Comment by marekcirkos** [comment]
Hmm, You should be able to recover from this error, by cleaning text and re-enering it. 
Maybe you have different underlying issue. 
Do you boot WDA per test or keep it running in between tests?

**Comment by yaphatak** [comment]
keep it running and no boot per test. This is on real device

**Comment by marekcirkos** [comment]
Yeah, that would fit 900 sec issue. Definitely check if running single test over 900 sec fails on devices and open ticket for Apple.

**Comment by yaphatak** [comment]
Thanks @marekcirkos : That explains small stress tool I wrote doesn't work after 15 minutes. But for tests since none of them is more than 3 minutes doesn't and run continuously. So they last little longer for sure. Is there way not to build but just run like simulator but for device

**Comment by marekcirkos** [comment]
You can use [FBDeviceControl](https://github.com/facebook/FBSimulatorControl/tree/master/FBDeviceControl) framework to write simple app for it.

**Comment by zoutingapple** [comment]
IOS version 9.3.5,Xcode 8,also show this issue,i should how to do,I tried the above method.
-------------------------------------------------------------------------------------------
macaca.webdriverexception.WebDriverException: 
Error: WebDriverError.UNKNOWN_ERROR
Message: Error Domain=com.facebook.WebDriverAgent Code=1 "Timeout waiting for keybord to stop animating" UserInfo={NSLocalizedDescription=Timeout waiting for keybord to stop animating}
