### ISSUE TITLE
deactivateApp doesn't reactivate if target app is not in view

### ISSUE THREAD

**Issue by ravron** [facebook/WebDriverAgent#269]
Steps to reproduce:

1. Install app under test. For instance, an app with bundle ID `com.acme.TestApp`.
1. Install and launch WDA into the same page in Springboard.
1. Change to a different page in Springboard that doesn't include TestApp.
1. Start a session with `com.acme.TestApp`.
1. Send the `deactivateApp` command.
1. Note that the app never reactivates.

See the following log for WDA output:
```
 t =     6.28s     Find the Application "com.acme.TestApp" 0x7af96900
 t =     6.28s         Snapshot accessibility hierarchy for com.acme.TestApp
 t =     6.37s     Find the Application "com.acme.TestApp" 0x7af96900
 t =     6.37s         Use cached accessibility hierarchy for com.acme.TestApp
 t =     6.38s     Pressing Home button
 t =    11.40s     Find the Application "com.apple.springboard" 0x7d66def0
 t =    11.40s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    11.50s     Find the Any
 t =    11.50s         Use cached accessibility hierarchy for com.apple.springboard
 t =    11.51s         Find: Descendants matching type Any
 t =    11.52s         Find: Elements matching predicate 'identifier == "TestApp"'
 t =    11.53s     Find the "TestApp" Icon
 t =    11.53s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    11.62s         Find: Descendants matching type Any
 t =    11.63s         Find: Elements matching predicate 'identifier == "TestApp"'
 t =    11.71s     Find the Application "com.apple.springboard" 0x7d66def0
 t =    11.71s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    16.99s     Find the "TestApp" Icon
 t =    16.99s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    17.09s         Find: Descendants matching type Any
 t =    17.10s         Find: Elements matching predicate 'identifier == "TestApp"'
 t =    17.11s     Find the Application "com.apple.springboard" 0x7d66def0
 t =    17.11s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    22.31s     Find the "TestApp" Icon
 t =    22.31s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    22.41s         Find: Descendants matching type Any
 t =    22.41s         Find: Elements matching predicate 'identifier == "TestApp"'
```
The log will continue in that pattern until I manually swipe the Springboard back to the page that includes TestApp. 

It [looks like WDA should be scrolling to put the element on screen][1], but it doesn't appear to ever return from [trying to find the element in the first place][2].

[1]: https://github.com/facebook/WebDriverAgent/blob/70616e87aa59663fd5bfd8c33d5addcc1fc49994/WebDriverAgentLib/FBSpringboardApplication.m#L42-L44
[2]: https://github.com/facebook/WebDriverAgent/blob/70616e87aa59663fd5bfd8c33d5addcc1fc49994/WebDriverAgentLib/FBSpringboardApplication.m#L39-L41

**Comment by marekcirkos** [comment]
Which iOS are you testing? It should work on iOS 9. Tho this behaviour is expected on iOS 10.x and definitely needs fixing.

**Comment by ravron** [comment]
I see. This was on iOS 10.0 beta. I may take a look at fixing this then.

**Comment by ravron** [comment]
Update: this is also broken on iOS 9.3 with Xcode 7.3.1. If the installed app is on a homescreen page that comes before the one that appears when the app is deactivated, WDA will attempt to continue to swipe right until it hits the 25 swipe limit, and then report failure. 

```
 t =    27.52s     Find the Application "com.apple.mobilesafari" 0x7b6aa6c0
 t =    27.52s         Snapshot accessibility hierarchy for com.apple.mobilesafari
 t =    27.56s     Find the Application "com.apple.mobilesafari" 0x7b6aa6c0
 t =    27.56s         Use cached accessibility hierarchy for com.apple.mobilesafari
 t =    27.57s     Pressing Home button
 t =    30.59s     Find the Application "com.apple.springboard" 0x7b75d9f0
 t =    30.59s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    30.65s     Find the Any
 t =    30.65s         Use cached accessibility hierarchy for com.apple.springboard
 t =    30.66s         Find: Descendants matching type Any
 t =    30.67s         Find: Elements matching predicate 'identifier == "Safari"'
 t =    30.68s     Find the "Safari" Icon
 t =    30.68s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    30.74s         Find: Descendants matching type Any
 t =    30.75s         Find: Elements matching predicate 'identifier == "Safari"'
 t =    30.86s     Find the Application "com.apple.springboard" 0x7b75d9f0
 t =    30.86s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    35.40s     Find the "Safari" Icon
 t =    35.40s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    35.46s         Find: Descendants matching type Any
 t =    35.48s         Find: Elements matching predicate 'identifier == "Safari"'
 t =    35.48s     Find the Application "com.apple.springboard" 0x7b75d9f0
 t =    35.48s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    40.02s     Find the "Safari" Icon
 t =    40.02s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    40.09s         Find: Descendants matching type Any
 t =    40.10s         Find: Elements matching predicate 'identifier == "Safari"'
 t =    40.10s     Find the Application "com.apple.springboard" 0x7b75d9f0
 t =    40.11s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    44.62s     Find the "Safari" Icon
 t =    44.62s         Snapshot accessibility hierarchy for com.apple.springboard
 t =    44.68s         Find: Descendants matching type Any
 t =    44.70s         Find: Elements matching predicate 'identifier == "Safari"'
 t =    44.70s     Find the Application "com.apple.springboard" 0x7b75d9f0
 t =    44.70s         Snapshot accessibility hierarchy for com.apple.springboardt =    44.70s         Snapshot accessibility hierarchy for com.apple.springboard
```

**Comment by ravron** [comment]
Ok, I've discovered the root cause of this problem. It actually doesn't have anything to do with the iOS version – it has to do with the layout of apps on the page of the homescreen reached when the home button is pressed. 

`fb_scrollToVisibleWithNormalizedScrollDistance:error:` [uses the vector from the first visible cell to the last visible cell][1] to determine whether the scrollview it's looking at scrolls horizontally or vertically. If your homescreen looks like this:

<img width="432" alt="wda-broken" src="https://cloud.githubusercontent.com/assets/5354796/18404664/c9740aa4-76a0-11e6-8708-72814f050080.png">

then `fb_scrollToVisibleWithNormalizedScrollDistance:error:` incorrectly decides that the scrollview is vertical, since the vector from the Calendar icon to the Safari icon is purely vertical. If it looks like this, though:

<img width="432" alt="wda-works" src="https://cloud.githubusercontent.com/assets/5354796/18404692/f8995d98-76a0-11e6-9b0b-311ac73311f7.png">

then `fb_scrollToVisibleWithNormalizedScrollDistance:error:` gets lucky, correctly deciding that the scrollview is horizontal, since the vector from the Calendar icon to the Settings icon is more horizontal than vertical. 

It seems like we shouldn't be guessing the scrollview's direction. I'm not familiar enough with `XCElementSnapshot` yet to determine the scroll direction correctly. Maybe there's something useful in the `additionalAttributes` dictionary. 

[1]: https://github.com/facebook/WebDriverAgent/blob/14820677342fc035bb1df29a206d613542dc5c13/WebDriverAgentLib/Categories/XCUIElement%2BFBScrolling.m#L115
