### ISSUE TITLE
Failed Build file not found

### ISSUE THREAD

**Issue by joshrlesch** [facebook/WebDriverAgent#277]
I just cloned master for WDA, and tried to run the `WebDriverAgentRunner` scheme. Getting the following error. Not sure if its just me, or something is up. 

```
/Users/josh.lesch/Documents/Github/Open_Source_Repos/WebDriverAgent/WebDriverAgentLib/Routing/FBHTTPOverUSBServer.m:13:9: fatal error: 'RoutingHTTPServer/RoutingHTTPServer.h' file not found
#import <RoutingHTTPServer/RoutingHTTPServer.h>
        ^
1 error generated.
```

**Comment by marekcirkos** [comment]
Did you follow "Getting started" steps? https://github.com/facebook/WebDriverAgent#getting-started

**Comment by joshrlesch** [comment]
:facepalm: I thought I ran that script. My bad, thanks for the quick response.
