### ISSUE TITLE
Running WDA on multiple devices simultaneously

### ISSUE THREAD

**Issue by ssynix** [facebook/WebDriverAgent#280]
We have a use case to run WDA on multiple devices simultaneously. These devices do not necessarily use the same provisioning profile. While I have been able to run WDA on a simulator and a real device at the same time with no apparent issues, I have the following concerns:
* Can there be any problems with running simultaneous instances of the WDA xcode project?

* Is there a way to specify the signing profile through the command line? So far I've only been able to do this manually through XCode.

Thanks!

**Comment by makhov** [comment]
Yes.
1) Use [fbsimctl](https://github.com/facebook/FBSimulatorControl/tree/master/fbsimctl)
2) 
```
xcodebuild \
        -exportArchive \
        -exportFormat IPA \
        -archivePath build/MyApp.xcarchive \
        -exportPath $IPADIR/MyApp.ipa \
        -exportProvisioningProfile "$profileName"
```

**Comment by ssynix** [comment]
Thanks for your suggestion! Can `fbsimctl` be used with physical devices as well?

**Comment by makhov** [comment]
I don't know, but you try this:
```
fbsimctl [DEVICE_UDID] \
           launch_xctest [path]/WebDriverAgentRunner.xctest com.apple.mobilesafari --port 8100 -- \
           listen
```
If it doesn't work, you can use xcodebuild:
```
xcodebuild -project WebDriverAgent.xcodeproj \
           -scheme WebDriverAgentRunner \
           -destination 'platform=iOS,name=iPhone 6' \
           test
```
or 
```
xcodebuild -project WebDriverAgent.xcodeproj \
           -scheme WebDriverAgentRunner \
           -destination 'platform=iOS,id=[DEVICE_UDID]' \
           test
```

**Comment by marekcirkos** [comment]
Unfortunately, `fbsimctl` does not fully support devices yet. However you can make simple app using [FBDeviceControl](https://github.com/facebook/FBSimulatorControl/tree/master/FBDeviceControl)
