### ISSUE TITLE
appium endpoints

### ISSUE THREAD

**Issue by yaphatak** [facebook/WebDriverAgent#284]
@marekcirkos : There are several endpoints that appium supports are not implemented in WDA. Eg. double tap @ particular coordinate. If we add such implementations in WDA and submit PR, will that be accepted? or its better that we write extension as you suggested [here](https://github.com/facebook/WebDriverAgent/pull/231#issuecomment-238490340)

**Comment by marekcirkos** [comment]
It depends on endpoint it self. I will definitely accept anything that is defined by WD protocol.
Anything else is on case by case basis. 
Btw we do support (double tap)[https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L55]

**Comment by yaphatak** [comment]
@marekcirkos : most of endpoints that appium needs and not in `WDA` are like doubleTapping or longPressing at coordinate and not element and is that fine if we add such endpoints

**Comment by marekcirkos** [comment]
In general we avoid using tap at x y on the screen because it is super flaky, due to dependency on screen size etc. However if you have strong use, we can add it as WD extension

**Comment by yaphatak** [comment]
Thanks @marekcirkos Can you elaborate on WD Extension? Will that be separate project referencing `WDALib`? And if its separate project then will it be in separate repository or in this repository only ? or we just add separate classes like `FBAppiumEndpoints`?

**Comment by marekcirkos** [comment]
No, I was talking about route :). Have a look at http://www.w3.org/TR/webdriver/#protocol-extensions
. Something similar to all legacy "uielement" routes, but do not call them "uielement" :)

**Comment by yaphatak** [comment]
Thanks, that should work. And I will use `appium`
