### ISSUE TITLE
Feature request: api for get default session

### ISSUE THREAD

**Issue by codeskyblue** [facebook/WebDriverAgent#287]
This my case, every time I need to start an app so I can get a session, One day I started to think about it, can I get the original session so there is no necessary to launch app again.

Or if there is another way? I don't know, ask here for help. thanks any way.

**Comment by marekcirkos** [comment]
What is your use case? I am not sure where is the problem

**Comment by codeskyblue** [comment]
First I need to start app, so I can get the session id, after the test case went for a long time and test failed, the test procedure finished, so the session is gone.
If I don't have that session id and I have to start app again and run the test again until that failed code. What a waste of time.

**Comment by marekcirkos** [comment]
But if you are testing app you need to start application anyway, so I am not sure how it will improve your issue here?

**Comment by codeskyblue** [comment]
but no need to start again if want to continue test

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/32d50f9e4463f62088e759d323a6a6d11ad56c44

**Comment by codeskyblue** [comment]
thanks @marekcirkos for take care of this issue. very thanks.

sorry have to reopen this issue.

The case is I update the code today. sha is `a4c4f7ed24bb54a67d29719a57d397a5c90571af` 2016-09-22

This is my test steps.

```
Shell: curl -X POST -d '{"desiredCapabilities": {"bundleId": "com.apple.Health"}}' 'http://127.0.0.1:8100/session'
Return: {
    "status": 0, 
    "sessionId": "3A0D1EC4-F5C9-4E90-9FFB-0BD026C24730", 
    "value": {
        "sessionId": "3A0D1EC4-F5C9-4E90-9FFB-0BD026C24730", 
        "capabilities": {
            "device": "iphone", 
            "CFBundleIdentifier": "com.apple.Health", 
            "browserName": "\u5065\u5eb7", 
            "sdkVersion": "9.3.5"
        }
    }
}

Shell: curl -X GET -d '' 'http://127.0.0.1:8100/status'
Return: {
    "status": 0, 
    "sessionId": "3A0D1EC4-F5C9-4E90-9FFB-0BD026C24730", 
    "value": {
        "ios": {
            "simulatorVersion": "9.3.5"
        }, 
        "state": "success", 
        "os": {
            "version": "9.3.5", 
            "name": "iPhone OS"
        }, 
        "build": {
            "time": "Sep 23 2016 10:45:40"
        }
    }
}
```

In the last status request, `currentSessionID` is not found in reponse.

**Comment by codeskyblue** [comment]
I can found sessionId, just a little not as expected in the code.

**Comment by marekcirkos** [comment]
Yeah we removed it as it was duplication of `sessionId` ;)

**Comment by codeskyblue** [comment]
thanks @marekcirkos for reply
