### ISSUE TITLE
getWindowSize no longer works

### ISSUE THREAD

**Issue by imurchie** [facebook/WebDriverAgent#289]
Since `getRect` was changed (https://github.com/facebook/WebDriverAgent/commit/30b17410421f3f2382969659c8793620cc6f8ee4) the `getWindowSize` method (https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L284) no longer works, since the rect is not the same.

**Comment by marekcirkos** [comment]
@imurchie feel free to open PR ;)

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/6813e2549b684379e1b6a6ee96deb2b42f4e1a85

**Comment by imurchie** [comment]
Awesome! Thanks!

I've been getting Appium up to date with WDA changes, so didn't have time to get to this. :)
