### ISSUE TITLE
Test speed

### ISSUE THREAD

**Issue by cltnschlosser** [facebook/WebDriverAgent#291]
This is more of a question than an issue, but I didn't know where else to post it. I'm looking at using real devices to run tests, but I found that everything was really slow. More specifically finds and clicks took several seconds each (sometimes around 10-15), after the screen was stable.

I initially assumed that I was doing something wrong, so I played around with it a bit more and found that using "link text" was much faster than using "xpath", but the tests still seem to bit idling for several seconds between every action. Is there a key thing that I am missing, or are tests just slow?

**Comment by marekcirkos** [comment]
XPath in general is much slower than any other request, especially on crowdy screens.
This is because it needs to build xml by querying every single element on screen. 

In terms of slow execution in general, executing WDA from Xcode directly is slower due to logging. 
When starting WDA with fbsimctl it looks pretty natural. Maybe your client does some additional validation?

**Comment by cltnschlosser** [comment]
Can I use fbsimctl to connect to a real device?

**Comment by cltnschlosser** [comment]
Also which type of search is the fastest? or are they all pretty similar (aside from xpath)?

**Comment by marekcirkos** [comment]
1. No but you can use [FBDeviceControl](https://github.com/facebook/FBSimulatorControl/tree/master/FBDeviceControl) framework to write one
2. Rest of them are pretty much similar

**Comment by cltnschlosser** [comment]
Is there a command line tool for FBDeviceControl?

**Comment by marekcirkos** [comment]
Nope

**Comment by cltnschlosser** [comment]
Is there an example somewhere using FBDeviceControl to start WDA (or any XCTest)?

**Comment by marekcirkos** [comment]
Not much, but you should check out it's repository for more information
