### ISSUE TITLE
Requesting element with bad class name freezes WDA

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#292]
Triggering REST API call like
http://localhost:8100/session/B7624B4E-B00B-44AA-9265-7AB640CFB4D3/elements
with input data

```javascript
{"using":"class name","value":"Table"}
``` 

where "Table" is a container with many children causes webdriver to freeze. Tried with xpath and predicate search strategies and got the same result.
_/element_ API call works as expected though and properly finds the element

![table](https://cloud.githubusercontent.com/assets/7767781/18705943/47366a6a-7ff0-11e6-886f-d2b1bc1bc327.png)

**Comment by marekcirkos** [comment]
You should be querying "XCUIElementTypeTable" instead of "Table". Nether than less WDA should not freeze, if you request bad class name.

**Comment by mykola-mokhnach** [comment]
It does not matter which locator type I use - it freezes in all cases. Tried all of these:
- "using":"class name","value":"Table"
- "using":"class name","value":"XCUIElementTypeTable"
- "using":"xpath","value":"//XCUIElementTypeTable"
- "using":"name","value":"TableName"

**Comment by marekcirkos** [comment]
By freeze you mean freeze infinitely or responds really slowly?
Can you see anything interesting in simulator logs?

**Comment by mykola-mokhnach** [comment]
It just stops responding completely unless I kill the driver and start it again. Nothing interesting in simulator logs. Sending any other request to the driver at the same time just makes a browser/curl to wait without ending (constant spinner).

**Comment by mykola-mokhnach** [comment]
Also xcodebuild and XCTRunner processes use almost all available CPU resources at that time.

**Comment by mykola-mokhnach** [comment]
Adding samples of both processes:
[Sample of xcodebuild.txt](https://github.com/facebook/WebDriverAgent/files/485531/Sample.of.xcodebuild.txt)
[Sample of XCTRunner.txt](https://github.com/facebook/WebDriverAgent/files/485532/Sample.of.XCTRunner.txt)

**Comment by marekcirkos** [comment]
This is nice. 
In general xpath is super expensive, especially on complex views. So I'm not surprised, that it is stuck processing your views. More surprising is why other selectors are slow. This is also why WDA stops responding, as all requests must be handled on main thread.

Can you sample query with "class name"?

**Comment by mykola-mokhnach** [comment]
Hm, strange thing... I've double checked it:

```
 "using":"class name","value":"XCUIElementTypeTable"
```

This worked almost instantly this time. Looks like I had to start this query before xpath, but not after. Although, this locator 

```
"using":"class name","value":"Table"
```

still freezes. I've noticed, that WD knows how to automatically add "XCUIElementType" prefix to ByClass locators, but this seems to work not as expected in such case. 
And why exactly the same xpath locator used in combination with _/element_ method does not cause such freeze?

**Comment by marekcirkos** [comment]
We do not support it. By we might want to support it or at least throw proper error.

**Comment by marekcirkos** [comment]
Ok, I know what was wrong. If you pass unknown class name, we will map that to Any which with your screen will make XCTest busy mapping everything. Going add diff that will throw an error in case of unknown class name

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/227135a6c58eafa42ec731c0bed269b16e5d9a8e

**Comment by mykola-mokhnach** [comment]
Cool, I'm happy to have it fixed. Thanks @marekcirkos
