### ISSUE TITLE
WebDriver is unable to scroll to an item if it is too close to the end of a list

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#293]
I get 

```javascript
{
  "value" : "Error Domain=com.facebook.WebDriverAgent Code=1 \"Failed to perform scroll with visible cell due to max scroll count reached\" UserInfo={NSLocalizedDescription=Failed to perform scroll with visible cell due to max scroll count reached}",
  "sessionId" : "B7624B4E-B00B-44AA-9265-7AB640CFB4D3",
  "status" : 13
}
```

response if I try to scroll to a TableView item, which is close to the end of the table (there are more than 200 items in that table). REST API call looks like 

POST http://localhost:8100/session/B7624B4E-B00B-44AA-9265-7AB640CFB4D3/uiaElement/4DEC123C-62F9-4B2A-BDA4-0955DE810630/scroll

```javascript
{"name":"USA"}
```

Triggering _click_ API on this element has no effect unless it is visible.

**Comment by marekcirkos** [comment]
Yeah, this is a scroll limit that should prevent infinite scrolling. We can increase it, but then we will have issue with timeouts.

I have two suggestions for you:
1) Scroll in two (or more) step manner
2) If your app supports searching through that Table View, search instead of scrolling.

**Comment by mykola-mokhnach** [comment]
Thanks for the response. Yep, using search looks like the fastest possible option here. Just wanted to mention that with previous UIAutomation framework it was possible to scroll to the necessary element in one step by using _.scrollToElementWithPredicate("name CONTAINS '<text>'")_ API call

**Comment by marekcirkos** [comment]
Yeah, XCTest is very very different ;)

**Comment by saritau** [comment]
Can anyone pls share some sample code for both the suggestions asked to be implemented.

Thanks in advance.

**Comment by saritau** [comment]
@marekcirkos : Can you pls share some sample code for both the suggestion to be implemented.

Thanks in advance.

**Comment by marekcirkos** [comment]
@saritau I am not really able to tho that since 1) this is client specific code, just scroll twice, 2) Is app specific.

**Comment by mayukataoka** [comment]
Is there a sample code to perform search in iOS? 

I am also getting the following error.

E               WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Failed to perform scroll with visible cell due to max scroll count reached" UserInfo={NSLocalizedDescription=Failed to perform scroll with visible cell due to max scroll count reached}
