### ISSUE TITLE
It is not possible to perform double tap or long tap at any point of an element

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#294]
The WebDriver currently provides 4 API calls for different click types: _tap_, _click, _doubleTap_ and _touchAndHold_. The problem is, that it is only possible to pass coordinates to the _tap_ method and the other methods don't support such option. As a result, there is no possibility to perform double tap or long tap at any point of an element - only single tap is available.

**Comment by marekcirkos** [comment]
Duplicate of https://github.com/facebook/WebDriverAgent/issues/284
