### ISSUE TITLE
[Random] The application under test fails to start

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#298]
Sometimes WD fails to start application under test, though it is installed successfully. Here is what is visible in the Simulator log (iOS 9.3, Xcode 7.3):

```
Sep 23 10:27:38 Nick CoreSimulatorBridge[33314]: Requesting launch of com.wearezeta.zclient-alpha with options: {
	    arguments =     (
	       ...
	    );
	    environment =     {
	        NSUnbufferedIO = YES;
	    };
	    stderr = "/dev/ttys005";
	    stdout = "/dev/ttys005";
	    "wait_for_debugger" = 0;
	}
Sep 23 10:27:38 Nick assertiond[33310]: assertion failed: 15G1004 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
Sep 23 10:27:40 Nick searchd[33366]: tcp_connection_tls_session_error_callback_imp 5 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22
Sep 23 10:27:41 Nick searchd[33366]: tcp_connection_tls_session_error_callback_imp 6 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22
Sep 23 10:27:41 Nick mstreamd[33296]: (Note ) PS: Media stream daemon stopping.
Sep 23 10:27:41 Nick mstreamd[33296]: (Note ) AS: <MSIOSAlbumSharingDaemon: 0x7fa84050e1f0>: Shared Streams daemon has shut down.
Sep 23 10:27:41 Nick mstreamd[33296]: (Warn ) mstreamd: mstreamd shutting down.
Sep 23 10:27:58 Nick com.apple.CoreSimulator.SimDevice.949BAA5F-9949-453C-920D-DFD7522662F5.launchd_sim[33290] (UIKitApplication:com.wearezeta.zclient-alpha[0xd139][33524]): Service exited due to signal: Killed: 9
Sep 23 10:27:58 Nick SpringBoard[33306]: Application 'UIKitApplication:com.wearezeta.zclient-alpha[0xd139]' exited abnormally via signal.
Sep 23 10:28:06 Nick searchd[33366]: tcp_connection_destination_handle_tls_close_notify 3 closing socket due to TLS CLOSE_NOTIFY alert
Sep 23 10:28:06 Nick searchd[33366]: tcp_connection_tls_session_error_callback_imp 7 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22
Sep 23 10:28:58 Nick coresymbolicationd[33543]: /Users/elf/Library/Developer/CoreSimulator/Devices/949BAA5F-9949-453C-920D-DFD7522662F5/data/Library/Caches/com.apple.coresymbolicationd/data does not exist, resetting cache
Sep 23 10:28:59 Nick XCTRunner[33508]: Enqueue Failure: UI Testing Failure - '<XCUIApplicationImpl: 0x7fbba8ea04d0 com.wearezeta.zclient-alpha at /var/folders/4s/4pd60d1j5cj2bkg1lr_s5c100000gn/T/2016823-4417-izg3qz/Payload/Wire.app>' App state is still not running active, state = XCApplicationStateNotRunning /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
```

**Comment by marekcirkos** [comment]
Application might be crashing at launch.

**Comment by mykola-mokhnach** [comment]
@marekcirkos This was also my first idea. But why there are no any stacktraces or crash reports? 

```
Service exited due to signal: Killed: 9
```

It looks like the system or some other process simply sends SIGKILL to app process without any visible reason.

**Comment by mykola-mokhnach** [comment]
I was googling it and found this page: https://forums.developer.apple.com/thread/25221
Does it contain any useful information for fixing this in WD?

**Comment by marekcirkos** [comment]
@mykola-mokhnach If application crashes during WDA session (or at launch). You will not get any crash report. This is because, we overwrite test failure in order to keep WDA running. So from system point of you everything is ok. 

We do have some crash detection checks. Eg. if you query for elements later, respond should inform about app crash.

**Comment by mykola-mokhnach** [comment]
So you don't think this might that race condition issue described in the forum thread above, but rather an application crash? BTW the size of my .ipa file is bigger than 50 MB.

**Comment by marekcirkos** [comment]
@mykola-mokhnach I am not saying it absolutely is. It is possible it is race condition you mention. But there is not much WDA can do. 

However you could preinstall application, before starting WDA and launch it by bundleID only

**Comment by mykola-mokhnach** [comment]
:-( I was just thinking about making the pause between application install and startup configurable in POST /session API call. If that's not possible then let it be - the described issue randomly happens to 2-5 of our  ~200 automated tests, which is acceptable.

**Comment by marekcirkos** [comment]
@mykola-mokhnach As I was saying, you can install application on simulator before you ask WDA to launch it. That should nail your issue
