### ISSUE TITLE
uuid parameter is not used in /window/:uuid/size API call

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#299]
The :uuid parameter is not used for _/window/:uuid/size_ API call, because it is not needed to have an element id to know the size of the whole screen. Can the signature be simplified to just _/window/size_ or there is some particular reason of why it is not possible?

**Comment by marekcirkos** [comment]
You are absolutely right. I also checked [WD Spec](https://www.w3.org/TR/webdriver/#get-window-size) and it is specified as `/session/:sessionid/window/size. Feel free to pop a PR :)
