### ISSUE TITLE
Extended README

### ISSUE THREAD

**Issue by gekitz** [facebook/WebDriverAgent#3]
It would be good to have an extended README, which gives examples of how to use it. 
At the moment it just describes how to start the driver.

**Comment by mmmulani** [comment]
hmm yeah. what sort of examples were you thinking of? maybe some commands to run?

**Comment by ericwengelking** [comment]
Some example commands would be helpful.

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/d0210e62c3ce56c994e83514c5e186eafb1b78f1
