### ISSUE TITLE
Screen rotation is reset if an alert is visible 

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#300]
Steps to reproduce:
1. Start a test in landscape mode (use setRotation API call to set Landscape mode on iPad)
2. Trigger an alert in your app

Actual result:
All the application metrics are forcefully changed to portrait mode, thus the UI and getRotation API say we are still in landscape:
![1](https://cloud.githubusercontent.com/assets/7767781/18868667/58b85376-84a9-11e6-867a-fe5612c0eeb7.png)
Everything returns back to normal after the alert is accepted or dismissed:
![2](https://cloud.githubusercontent.com/assets/7767781/18868692/6b82eafc-84a9-11e6-902d-d88d4721e6c1.png)
Although the standard alert.accept API call has no effect, since it internally assumes wrong alert coordinates (in portrait mode it works as expected) 

Expected result:
- The device orientation should not be reset while alert is visible
- The alert/accept API call should work properly after the described steps

**Comment by marekcirkos** [comment]
Looks like XCTest issue.

**Comment by marekcirkos** [comment]
@mykola-mokhnach can you raise this issue to Apple?

**Comment by mykola-mokhnach** [comment]
@marekcirkos With pleasure. Can you please provide a link to their bugtracker, where I can place this issue?

**Comment by marekcirkos** [comment]
https://bugreport.apple.com

**Comment by mykola-mokhnach** [comment]
Reported this to Apple. Shell we keep this issue opened?

**Comment by marekcirkos** [comment]
I think we should keep it for tracking and to let people know it is "Know issue"

**Comment by marekcirkos** [comment]
@mykola-mokhnach Is this still an issue?

**Comment by mykola-mokhnach** [comment]
I will check it again and comment the issue. In theory, this workaround we did for landscape, should work for it.

**Comment by mykola-mokhnach** [comment]
Yup, the workaround works perfectly now with the recent WDA commits. The issue can be closed.

**Comment by mykola-mokhnach** [comment]
Seems like the problem is relevant only for security alerts generated by iOS itself.
https://github.com/facebook/WebDriverAgent/pull/470 might handle it.

**Comment by drapostolos** [comment]
is there a way to follow this issue in the apple bugtracker?

**Comment by marekcirkos** [comment]
You should open your own, to give Apple stronger signal.

**Comment by alexander-poulikakos** [comment]
@marekcirkos what is the reason for closing this? Is there a solution from Apple available?

**Comment by marekcirkos** [comment]
This should be fix. If it is not please reopen

**Comment by alexander-poulikakos** [comment]
@marekcirkos I'm using the below configuration and I still have this problem.  

- MacOS Sierra version 10.12.5 (16F73)
- Appium v1.6.5-beta
- XCUITestDriver  v2.29.0 
- Xcode version 8.3.2 (tools v8.3.2.0.1.1492020469)
- iOS SDK Version 10.3

Device:
- iphone 6 (10.3.1)
