### ISSUE TITLE
Timed out waiting for key event to complete

### ISSUE THREAD

**Issue by omoskovko** [facebook/WebDriverAgent#301]
Can't type text value in XCUIElementTypeSearchField element on iPhone 5 iOS 9.3.5 real device
Command to execute:
```
export DEVICE_URL=http://localhost:8100
export SESSION_ID=8D37AA61-51F4-406D-B9F8-3ED37E48AAFC
export JSON_HEADER="-H \"Content-Type: application/json\""

curl -X POST $JSON_HEADER \
 -d "{\"value\":[\"1\",\"0\",\"0\",\"3\"]}" \
 $DEVICE_URL/session/$SESSION_ID/keys
```

As result exception is raised 
```
{
  "sessionId" : "8D37AA61-51F4-406D-B9F8-3ED37E48AAFC",
  "value" : "Error Domain=XCTestManagerErrorDomain Code=14 \"Timed out waiting for key event to complete\" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete}",
  "status" : 13
```

**Comment by marekcirkos** [comment]
Is it consistent or random?

**Comment by marekcirkos** [comment]
From time to time typing my fail due to that reason. It is XCTest issue, that you can detect with that error message.

**Comment by marekcirkos** [comment]
If it is consistent I would love to get an app sample and command you are running.

**Comment by omoskovko** [comment]
@marekcirkos I'm sorry but it's our application issue.
Search component work really slow.

**Comment by ohadschn** [comment]
I just got this on some random test run. Upon inspecting the test screenshot taken at the point of failure, I could clearly see the emulated key typing stopped short. The string I sent was pretty long though, something like "foobar1@mygreatsubdomain.mydomain.com" and it only typed in "foobar1@m".
