### ISSUE TITLE
'OSAtomicOr32Barrier' is deprecated: first deprecated in iOS 10.0 - Use atomic_fetch_or() from <stdatomic.h> instead

### ISSUE THREAD

**Issue by arsonistqa** [facebook/WebDriverAgent#302]
I have this error when build project using Xcode Version 8.0 (8A218a)
Deployment target 10.0
Team for signing was selected
/workspace/WebDriverAgent/WebDriverAgentLib/Utilities/FBRunLoopSpinner.m:30:5: 'OSAtomicOr32Barrier' is deprecated: first deprecated in iOS 10.0 - Use atomic_fetch_or() from <stdatomic.h> instead

**Comment by vikaspune** [comment]
@arsonistqa I am also facing same issue https://github.com/appium/appium-xcuitest-driver/issues/188

I also found same issue reported yesterday on Appium https://github.com/appium/appium/issues/6901

I am not sure but is something broken in WebDriverAgent recents commits/changes?

**Comment by arsonistqa** [comment]
@marekcirkos any ideas?

**Comment by marekcirkos** [comment]
Not sure why I don't have this issue, but fix is on the way.

**Comment by arsonistqa** [comment]
@marekcirkos do you have eta for fix?

**Comment by vikaspune** [comment]
@marekcirkos thanks for proposing fix. I am hoping it should get released as soon as possible.

**Comment by vikaspune** [comment]
Hey @arsonistqa do you have 2 versions of xcode installed on your machine? Though we use xcode-select commend to use xcode8 as default still it's not working. @marekcirkos I think this issue is caused due to having 2 versions of xcode

**Comment by arsonistqa** [comment]
@vikaspune no I don't

**Comment by vikaspune** [comment]
Ohhh . I thought because of this similar  old issue https://github.com/facebook/WebDriverAgent/issues/194#issuecomment-230907439 . 
But for me the solution proposed to restart machine did not help me.

**Comment by arsonistqa** [comment]
@vikaspune the same for me, my idea is to have appium tests to be run on real device in safari but I faced this problem when I updated to iOS 10

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/222279c868459f88640f3496198888c942873f12

**Comment by marekcirkos** [comment]
Travis actually builds with Xcode 8 and it is fine. So I suspect that you might have different default system settings for warnings.
