### ISSUE TITLE
Width and height values are not exchanged if screen orientation is set to landscape

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#303]
1. Execute automation test on iPad
2. Rotate the screen to landscape
3. Trigger _window/size_ API call

AR:
Window height is still greater as window width in the returned value and is equal to the function output in portrait mode

ER:
Height and width values should be exchanged if device's screen orientation is landscape

**Comment by marekcirkos** [comment]
Can you check if there is the same issue when running regular UITest?

**Comment by marekcirkos** [comment]
Is this the same as https://github.com/facebook/WebDriverAgent/issues/300 ?

**Comment by mykola-mokhnach** [comment]
No, it is not. The issue described in https://github.com/facebook/WebDriverAgent/issues/300 is about sizes returned for all application elements (they are "inverted" if an alert is visible). 
And this one is about the size retuned by _window/size_ API call.

**Comment by marekcirkos** [comment]
AA, didn't notice. Thanks!! Definitely raise an issue for Apple.

**Comment by nhanvpt102** [comment]
Use "UIInterfaceOrientation orientation = request.session.application.interfaceOrientation;"
to detect the status of screen and return the Width/Height accordingly. It works fine.

+ (id<FBResponsePayload>)handleGetWindowSize:(FBRouteRequest *)request
{
    CGRect frame = request.session.application.wdFrame;

    NSNumber *width = @(CGRectGetWidth(frame));
    NSNumber *height = @(CGRectGetHeight(frame));
    NSNumber *orientationValue = @0;

    UIInterfaceOrientation orientation = request.session.application.interfaceOrientation;
    if(orientation == UIInterfaceOrientationPortrait) {
        //Portrait orientation
        orientationValue = @0;
    } else if (orientation == UIInterfaceOrientationPortraitUpsideDown) {
        //Portrait orientation
        orientationValue = @1;
    } else if(orientation == UIInterfaceOrientationLandscapeRight){
        //Landscape orientation
        height = @(CGRectGetWidth(frame));
        width = @(CGRectGetHeight(frame));
        orientationValue = @2;
    } else if (orientation == UIInterfaceOrientationLandscapeLeft) {
        //Landscape orientation
        height = @(CGRectGetWidth(frame));
        width = @(CGRectGetHeight(frame));
        orientationValue = @3;
    } else {
        orientationValue = @4;
    }
    return FBResponseWithStatus(FBCommandStatusNoError, @{
                                                          @"width": width,
                                                          @"height": height,
                                                          @"orientation":orientationValue,
                                                          });
}

**Comment by marekcirkos** [comment]
@nhanvpt102  You mean check orientation and then replace coordinates?

**Comment by marekcirkos** [comment]
@mykola-mokhnach I think this is resolved right?

**Comment by mykola-mokhnach** [comment]
right. it's done already
