### ISSUE TITLE
Can't run test on xCode 8

### ISSUE THREAD

**Issue by omoskovko** [facebook/WebDriverAgent#304]
OS X El Capitan Version 10.11.6
xCode version 8.0 Build version 8A218a
iPhone 6 with iOS version 10.0.2

Command to run test:
```
# idevice_id installed with http://macappstore.org/ideviceinstaller/
export idDev=$(idevice_id -l)

xcodebuild \
 -project WebDriverAgent.xcodeproj \
 -scheme WebDriverAgentRunner \
 -destination id=$idDev \
 test
```
As result Test Failed with following:
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/yr/n16wjh3s67j96pvm1cjr8n_c0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/ffa486393274a0de7b7a989598b7f791/bef02ea2396c157f6c24be45280a40260bffc2ad/ManifestCache.plist
2016-09-28 17:11:04.998292 XCTRunner[1994:604509] [Accessibility] ****************** Loading GAX Client Bundle ****************
2016-09-28 17:11:05.066648 XCTRunner[1994:604509] Running tests...
2016-09-28 17:11:05.116537 XCTRunner[1994:604509] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2016-09-28 17:11:05.116647 XCTRunner[1994:604509] 
(dlopen_preflight(/var/containers/Bundle/Application/CDBF7FEC-8737-4492-8144-3C3EC33DE0FF/WebDriverAgentRunner-
Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: 
@rpath/KissXML.framework/KissXML

  Referenced from: /private/var/containers/Bundle/Application/CDBF7FEC-8737-4492-8144-
3C3EC33DE0FF/WebDriverAgentRunner-
Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDr
iverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/CDBF7FEC-8737-4492-8144-
3C3EC33DE0FF/WebDriverAgentRunner-
Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frame
works/KissXML.framework/KissXML: required code signature missing for 
'/private/var/containers/Bundle/Application/CDBF7FEC-8737-4492-8144-
3C3EC33DE0FF/WebDriverAgentRunner-
Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frame
works/KissXML.framework/KissXML'
)
2016-09-28 17:11:05.154 xcodebuild[12323:214742] Error 
Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never 
finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early 
unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never 
finished bootstrapping - no restart will be attempted)
** TEST FAILED **

With xCode 7 there is no any issue.

**Comment by marekcirkos** [comment]
Make sure you select teams on all targets and you have valid prov profiles

**Comment by omoskovko** [comment]
Thanks. It works now.
