### ISSUE TITLE
XPath queries performance is low

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#306]
Currently WD uses DOM-based KissXML framework to perform XPath lookup. And its performance is quite bad in comparison to other solutions based on SAX, for example libxml2. Some complicated XPath queries take about 10 seconds for me and this happens with pretty simply XML tree. Although, I see that the tree itself is built almost instantly, so the problem must be in the lookup method.
Is it possible to replace KissXML with libxml2 to improve the lookup performance?

**Comment by marekcirkos** [comment]
We are not particular attached to KissXML. If you want to put a diff that improves xpath. I am happy to review it.

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/pull/308
