### ISSUE TITLE
Periodically failing to install due to TCTest.tbd existing?

### ISSUE THREAD

**Issue by sleekweasel** [facebook/WebDriverAgent#307]
I'm a bit stumped by this - not really even sure how to tackle it: most of the time, this all works for me against my physical phone, but frequently (about 10%), I'm seeing the AgentRunner fail to install, with the first obvious syslog error being this:

Sep 29 10:11:00 ALON-670-53-81ie-iPhone-5c-8Gb-Blue-W com.apple.StreamingUnzipService[206] <Warning>: -[StreamingUnzipper _supplyBytes:length:withReply:]:1376: Failed to create symlink at /private/var/mobile/Media/PublicStaging/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest.tbd to TextBasedStubs/XCTest.tbd: File exists

I'm attaching the fuller log, but I don't see anything particularly causing this file not to be deleted - unless the kill -9 is somehow leaving an associated process behind that keeps a lock on the directory and soft-link (I thought processes kept hold of the files to which soft-links point, not soft links themselves).

[testproc_0_fbook_20160929-101048.txt](https://github.com/facebook/WebDriverAgent/files/500230/testproc_0_fbook_20160929-101048.txt)

I presume it's something I'm doing, not having seen this mentioned in any other issue. I use ideviceinstaller to install and uninstall, and have tried the Ruby Gem ios_app_installer to uninstall with no appreciable difference - I imagine it's doing the same stuff behind the scenes.

**Comment by marekcirkos** [comment]
I assume you use Xcode to launch WDA? If so there is not much we can do as this is Xcode issue that you should report. Sorry.

**Comment by sleekweasel** [comment]
Hi, and thanks for getting back to me.

I'll happily use something other than XCode if it'll get this working, although the only other tool to start an app on an iOS device I know of is instruments, and I kind-of assumed that's what XCode is using internally.

Is instruments different? Aside from jailbreaking the device, is there anything besides Instruments I can use if not? It's just a question of running the app, isn't it?

I presume the suggestion to report the bug in XCode to Apple was kind-of tongue-in-cheek: my perception of Apple is that they're not very interested in unofficial stuff like this.

**Comment by sleekweasel** [comment]
Sorry, I forgot about the fbsimctl and friends. I'll try those.

**Comment by sleekweasel** [comment]
Hah. I started trying to use fbsimctl stuff on the iphone device. I keep forgetting that iPhones and Simulators aren't the same: I'm too used to Android where they're largely identical.

**Comment by marekcirkos** [comment]
It is highly experimental and does not work with iOS 10 yet, but you can try FBDeviceControl libs to write a small app to do it.

**Comment by marekcirkos** [comment]
Other than that I can help you, sorry. You should really open a ticket with Apple. It is common issue.

**Comment by sleekweasel** [comment]
OK. I've opened a ticket. Thanks for your help.
