### ISSUE TITLE
Slow /tap and /elements round-trip request time to real devices.

### ISSUE THREAD

**Issue by sleekweasel** [facebook/WebDriverAgent#311]
I'm seeing something similar to issue #291 in the WireShark log between my laptop and my device, where /tap (by coordinate) and /elements request/response pairs take between 4 and 10 seconds.

For example a request like, http://192.168.19.45:8100/session/033796C0-C3AE-4BDA-940F-C160E44D8029/tap/1CB182CC-FBF7-4C50-8AD1-B56E2A34E502 which doesn't do any obvious XML path stuff and presumably knows exactly where to look, took 7.6 seconds. (Needless to say, each tests needs more than 4 clicks, and 30 seconds per test means we can only run the essential suite on devices.)

In #291, it mentioned excessive logging, but looking at the device syslog while running the tests at the moment, I can't see any logging (excessive or otherwise) that shows up when these slow calls are made that could be causing 10 second delays. Where should I be looking for that?

I'm happy to try to look into this in the agent's code if it's not a priority for you guys, but I'd like to know that I'd not be duplicating effort already expended by my betters!

Thanks.

**Comment by marekcirkos** [comment]
Taping element does not do any XML stuff. It resolves element (1-2 sec) and then performs tap (super fast). Anything that can slow it down is reporting activities and logging.

Other case when you might get super slow response is when XCTest can't query element for some reason eg. queried application is in background. etc.

**Comment by sleekweasel** [comment]
Hi, thanks for responding.

Interesting: 2-3 seconds is consistent with the faster response times I'm seeing, but the 7-10 second end is frequent enough to be significant. The application is always in the foreground so far as the display is concerned, so I guess it's something else.

I'm not seeing any reporting or logging in syslog. If you can suggest what other logs or reports I could look in, I can check.

I'm inferring that nobody else has explored this as such, so I'll try to schedule time for it: even if I can simply narrow it down to something irresolvable, it'll be better than suffering in ignorance.

Cheers.

**Comment by marekcirkos** [comment]
Activity reporting happens in Xcode's console. You should check those. It will show any XCTest issues as well.

**Comment by marekcirkos** [comment]
@sleekweasel any update here?

**Comment by sleekweasel** [comment]
Afraid not - I've lost all my spare cycles for the moment, so I'll have to
schedule this later: our main tests are on the simulator, and a couple of
dozen slow tests in a secondary build are lower priority than profiling our
parallel iPhone simulator clustering to get it under 30 minutes.
