### ISSUE TITLE
Simulating a flick gesture with WDA

### ISSUE THREAD

**Issue by ssynix** [facebook/WebDriverAgent#313]
I have a scrollable list of draggable items that I want to scroll on. As a user, I can easily do that by a quick flick motion on the screen. Dragging is only triggered by tap and holding on an element and then dragging, so accidentally moving things around while scrolling wouldn't happen.

`handleScroll` seems to do the job if I pass in a direction, but there's no way for me to specify how fast, or how much it should scroll in that direction. The default speed/rate is just too slow for my use case and doesn't trigger the accelerated scrolling.

I could cover some distance by repeatedly calling `handleDrag`, but I've noticed that the wait duration here doesn't seem to affect the dragging speed, and I still get the same slow behavior.

Am I missing something here? Is this out-of-scope for WDA?

**Comment by marekcirkos** [comment]
I think that would require custom action implementation. Probably simply swipe on element will work for you?

**Comment by ssynix** [comment]
I looked into it further and `[element swipeUp]` does work better, but I realized that apparently customizing it any further is an Xcode limitation (except where you guys use things like `XCPointerEventPath`). 

I'll try to make do with already-exposed API. I just wanted to make sure that I'm not missing anything in WDA.

Thanks!
