### ISSUE TITLE
scroll on iOS 10

### ISSUE THREAD

**Issue by SmithaVemuri** [facebook/WebDriverAgent#315]
Is scroll supported on iOS 10? if so what is the endpoint to use. 

/uiaElement/:uuid/scroll doesn't seem to work for iOS 10

**Comment by marekcirkos** [comment]
Scroll works for us. Can you post full request ?

**Comment by SmithaVemuri** [comment]
Request:
http://ipaddress:8100/session/2DDD0C65-DC5A-48C4-B5B2-9846EDF7819F/uiaElement/8D228646-2D33-46DB-9054-A905792BDF7E/scroll

POSTDATA: {"using":"class name","value":"XCUIElementTypeScrollView"}

Response:
{
"value": "Unsupported scroll type"
"sessionId": "2DDD0C65-DC5A-48C4-B5B2-9846EDF7819F"
"status": 13
}

**Comment by marekcirkos** [comment]
Your post data are wrong. They look like you want to find an elements. 
Try using {"direction" : "down"}

**Comment by SmithaVemuri** [comment]
Still I don't see scroll working on iOS 10. No error in the response but 

request: 
{"direction":"down"}

response

{
"value": {}
"sessionId": "A244EFF7-E884-4299-B8CD-ECD0822D90F5"
"status": 0
}

Was it working for you on iOS 10 iphone ?

**Comment by marekcirkos** [comment]
Can you post full request with URL, data and description what your Ids point to?

**Comment by SmithaVemuri** [comment]
worked with below request
request: 
{"toVisibile":"true"}

thank you
