### ISSUE TITLE
"Get Active Element" not supported

### ISSUE THREAD

**Issue by toejough** [facebook/WebDriverAgent#318]
It appears that the [get active element endpoint](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-get-active-element) is not supported:

```
curl -X GET "${JSON_HEADER}" "${DEVICE_URL}"/session/14A34247-3ABF-4EE2-B081-4205516555FC/element/active
{
  "value" : "Unhandled endpoint: \/session\/14A34247-3ABF-4EE2-B081-4205516555FC\/element\/active -- http:\/\/localhost:8100\/ with parameters {\n    wildcards =     (\n        \"session\/14A34247-3ABF-4EE2-B081-4205516555FC\/element\/active\"\n    );\n}",
  "sessionId" : "14A34247-3ABF-4EE2-B081-4205516555FC",
  "status" : 1
}
```

Could support be added?

**Comment by marekcirkos** [comment]
Feel free to pop a PR :)

**Comment by toejough** [comment]
Sure - I'm going to need a little help, though :-)

I found https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBFindElementCommands.m, which I assume is the right place to add a
```
[[FBRoute POST:@"/element/active"] respondWithTarget:self action:@selector(handleFindActiveElement:)],
```
line, but the actual implementation of `handleFindActiveElement`?  Going to need help with that.  Does WDA already know what the active element is?  Do you have to retrieve that information via some XCUI API?

**Comment by marekcirkos** [comment]
There is `hasKeyboardFocus` on XCUIElement that you can use as predicate while searching for en element.

**Comment by toejough** [comment]
so...I actually found a workaround for my usecase.  I'm still interested in helping out with this for philosophical reasons, but work priorities mean I can't spend time on it right now.  :-/

**Comment by marekcirkos** [comment]
That is ok. Pop an pull request when you are ready :)
