### ISSUE TITLE
Accessible Attributes

### ISSUE THREAD

**Issue by imurchie** [facebook/WebDriverAgent#319]
Is there a list of the attributes that are retrievable through `handleGetAttribute`? I cannot find anything.

**Comment by marekcirkos** [comment]
Everything here https://github.com/facebook/WebDriverAgent/blob/6813e2549b684379e1b6a6ee96deb2b42f4e1a85/WebDriverAgentLib/Routing/FBElement.h 
If there is any Wiki you think we should add. Let me know or even send not to me. I'll be happy to add it.
