### ISSUE TITLE
pagesource endpoint is intermittently extremely slow

### ISSUE THREAD

**Issue by toejough** [facebook/WebDriverAgent#320]
Since trying to use WDA for ios 10 tests, I've found that pagesource fetches sometimes take several minutes to come back.

My tests are pretty tolerant regarding timing, but not _that_ tolerant.

There are a lot of things I can do element searches for, but for our app I often find I need to find an element, pop up a few parents, and then find another element (say, a sibling or cousin element of the one I found originally).  I don't know of any way to do that besides just getting the XML tree and traversing it.

The other thing that I use pagesource for is for capturing the environment when a test fails.  The tests grab the screenshot and the page source, among other things, so that a human can look over them later.

A delay of several minutes makes pagesource unusable for me.  Any chance this is already known and being worked on?

**Comment by toejough** [comment]
When the pagesource fetch is slow, I get this error in my appium logs:

```
[debug] [WebDriverAgent] Sim: Oct  6 17:06:05 vision XCTRunner[39295]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x600000253230> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
```

Does that mean anything to anyone?  Is there any additional debugging I can perform/enable/report to help?

**Comment by marekcirkos** [comment]
1) Log you posted means that XCTest has an issue resolving some elements and it will also explain long responses. It can take over an minute to recover. Usually that means that you requested update on inactive application, or bug in XCTest.

2) In general using xpath is much slower than anything else, so you might consider changing to other element finder.

**Comment by toejough** [comment]
1) gross.  Ok.  I guess that means I won't see a resolution to this any time soon.  I'll close this issue and try to file something with them.

2) well, that's the thing - under the old appium interface (via UIAutomation), I started with individual element searches, but they were super slow, especially when checking for a single condition meant finding several elements and inspecting their attributes - switching to just grabbing the entire screen's xml and using a fast xml parser sped up my tests significantly.  

The other rationale for using pagesource so heavily has been the need to find parent/sibling elements once you find a unique one.  I can do that with xpath, but I haven't found a way to do so with other element finders - if you've got a trick for that, let me know.

In any case, I'll close this issue - thank you very much for your responsiveness - it's been a tremendous help :-)

**Comment by marekcirkos** [comment]
I theory you can grab whole element hierarchy via `/source` endpoint and travers graph your self.

**Comment by toejough** [comment]
hmmm, I think there's a misunderstanding - that's the endpoint the bug was opened about.  The `/source` endpoint is what is producing those errors and responding so slowly for me.

**Comment by toejough** [comment]
^ does re-opening mean there might be a WDA-side resolution coming?

**Comment by marekcirkos** [comment]
If `/source` is failing for you that is not  expected.

**Comment by toejough** [comment]
Absolutely.  Besides what's above, what other info would you like?

**Comment by marekcirkos** [comment]
Anything related. Best would app sample.

**Comment by Gogle** [comment]
I have exactly the same problem and with the same error output (on iOS 10).

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/52a40e332703ebe576f6735ee3cc89be3cb47a25
