### ISSUE TITLE
how to restart application ?

### ISSUE THREAD

**Issue by bearxc** [facebook/WebDriverAgent#322]
In our automation , we launch app at the beginning of  each test and close it at the end , make sure app in clean state , is it possible to do through WDA  without relaunch whole session ?

**Comment by marekcirkos** [comment]
Why creating new session is a problem?

**Comment by bearxc** [comment]
when we run it from appium , it looks like we have to redeploy and launch agent on the device agin   , it is pretty slow .

**Comment by marekcirkos** [comment]
With WDA you can simply stat new session without need for re-deploying. Not sure how it works with appium. You should talk to them about this :)

**Comment by bearxc** [comment]
Good to know   :)
