### ISSUE TITLE
Is there a way to perform swipe on the element

### ISSUE THREAD

**Issue by SmithaVemuri** [facebook/WebDriverAgent#325]
I do not see a command for swipe on the element in code. Is there any other way to perform swipe with WDA on ios 10?

**Comment by marekcirkos** [comment]
Not at this moment

**Comment by SmithaVemuri** [comment]
Any plans to support in near future? thanks.

**Comment by marekcirkos** [comment]
Nope, but I am happy to review a diff and land it.
