### ISSUE TITLE
cannot access server on iphone device

### ISSUE THREAD

**Issue by sixleaves** [facebook/WebDriverAgent#326]
i have build WD to iphone device.but cannot access by ip:8100.but on iphone device, i open safari, and type 127.0.0.1:8100, can access.

**Comment by marekcirkos** [comment]
You should check you network configuration or/and device settings. From what you are saying it is clear WDA boots properly. WDA does not do any access filtering.

**Comment by sixleaves** [comment]
thanks.i test both ios10 and ios9. but only in ios 10, cannot access.
