### ISSUE TITLE
"'bundleId' desired capability not provided"

### ISSUE THREAD

**Issue by sixleaves** [facebook/WebDriverAgent#331]
when i use URLSession for launch app, get the infomation.
can u help me?

**Comment by sixleaves** [comment]
```curl -X POST $JSON_HEADER \
-d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.mobilesafari\", \"app\":\"[host_path]/magicapp.app\"}}" \
$DEVICE_URL/session
-d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.mobilesafari\", \"app\":\"[host_path]/magicapp.app\"}}" \
$DEVICE_URL/session
```
can i use URLSession , and set "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.mobilesafari\", \"app\":\"[host_path]/magicapp.app\"}} to http request message body?

**Comment by marekcirkos** [comment]
Yes, you should be able to set body on URL request with that JSON. Closing since this is not really WDA issue
