### ISSUE TITLE
Unable to get the same Id's in all devices of Android Hybrid Application

### ISSUE THREAD

**Issue by tekisrinivas20** [facebook/WebDriverAgent#336]
Hi team,

I am automating Android Hybrid Application using Appium, while working I am getting the Id's from UIA Automator viewer But I am not getting some of the Id's in one device and some of the Id's not getting in another device, what is the reason both the devices are having same android version and also I have installed all android versions like Android 5.0.1, 5.1.1 and 6.0. And also I have verified in Emulator. Is there any version dependency to get the Id's from UIA automator viewer. Could any one please help on this issue. I am attaching both the device screenshots and Working environment.

Environment

Appium version1_4_16_1
Windows 7 64 bit
Android - 5.1.1
Real device (Samsung 10 inch tablet)
Latest Chrome driver - 2.24
Appium server logs :

![android_hybridapp_device-1](https://cloud.githubusercontent.com/assets/22059441/19680851/cf947390-9ac4-11e6-89d6-d94515d3cbef.jpg)
![android_hybridapp_device-2](https://cloud.githubusercontent.com/assets/22059441/19680849/cf090a12-9ac4-11e6-8a5d-acd83e0f281f.jpg)

Thank you,

**Comment by marekcirkos** [comment]
Hey, WebDriverAgent is iOS specific so probably you should raise an issue with Appium :)
