### ISSUE TITLE
Add support for sliders

### ISSUE THREAD

**Issue by dpgraham** [facebook/WebDriverAgent#339]
-In prior versions of Appium we were able to set the value of sliders using 'setImmediateValue' or 'sendKeys' function
-We're unable to do that now that we're using XCUITest
-Is this because XCUITest doesn't support this, or is it because WebDriverAgent doesn't support this yet or is it supported in another way and we need to update Appium to support this

**Comment by marekcirkos** [comment]
Sliders should work, let me double check that.

**Comment by marekcirkos** [comment]
Ok, we do not support it, but it can be easily added thanks to `XCUIElementTypeSlider` category.

**Comment by imurchie** [comment]
I had tried to add support but it did nothing to the slider. Alas. I've opened a bug with Apple but no word yet about it.

Perhaps I was doing it wrong? My addition was to `FBElementCommands#handleSetValue`:

```objective-c
if (element.elementType == XCUIElementTypePickerWheel) {
  [element adjustToPickerWheelValue:textToType];
  return FBResponseWithOK();
} else if (element.elementType == XCUIElementTypeSlider) {
  CGFloat floatValue = [textToType doubleValue];
  [element adjustToNormalizedSliderPosition:floatValue];
  return FBResponseWithOK();
}
```

**Comment by marekcirkos** [comment]
I got diff waiting to be landed.

**Comment by imurchie** [comment]
👍

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/d5694557113d6f875457472c7bb0501e21155ec5
