### ISSUE TITLE
support "accessibility id" locator strategy

### ISSUE THREAD

**Issue by Jonahss** [facebook/WebDriverAgent#34]
does this make sense here? Or would this just return the "name" attribute. Not sure what attribute actually ends up on the UIAElement

**Comment by marekcirkos** [comment]
Do we need both `id` and `accessibility id` strategies?

**Comment by Jonahss** [comment]
`id` is actually deprecated I believe. So we could remove that one.

**Comment by marekcirkos** [comment]
Resolved by #72
