### ISSUE TITLE
cannot get the source with the view of WeChat app public account dialog box

### ISSUE THREAD

**Issue by jessezyl** [facebook/WebDriverAgent#340]
when i try to get the source or inspect the view, i got the error output below:

> ...
> 2016-10-27 17:39:31.123220 XCTRunner[12438:3579101] Built at Oct 27 2016 17:39:15
> 2016-10-27 17:39:31.152072 XCTRunner[12438:3579101] ServerURLHere->http://192.168.31.220:8100<-ServerURLHere
> 2016-10-27 17:39:31.152761 XCTRunner[12438:3579101] Listening on USB
>     t =     6.57s     Find the Application "local.pid.57" 0x1740aaf20
>     t =     6.57s         Snapshot accessibility hierarchy for local.pid.57
>     t =    35.64s     Find the Application "local.pid.12422" 0x1740aaf80
>     t =    35.64s         Snapshot accessibility hierarchy for local.pid.12422
> 2016-10-27 17:40:06.946801 XCTRunner[12438:3579383] Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error -25204 getting snapshot for element <AXUIElement 0x1002153a0> {pid=12422}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element <AXUIElement 0x1002153a0> {pid=12422}} <unknown> 0 1
>     t =    51.90s         Find the Application "local.pid.12422" 0x1740aaf80 (retry 1)
>     t =    51.91s             Snapshot accessibility hierarchy for local.pid.12422
> 2016-10-27 17:40:29.145610 XCTRunner[12438:3579515] Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=12 "Failed to get main window after 30 retries: kAXErrorServerNotFound (see rdar://problem/15530121)" UserInfo={NSLocalizedDescription=Failed to get main window after 30 retries: kAXErrorServerNotFound (see rdar://problem/15530121)} <unknown> 0 1
>     t =    68.07s         Find the Application "local.pid.12422" 0x1740aaf80 (retry 2)
>     t =    68.07s             Snapshot accessibility hierarchy for local.pid.12422
> 2016-10-27 17:40:45.302050 XCTRunner[12438:3579646] Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=12 "Failed to get main window after 30 retries: kAXErrorServerNotFound (see rdar://problem/15530121)" UserInfo={NSLocalizedDescription=Failed to get main window after 30 retries: kAXErrorServerNotFound (see rdar://problem/15530121)} <unknown> 0 1
> ...

and the app crashed (seems like the wda session crash), any idea about it?

**Comment by marekcirkos** [comment]
`kAXErrorServerNotFound` usually indicates app has crashed.

**Comment by jessezyl** [comment]
yes, it has crashed after i requested the source of the view, so is this wda issue or something else?

**Comment by marekcirkos** [comment]
WDA will not crash the application. Most likely it is app issue. If you use Xcode and add exception breakpoint  it should stop what app crashes.

**Comment by jessezyl** [comment]
ok, thanks for the advice.
