### ISSUE TITLE
inspector can not get the tree of elements

### ISSUE THREAD

**Issue by lyt19871224** [facebook/WebDriverAgent#343]
hi, tesing my company's ios app ,when i visit the inspector through the url , the webdriveragent xcode will console :

> 2016-10-26 18:58:24.461947 XCTRunner[1301:730895] Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x174642f10> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1

another page of simple structure ，the inpector can get the tree of element,but can not  Identify the specific elements ，see the image below

![1b3f4a1b-dae5-412b-a624-a129a795af70](https://cloud.githubusercontent.com/assets/7929135/19843941/3676154a-9f62-11e6-9e83-47002921059f.png)

xcode8    mac 10.11

**Comment by marekcirkos** [comment]
Try updating WDA, @mykola-mokhnach fixed that issue

**Comment by marekcirkos** [comment]
According other issue, this most likely is due to how application reports elements. XCTest uses accessibility to do that. I would check if your app properly sets accessibility attributes for that elements.

**Comment by hamena** [comment]
Is this issue fixed in current npm webpack package?
Could a native wheel picker suffer this problem too? Which accessibility attribute?

**Comment by mykola-mokhnach** [comment]
@hamena check the recent comment from Isaak Murchie there https://github.com/appium/appium/issues/7034

It's already in Appium and you can install it using the following commands

```
npm uninstall -g appium
npm install -g appium --no-shrinkwrap
```

**Comment by uimator** [comment]
@marekcirkos  I got same error in WDA master code. Xcode8 and os 10.12

**Comment by hamena** [comment]
@mykola-mokhnach it worked at all. Thank you.

**Comment by marekcirkos** [comment]
I guess we can close this issue?

**Comment by uimator** [comment]
@marekcirkos I get this error in page souce. Some of the page elements don't sets accessibility attributes, but I think you'll skip that elements and return others.
