### ISSUE TITLE
how to swipe  on  element ?  

### ISSUE THREAD

**Issue by bearxc** [facebook/WebDriverAgent#344]
Given an element  , is it possible to swipe on that  based on its x , y  coordinate ?

I gave a try on   left swipe with  following command and it turns out as click instead of swipe .

curl -X POST  $JSON_HEADER  -d "{fromX:187,fromY:660,toX:0,toY:660,duration:800}" $DEVICE_URL/session/$SESSION/uiaTarget/0/dragfromtoforduration

**Comment by marekcirkos** [comment]
Duration seems to be very long, so system might interpret that as a touch.

**Comment by bearxc** [comment]
both duration and toX   are too long .

**Comment by toejough** [comment]
@marekcirkos - I ran into this issue, too, as appium is not translating ms to s.  Is this command performing a long-press and returning 200 in this scenario on purpose?  It seems wrong, and definitely made my debugging more difficult.

If I specify a really long drag, I'd expect that either:
* the really long drag is performed OR
* the command errors out with a message about exceeding a maximum duration

Instead, WDA performs a completely different command.

**Comment by marekcirkos** [comment]
@toejough You should think about WDA/XCUITest as touching service. We do not trigger gesture recognisers directly and imitate touching instead. How app interprets that it is up to it. If you perform super slow swipe you will trigger long press gesture recogniser, if there is one. Validating that on WDA will not be a good idea as you might want to test super slow swipe on your app etc.

**Comment by toejough** [comment]
Ah, ok.  Thank you for the explanation - that makes sense, and will help me reason better about the right behaviors/interactions to expect.
