### ISSUE TITLE
Using WebDriverAgentLib directly with unit testing target

### ISSUE THREAD

**Issue by drptbl** [facebook/WebDriverAgent#348]
Hey,

I'm trying to use `WebDriverAgentLib.framework` directly in unit testing target.

It seems that it doesn't work at all. While trying to use anything related to `XCUIApplication`, for example:
```
let alert = FBAlert(application: XCUIApplication.init(privateWithPath: nil, bundleID: "com.valid.BundleID"))
alert.isPresent()
```

I'm getting this error:
```
SomeTests.swift:0: error: -[UnitTestingTarget.SomeTests testSimple] : UI Testing Failure - Unable to update application state promptly.
```

However I'm able to use other commands which are not related to `XCUIApplication` directly, for example:
```
FBLogger.log("smth")
```
Output:
```
2016-11-02 02:17:16.480 MyApp[51158:2596829] smth
```
and no error.

Is this something that is supported but I'm doing it wrong or it's just not supported / going to be?

If it's not supported - is there any way to use it in unit testing target anyway?

Thanks in advance!

**Comment by marekcirkos** [comment]
Either you didn't launch application or you pass wrong bundle id.

**Comment by drptbl** [comment]
@marekcirkos I'm sure that bundle ID is proper (took it from Xcode) and application is launched (and visible on mobile screen) while trying to attach to it using `WebDriverAgentLib`.

**Comment by marekcirkos** [comment]
@drptbl Have a look at `FBAlertTests.m`

**Comment by drptbl** [comment]
@marekcirkos But `IntegrationTests` are UI testing target and my issue is related to unit testing target.

**Comment by marekcirkos** [comment]
WDA will not give you anything for unit tests. It is implemented as UIXCTest and can be used as a helper for ui test, but will not work with regular unit tests.

**Comment by drptbl** [comment]
@marekcirkos EarlGrey is using unit testing target and combining it together with WDA would make it even more powerful.

**Comment by marekcirkos** [comment]
All classes that WDA uses are XCUI related and they do not work in UnitTests.
