### ISSUE TITLE
typing requires the software keyboard <- provide a useful error

### ISSUE THREAD

**Issue by Jonahss** [facebook/WebDriverAgent#35]
Trying to use a command like `PUT /value` or `PUT /keys` to type into a text field fails pretty cryptically with a "cannot tap ..." error if the software keyboard is not up.

Is there an easy way to detect if software keyboard is enabled/present in order to give users a more informative error?

**Comment by lawrencelomax** [comment]
You will probably see a `UIAKey` in the hierarchy.

**Comment by Jonahss** [comment]
Ill look for it.

Also, do you know how I could activate the software keyboard for simulators? (command + k on simulator app)

**Comment by mmmulani** [comment]
Open Simulator.app in Hopper, it should have some API for it

**Comment by lawrencelomax** [comment]
You should check out how FBSimulatorControl does this. There's an arg that is passed to the Simulator app that overrides the default for the launch.

**Comment by Jonahss** [comment]
Thanks.
I found out that new sims by default have it enabled, there was just an unrelated issue with the /value command. All fixed now :)

**Comment by Jonahss** [comment]
I'll leave this, as a reminder to give the user a useful error if their soft keyboard is disabled.

**Comment by marekcirkos** [comment]
@Jonahss is this an issue for xctwda as well?

**Comment by Jonahss** [comment]
I don't remember, it's enabled by default on simulators.

Easy to test though.

**Comment by marekcirkos** [comment]
@Jonahss any update?

**Comment by Jonahss** [comment]
No update. I'm no longer working on much appium code in the near future, but the other appium devs will be picking it up

**Comment by marekcirkos** [comment]
@bootstraponline Any update here?

**Comment by bootstraponline** [comment]
@marekcirkos there are currently no appium developers allocated to WebDriverAgent. It'll be up to the Facebook devs & other contributors to keep things moving forward. I'm hoping at some point the appium team expands and we'll be able to spend time on WDA.

**Comment by marekcirkos** [comment]
@bootstraponline Cool, thanks for information

**Comment by marekcirkos** [comment]
Check with XCTWDA and it works with both software and hardware keyboard.
