### ISSUE TITLE
Socket Timeout - Too many instances of this services are already running

### ISSUE THREAD

**Issue by andreiaionitoaiesv** [facebook/WebDriverAgent#355]
The problem

After 5-6 test runs (i ran only one test) the WebDriverAgent seems to be stucked in a weird state. The only thing that I can do here is to restart the phone. Not a viable solution. Any thoughts?

Environment

Appium version - 1.6.1-beta
OS X El Capitan 10.11.6
Node.js version 7.0.0
iOS 10.1.1
Real device
Link to Appium logs

https://gist.github.com/andreiaionitoaiesv/ed88032ed99e301ba32e2af344bbf6f6

**Comment by marekcirkos** [comment]
This is Xcode issue, nothing I can do, sorry.

**Comment by andreiaionitoaiesv** [comment]
Oh that's a bummer. Can you provide a workaround if you know? Anyway thanks.

**Comment by marekcirkos** [comment]
It was either Xcode restart or system restart.

**Comment by andreiaionitoaiesv** [comment]
@marekcirkos 
Does the WebDriver needs to be compiled at every test session? Can I skip this step and send a server command to start the server directly? I'm looking ways to increase the test execution speed.

**Comment by marekcirkos** [comment]
1. There is xcodebuild switch that can launch pre-build xctest
2. Single WDA launch can handle multiple non-concurrent sessions.

**Comment by LeicaAPiQ** [comment]
Has anybody reported this issue to apple support team ??
