### ISSUE TITLE
Setting Orientation no long works

### ISSUE THREAD

**Issue by imurchie** [facebook/WebDriverAgent#356]
Ever since commit 61323c31289e76f2618347c385f78a0b5b7ea838 setting the orientation stopped working. Now when the following is sent:

```
POST http://localhost:8100/session/78750393-C544-4B9B-8FFE-CD92E7DD6B1A/orientation 
with body: {"orientation":"LANDSCAPE"}
```

We get an odd error (code 777?)

```
{"value":"Unable To Rotate Device","sessionId":"78750393-C544-4B9B-8FFE-CD92E7DD6B1A","status":777}
```

**Comment by marekcirkos** [comment]
Probably `return [self waitUntilInterfaceIsAtOrientation:orientation]` in `fb_setDeviceInterfaceOrientation ` should be `return [self waitUntilInterfaceIsAtOrientation:[XCUIDevice sharedDevice].orientation]`

**Comment by marekcirkos** [comment]
I'll have a look tomorrow, or you can create PR :)

**Comment by marekcirkos** [comment]
Btw I guess I was super lucky with integration tests.

**Comment by imurchie** [comment]
That doesn't seem to work, either. The orientation is never changed.

**Comment by marekcirkos** [comment]
Omg, I made super simple mistake. Fix is on the way

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/c385dc34c7b3a5facffc7872d6e9263c037fa022

**Comment by imurchie** [comment]
Awesome! Fixed. Thanks!
