### ISSUE TITLE
Error copying attributes

### ISSUE THREAD

**Issue by philipsTanoto** [facebook/WebDriverAgent#357]
When trying to get the page source for a specific page of the App I get this error:
The page contains user profile info, which includes email, name, sex, gender, birthdate, height, weight.
It is working on any other pages, so I'm not quite sure what is causing this error.

XCTRunner[453:180715] Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x17405b120> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1

full error log:
https://gist.github.com/philipsTanoto/5e2ebe49e3a3e3ddd4cdca81a22d8574

https://github.com/mykola-mokhnach suggested that https://github.com/facebook/WebDriverAgent/pull/332 should fix my issue, but it doesn't, any way to fix this?

Running on iOS 10.0.0 with iPhone 5S.

**Comment by uimator** [comment]
+1

**Comment by marekcirkos** [comment]
Can you check https://github.com/facebook/WebDriverAgent/commit/381a4845aaf839858e05e07e10ea86eea8bf37c2 ?

**Comment by mykola-mokhnach** [comment]
@philipsTanoto There might be also cases where this errors happens because UI is doing some updates in background while XCTest is trying to read attribute values. In such case only hardcoded sleep may help sometimes to make sure all the background updates are finished before doing any actions with XCTest. See the discussion in https://github.com/facebook/WebDriverAgent/pull/358 for more details

**Comment by philipsTanoto** [comment]
@marekcirkos https://github.com/facebook/WebDriverAgent/commit/381a4845aaf839858e05e07e10ea86eea8bf37c2 fixed the issue. Thanks a lot @mykola-mokhnach @marekcirkos !

**Comment by toejough** [comment]
what's the right way to update to get this fix working with Appium?  I've checked out the commit, replaced the appium version of WDA with this one, run the boostrap.sh, and also built with xcode - I still have this exact error.  I'm hoping I'm just missing some simple step...
