### ISSUE TITLE
I can't localize WebDriverAgentRunner.xctest file

### ISSUE THREAD

**Issue by fabiomeyra** [facebook/WebDriverAgent#359]
Hi all,

i'm trying start up webdriver via fbsimctl, but i can't localize 'WebDriverAgentRunner.xctest' file to start the service, already tried find them with the mdfind command, however, it no find's anything.  
anyone can help's me?

**Comment by marekcirkos** [comment]
On Xcode after you build, you can right click on WebDriverAgentRunner.xctest product and select "Show in Finder". It might point some runner app, but if you inspect the package you could be able to find it there

**Comment by fabiomeyra** [comment]
thank you, it work. how i use curl commands to interact with device?
how it work's? i should program my features? it's not clear for me.
sorry, i'm beginner. if could you help me i would grateful.

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/wiki/Queries
