### ISSUE TITLE
difficulty typing into UIATextField

### ISSUE THREAD

**Issue by Jonahss** [facebook/WebDriverAgent#36]
Typing into a TextField on [our test app](https://github.com/appium/ios-test-app), I'm running into difficulties.

Hitting the `/value` endpoint like `POST http://localhost:8111/session/c3152b20-b9ea-4143-bb73-cbfa66ed80a0/element/3/value] with body: {"value":["hello"]}` triggers this code:

https://github.com/facebook/WebDriverAgent/blob/79cc04d9fff39da03d49180986cca1fbb227ba33/WebDriverAgentLib/WebDriverCommands/FBElementCommands.m#L91-L100

We check if the element has keyboard focus. Logging the value of `[element hasKeyboardFocus]` evaluates to `(null)` even when the element has keyboard focus in the simulator.

If the keyboard is hidden, the keys cannot be tapped, so we call `[element tap]` to bring it up. My problem is that this code never brings the keyboard up.

If I hit the `/click` endpoint for the TextField the keyboard comes up, and I can then hit the `/value` endpoint and everything works. But the "automatic" tap to give the TextField focus and bring up the keyboard isn't working for me.

What baffles me, is the same method call is used in the `/click` and `/value` endpoints, so why one works and the other doesn't is beyond me. I tried adding a sleep command after the tap to no avail.

Have you been able to call the `/value` endpoint to type, without first calling `/click`?

**Comment by mmmulani** [comment]
so this is bizarre. Yes calling `/value` without calling `/click` is actually how most of our code works.

one thing that's kind of weird is we send an array of the characters, e.g. we hit `/value` with a body of `{"value":["h","e","l","l","o"]}`. Try that out?

**Comment by Jonahss** [comment]
I tried sending the array and still got the same behavior. WebDriverAgent responds like so:
```
{
    "sessionId": null,
    "status": 10,
    "value": "-[UIAElementNil setInterKeyDelay:]: unrecognized selector sent to instance 0x7ff013cf0330"
}
```

That interKeyDelay happens here I assume: https://github.com/facebook/WebDriverAgent/blob/79cc04d9fff39da03d49180986cca1fbb227ba33/WebDriverAgentLib/WebDriverCommands/FBElementCommands.m#L184

And probably happens because `keyboard` is null. `keyboard` is null because the `tap` command didn't bring up the keyboard.

Perplexing because this must work fine for you. What version of XCode are you able to run this successfully on? What version of iOS? I'm, using XCode 7.1 iOS 9.1

**Comment by Jonahss** [comment]
Ahhhhhhhhhh figured it out. Almost drove me crazy, but noticed this: https://github.com/facebook/WebDriverAgent/blob/79cc04d9fff39da03d49180986cca1fbb227ba33/WebDriverAgentLib/WebDriverCommands/FBElementCommands.m#L92

It's getting elementID from `arguments` instead of `parameters` >.<
So it got a null ID, which it just silently taps.
