### ISSUE TITLE
Too long loop

### ISSUE THREAD

**Issue by Lexx918** [facebook/WebDriverAgent#361]
If the string length is large, loop takes too long. Define it before the loop. Please!
```
- (BOOL)fb_clearTextWithError:(NSError **)error
{
  NSMutableString *textToType = @"".mutableCopy;
  for (NSUInteger i = 0 ; i < [self.value length] ; i++) {
    [textToType appendString:@"\b"];
```
(C) [WebDriverAgentLib/Categories/XCUIElement+FBTyping.m line 31](https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement%2BFBTyping.m#L31)

**Comment by marekcirkos** [comment]
1. Please open PR if you want to improve WDA, I will be more than happy to review it.
2. How do you know it is loop issue?
3. How long is you string?

**Comment by Lexx918** [comment]
> How do you know it is loop issue?

Cause I checked it https://github.com/qa-dev/WebDriverAgent/pull/11/files

> How long is you string?

About 100-200 bytes. You calculate the length of the string in each iteration of the loop. Running another search element. Again and again. _**facepalm.jpg**_

**Comment by mykola-mokhnach** [comment]
Yup, this is not a problem in "usual" C world, but ObjectiveC is not the case:
http://iosdevelopertips.com/objective-c/high-performance-collection-looping-objective-c.html

**Comment by marekcirkos** [comment]
@Lexx918 We call length on immutable string, which I highly doubt it actually runs a string every single time and most likely uses cached value. Thing that might be problematic is calling `self.value` it might be resolving element which would be super slow. @Lexx918 can you pop a PR?

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/38c7e7c925198267df15a611462fd85758a681d2
