### ISSUE TITLE
tap coordinate still wrong on landscape mode, iOS 10

### ISSUE THREAD

**Issue by codeskyblue** [facebook/WebDriverAgent#362]
- iOS: 10.0.1
- Lastest WDA code
- Model: iPhone 6 Plus (MGAJ2CH/A)

Use `iproxy` to communicate to phone.

Should tap `关于本机`, Actually tap `CarPlay`

![image](https://testerhome.com/photo/2016/eb47f80e27717cb5cefd5098f699dd12.png)

**Comment by marekcirkos** [comment]
I broke rotations, so that might be related. However can you post what are frames for both?

**Comment by marekcirkos** [comment]
Found an issue, fix is on the way.

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/464e7adb32ac3e2cdc24129d4cb4e2f2ec87c834

**Comment by marekcirkos** [comment]
@codeskyblue Please confirm

**Comment by codeskyblue** [comment]
last night I update my iPhone to 10.1.1
So xcode should also update, It may take 6~8 hours because of the slow network.
Sorry I can't confirm recently.

**Comment by codeskyblue** [comment]
last night I update my iPhone to 10.1.1
So xcode should also update, It may take 6~8 hours because of the slow network.
Sorry I can't confirm recently.

**Comment by codeskyblue** [comment]
last night I update my iPhone to 10.1.1
So xcode should also update, It may take 6~8 hours because of the slow network.
Sorry I can't confirm recently.

**Comment by codeskyblue** [comment]
last night I update my iPhone to 10.1.1
So xcode should also update, It may take 6~8 hours because of the slow network.
Sorry I can't confirm recently.

**Comment by codeskyblue** [comment]
Confirm. still the wrong coordinate.

**Comment by marekcirkos** [comment]
Which endpoint are you using?

**Comment by marekcirkos** [comment]
@codeskyblue ?

**Comment by codeskyblue** [comment]
Sorry for my delay, I can not upload the image, because the bad network.

This is my request

```
curl -X POST -d '{"using": "link text", "value": "name=\u652f\u4ed8\u5b9d"}' 'http://127.0.0.1:8100/session/E0C2F178-039B-4585-9FF1-CAC68E8B41AA/elements'
Return: {
    "status": 0, 
    "sessionId": "E0C2F178-039B-4585-9FF1-CAC68E8B41AA", 
    "value": [
        {
            "label": "\u652f\u4ed8\u5b9d", 
            "type": "XCUIElementTypeIcon", 
            "ELEMENT": "1DACE820-4D21-4163-9308-3E9ACCC11AA1"
        }
    ]
}
```

**Comment by marekcirkos** [comment]
@codeskyblue This finds elements not taps them right?

**Comment by codeskyblue** [comment]
no. not right. or I will close this issue

**Comment by marekcirkos** [comment]
@codeskyblue I don't understand. Your curl request finds elements does not tap them.

**Comment by codeskyblue** [comment]
tapped but with wrong position.

**Comment by marekcirkos** [comment]
@codeskyblue I understand that, but which endpoint do you use to tap element?

**Comment by codeskyblue** [comment]
I dont very understand. Are you mean

```
curl -X POST -d '{"using": "link text", "value": "name=\u652f\u4ed8\u5b9d"}' 'http://127.0.0.1:8100/session/E0C2F178-039B-4585-9FF1-CAC68E8B41AA/elements'
Return: {
    "status": 0, 
    "sessionId": "E0C2F178-039B-4585-9FF1-CAC68E8B41AA", 
    "value": [
        {
            "label": "\u652f\u4ed8\u5b9d", 
            "type": "XCUIElementTypeIcon", 
            "ELEMENT": "1DACE820-4D21-4163-9308-3E9ACCC11AA1"
        }
    ]
}
```

**Comment by marekcirkos** [comment]
@codeskyblue Request you posted will search for an element, not tap it. Which you request do you use to tap this element.

**Comment by codeskyblue** [comment]
```
Shell: curl -X POST -d '{"using": "link text", "value": "name=\u652f\u4ed8\u5b9d"}' 'http://127.0.0.1:8100/session/959F6D0F-1906-43F0-A3C7-5189124E5F54/elements'
Return: {
    "status": 0, 
    "sessionId": "959F6D0F-1906-43F0-A3C7-5189124E5F54", 
    "value": [
        {
            "label": "\u652f\u4ed8\u5b9d", 
            "type": "XCUIElementTypeIcon", 
            "ELEMENT": "A5F50B69-CE78-4171-B95C-6BF59AC89BAA"
        }
    ]
}
Shell: curl -X POST -d '' 'http://127.0.0.1:8100/session/959F6D0F-1906-43F0-A3C7-5189124E5F54/element/A5F50B69-CE78-4171-B95C-6BF59AC89BAA/click'
Return: {
    "status": 0, 
    "sessionId": "959F6D0F-1906-43F0-A3C7-5189124E5F54", 
    "id": "A5F50B69-CE78-4171-B95C-6BF59AC89BAA", 
    "value": ""
}
```

**Comment by marekcirkos** [comment]
@codeskyblue Does it still tap `CarPlay` or something else?

**Comment by codeskyblue** [comment]
tap something else. I really wish I can send pictures to you. But my network just not allow me to do that.

**Comment by codeskyblue** [comment]
should here

```
.--------------.
|                        |
|         x             |
\_______________/
```

but actually here

```
.--------------.
|                        |
|       x               |
\_______________/
```

**Comment by AliNL** [comment]
@marekcirkos I'm facing this issue too with the latest commit. Seems the rotation fix for landscape still not working as expected.

**Comment by marekcirkos** [comment]
@AliNL @codeskyblue both cases are iOS 10?

**Comment by AliNL** [comment]
@marekcirkos Yes, mine is IOS 10.1

**Comment by mykola-mokhnach** [comment]
I can confirm it for tablet landscape mode.

```
2016-12-06 16:05:36 DEBUG FBDriverRESTClient: Request to http://localhost:8100/session/1A7C77BB-C888-4FF9-91D1-9FBA2132390C/tap/1614A5EF-DB6A-47E7-B07A-5520EC65A609...
2016-12-06 16:05:36 DEBUG CommonRESTHandlers: POST REQUEST...
2016-12-06 16:05:36 DEBUG CommonRESTHandlers:  >>> Input data: {"x":15,"y":15}
2016-12-06 16:05:38 DEBUG CommonRESTHandlers:  >>> Response: {
  "value" : {

  },
  "sessionId" : "1A7C77BB-C888-4FF9-91D1-9FBA2132390C",
  "status" : 0
}
```

This was supposed to click at the center of the corresponding element but clicked somewhere else instead.

**Comment by mykola-mokhnach** [comment]
BTW, _/rect_ API call returns correct values for the element in landscape mode.

**Comment by marekcirkos** [comment]
@mykola-mokhnach Tapping at coordinates will probably not work. I patched only tapping elements using `click` command. I wanted to come up with more general approach rather than patching all places one by one, but didn't have time to do it.

**Comment by mykola-mokhnach** [comment]
@codeskyblue  Can you try to apply this [patch](https://github.com/facebook/WebDriverAgent/issues/411) and check whether it fixes landscape clicking issues for you?

**Comment by codeskyblue** [comment]
@mykola-mokhnach only tested your code in iOS9.3.5 iPhoneSE. it works.

**Comment by codeskyblue** [comment]
@marekcirkos any progress on this issue?
