### ISSUE TITLE
'RoutingHTTPServer/RoutingConnection.h' file not found/'RoutingHTTPServer/RoutingHTTPServer.h' file not found

### ISSUE THREAD

**Issue by HenryGu8** [facebook/WebDriverAgent#363]
Hi,
 
I encountered following issue when trying to run IDEA to access Appium.

'RoutingHTTPServer/RoutingConnection.h' file not found/'RoutingHTTPServer/RoutingHTTPServer.h' file not found

Appium: 1.6
Xcode: 8

Please help to find following log and attached file

[Xcode] 2016-11-10 14:06:34.523 xcodebuild[10705:233757] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/ArsenalHenry/Library/Developer/Xcode/DerivedData/WebDriverAgent-dbspoxabprehmoamvpuchbnacbpt/Logs/Test/7E74D026-822C-41E8-9419-BE04F30E3BCE/Session-WebDriverAgentRunner-2016-11-10_140632-qlRaGL.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/ArsenalHenry/Library/Developer/Xcode/DerivedData/WebDriverAgent-dbspoxabprehmoamvpuchbnacbpt/Logs/Test/7E74D026-822C-41E8-9419-BE04F30E3BCE/Session-WebDriverAgentRunner-2016-11-10_140632-qlRaGL.log}

[Xcode] 2016-11-10 14:06:34.525 xcodebuild[10705:233764] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7f8c38fdb490>

[Xcode]
**Testing failed:
	'RoutingHTTPServer/RoutingHTTPServer.h' file not found
** TEST FAILED ****
![image](https://cloud.githubusercontent.com/assets/23373988/20166793/2eafcdfe-a752-11e6-9a00-b32d7109a0db.png)

**Comment by sixleaves** [comment]
u should open terminal and input ./Scripts/bootstrap.sh

**Comment by marekcirkos** [comment]
or/and raise this issue with Appium.
