### ISSUE TITLE
"(null)" value is shown in log as server name if WiFi is disabled/not available on real device

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#364]
1. Disable WiFi on real iPhone
2. Build the runner using command:

```
xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=dev_id -configuration Debug
```

3. Wait until "ServerURLHere->" log record appears

AR:
There is 

```
1970-01-01 02:06:55.494327 XCTRunner[279:13639] ServerURLHere->http://(null):8100<-ServerURLHere
1970-01-01 02:06:55.497262 XCTRunner[279:13639] Listening on USB
```

log record

ER:
I expect to see correct output here
OR
WDA should throw an exception instead

**Problem source:**

FBWebServer.m

```
[XCUIDevice sharedDevice].fb_wifiIPAddress
```

variable, which is set to _null_ if WiFi network address is not set and is not verified against that.

**Comment by marekcirkos** [comment]
If WiFi is disabled, obviously we can't print IP address. Throwing an exception is not a good ideas as you might still want to communicate with device via USB. Best we can do is not print this message or print warning.

If you want to create PR I will be happy to review it.

**Comment by mykola-mokhnach** [comment]
The importtant thing is, that Appium code relies on this particular log line. So, probably, it would be better to sync with @imurchie or @jlipps on how to implement the fix properly.

**Comment by imurchie** [comment]
Appium does not rely on this anymore. We wait for it to be printed, so we know the system is ready to accept commands, but then we use `iproxy` to connect through USB. The host is always changed to `localhost`.

**Comment by marekcirkos** [comment]
Probably you can watch for this message or warning message.

**Comment by marekcirkos** [comment]
I guess you search for `ServerURLHere`?
We can replace `null with better one like `localhost`.
Any other ideas?
