### ISSUE TITLE
Automatically close alert "leftovers" after WDA startup

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#367]
This is mostly relevant for real device testing. The problem is that if we run multiple tests there could be a situation when a test fails and WDA closes application under test, but any alert stays on the screen if it was previously invoked by the app. This prevents WDA driver to start for the following test cases and there is no way to close this "zombie" alert from automated test. Only manual close is possible.
I have added a workaround in my code to call accept alert on quit, but it only works if the driver is still alive at this moment. And in situations, when the driver fails because of a timeout or because of an internal exception there is no way to properly close the alert.

I see one possible solution for the described problem (dunno if it is possible even in theory): close all visible alerts as soon as WDA application starts.

**Comment by marekcirkos** [comment]
Can't your client check for alerts and dismiss them before starting session?

**Comment by mykola-mokhnach** [comment]
Do you mean the application under test(AUT) itself or the testing framework? AUT cannot do this, because it is started by WDA, which cannot be started due to the issue described above. Regarding the framework itself - I don't know any iOS command line tool, which allows to close on-screen alerts. Probably you know any?

**Comment by marekcirkos** [comment]
I meant testing framework, could check for alert presence using WDA just before starting new session (launching AUT). Do you have problems starting WDA with alert present?

**Comment by mykola-mokhnach** [comment]
yep, WDA just cannot start properly. xcodebuild fails with error 1, since it cannot be put to the background. The problem is easy to reproduce: execute any app, that produces alerts, leave the alert be and then start WDA.

**Comment by marekcirkos** [comment]
I don't think we can handle that from WDA point of view. This must by system alert tho any application alert die when application dies.

**Comment by marekcirkos** [comment]
@mykola-mokhnach Are you ok to close this task or you still validating it?

**Comment by mykola-mokhnach** [comment]
no pb. I can close it.

**Comment by ACBNair** [comment]
@imurchie  Did we fix this issue? Pardon me, I didn't get why you referenced this in one of the commits. Could you explain?
