### ISSUE TITLE
Question about type text to a TextField

### ISSUE THREAD

**Issue by Royshcn** [facebook/WebDriverAgent#368]
I got error when I use DEVICE_URL/session/$SESSION_ID/element/5/value 

{  "value" : "Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}",  "sessionId" : "09AB695F-1221-4C50-98F2-85CAF8494315",  "status" : 13}

I guess the reason was that TextField is almost invisible.  

How can I scroll page a little bit down before typing text? I tried using scroll {'direction':'down'}  but it seems scrolling to big.

please give some help.

**Comment by imurchie** [comment]
You ought to be able to click on a TextField and the keyboard will come up and the placement of the TextField will be adjusted by iOS.

**Comment by marekcirkos** [comment]
This endpoint should tap on textview if it does not have keyboard focus. Looks like we failed to deliver  tap. You can try to scroll till visible https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L272

**Comment by marekcirkos** [comment]
@Royshcn Can you create PR with this test case on `IntegrationApp`?

**Comment by marekcirkos** [comment]
Ping

**Comment by Royshcn** [comment]
@marekcirkos Sorry for repling too late. I will try  to use scroll till visible. Thanks.

**Comment by marekcirkos** [comment]
@Royshcn Please let us know if it helped.
