### ISSUE TITLE
Why WebDriverAgentLib Deployment Target is set to iOS9.3?

### ISSUE THREAD

**Issue by chsasaw** [facebook/WebDriverAgent#370]
Since XCUITest supports iOS9.0 and above, I have tested WDARuner on iOS9.2, it was running normally.

**Comment by marekcirkos** [comment]
I do not remember exactly, but there were some differences in XCTest private methods related to visibility checks. Same code on pre iOS 9.3 will most likely crash on visibility checks.

**Comment by chsasaw** [comment]
Would you please find out those methods?

**Comment by chsasaw** [comment]
I can't find any crashes on iOS9.0, Any suggestion?

**Comment by marekcirkos** [comment]
Open inspector and check if it works properly? Also make sure if "isVisible" properties have correct values

**Comment by chsasaw** [comment]
Have checked on simulator 9.0, iPhone5, inspector works properly, and "isVisible" value is correct.Any other problems?

**Comment by marekcirkos** [comment]
Which Xcode do you use?

**Comment by chsasaw** [comment]
Xcode8.1

**Comment by marekcirkos** [comment]
@chsasaw I would check that on devices. Simulators will most likely be fine as the all will use same XCTest.framework. If you want to check on simulators, best would be to get Xcode 7.0.

**Comment by marekcirkos** [comment]
ping

**Comment by chsasaw** [comment]
@marekcirkos 
Sorry for waiting for so long time, I have tested on device(iOS9.2.1 iPhone5s), and it works fine. Include inspector and click events and element's visibility is correct.Tried my best....

**Comment by marekcirkos** [comment]
@chsasaw I am not sure, there defiantly was a problem that, but I do not remember exactly what was it (It was over a year ago). @chsasaw Do you really care about changing it in repo?

**Comment by chsasaw** [comment]
@marekcirkos  Yes, it is important to me. It decides the devices I can connect.

**Comment by marekcirkos** [comment]
I think this is Xcode version specific than and not iOS. Feel free to pop a PR
