### ISSUE TITLE
Make screenshoting option configurable from WDA

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#373]
This report is based on https://github.com/appium/appium/issues/7242
XCTest creates a lot of extra data by default, which is not needed (and slows down testing, since screenshoting takes time). It would be useful to disable derived data collection directly from untiltest config in WDA if there is a way to it.
The [solution](http://stackoverflow.com/questions/35697867/how-to-turn-off-automatic-screenshots-on-ui-testing-xcode/35853146) with /dev/null looks more like a hacky workaround to me, since XCTest is still trying to generate the data even if this data is going to be recorded to nowhere.

**Comment by marekcirkos** [comment]
Yes there is a way. You can use fbsimctl to launch WDA :). Unfortunately from WDA point of view there is nothing we can do.

**Comment by mykola-mokhnach** [comment]
Can you please provide more details on this? Probably, we might implement the same stuff in Appium as well. I have checked fbsimctl source and it looks like XCTestConfiguration contains some properties, which might be useful to us, but this bloody stuff is private and has no documentation, so I have no idea how to work with it.

@imurchie FYI

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/wiki/Starting-WebDriverAgent#c-using-fbsimctl-from-fbsimulatorcontrol-framework
