### ISSUE TITLE
xcodebuild archive commas is failing due to warnings and -Werror

### ISSUE THREAD

**Issue by among29** [facebook/WebDriverAgent#374]
osx：10.11.6
Xcode 8.1

git clone --depth 1 https://github.com/facebook/WebDriverAgent.git
./Scripts/build.sh

error info:

diateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/XCTestPrivateSymbols.o
/Users/among/xpj/WebDriverAgent/WebDriverAgentLib/Utilities/XCTestPrivateSymbols.m:35:97: error: must specify at least one argument for '...' parameter of
      variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
  NSCAssert(FB_XCAXAIsVisibleAttribute != nil , @"Failed to retrieve FB_XCAXAIsVisibleAttribute");
                                                                                                ^
In module 'Foundation' imported from /Users/among/xpj/WebDriverAgent/WebDriverAgentLib/Utilities/XCTestPrivateSymbols.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSException.h:139:9: note: 
      macro 'NSCAssert' defined here
#define NSCAssert(condition, desc, ...) do {} while (0)
        ^
/Users/among/xpj/WebDriverAgent/WebDriverAgentLib/Utilities/XCTestPrivateSymbols.m:36:97: error: must specify at least one argument for '...' parameter of
      variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
  NSCAssert(FB_XCAXAIsElementAttribute != nil , @"Failed to retrieve FB_XCAXAIsElementAttribute");
                                                                                                ^
In module 'Foundation' imported from /Users/among/xpj/WebDriverAgent/WebDriverAgentLib/Utilities/XCTestPrivateSymbols.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSException.h:139:9: note: 
      macro 'NSCAssert' defined here
#define NSCAssert(condition, desc, ...) do {} while (0)
        ^
/Users/among/xpj/WebDriverAgent/WebDriverAgentLib/Utilities/XCTestPrivateSymbols.m:42:67: error: must specify at least one argument for '...' parameter of
      variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
  NSCAssert(XCTestClass != nil, @"XCTest should be already linked");
                                                                  ^
In module 'Foundation' imported from /Users/among/xpj/WebDriverAgent/WebDriverAgentLib/Utilities/XCTestPrivateSymbols.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSException.h:139:9: note: 
      macro 'NSCAssert' defined here
#define NSCAssert(condition, desc, ...) do {} while (0)
        ^
/Users/among/xpj/WebDriverAgent/WebDriverAgentLib/Utilities/XCTestPrivateSymbols.m:45:71: error: must specify at least one argument for '...' parameter of
      variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]
  NSCAssert(binaryPath != nil, @"XCTest binary path should not be nil");
                                                                      ^
In module 'Foundation' imported from /Users/among/xpj/WebDriverAgent/WebDriverAgentLib/Utilities/XCTestPrivateSymbols.h:10:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSException.h:139:9: note: 
      macro 'NSCAssert' defined here
#define NSCAssert(condition, desc, ...) do {} while (0)
        ^
4 errors generated.

CompileC /Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/XCUIElement+FBTyping.o WebDriverAgentLib/Categories/XCUIElement+FBTyping.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/among/xpj/WebDriverAgent
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin:/Applications/android-sdk-macosx/tools:/Applications/android-sdk-macosx/platform-tools"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=156 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/among/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/among/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -fno-common -Werror -Wmissing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Warc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wunused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -pedantic -Wshadow -Wno-four-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wassign-enum -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=0 -DDDXML_LIBXML_MODULE_ENABLED=0 -DNS_BLOCK_ASSERTIONS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=9.3 -g -Wno-sign-conversion -Winfinite-recursion -iquote /Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-generated-files.hmap -I/Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-own-target-headers.hmap -I/Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-all-target-headers.hmap -iquote /Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-project-headers.hmap -I/Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/BuildProductsPath/Release-iphoneos/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/usr/include/libxml2 -I/Users/among/xpj/WebDriverAgent/Modules -I/Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/DerivedSources/armv7 -I/Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/DerivedSources -Weverything -Wno-objc-missing-property-synthesis -Wno-unused-macros -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-language-extension-token -Wno-overriding-method-mismatch -Wno-missing-variable-declarations -Rno-module-build -Wno-auto-import -Wno-objc-interface-ivars -Wno-documentation-unknown-command -Wno-reserved-id-macro -Wno-unused-parameter -Wno-gnu-conditional-omitted-operand -Wno-explicit-ownership-type -Wno-date-time -Wno-cast-align -Wno-cstring-format-directive -Wno-double-promotion -F/Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/BuildProductsPath/Release-iphoneos -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F/Users/among/xpj/WebDriverAgent/Carthage/Build/iOS -F/Users/among/xpj/WebDriverAgent/Carthage/Build/Mac -F/Users/among/xpj/WebDriverAgent/Carthage/Build/tvOS -MMD -MT dependencies -MF /Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/XCUIElement+FBTyping.d --serialize-diagnostics /Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/XCUIElement+FBTyping.dia -c /Users/among/xpj/WebDriverAgent/WebDriverAgentLib/Categories/XCUIElement+FBTyping.m -o /Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/XCUIElement+FBTyping.o

** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/among/Library/Developer/Xcode/DerivedData/WebDriverAgent-gjzlrzigwygatngajticarczdlpp/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/XCTestPrivateSymbols.o WebDriverAgentLib/Utilities/XCTestPrivateSymbols.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
macbook:WebDriverAgent among$

**Comment by marekcirkos** [comment]
This is archive, not build. Should be easy to fix as it fails due to warning on macro. Feel free to pop a PR
