### ISSUE TITLE
Auto scroll   is gone 

### ISSUE THREAD

**Issue by bearxc** [facebook/WebDriverAgent#375]
when try to click an invisible component ,   WDA did auto scroll before , now this auto scroll  has been removed , and click does not work any more .    we have to scroll manually   and make sure component  in the view before apply click action .  It is really not convince .  

I have to rollback to old code base  so far ,  and  maybe  cherry pick  other commits  .

**Comment by marekcirkos** [comment]
@bearxc  Yes, I did revert it, as it wasn't stable and caused a lot of failures for us.
