### ISSUE TITLE
WebDriverAgent only accepts orientation is uppercase value

### ISSUE THREAD

**Issue by nghiadhd** [facebook/WebDriverAgent#377]
I tried to set the new orientation (lowercase) via wd.io APIs but WebDriverAgent always returns "Unable To Rotate Device" message
http://webdriver.io/api/mobile/setOrientation.html

I investigated the WebDriverAgent sources and see it only accepts uppercase orientation value
https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBOrientationCommands.m#L103

I think that is big problem for tester who cannot access to WebDriverAgent's source and think that is problem of device

Expected: the orientation should be convert to uppercase before used as mapping key

**Comment by marekcirkos** [comment]
@nghiadhd I definitely agree. Feel free to pop a PR with that change.

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commits/master
