### ISSUE TITLE
Too much logs

### ISSUE THREAD

**Issue by isnifer** [facebook/WebDriverAgent#380]
Hi, guys!
How can I avoid this issue?
![image](https://cloud.githubusercontent.com/assets/1788245/20493711/f35e1044-b02a-11e6-83ce-7a2751f1cb1c.png)

**Comment by marekcirkos** [comment]
I assume you use Xcode to start WDA. This size of logs can be explained by all screenshots XCUITest gathers while running WDA. Unfortunately there is nothing we can do on WDA side, however you should consider to use FBSimulatorControl for starting WDA. It will perform much faster and reduces number of logging.
