### ISSUE TITLE
Application is not running, possibly crashed, but the app is still running in my simulator

### ISSUE THREAD

**Issue by phoebusliang** [facebook/WebDriverAgent#388]
Steps:

1. download newest version of webdriveragent project
2. use fbsimctl to boot and install my app: xx.app
3. execute ./Documents/fbsimctl/fbsimctl --state=booted launch_xctest /Users/name/Documents/workspace/xcode/WebDriverAgent/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest xxapp --port 8101 -- listen
4. the result of 'step3' in console like below, and xxapp start then run as background

Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
C23B6BE0-EC4A-4560-B00E-E23D64E7C706 | iPhone 7 Plus | Booted | iPhone 7 Plus | iOS 10.0: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
Application Did Launch => Process xxapp | PID 82610
C23B6BE0-EC4A-4560-B00E-E23D64E7C706 | iPhone 7 Plus | Booted | iPhone 7 Plus | iOS 10.0: launch: Process xxapp | PID 82610
Connecting Test Bundle
Creating the test bundle connection.
Listening for proxy connection request from the test bundle (all platforms)
Resuming the test bundle connection.
Checking test manager availability...
Starting test session with ID EB42A77E-C406-4FC6-8CFE-7B6381AC47F0
testmanagerd handled session request using protcol version 22.
Got proxy channel request from test bundle
Test bundle is ready, running protocol 22, requires at least version 8. IDE is running 22 and requires at least 8
Test Bundle is Ready
Starting the daemon connection
Resuming the daemon connection.
Whitelisting test process ID 82610
Got whitelisting response and daemon protocol version 22
Ready to execute test plan
Bundle Connection scheduling start of Test Plan
Daemon Notified of start of test plan
TestManager Did Connect => TestManager Awaiting Result for (Test Host PID 82610 | Test Host Bundle xxapp | Session ID EB42A77E-C406-4FC6-8CFE-7B6381AC47F0)
Listen Started: empty
Test Plan Started
Started initilizing for UI testing.

5. I access to http://localhost:8101/status, the JSON response is:
{
value: {
state: "success",
os: {
name: "iOS",
version: "10.0"
},
ios: {
simulatorVersion: "10.0"
},
build: {
time: "Nov 26 2016 23:43:05"
}
},
sessionId: "29533E81-24EF-415E-9717-A7EB77E4221B",
status: 0
}

6. when i execute curl -X POST '-H "Content-Type: application/json"' -d "{\"using\":\"class name\",\"value\":\"XCUIElementTypeButton\"}" http://localhost:8101/session/13B27F37-B0F0-4D85-9972-0B36520B33C1/elements

the response(but my app is still running and no log in fbsimctl session.):
{
"value" : "Application is not running, possibly crashed",
"sessionId" : "13B27F37-B0F0-4D85-9972-0B36520B33C1",
"status" : 10
}%

**Comment by marekcirkos** [comment]
@phoebusliang Did you start new session or use default one?

**Comment by marekcirkos** [comment]
Ping

**Comment by phoebusliang** [comment]
Thanks so much. @marekcirkos , yes I start up a new session. I think the key problem is I didn't build the XCUITest bundle on my simulator at first. Now I boot all my simulators and install XCUITest bundle, after that, I can handle the session.

**Comment by chsasaw** [comment]
@marekcirkos  @phoebusliang 
How can I just install and launch webdriveragent.app on device? But not start from build project.
I tried ios-deploy and idevicedebug, and it can launch app, but cannot manage the session. I think the reason is XCUITest bundle not started.Can I use some tools like fbsimctl?

**Comment by marekcirkos** [comment]
@chsasaw Yep, fbsimctl will work.
