### ISSUE TITLE
/Resources/WebDriverAgent.bundle: No such file or directory

### ISSUE THREAD

**Issue by sepiol** [facebook/WebDriverAgent#390]
I've already ran the bootstrap.sh file for the dependencies and still get this error when trying to run WebDriverAgentRunner.

The build fails of course after this error.
Any thoughts on this?

![image](https://cloud.githubusercontent.com/assets/17814584/20664824/8dc420ee-b565-11e6-8cd5-6636aa029a60.png)

**Comment by marekcirkos** [comment]
Did you run `./Scripts/bootstrap.sh`?

**Comment by sepiol** [comment]
@marekcirkos thanks for the quick answer. As i wrote in my issue i've already ran it

**Comment by marekcirkos** [comment]
Bundle is created by bootstrap.sh script. If you did run it, maybe it is failing for you, but we don't advertise that properly. Can you paste its output?

**Comment by sepiol** [comment]
@marekcirkos 

This is the terminal output

![image](https://cloud.githubusercontent.com/assets/17814584/20665112/fa4506c4-b566-11e6-8a99-64a8da478271.png)

**Comment by marekcirkos** [comment]
Run it without `-d`

**Comment by sepiol** [comment]
@marekcirkos That did the trick! thank you very much and sorry to bother you with this ;)
