### ISSUE TITLE
Start WDA on device use fbsimctl

### ISSUE THREAD

**Issue by chsasaw** [facebook/WebDriverAgent#391]
I use 
`fbsimctl $device_id --state=booted launch_xctest ~/Desktop/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest com.apple.mobilesafari --port 8100 -- listen`

the device shows nothing, and the log in terminal is short
`Listen Started: empty`

Am I using the wrong way?

**Comment by marekcirkos** [comment]
You should poke that question on fbsimctl repo
