### ISSUE TITLE
Can we query elements with multi values?

### ISSUE THREAD

**Issue by phoebusliang** [facebook/WebDriverAgent#393]
WDA query elements with post body:

{
	"using":"class name",
	"value":"XCUIElementTypeButton"
}

Can we query different values one time with array like:

{
	"using":"class name",
	"value":[
		"XCUIElementTypeButton",
		"XCUIElementTypeTextField"
	]
}

**Comment by marekcirkos** [comment]
Using "class name" it does not. However with xpath or predicate it should be possible
