### ISSUE TITLE
Web Driver agent remains in state Listening on USB and the appium tests never start in real device.

### ISSUE THREAD

**Issue by ptsiakos77** [facebook/WebDriverAgent#399]
The problem

Web Driver agent remains in state Listening on USB and the appium tests never start in real device.

Environment
Appium version 1.6.2:

I start the appium programatically in order to run test in real device using XCuiTest:
You can find attached the logs from test and WebDriverAgent as well

[Session-2016-12-06_15:48:18-DNbfdC.txt](https://github.com/facebook/WebDriverAgent/files/634128/Session-2016-12-06_15.48.18-DNbfdC.txt)
[testLog.txt](https://github.com/facebook/WebDriverAgent/files/634129/testLog.txt)

The following desired capabilities are also set:

realDeviceLogger=usr/local/lib/node_modules/deviceconsole/deviceconsole
xcodeConfigFile=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/driverAgent.xcconfig

**Comment by marekcirkos** [comment]
From your logs it looks like WDA booted property and is waiting for requests.
If you can make request you should poke Appium guys.

**Comment by ptsiakos77** [comment]
The strange think here is that the first time I run a test in a new device the test starts. Subsequent tests never start even if I remove the webdriver agent from the mobile device, restart the iphone or even restart my mac. I even reinstalled appium. I observed this behavior in 2 different devices so I don't think is coincidence.

**Comment by mykola-mokhnach** [comment]
This is a problem in the recent Appium code:
https://github.com/appium/appium/issues/7313#issuecomment-265429856

@marekcirkos please close
