### ISSUE TITLE
how to use - (double)pinchInRect:(CGRect)arg1 withScale:(double)arg2 velocity:(double)arg3 orientation:(UIInterfaceOrientation)arg4 handler:(XCEventGeneratorHandler)arg5？

### ISSUE THREAD

**Issue by fenping** [facebook/WebDriverAgent#400]
when is use it ,throw EXC_BAD_ACCESS，all parameter is not nil

**Comment by marekcirkos** [comment]
WDA does not support that right? 
Regardless, I have no idea how you are calling so I can't really help you here. I would bet on bad `arg5` as it is callback block

**Comment by fenping** [comment]
I want to achieve pinch event，You can try to help achieve it?

**Comment by marekcirkos** [comment]
@fenping I can't help you if you will not give more information.
