### ISSUE TITLE
Any ideas why alert_text doesn't work for me ?

### ISSUE THREAD

**Issue by VasilijSviridov** [facebook/WebDriverAgent#401]
curl -X GET 'http://172.16.11.16:8100/session/66ADF8CF-D370-452E-AFC3-6C8FC24CC1B5/alert_text'

{
  "value" : "Unhandled endpoint: \/session\/66ADF8CF-D370-452E-AFC3-6C8FC24CC1B5\/alert_text -- http:\/\/172.16.11.16:8100\/ with parameters {\n    wildcards =     (\n        \"session\/66ADF8CF-D370-452E-AFC3-6C8FC24CC1B5\/alert_text\"\n    );\n}",
  "sessionId" : "66ADF8CF-D370-452E-AFC3-6C8FC24CC1B5",
  "status" : 1
}

**Comment by marekcirkos** [comment]
You should use `../alert/text` instead. https://w3c.github.io/webdriver/webdriver-spec.html#get-alert-text
