### ISSUE TITLE
Failed to get snapshot for Table with 200 cells.

### ISSUE THREAD

**Issue by tyutyunnykusa** [facebook/WebDriverAgent#402]
I have no ability to work with Table which contains 200 cells.
Please, advise!

Log:

2016-12-07 16:20:45.952404 XCTRunner[489:71350] Built at Dec  7 2016 15:49:28
2016-12-07 16:20:46.014124 XCTRunner[489:71350] ServerURLHere->http://10.10.28.5:8100<-ServerURLHere
2016-12-07 16:20:46.014895 XCTRunner[489:71350] Listening on USB
    t =   127.00s     Find the Application "local.pid.482" 0x1700b7f40
    t =   127.01s         Snapshot accessibility hierarchy for local.pid.482
2016-12-07 16:23:08.003458 XCTRunner[489:71797] Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error -25204 getting snapshot for element <AXUIElement 0x13be2a910> {pid=482}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element <AXUIElement 0x13be2a910> {pid=482}} <unknown> 0 1
2016-12-07 16:23:08.023830 XCTRunner[489:71350] Enqueue Failure: UI Testing Failure - Failed to get snapshot within 15.0s <unknown> 0 1
    t =   143.10s         Find the Application "local.pid.482" 0x1700b7f40 (retry 1)
    t =   143.10s             Snapshot accessibility hierarchy for local.pid.482
2016-12-07 16:23:24.033812 XCTRunner[489:72141] Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204} <unknown> 0 1
    t =   159.12s         Find the Application "local.pid.482" 0x1700b7f40 (retry 2)
    t =   159.12s             Snapshot accessibility hierarchy for local.pid.482
2016-12-07 16:23:40.053187 XCTRunner[489:71993] Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204} <unknown> 0 1
2016-12-07 16:23:40.158743 XCTRunner[489:71350] Enqueue Failure: UI Testing Failure - (null) <unknown> 0 1

**Comment by marekcirkos** [comment]
Could elaborate on queries you are making?

**Comment by tyutyunnykusa** [comment]
I opened view with  this huge Table on my iPhone device and refreshed Inspector in browser.

**Comment by marekcirkos** [comment]
`Error getting main window -25204` usually shows when we query application that is not active anymore. Does it still happen you wait a bit before opening inspector.

**Comment by patotskiy** [comment]
I have same issue on iPhone and iPad: 

`[debug] [WebDriverAgent] Sim: Dec 13 00:50:08 Yauhenis-MacBook-Pro XCTRunner[40797]: Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Dec 13 00:50:24 Yauhenis-MacBook-Pro XCTRunner[40797]: Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Dec 13 00:50:40 Yauhenis-MacBook-Pro XCTRunner[40797]: Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Dec 13 00:50:41 Yauhenis-MacBook-Pro XCTRunner[40797]: Enqueue Failure: UI Testing Failure - (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[debug] [WebDriverAgent] Sim: Dec 13 00:50:57 Yauhenis-MacBook-Pro XCTRunner[40797]: Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Dec 13 00:51:00 Yauhenis-MacBook-Pro XCTRunner[40797]: Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204} <unknown> 0 1
[debug] [WebDriverAgent] Sim: Dec 13 00:51:15 Yauhenis-MacBook-Pro XCTRunner[40797]: Enqueue Failure: UI Testing Failure - Application is not running, unable to get Accessibility data. Did you call -launch? /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
`

**Comment by tyutyunnykusa** [comment]
marekcirkos, yes it happens if I wait some time before launching Inspector, application is active.

**Comment by patotskiy** [comment]
any updates?

**Comment by huanglik** [comment]
I have same issue too, when get snapshot for Table with 200 cells, it takes too long . 
So find elements or using inspector takes so long time to return (almost a few mins ) 
thus it reduces test efficiency so much。
please try to fix this for WDA？

**Comment by mykola-mokhnach** [comment]
I had similar problem in our tests. UI just freezes at some point and it was not possible to tap anything unless WDA is terminated at all. The source of the problems lies in this XCTest bug: http://www.openradar.me/25623858

Replacing all usages of NSMutableAttributedString in the corresponding UI view solved the problem.

**Comment by marekcirkos** [comment]
There not much we can do as TestManager it-self is slow in querying elements.

**Comment by pluie-cloud** [comment]
@mykola-mokhnach  hi i has same  situation，should i change my tested app code?or wda code?
thx
