### ISSUE TITLE
Broken XPath

### ISSUE THREAD

**Issue by marekcirkos** [facebook/WebDriverAgent#403]
After new xpath implementation was merged I noticed that some of our queries are failing.
E.G. `.//XCUIElementTypeSheet//XCUIElementTypeButton[@name="Forgot Password?"]` query nukes WDA down.
@mykola-mokhnach Can you have a look?

**Comment by mykola-mokhnach** [comment]
There might be two potential problems in this xpath:
- remove leading dot character
- replace double quotes with single quotes

Let me know which one helps

**Comment by mykola-mokhnach** [comment]
Also, there should be detailed description of the problem in device logs, which libxml2 itself generates if it does not like a query.

**Comment by marekcirkos** [comment]
It looks like it crashes WDA in a hard way. We should be able to handle this query regardless of double quotes or dot. Easies way would be to add unit/integration test with that particular request.

**Comment by mykola-mokhnach** [comment]
that's unfortunate :(
OK, I'll prepare a test tomorrow

**Comment by mykola-mokhnach** [comment]
This was an [easy one](https://github.com/facebook/WebDriverAgent/pull/404/files). Thanks for the hint 👍
