### ISSUE TITLE
ServerUrl

### ISSUE THREAD

**Issue by VasilijSviridov** [facebook/WebDriverAgent#407]
Is there any possibility to fetch ServerUrl ? 
As example on iOS 9.3 real device there is XCUIT log which says ServerUrl:8100, while on 10.1 real device there is no such message ?

It would be really easy if we could get ServerUrl before starting app session.

**Comment by jessezyl** [comment]
Or you can connect your device over USB cable, map the device url to localhost, here there is a tool 
`iproxy`:https://github.com/libimobiledevice/libusbmuxd

it's easy to use:
`iproxy local_port remote_port device_udid`
`e.g: $ iproxy 8100 8100 abcdefghijklmabcdefg01234567890123456789`

**Comment by VasilijSviridov** [comment]
interesting =)

Thank you @jessezyl , I will try use your suggested method.

Cheers

**Comment by VasilijSviridov** [comment]
Waw working as expected without delays. 

Thank you @jessezyl

**Comment by VasilijSviridov** [comment]
@jessezyl any ideas if for example I would like to proxy 1+n devices ? 

Sincerely

**Comment by marekcirkos** [comment]
@VasilijSviridov  You will definitely find logs on device logs and on xcodebuild output depending on Xcode version. However `iproxy` is the best way to go. 

According many devices you should just run WDA on different ports by passing `USE_PORT` env or `--port` argument

**Comment by VasilijSviridov** [comment]
Sounds good to me,

Cheers

**Comment by VasilijSviridov** [comment]
@marekcirkos could you suggest, I am trying to pass USE_PORT parameter:
 xcodebuild -project WebDriverAgent.xcodeproj  -scheme WebDriverAgentRunner 'USE_PORT=8101'  -destination 'id=xxxxxxxxxxxxxxxxxxx'  test
Build settings from command line:
    USE_PORT = 8101

But on device I still see that ServerUrl started with default port 8100 , any ideas what's wrong ?

**Comment by marekcirkos** [comment]
@VasilijSviridov can you try:

`env USE_PORT=8101 xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=xxxxxxx' test`?

**Comment by marekcirkos** [comment]
Oh wait, that will work with sims. For devices most likely you will need to modify scheme and edit env there.

**Comment by VasilijSviridov** [comment]
got it @marekcirkos 

Thank you for your help

**Comment by VasilijSviridov** [comment]
@marekcirkos  its working, was able to set and running 4 different iOS devices running in parallel, looks awesome!! :)

Thank you one more time!
