### ISSUE TITLE
when install the WebDriverAgent,it failed with "Failed at the web-driver-inspector@1.0.0 build script 'webpack --progress --colors'."

### ISSUE THREAD

**Issue by debbie-qin** [facebook/WebDriverAgent#408]
Here is the log: 
UNKNOWN-10-89-105-X:WebDriverAgent cd XX$ ./Scripts/bootstrap.sh
Fetching dependencies
Building Inspector
Creating bundle directory...
Building inspector.js...

> web-driver-inspector@1.0.0 build /Users/beyondsoft/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
> webpack --progress --colors

sh: webpack: command not found

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! web-driver-inspector@1.0.0 build: `webpack --progress --colors`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the web-driver-inspector@1.0.0 build script 'webpack --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web-driver-inspector package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web-driver-inspector
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web-driver-inspector
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/beyondsoft/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/npm-debug.log
Error occured during 'npm run build', please check npm build log

I find the "Make sure you have the latest version of node.js and npm installed."  and they are the latest version:
UNKNOWN-10-89-105-X:WebDriverAgent cd-XX$ node --version
v7.2.1
UNKNOWN-10-89-105-X:WebDriverAgent cd-XX$ npm -version
3.10.10

**Comment by debbie-qin** [comment]
Besides, I have installed the webpack agian...   then keep the same error.

**Comment by marekcirkos** [comment]
@debbie-qin Can you try fetching WDA independently from this repo and running `./Scripts/bootstrap.sh` ? I know there is some magic appium does with WDA that sometimes breaks it.

**Comment by debbie-qin** [comment]
I have tryed again, but now it failed with another issue.....here is the link:

**Comment by marekcirkos** [comment]
@debbie-qin I assume this one is resolved? Feel free to reopen if that is not true
