### ISSUE TITLE
i found there is a memory leak about peertalk framework

### ISSUE THREAD

**Issue by sixleaves** [facebook/WebDriverAgent#413]
hi, when i use wda and communicating use you provided FBHTTPOverUSBClient, at beginning every thing is ok, but about 3 miniutes.the client crashed about memory leak of FBHTTPOverUSBClient.that is peertalk, i don't know how to solve this.

![2](https://cloud.githubusercontent.com/assets/3601210/21140875/3ad84c40-c175-11e6-9994-6f4b7402b6a9.png)

**Comment by marekcirkos** [comment]
How do you know it is memory leak?
