### ISSUE TITLE
Does FB use WebDriverAgent to test react native UI?

### ISSUE THREAD

**Issue by bootstraponline** [facebook/WebDriverAgent#414]
I'm looking into react native UI testing. I'm wondering what does FB use to write iOS UI tests?

I'm aware of the snapshot tests ([ios-snapshot-test-case](https://github.com/facebook/ios-snapshot-test-case)).

**Comment by marekcirkos** [comment]
You can definitely use WDA to test react native apps, as they use native views anyway. This mean that most label and name locators will work.

**Comment by bootstraponline** [comment]
Right, I'm trying to find out what FB itself uses so I won't have a lot of problems. The best I can tell from the [238+ comment E2E PR](https://github.com/facebook/react-native/pull/9942) is that FB's solution for [E2E testing react-native apps isn't open source.](https://github.com/facebook/react-native/pull/9942#issuecomment-259588213)

I also don't think there's much harmony between the WDA endpoints and existing Android E2E solutions, even though that's probably a goal.

**Comment by marekcirkos** [comment]
@bootstraponline Those are android specific problems. WDA works on iOS devices only and as I mentioned it will work with ReactNative written app.

**Comment by bootstraponline** [comment]
will work with != used by FB.

**Comment by bootstraponline** [comment]
I found a thread from a year ago. It looks like there's an internal only solution for iOS as well.

> https://www.reddit.com/r/IAmA/comments/3wyb3m/we_are_the_team_working_on_react_native_ask_us/cxzwa6s/

**Comment by marekcirkos** [comment]
@bootstraponline you may think that I couldn't possibly comment
