### ISSUE TITLE
WebDriverAgent and libmobiledevice issue

### ISSUE THREAD

**Issue by dcaric** [facebook/WebDriverAgent#417]
Hi I have problem with starting APP on the real device.
Environment:
macOS Sierra 10.12.2
iOS 10.2
Xcode 8.2

[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/dariocaric/Library/Developer/Xcode/DerivedData/iSierra-fcsvktyeauaajeawtcwmodifinjc/Build/Products/Debug-iphoneos/MediaFirst.app'
[Appium]   appium-version: '1.6.3'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '10.2'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.facebook.IntegrationApp'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'Dario\'s iPhad Air2'
[Appium]   udid: '<UDIDNUMBER>'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appium-version.
[BaseDriver] Session created with session id: 1cd40018-2aba-4950-893a-d98a1efb1bb2
[debug] [XCUITest] Xcode version set to '8.2'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: <UDIDNUMBER>
[debug] [XCUITest] Creating iDevice object with udid <UDIDNUMBER>
[XCUITest] Determining device to run tests on: udid: '<UDIDNUMBER>', real device: true
[BaseDriver] Using local app '/Users/dariocaric/Library/Developer/Xcode/DerivedData/iSierra-fcsvktyeauaajeawtcwmodifinjc/Build/Products/Debug-iphoneos/MyAPP.app'
[debug] [XCUITest] Checking whether app '/Users/dariocaric/Library/Developer/Xcode/DerivedData/iSierra-fcsvktyeauaajeawtcwmodifinjc/Build/Products/Debug-iphoneos/MyAPP.app' is actually present
[debug] [XCUITest] App is present
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=a79e9243fd45c7000727b9187346ef9fdeedbeab -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u <UDIDNUMBER>' exited with code 255
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u <UDIDNUMBER>' exited with code 255
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session 500 1798 ms - 262 

As I understand WebDriverAgent is using libmobiledevice library - which is not working because of some new security/restriction settings. I just don't know is it about iOS10 or macOS Sierra but I think it it's about iOS.

Are you aware of this issue ?

Thanks!
Dario

**Comment by marekcirkos** [comment]
@dcaric You should post that question on appium, WDA it self does not use libmobiledevice, but Appium most likely does to manage device.

**Comment by dcaric** [comment]
Ok I did already, thx!

**Comment by Dineshk1** [comment]
I'm also facing the same issue. Did u get the solution for this?

**Comment by marekcirkos** [comment]
This is not related to WDA. We do not use libmobiledevice.
