### ISSUE TITLE
Where can we change response time from WDA to appium server

### ISSUE THREAD

**Issue by Siddh010** [facebook/WebDriverAgent#421]
Response from WDA side taking more time . I got this message  "Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT"

Currently it is taking around "240304 ms " i,e 4 min approx to get response.

[HTTP] <-- POST /wd/hub/session/2a09db5f-84fd-4dda-bade-5217a12394b5/element/8CCFAA0C-D972-468F-88F8-AAC03DDC95C1/value 
240304 ms 
device log message  : -
https://gist.github.com/Siddh010/65f05fa1b0d8bdc7b69109f6f3bb13cd

So I would like to ignore this error and follow with other step. Is there any place where we can set this value to reduce timeout.

As mention in https://github.com/appium/appium/issues/7572 link  :- There should be some delay on WDA side and iproxy fails here because it does not get any response from WDA after the timeout expires

**Comment by Siddh010** [comment]
I am facing similar issue : -
http://stackoverflow.com/questions/23925284/how-to-modify-the-nodejs-request-default-timeout-time

https://nodejs.org/api/http.html#http_server_timeout : - server.timeout Default = 120000 (2 minutes)

[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"BCAB503D-D9E7-4A5D-8443-FE56CB28E626","type":"XCUIElementTypePickerWheel","label":null}
[HTTP] <-- POST /wd/hub/session/2a09db5f-84fd-4dda-bade-5217a12394b5/element 200 122634 ms - 171

https://discuss.newrelic.com/t/how-to-ignore-esockettimedout-socket-hang-up-errors/10697

Thanks
Siddartha

**Comment by Siddh010** [comment]
Hi please let me know where can we change response time from WDA to appium server. Right now it is taking 240000 mill second. 
 Thanks
 Siddharth

**Comment by marekcirkos** [comment]
@Siddh010 You should poke that question to appium repo. WDA is only used by Appium.
