### ISSUE TITLE
Identifier support in predicate string

### ISSUE THREAD

**Issue by wfanforever** [facebook/WebDriverAgent#422]
Latest wda added the predicate verification, how to use the predicate string to check that identifier not contains a certain value? 

Previous we can use ios predicate string and pass the value: `not (identifier contains 'xxx' or identifier contains 'xxxx') `?

\

**Comment by benzhou29** [comment]
I am seeing same issue it seems like the use of "identifier" does not work anymore. Even something simple like 'identifier == "xxx"' does not work anymore. I hope there is an alternative.

**Comment by mykola-mokhnach** [comment]
try 

```
NOT (wdName CONTAINS 'blabla')
```

**Comment by marekcirkos** [comment]
@mykola-mokhnach Shouldn't we translate `name` to `wdName` ?

**Comment by mykola-mokhnach** [comment]
@marekcirkos Current code is designed to support both: 'wdName' and 'name'. The 'wd' pefix will be added automatically in such case.

**Comment by benzhou29** [comment]
I don't think identifier and name are equivalent, at least from what I tested. I used to be able to query for elements based on accessibility identifier with "identifier".

**Comment by marekcirkos** [comment]
@mykola-mokhnach This should be resolved right?

**Comment by mykola-mokhnach** [comment]
Yep, just close it.
