### ISSUE TITLE
xcodebuild failed in real devices: dyld: Library not loaded: @rpath/XCTest.framework/XCTest

### ISSUE THREAD

**Issue by jibingli** [facebook/WebDriverAgent#424]
Help!
failed to run WDA in real devices with follow command, but it is OK when destination is simulator.

command:
xcodebuild build test -project ./WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=ae7a94577f4832e37756a7b8080e655e8ebe2469' -configuration Debug

log:
=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/1_/br65ycnn7yb5gwfpsjb_g9680000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/6956432208ab720818d0e046a9622e29/ae7a94577f4832e37756a7b8080e655e8ebe2469/ManifestCache.plist
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/BF2AC79C-12B8-44A2-A92C-8B0494469BF9/WebDriverAgentRunner-Runner.app/XCTRunner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/BF2AC79C-12B8-44A2-A92C-8B0494469BF9/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/BF2AC79C-12B8-44A2-A92C-8B0494469BF9/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/BF2AC79C-12B8-44A2-A92C-8B0494469BF9/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/BF2AC79C-12B8-44A2-A92C-8B0494469BF9/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
2016-12-22 18:11:53.431 xcodebuild[53745:369678] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

**Comment by jibingli** [comment]
use xcode 8.2.1, ios 10.2

**Comment by nhanvpt102** [comment]
- run the command './Scripts/bootstrap.sh' and try again.

**Comment by jibingli** [comment]
@nhanvpt102 thank you for your suggestion, error happened again.
log:
Fetching dependencies
Building Inspector
Creating bundle directory...
Fetching Inspector dependencies...
npm WARN react-treeview@0.4.6 requires a peer of react@>=0.14.0 but none was installed.
npm WARN web-driver-inspector@1.0.0 No repository field.
Building Inspector...

Hash: 464241247f16d853b410  
Version: webpack 1.14.0
Time: 2378ms
       Asset    Size  Chunks             Chunk Names
inspector.js  712 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 182 hidden modules
Done

**Comment by miaomiao413** [comment]
i have the same problem

**Comment by AllocAndInit** [comment]
what happend ?  I come across the same problem just today ,is there any solulation ?

**Comment by AllocAndInit** [comment]
Does there anyone who knows how to solve this problem ?

**Comment by debbie-qin** [comment]
Same problem- -

**Comment by AllocAndInit** [comment]
@jibingli  @miaomiao413  http://www.jianshu.com/p/b6b2fc31eb2a 这个链接解决了我的问题，不知道对你们有没有用，你们可以试试看

**Comment by miaomiao413** [comment]
Xcode, Product->Clean,solves my problem

**Comment by marekcirkos** [comment]
Is it still an issue? @jibingli You second log looks correct.

**Comment by jibingli** [comment]
try AllocAndInit's solution, fixed now!
