### ISSUE TITLE
WebDriverAgentLib Integration

### ISSUE THREAD

**Issue by testobjectnishant** [facebook/WebDriverAgent#425]
I am trying to integrate WebDriverAgentLib in the fresh wrapper application project but getting following error while running the application on phone:

`dyld: Library not loaded: @rpath/Peertalk.framework/Peertalk
  Referenced from: /private/var/containers/Bundle/Application/5E6862A7-B629-454D-A6D9-685CDC8A31AC/TestObjectExtension.app/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
 /private/var/containers/Bundle/Application/5E6862A7-B629-454D-A6D9-685CDC8A31AC/TestObjectExtension.app/Frameworks/WebDriverAgentLib.framework/Frameworks/Peertalk.framework/Peertalk: required code signature missing for '/private/var/containers/Bundle/Application/5E6862A7-B629-454D-A6D9-685CDC8A31AC/TestObjectExtension.app/Frameworks/WebDriverAgentLib.framework/Frameworks/Peertalk.framework/Peertalk'`

I have also tried adding WebDriverProject directly in my project and added WebDriverAgent library as Target Dependency, Embedded Binaries and Linked Framework and Libraries but it did not work.

**Comment by mykola-mokhnach** [comment]
First you need to download third-party dependencies using Carthage.
Just execute 

```
./Scripts/bootstrap.sh -d
```

**Comment by testobjectnishant** [comment]
I have already did it. It works fine when I run it directly but it gives the above error while I integrate it as Library project in another project.

**Comment by marekcirkos** [comment]
@testobjectnishant you need to add WDA's dependencies to your project as well, meaning `.frameworks` from `Carthage/Build/iOS`. Make sure to run `./Scripts/bootstrap.sh` beforehand.
