### ISSUE TITLE
UITestingUITests testRunner stop at Set up on ios 10.2

### ISSUE THREAD

**Issue by wwjackli** [facebook/WebDriverAgent#429]
Help
when testRunner stop at step of set up on ios 10.2(iphone7=), it work on ios 9.1 (iphone6+)
thanks

INFOMATION
Device:iphone 7+ 
Model:MNQP2KH/A
OS:10.2

LOG
2016-12-26 23:58:01.676 xcodebuild[2151:36590]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/jackli/Library/Developer/Xcode/DerivedData/WebDriverAgent-euybcxucqlktejefdqfqdkijmwjt/Logs/Test/4C025021-7A61-4924-8F66-038B0B89779F/Session-ATX-2016-12-26_235801-m8iDUT.log
2016-12-26 23:58:01.677 xcodebuild[2151:36580] [MT] IDETestOperationsObserverDebug: (0A8EAEC3-E591-4021-83D9-965C1CC53A78) Beginning test session ATX-0A8EAEC3-E591-4021-83D9-965C1CC53A78 at 2016-12-26 23:58:01.670 with Xcode 8C1002 on target <DVTiOSDevice: 0x7fd65df49080> {
		deviceSerialNumber:         C39SM4AKHG06
		identifier:                 19162944a7cd109dc7b463ced448ee205a64593c
		deviceClass:                iPhone
		deviceName:                 iPhone7+
		deviceIdentifier:           19162944a7cd109dc7b463ced448ee205a64593c
		productVersion:             10.2
		buildVersion:               14C92
		deviceSoftwareVersion:      10.2 (14C92)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        27573993472
		deviceAvailableCapacity:    20664836096
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fd65d9958b0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.2 (14C92))
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/z3/dv8jp6ks63540gr1b6styz9m0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/23f2f57059bbbf68fec81c05d5e23ce0/19162944a7cd109dc7b463ced448ee205a64593c/ATX-Runner.app
state->new_bundle: /Users/jackli/Library/Developer/Xcode/DerivedData/WebDriverAgent-euybcxucqlktejefdqfqdkijmwjt/Build/Products/Debug-iphoneos/ATX-Runner.app
state->dst_bundle: /var/folders/z3/dv8jp6ks63540gr1b6styz9m0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/ATX-Runner.app.NLNDiM/ATX-Runner.app_sparse.ipa/Payload//ATX-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/z3/dv8jp6ks63540gr1b6styz9m0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/ATX-Runner.app.NLNDiM/ATX-Runner.app_sparse.ipa
__MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/z3/dv8jp6ks63540gr1b6styz9m0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/ATX-Runner.app.NLNDiM/ATX-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/z3/dv8jp6ks63540gr1b6styz9m0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/ATX-Runner.app.NLNDiM/ATX-Runner.app_sparse.ipa/ManifestCache.plist
Test Suite 'All tests' started at 2016-12-26 23:58:09.348
Test Suite 'ATX.xctest' started at 2016-12-26 23:58:09.349
Test Suite 'UITestingUITests' started at 2016-12-26 23:58:09.349
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2016-12-26 23:58:09.352
    t =     0.00s     Set Up

**Comment by huanglik** [comment]
me too.   using xcodebuild to launch wda it will stuck at set up.
               using xcode to launch wda it is ok
so i can not  using appium or any other client for wda now

**Comment by jpsalada** [comment]
same problem here.

**Comment by marekcirkos** [comment]
This is TestManager issue in Xcode. I am not joking can you try restarting your computer?

**Comment by lilfry14** [comment]
I get the same problem. A restart did not help. xcode Version 8.2, iOS 10.1.1

**Comment by 304883563** [comment]
I get the same problem. xcode Version 8.2.1, iOS 10.2 appium 1.6.3

**Comment by baozhida** [comment]
me too. how to solve the problem? Xcode 8.2.1  ip7 10.2

**Comment by jpsalada** [comment]
So the problem is not the WDA gets stuck. It just do not output any logs on the xcodebuild process. This is a bit a problem because we need the ServerURL log to get he device ip. This log shows on the device logs, but it is way straightforward to get it from xcodebuild process output.

**Comment by 12288505** [comment]
Did you solve the issue?

**Comment by thanksdanny** [comment]
i got same problem,too...

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/wiki/Common-Issues#booting-wda-on-device-stops-after-set-up-and-does-not-actually-start-wda

**Comment by thanksdanny** [comment]
but i restart my mac and iPhone, it still stop at "set up" ，is some step wrong by me ?😂

**Comment by laiyuncong8404** [comment]
@thanksdanny me too. Have u solve this problem now?

**Comment by marekcirkos** [comment]
Try rebooting host. Most of the time works for me

**Comment by laiyuncong8404** [comment]
@marekcirkos I have reboot my Mac and iPhone, but it doesn't for me, so sad.

**Comment by marekcirkos** [comment]
@laiyuncong8404 Yeah this is sad, Unfortunately I can't help you here :/

**Comment by stephenws** [comment]
Same Issue for me.
