### ISSUE TITLE
iOS App crashes after calling window().getSize() - Appium 1.6.3 - XCUITest

### ISSUE THREAD

**Issue by limitcracker** [facebook/WebDriverAgent#432]
**The problem**

I go to a screen that is our Sing Out screen. When I go by hand and perform actions app doesn't crash, but when I call window().getSize() or any other method via appium on that screen the app crashes.

**Environment**

Desktop OS/version used: MacOS
Mobile platform/version under test: iOS 10.2 on 
Real device or emulator/simulator: real(iPhone 6 Plus) and emulator
Test platform: Appium 1.6.3

**System logs**
[iphone-6-plus-emulator-logs.txt](https://github.com/facebook/WebDriverAgent/files/677494/iphone-6-plus-emulator-logs.txt)

**Comment by marekcirkos** [comment]
It crashes during collection of accessibility information. That means that it will also crash when application is launched in accessibility mode. It is either Apples bug or you are using same selector that apple uses in injected categories. I had similar issues and in my case it was proper named 'viewDelegate'. Renaming it fixed the issue.

**Comment by marekcirkos** [comment]
@limitcracker any luck?
