### ISSUE TITLE
Multiple instances of WebDriverAgent on a single device/simulator

### ISSUE THREAD

**Issue by tylerrrrrr** [facebook/WebDriverAgent#433]
Hello

My question is related to https://github.com/facebook/WebDriverAgent/issues/216 but with a test case in mind. 

My goal is to automate app A, which then launches app B to then verify/interact with it, then finally return to resuming the previous session for app A. WDA currently has one total instance running, so when trying to resume back to app A, that session no longer exists since session A was overridden by session B.

I am wondering if there is anyway to do this currently with WDA or if this would be a worthy future enhancement. Since many applications can launch other applications, this could be a desired test case for other organizations. Thanks.

**Comment by marekcirkos** [comment]
The fact that WDA holds one session shouldn't be a problem for you. You can 
1) Start sessions #1 with app A and do some stuff,
2) Start session #2 with app B,
3) Start another session #3 with app A and keep doing it.

Other approach could be simply navigating to springboard and re-activating first app. WDA will still work as it will use active application if session's one is inactive.

**Comment by tylerrrrrr** [comment]
Interesting. Our suite uses Appium(1.6.3), and the driver for App A & B are stored. When going back to app A, I switch drivers no problem but WDA current session is pointing to app B. Is there a way to start a new WDA session for app A with Appium(or programmatically) during a test?

**Comment by marekcirkos** [comment]
You don't need to. Even if you start session with some app A. You can still operate other applications if you navigate to them your self.

**Comment by AliNL** [comment]
Hi @marekcirkos , if I start a session with app A, then app A will restart right? What if I want to start a new session and continue working on the current app?

**Comment by marekcirkos** [comment]
If you restart session with same app it will relaunch it yes. If that is a problem, you can also navigate to it without starting session

**Comment by marekcirkos** [comment]
@tylerrrrrr Closing, if there is something you want still to discuss, feel free tor reopen
