### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by TeresaP** [facebook/WebDriverAgent#436]
If someone wants to use the PrivateHeaders/XCTest files in a (non-shipping) project, does the license from https://github.com/facebook/WebDriverAgent/blob/master/LICENSE apply and should it be copied to the folder containing the .h files?

**Comment by marekcirkos** [comment]
You can generate them your self with `class-dump`.

**Comment by TeresaP** [comment]
Thanks @marekcirkos I will do that.
