### ISSUE TITLE
tap is not working 

### ISSUE THREAD

**Issue by nairouz12** [facebook/WebDriverAgent#438]
tap is not working for me with appium 1.6.3 with appium_console: v2.0.1 and appium_lib: v9.1.2 in this case:
I have a XCUIElementTypeAlert displayed on my screen
these are the coordinates of my XCUIElementTypeAlert: x=52, y=263, h=141, w=271
and this is the size of my screen where XCUIElementTypeAlert is displayed: height = 667, width = 375
I want to tap outside XCUIElementTypeAlert, it does not give any error but it tap the first button of the element XCUIElementTypeAlert instead of tapping outside:
`> Appium::TouchAction.new.tap(:x => 0, :y => window_size.width*0.5).perform <Appium::TouchAction:0x007fe958d77fa0 @actions=[{:action=>:tap, :options=>{:x=>0, :y=>187.5, :count=>1}}]>`

The action seems depends on WebDriverAgent, because between ruby_lib and appium-xcuitest-driver looks works fine.
`( from <Appium::TouchAction:0x007fe958d77fa0 @actions=[{:action=>:tap, :options=>{:x=>0, :y=>187.5, :count=>1}}]> )`

I don't know how to send commands directly to WDA. Can anyone check what could be the issue?

**Comment by marekcirkos** [comment]
Do you tap it on portrait or landscape orientation?
Otherwise without knowing what WDA endpoint with what attributes was executed, I can't really help you here.

**Comment by nairouz12** [comment]
curl -X POST $JSON_HEADER \
-d "{\"x\":\"0\",\"y\":\"187.5\"}" \
$DEVICE_URL/session/$SESSION_ID/tap/0

**Comment by AlexJinsin** [comment]
i want to slide the csreen. left slide or right slide . which comman should i used?

**Comment by marekcirkos** [comment]
@nairouz12 What screen orientation is it? @AlexJinsin probably druganddrop

**Comment by nairouz12** [comment]
@marekcirkos 
Portrait

**Comment by codeskyblue** [comment]
similar to <https://github.com/facebook/WebDriverAgent/issues/362>

**Comment by marekcirkos** [comment]
@codeskyblue This is portrait so most likely not related.
@nairouz12 What Xcode and iOS version are you using? If you tap awn higher coordinates does it still tap alert button?

**Comment by nairouz12** [comment]
@marekcirkos 
I'm using:  xcode: 8.2.1 and iOS version: 10.2
Whatever coordinates I use, it always taps the first button of the alert popup.

**Comment by AlexJinsin** [comment]
@marekcirkos  I do not get the point.

**Comment by nairouz12** [comment]
@marekcirkos 
this ths code that i'm executing:
`Appium::TouchAction.new.tap(:x => 10, :y => 10).perform`
and these are the logs I'm getting
`[HTTP] --> POST /wd/hub/session/5f90ed46-d917-44b5-a6a5-f23c3f6b2009/touch/perform {"actions":[{"action":"tap","options":{"x":10,"y":10,"count":1}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":10,"y":10,"count":1}}],"5f90ed46-d917-44b5-a6a5-f23c3f6b2009"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: tap
[debug] [JSONWP Proxy] Proxying [POST /tap/0] to [POST http://localhost:8100/session/B9B456C1-7674-4F86-BB8B-E02324C52B3B/tap/0] with body: {"x":10,"y":10}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"B9B456C1-7674-4F86-BB8B-E02324C52B3B","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/5f90ed46-d917-44b5-a6a5-f23c3f6b2009/touch/perform 200 2383 ms - 74`
So instead of tapping the correct coordinates, it taps the first button of the alert popup

**Comment by AlexJinsin** [comment]
@nairouz12 
`curl -X POST $JSON_HEADER -d "{"x":"0","y":"187.5"}" $DEVICE_URL/session/$SESSION_ID/tap/0`
Can this command click screen?

**Comment by nairouz12** [comment]
@AlexJinsin 
I don't know how to send commands directly to WDA

**Comment by marekcirkos** [comment]
@nairouz12 This is interesting. Maybe this is how iOS handles outside taps. I'll play with it when I have some time

**Comment by mykola-mokhnach** [comment]
@nairouz12 Can you please check comments to [this PR](https://github.com/facebook/WebDriverAgent/pull/411)? Probably, you issue will be fixed after you merge it with the local WDA source.

**Comment by nairouz12** [comment]
@mykola-mokhnach the issue happened on portrait orientation and not on landscape

**Comment by nairouz12** [comment]
@marekcirkos  any update about this issue?

**Comment by marekcirkos** [comment]
@nairouz12 Sorry I didn't have much time to investigate it.
