### ISSUE TITLE
can i use personal team to run wda on real device?

### ISSUE THREAD

**Issue by channingbreeze** [facebook/WebDriverAgent#439]
Hi, i am new to ios development and i want to know can i use personal team to run wda on real device? if can ,how?

i always got the error: Failed to create provisioning profile.
The app ID "com.facebook.WebDriverAgentRunner" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.
No profiles for 'com.facebook.WebDriverAgentRunner' were found
Xcode couldn't find a provisioning profile matching 'com.facebook.WebDriverAgentRunner'.

and i changed Identity in WebDriverAgentLib target, it's the same. i do not know how to do

thank you very much

**Comment by marekcirkos** [comment]
Yes, you can. All you need to do is to create wildcard prov profile and select your team in all WDA targets

**Comment by VasilijSviridov** [comment]
@marekcirkos  can I use Dev Wildcard Profile for building WDA ? 
Cheers

**Comment by marekcirkos** [comment]
@VasilijSviridov I promis I will not punish you for it ;)
