### ISSUE TITLE
[IOS] how to make Keyboard disappear or put away 

### ISSUE THREAD

**Issue by lyt19871224** [facebook/WebDriverAgent#444]
[IOS] 
I am trying test  suggest feature of a textfield . When I  type text to  a  textbox, the Keyboard appears.    But when finish typing,the Keyboard still exists there  and  cover a part of content which I want to test . So  my question is how can I make the Keyboard  disappear  after finishing typing and staying this page.

**Comment by marekcirkos** [comment]
Application is responsible for dismissing keyboard. So you can as WDA to perform action that triggers keyboard dismiss.

**Comment by lyt19871224** [comment]
Hi,I try modify the code like below:
**add one method to FBElementCommands.m**
`[[FBRoute POST:@"/wda/element/:uuid/dismisskeyboard"] respondWithTarget:self action:@selector(handleDismissKeyboard:)]
`
`+ (id<FBResponsePayload>)handleDismissKeyboard:(FBRouteRequest *)request
{
    [[FBApplication fb_activeApplication] dismissKeyboard];
    //some other code
    return FBResponseWithOK();
}
`

**But  I got log like below , fail to dismiss the keyboard:**

 t =  1151.26s     Find the Keyboard
    t =  1151.26s         Snapshot accessibility hierarchy for local.pid.4503
    t =  1155.86s         Find: Descendants matching type Keyboard
    t =  1155.88s         Find: Element at index 0
    t =  1158.94s     Find the Application "local.pid.4503" 0x174aa3e40
    t =  1158.94s         Snapshot accessibility hierarchy for local.pid.4503
    t =  1163.74s     Use cached accessibility hierarchy for local.pid.4503
    t =  1164.00s     Find: Descendants matching type Keyboard
    t =  1164.03s     Tap "Hide keyboard" Button
    t =  1164.03s         Wait for app to idle
    t =  1164.12s         Find the "Hide keyboard" Button
    t =  1164.12s             Snapshot accessibility hierarchy for local.pid.4503
    t =  1169.13s             Find: Descendants matching type Button
    t =  1169.28s             Find: Elements matching predicate '"Hide keyboard" IN identifiers'
    t =  1169.32s             Wait for app to idle
    t =  1170.48s             Find the "Hide keyboard" Button (retry 1)
    t =  1170.48s                 Snapshot accessibility hierarchy for local.pid.4503
    t =  1175.58s                 Find: Descendants matching type Button
    t =  1175.73s                 Find: Elements matching predicate '"Hide keyboard" IN identifiers'
    t =  1175.77s                 Wait for app to idle
    t =  1176.98s             Find the "Hide keyboard" Button (retry 2)
    t =  1176.99s                 Snapshot accessibility hierarchy for local.pid.4503
    t =  1182.34s                 Find: Descendants matching type Button
    t =  1182.51s                 Find: Elements matching predicate '"Hide keyboard" IN identifiers'
    t =  1182.55s                 Wait for app to idle
2017-01-23 12:04:56.576923 XCTRunner[4466:2707494] Enqueue Failure: UI Testing Failure - No matches found for "Hide keyboard" Button
Query input was {(
    Button 0x1707726c0: traits: 8589934593, {{0.0, 20.0}, {44.0, 44.0}},
    Button 0x17076df80: traits: 8589934593, {{331.0, 20.0}, {44.0, 44.0}},
    Button 0x170369b40: traits: 8589934593, {{325.0, 80.0}, {40.0, 40.0}}, label: '',
    Button 0x170777d00: traits: 8589934593, {{5.5, 161.5}, {121.3, 96.5}},
    Button 0x170d64500: traits: 8589934593, {{5.5, 258.0}, {121.3, 96.5}},
    Button 0x170572780: traits: 8589934593, {{5.5, 263.5}, {121.3, 96.5}},
    Button 0x170d639c0: traits: 8589934593, {{5.5, 360.0}, {121.3, 96.5}},
    Button 0x170b67380: traits: 8589934593, {{5.5, 365.5}, {121.3, 96.5}},
    Button 0x170d63540: traits: 8589934593, {{5.5, 462.0}, {121.3, 96.5}},
    Button 0x17076d2c0: traits: 8589934593, {{5.5, 467.5}, {121.3, 48.0}},
    Button 0x17077bfc0: traits: 8589934593, {{5.5, 515.5}, {121.3, 48.0}},
    Button 0x170578e40: traits: 8589934593, {{127.3, 161.5}, {121.3, 48.0}},
    Button 0x17037d400: t  0 1
2017-01-23 12:04:56.863290 XCTRunner[4466:2707494] Enqueue Failure: UI Testing Failure - Application for "Hide keyboard" Button is not frontmost. <unknown> 0 1
    t =  1183.03s         Synthesize event
    t =  1183.61s         Wait for app to idle
    t =  1183.69s     Snapshot accessibility hierarchy for local.pid.4503
    t =  1189.28s     Find: Descendants matching type Keyboard
    t =  1190.31s     Snapshot accessibility hierarchy for local.pid.4503
    t =  1196.02s     Find: Descendants matching type Keyboard
    t =  1197.05s     Snapshot accessibility hierarchy for local.pid.4503
    t =  1203.03s     Find: Descendants matching type Keyboard
    t =  1204.05s     Snapshot accessibility hierarchy for local.pid.4503
    t =  1210.23s     Find: Descendants matching type Keyboard
    t =  1210.25s     Use cached accessibility hierarchy for local.pid.4503
    t =  1210.56s     Find: Descendants matching type Keyboard
2017-01-23 12:05:24.422188 XCTRunner[4466:2707494] Enqueue Failure: UI Testing Failure - 'Application "local.pid.4503" 0x174aa3e40' Keyboard still present. <unknown> 0 1
    t =  1291.32s     Terminate <XCUIApplicationProcess: 0x1702a0780  (4514)>

**Comment by marekcirkos** [comment]
I would guess this works only for iPads.
