### ISSUE TITLE
WebDriverAgent keeps on black screen after running of several tests

### ISSUE THREAD

**Issue by MaisGurbanov** [facebook/WebDriverAgent#446]
After running 5-10 tests on real device (iPhone 5, iOS 10.2), WebDriverAgent keeps on black screen and does not want to minimize itself in background: there is black screen with battery icon. So only solution which I can make for now, just restart device and start tests again.

Is there any other solution?

Thanks in advance.

**Comment by marekcirkos** [comment]
Does the screen at one point turn black. Does anything happen when you press home button? Sounds like serious iOS issue.

**Comment by MaisGurbanov** [comment]
After pressing  home button WebDriverAgent minimizes but tests are not continuing. Even when I try to close WebDriverAgent (by clicking home button twice and swipe window up), appium tries to run WebDriverAgent and the mentioned process (WebDriverAgent opens again, keeps on black screen with battery icon) continues until I will restart device.

**Comment by marekcirkos** [comment]
Ok, so WDA stops working on device after multiple tests, but device is still ok. It happened to me few times as well. This is known issue with XCTest. If you try to run any XCUITest at that point it will not work.

**Comment by MaisGurbanov** [comment]
Is there any related issue with existed one to track it or this problem will stay without any solution?

**Comment by marekcirkos** [comment]
You should file bug report to Apple.

**Comment by pragpatel** [comment]
hi , I am having the exact same problem as @MaisGurbanov , is there any solution to it yet ?

**Comment by LeicaAPiQ** [comment]
Has anybody reported this issue to apple support team ??

**Comment by marekcirkos** [comment]
You should import it independently. Stronger signal to Apple ;)
