### ISSUE TITLE
tap and dragfromtoforduration cost too much time

### ISSUE THREAD

**Issue by CodeToSurvive1** [facebook/WebDriverAgent#448]
when i try to do the tap or dragfromtoforduration action,it often costs too much time, usually 3-4 seconds .And i feel like that the time the screen costs relys on the complex of the screen,for example 

```

http://127.0.0.1:8100/session/2BE1BFAE-C7C7-4FCF-AC06-9D46E61AB687/tap/null

with data

{"x":300,"y":300}

it costs 2.5s 


http://127.0.0.1:8100/session/22279C3A-ECEF-4A6F-846D-A45E540CA505/uiaTarget/0/dragfromtoforduration

with data 

{"fromX":100,"fromY":100,"toX":100,"toY":400,"duration":0.5}

it costs 3.5s

```

And I also debug the webdriveragent ,it looks like the real code that handles actions costs time,like:

```
handleTap:

  [tapCoordinate tap];

handleDrag:
  [startCoordinate pressForDuration:duration thenDragToCoordinate:endCoordinate];

```

I don't know why and is there any solution to solve this?

thanks in advance.

**Comment by CodeToSurvive1** [comment]
Why nobody answered it?

**Comment by codeskyblue** [comment]
for this is weekend

**Comment by marekcirkos** [comment]
@CodeToSurvive1 Do you run it on device or sim? WDA does some additional stuff before taping. Eg. We make sure element is not being animated. Also using Xcode to boot WDA is will significantly slow down all operations due to logging and debugger.

**Comment by CodeToSurvive1** [comment]
i run webdriveragent on real device,i have tried iphone 6,6plus and 6s ,all of these cost too much time.And when i tried to debug the code,the code before and after tap or  dragfromtoforduration run quickly,and cost little time,only the step tap or  dragfromtoforduration cost time. And i also tried to start the webdriveragent on the phone not using xcode and used iproxy through usb,it also cost too much time.

**Comment by marekcirkos** [comment]
There is not much we can do then. All gestures are executed by TestManager which is completely separate process.
