### ISSUE TITLE
keyboard

### ISSUE THREAD

**Issue by VasilijSviridov** [facebook/WebDriverAgent#449]
Is it possible to send keys to keyboard without accessing element ? 

On appium there is a function driver -> getKeyboard -> sendKeys, is there something similar on WDA ?

**Comment by codeskyblue** [comment]
yes, it is possible.

**Comment by codeskyblue** [comment]
But I'm not familar with appium

**Comment by VasilijSviridov** [comment]
@codeskyblue  could you send me POST/GET which you are using to type keyboard without accessing element ?

**Comment by codeskyblue** [comment]
hard to type with phone, you chould search a repo named facebook-wda where you can find answer

**Comment by VasilijSviridov** [comment]
at least type the name of function =) that would really help :)

**Comment by VasilijSviridov** [comment]
@marekcirkos could you help with this one ? Please

**Comment by codeskyblue** [comment]
```
POST $DEVICE_URL/session/$sessionId/keys 
data={'value': value}
```

**Comment by VasilijSviridov** [comment]
thank you very much @codeskyblue !!!!!

Cheers all and Happy Friday!

**Comment by VasilijSviridov** [comment]
After update don't think that keys is available anymore, am using latest git version :/ 

Any help ?
