### ISSUE TITLE
Unable to successfully run WebDriverAgentRunner in Xcode

### ISSUE THREAD

**Issue by TheChell** [facebook/WebDriverAgent#450]
*Problem*
I am unable to successfully run WebDriverAgentRunner in Xcode. I have included values for both DEVELOPMENT_TEAM and CODE_SIGN_IDENTITY in a ProjectSettings.xcconfig file, but for some reason the absolute path of WebDriverRunnerAgent specifically, does not match the location of that file.

*Environment*
Xcode version: 8.2
Appium version: 1.6.3

![screen shot 2017-01-12 at 2 19 25 pm](https://cloud.githubusercontent.com/assets/8346663/21904650/6f9d1d92-d8d2-11e6-9783-0dcceca4c8b7.png)

I am 99% positive this is user error, but I cannot seem to figure out why **WebDriverAgentRunner** does not build. **WebDriverAgentLib** builds successfully, yet not **WebDriverAgentRunner**.  Any help would be greatly appreciated.

**Comment by marekcirkos** [comment]
I am pretty sure you still have to select team for both WebDriverAgentLib and WebDriverAgentRunner in order to make it run on devices. Please confirm
