### ISSUE TITLE
When run bootstrap.sh, got an issue: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by 12288505** [facebook/WebDriverAgent#451]
![qq20170113-173932](https://cloud.githubusercontent.com/assets/14194587/21925197/5597058a-d9b7-11e6-8d0f-1bea45c5272e.png)
Fetching dependencies
Building Inspector
Creating bundle directory...
Fetching Inspector dependencies...
npm WARN react-treeview@0.4.6 requires a peer of react@>=0.14.0 but none was installed.
npm WARN web-driver-inspector@1.0.0 No repository field.
Building Inspector...

> web-driver-inspector@1.0.0 build /usr/local/lib/node_modules/appium/node_modules/.2.5.3@appium-xcuitest-driver/WebDriverAgent/Inspector
> webpack --progress --colors

Hash: 9ed7d0b85cc08341fd0f  
Version: webpack 1.14.0
Time: 123ms
   [0] multi main 28 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in ./js/app.js
Module parse failed: /usr/local/lib/node_modules/appium/node_modules/.2.5.3@appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js Unexpected token (59:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (59:4)
Anyone can fix it?

**Comment by marekcirkos** [comment]
What version of node and npm do you use?

**Comment by 12288505** [comment]
node version 6.9.4
npm 3.10.10

**Comment by 12288505** [comment]
I placed the WebDriverAgent project to other folder, such as /infor/tool/WebDriverAgent, It works OK, Just got issue in the appuim-xcuitest-driver forlder, Why?

**Comment by marekcirkos** [comment]
@12288505 I assume this is due to way appium packages WDA. You should raise an issue with Appium.
