### ISSUE TITLE
Webview

### ISSUE THREAD

**Issue by VasilijSviridov** [facebook/WebDriverAgent#452]
Is it possible to send javascript to hybrid apps  webview ?

**Comment by marekcirkos** [comment]
No, only way you can interact with app is via UI.

**Comment by jlipps** [comment]
@VasilijSviridov if you want webview support, try using appium (https://github.com/appium/appium) which uses WDA for native and allows you to seamlessly switch into a hybrid webview for automation as well.

**Comment by VasilijSviridov** [comment]
@jlipps thanks, could you suggest where to check how to execute js with ios-webkit-debug-proxy help?

Cheers

**Comment by jlipps** [comment]
@VasilijSviridov with appium you can use selenium's `executeScript` command. Reading the Appium docs is probably a good place to start.

**Comment by VasilijSviridov** [comment]
Cheers @jlipps

**Comment by VasilijSviridov** [comment]
@jlipps instead of using selenium executeScript, you can just connect to WS and send json array to ios-webkit-debug-proxy, which I find much more simple and easier, might be helpful for you as well.

Cheers

**Comment by jlipps** [comment]
@VasilijSviridov that is indeed how we implement executeScript under the hood!
