### ISSUE TITLE
keyboard

### ISSUE THREAD

**Issue by VasilijSviridov** [facebook/WebDriverAgent#453]
After running test for about 2 hours, noticed that sending keys to inputs doesn't properly works, as example at 85min 45 sec, "text" string with POST command "element/value" (also tried /keys) was posted, on UI only "t" was visible.

Any ideas why ?

**Comment by VasilijSviridov** [comment]
How often do I have to restart WDA ?

**Comment by marekcirkos** [comment]
@VasilijSviridov This is know XCTest issue, sometimes it fails to type strings regardless of how long it is running. Good news is that WDA can detect that and returns an error in that case, so that you can try to handle it on client side.

**Comment by mykola-mokhnach** [comment]
People also say, that sometimes disabling the "Connect Hardware Keyboard" option helps to workaround this problem in Simulator.

**Comment by VasilijSviridov** [comment]
Thank you, will try to play with error from WDA if that happens again.

Cheers

**Comment by VasilijSviridov** [comment]
yes I am getting error you mentioned: 
Error Domain=XCTestManagerErrorDomain Code=14 \"Timed out waiting for key event to complete\" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete

**Comment by VasilijSviridov** [comment]
It seems that best idea is to restart WDA after a test.

Cheers

**Comment by marekcirkos** [comment]
Also if WDA is inactive for a while after test it might a good idea to keep poking it via /wda/healthcheck endpoint.

**Comment by codeskyblue** [comment]
for a while means how long?

**Comment by marekcirkos** [comment]
It might be a good idea to poke WDA every 20s-60s, whatever works best for you.

**Comment by codeskyblue** [comment]
@marekcirkos  After call `GET /wda/healthcheck` It went to Home Screen.

I'm using this version

```
commit 2eefc210ab3a775cfd1eff1b47e1a81484b64b50
Date:   Fri Jan 13 08:51:00 2017 -0800
```

**Comment by marekcirkos** [comment]
@codeskyblue This is expected. WDA tries to run some commands on XCTest to make sure connections are still there. You suppose to use this method between tests, so that it will not influence test themselves

**Comment by codeskyblue** [comment]
thanks a lot

**Comment by ptsiakos77** [comment]
@marekcirkos 
I run the tests in real devices there fore I cannot apply the fix with the keyboard

The thinks is that when the test hung on setValue it hangs for about 4 minutes
Is there way to reduce this timeout? (via a desired capability maybe?)

**Comment by ohadschn** [comment]
For anyone encountering this using `wd` (node.js client for webdriver), here's a convenient client-side retry method:

```js
var setTextWithRetries = function(text, element, attempts) {

    if (typeof element === 'undefined') { element = this; }
    if (typeof attempts === 'undefined') { attempts = 5;  }

    if (attempts === 0){
        throw new Error("All retry attempts for sendKeys exhausted"); 
    }

    console.log("Sending keys with retries (remaining attempt(s): %d)...", attempts);
    return element
            .clear()
            .sendKeys(text)
            .catch( function(e) {
                console.warn("sendKeys failed with", e);
                return setTextWithRetries(text, element, --attempts);
        });
}

wd.addElementPromiseChainMethod('setTextWithRetries', setTextWithRetries);
```

**Comment by SatishKumarKV** [comment]
Bug filed. ID : 31293498
