### ISSUE TITLE
WebDriverAgent can't show inspector! 

### ISSUE THREAD

**Issue by XLTH** [facebook/WebDriverAgent#457]
When I use iOS-simulator install WDA and open the URL http://localhost:8100/inspector ,it just show me this 
![image](https://cloud.githubusercontent.com/assets/17403786/22172657/37ccf9ce-dfe8-11e6-8efa-dd00b52e3ecd.png)
and the URL show me:
![image](https://cloud.githubusercontent.com/assets/17403786/22172674/5f370b9e-dfe8-11e6-9cbe-883b0bafe126.png)
I really need your help!!

**Comment by baozhida** [comment]
me too  xcode 8.2

**Comment by huanglik** [comment]
this error occurs because your environment is not fit well
just run ./Script/bootstrip.sh  again
run the shell without error ,and then you can use inspector~

**Comment by marekcirkos** [comment]
@XLTH Did it help?
