### ISSUE TITLE
xcodebuild start WDA on real phone ,stop at  Set Up

### ISSUE THREAD

**Issue by baozhida** [facebook/WebDriverAgent#458]
xocde:8.2.1
device:iPhone 7
IOS:10.2
last version WDA
Position:China
log:
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/d2/blcc_d555m97vhnxz1gp22w00000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.iFGP7E/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
Test Suite 'All tests' started at 2017-01-22 10:29:52.350
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-01-22 10:29:52.351
Test Suite 'UITestingUITests' started at 2017-01-22 10:29:52.351
**Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-01-22 10:29:52.352
    t =     0.00s     Set Up**

A lot of people have this problem.
Is this  Xcode problem?
How to solve this problem?

**Comment by huanglik** [comment]
it‘s not stop，that means  it is running now， you can use wda now～

**Comment by baozhida** [comment]
I check the IP on phone，bug I can not connect it .  http://ip:8100

**Comment by huanglik** [comment]
you should run 'iproxy 8100 8100', and then connect it by 'localhost:8100'

**Comment by marekcirkos** [comment]
This looks like issue with Xcode. Restarting your host should resolve it.

**Comment by marekcirkos** [comment]
Added to Known issues in Wiki

**Comment by DhivyaS19** [comment]
Hi all, am also facing the same issue in Xcode 10.2 iOS 12.1, did anyone find the solution for this issue. Kindly share.

**Comment by DhivyaS19** [comment]
> Hi all, am also facing the same issue in Xcode 10.2 iOS 12.1, did anyone find the solution for this issue?Kindly share.

I fixed the issues by replacing http://localhost:8000 by http://yourip:8000. It works fine and am able to see connected iOS device.
