### ISSUE TITLE
【Help】Failed to write value for key AutomationDisableFauxCollectionCells

### ISSUE THREAD

**Issue by huanglik** [facebook/WebDriverAgent#459]
**please look at the picture below， i try to set [FBConfiguration shouldShowFakeCollectionViewCells:NO];  and then start server**
![image](https://cloud.githubusercontent.com/assets/3026388/22182254/bd7f1bda-e0db-11e6-8e7f-3f440c076afd.png)

![image](https://cloud.githubusercontent.com/assets/3026388/22182257/dc6d5016-e0db-11e6-90d5-b30f98ededc4.png)

**the server can running， however， it raises up error like “Failed to write value for key AutomationDisableFauxCollectionCells in CFPrefsPlistSource<0x1740f8780>”**

_2017-01-22 19:47:46.983790 XCTRunner[332:53168] Running tests...
2017-01-22 19:47:47.892944 XCTRunner[332:53168] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-01-22 19:47:48.532
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-01-22 19:47:48.534
Test Suite 'UITestingUITests' started at 2017-01-22 19:47:48.535
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-01-22 19:47:48.537
    t =     0.00s     Set Up
2017-01-22 19:47:48.541743 XCTRunner[332:53199] [User Defaults] Failed to write value for key AutomationDisableFauxCollectionCells in CFPrefsPlistSource<0x1740f8780> (Domain: com.apple.Accessibility, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null)): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access, switching to read-only
2017-01-22 19:47:48.543087 XCTRunner[332:53168] Built at Dec 23 2016 10:20:46
2017-01-22 19:47:48.566961 XCTRunner[332:53168] ServerURLHere->http://10.9.184.70:8100<-ServerURLHere
2017-01-22 19:47:48.567360 XCTRunner[332:53168] Listening on USB_

****and it seems that setting the value of shouldShowFakeCollectionViewCells:NO  is not working
when i set shouldShowFakeCollectionViewCells to yes， it doesn't occur this error**

**## i wanna know：
1.  what the meaning of setting shouldShowFakeCollectionViewCells？（sorry i don't understand the meaning of this words ：  Switch for enabling/disabling reporting fake collection view cells by Accessibility framework.  If set to YES it will report also invisible cells.）
2. why this error happens ？
3. how to avoid that ？**

thank you for your help～

**Comment by marekcirkos** [comment]
Probably this is not needed anymore. However it was added to force iOS 9.x to report all table/collection cell. Anyway this error should not influence WDA in anyway, so you can ignore it.

We might remove it soon, after making sure it does not bring much of benefit

**Comment by huanglik** [comment]
ok,  another question i have
Is there any way to get all the visible  elements  ?
i find that the request with 'localhost:8100/source' will return all the elements ( between visiable and invisiable elements)
however, what if i only want to get all the visible and without those invisiable? what can i do?

**Comment by marekcirkos** [comment]
Unfortunately not. Best you can do is fetch `/source` and filter invisible elements, which shouldn't be too difficult.

**Comment by huanglik** [comment]
this maybe a way to do that.
why I raise up this question is that  it takes long time to get all  the elements ( between visiable and invisiable elements).
if my app has 200 cells in a page, return all elements takes long time. 
If it can return only visible elements, it will be nice.
and i am so sad that no way to fix this problem now ~
 ( the code of XCElementSnapshot is belong to Apple , i can't do anything  )

**Comment by marekcirkos** [comment]
@huanglik That wouldn't improve it anyway. We will have to query all element to determine visibility anyway.
