### ISSUE TITLE
unrecognized selector sent error with ioS 10.3(14E5230e)

### ISSUE THREAD

**Issue by SmithaVemuri** [facebook/WebDriverAgent#465]
Got the Element Id with POST

{"using":"class name","value":"XCUIElementTypeTextField"}

http://10.42.18.23:8100/session/1A265044-B7A7-4B0D-BB7F-9DA03EBBC047/element/7474AF30-63B0-4974-94F9-751A9623D4EA/value

POST: 

{"value":["t","e","s","t","u","s","e","r","1","2","3"]}

Response:

"value": "-[XCTestDriver managerProxy]: unrecognized selector sent to instance 0x170053a40 ( 0 CoreFoundation 0x0000000192623fc4 <redacted> + 148 1 libobjc.A.dylib 0x000000019108853c objc_exception_throw + 56 2 CoreFoundation 0x000000019262aee4 <redacted> + 0 3 CoreFoundation 0x0000000192627f38 <redacted> + 916 4 CoreFoundation 0x000000019252398c _CF_forwarding_prep_0 + 92 5 WebDriverAgentLib 0x0000000103d5d468 __29+[FBKeyboard typeText:error:]_block_invoke + 136 6 WebDriverAgentLib 0x0000000103d62a34 +[FBRunLoopSpinner spinUntilCompletion:] + 172 7 WebDriverAgentLib 0x0000000103d5d250 +[FBKeyboard typeText:error:] + 372 8 WebDriverAgentLib 0x0000000103d6c784 -[XCUIElement(FBTyping) fb_typeText:error:] + 168 9 WebDriverAgentLib 0x0000000103d7841c +[FBElementCommands handleSetValue:] + 860 10 WebDriverAgentLib 0x0000000103d61a28 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208 11 WebDriverAgentLib 0x0000000103d589ec __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496 12 RoutingHTTPServer 0x0000000103e1e3cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144 13 RoutingHTTPServer 0x0000000103e1eb80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44 14 libdispatch.dylib 0x00000001914daa00 <redacted> + 16 15 libdispatch.dylib 0x00000001914eb7f8 <redacted> + 304 16 libdispatch.dylib 0x00000001914daa00 <redacted> + 16 17 libdispatch.dylib 0x00000001914df64c _dispatch_main_queue_callback_4CF + 996 18 CoreFoundation 0x00000001925d2064 <redacted> + 12 19 CoreFoundation 0x00000001925cfc80 <redacted> + 1572 20 CoreFoundation 0x00000001924ff9bc CFRunLoopRunSpecific + 424 21 Foundation 0x000000019301a884 <redacted> + 304 22 Foundation 0x000000019306f1d8 <redacted> + 88 23 WebDriverAgentLib 0x0000000103d57a3c -[FBWebServer startServing] + 320 24 WebDriverAgentRunner 0x0000000103d47ed0 -[UITestingUITests testRunner] + 120 25 CoreFoundation 0x0000000192629e70 <redacted> + 144 26 CoreFoundation 0x000000019251ef0c <redacted> + 292 27 XCTest 0x0000000100101194 __24-[XCTestCase invokeTest]_block_invoke.237 + 48 28 XCTest 0x0000000100142c84 -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 56 29 XCTest 0x0000000100100de0 __24-[XCTestCase invokeTest]_block_invoke_2 + 564 30 XCTest 0x0000000100139fb0 -[XCTestContext performInScope:] + 208 31 XCTest 0x0000000100100b94 -[XCTestCase invokeTest] + 268 32 XCTest 0x00000001001014e4 -[XCTestCase performTest:] + 536 33 XCTest 0x00000001000fe6a8 __27-[XCTestSuite performTest:]_block_invoke + 240 34 XCTest 0x00000001000fe2c8 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44 35 XCTest 0x00000001000fe4b8 -[XCTestSuite performTest:] + 200 36 XCTest 0x00000001000fe6a8 __27-[XCTestSuite performTest:]_block_invoke + 240 37 XCTest 0x00000001000fe2c8 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44 38 XCTest 0x00000001000fe4b8 -[XCTestSuite performTest:] + 200 39 XCTest 0x00000001000fe6a8 __27-[XCTestSuite performTest:]_block_invoke + 240 40 XCTest 0x00000001000fe2c8 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44 41 XCTest 0x00000001000fe4b8 -[XCTestSuite performTest:] + 200 42 XCTest 0x0000000100147454 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 44 43 XCTest 0x000000010010cf94 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 520 44 XCTest 0x00000001001472d4 -[XCTTestRunSession runTestsAndReturnError:] + 292 45 XCTest 0x00000001000e99a4 -[XCTestDriver runTestsAndReturnError:] + 252 46 XCTest 0x000000010013d8fc _XCTestMain + 548 47 CoreFoundation 0x00000001925d22a8 <redacted> + 20 48 CoreFoundation 0x00000001925d1ac4 <redacted> + 288 49 CoreFoundation 0x00000001925cf934 <redacted> + 728 50 CoreFoundation 0x00000001924ff9bc CFRunLoopRunSpecific + 424 51 GraphicsServices 0x0000000193f6c074 GSEventRunModal + 100 52 UIKit 0x00000001988ae984 UIApplicationMain + 208 53 XCTRunner 0x0000000100028474 XCTRunner + 33908 54 libdyld.dylib 0x000000019150d59c <redacted> + 4 )",
"sessionId": "1A265044-B7A7-4B0D-BB7F-9DA03EBBC047",
"status": 13

Same request used to work with 10.1.1 I just upgraded my environment got the latest webDriverAgent code and starting to see this issue. Please let me know if any of you guys know the solution.

It seems to be issue with typing text.

Clicking on the button works
getting value of the textfield works

Messages from the WebDriverAgent start up log

    t =   928.79s     Find: Descendants matching type Keyboard
    t =   928.89s     Find the Keyboard
    t =   928.90s         Snapshot accessibility hierarchy for local.pid.285
    t =   929.01s         Find: Descendants matching type Keyboard
    t =   929.12s     Find the Keyboard
    t =   929.12s         Snapshot accessibility hierarchy for local.pid.285
    t =   929.23s         Find: Descendants matching type Keyboard
2017-01-25 17:04:36.169855-0500 XCTRunner[273:9976] -[XCTestDriver managerProxy]: unrecognized selector sent to instance 0x174057b50

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/6a8281374f5976517bde5f54fb5291c231d7e452
