### ISSUE TITLE
Can't able to launch inspector

### ISSUE THREAD

**Issue by PradeshKumar-emisweb** [facebook/WebDriverAgent#472]
I'm getting the following error, whenever I'm trying to launch the inspector,

*** Assertion failure in -[FBResponseFilePayload initWithFilePath:], /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBResponseFilePayload.m:24

Any help?
<img width="669" alt="untitled" src="https://cloud.githubusercontent.com/assets/21124106/22463057/fb72f686-e7d5-11e6-8f08-84b01e79939f.png">

**Comment by marekcirkos** [comment]
Did you run bootstrap.sh script?

**Comment by PradeshKumar-emisweb** [comment]
Yes

**Comment by PradeshKumar-emisweb** [comment]
I found the solution from the net, I followed the below steps. It's working fine now.

```
cd ~/"${REPOS}"
git clone https://github.com/facebook/WebDriverAgent.git
cd WebDriverAgent
./Scripts/bootstrap.sh
cd "${APPIUM}"
rm -rf WebDriverAgent
ln ~/"${REPOS}"/WebDriverAgent
```
