### ISSUE TITLE
Can we use webdriverAgent to automate iPhone settings 

### ISSUE THREAD

**Issue by vathsalahn** [facebook/WebDriverAgent#475]
We need to turn on and off the Bluetooth .Can we use webdriverAgent for this and can we use only curl commands to communicate without appium support .

**Comment by marekcirkos** [comment]
Yes, Yes. :) Have a look here https://github.com/facebook/WebDriverAgent/wiki/Queries

**Comment by vathsalahn** [comment]
Thank you .:) .
