### ISSUE TITLE
can not dump tree for big app

### ISSUE THREAD

**Issue by channingbreeze** [facebook/WebDriverAgent#477]
when I visit /source or /source/xml，I can get tree when iphone is showing desktop or simple app.
but when i open some complicated apps, /source will not work, it is very slow and no response back.
does anyone meet this situation? can anyone help me fix this?
thank you very much!

**Comment by wxyfight** [comment]
similar question, when I call getPageSource() method with complicated app, it's very slow. I used Appium.

**Comment by mykola-mokhnach** [comment]
Did you try to update WDA sources to the most recent version? It should work better there, since \@visible attribute has been removed from xml source
