### ISSUE TITLE
tap cost so long seems because of snapshot

### ISSUE THREAD

**Issue by leocone** [facebook/WebDriverAgent#479]
I send a position {x, y} to tap on web, the log seems during tap, WDA did snapshot (log is below).
Can I ignore the snapshot to speed up the tab action done?

WDA log:
t = 117.41s Find the Application "local.pid.251" 0x157a9150
t = 117.41s Snapshot accessibility hierarchy for local.pid.251
t = 123.66s Find the Application "local.pid.251" 0x157a9150
t = 123.67s Use cached accessibility hierarchy for local.pid.251
t = 124.32s Tap Application "local.pid.251" 0x157a9150[0.00, 0.00] -> (90.0, 300.0)
t = 124.32s Wait for app to idle
t = 124.59s Find the Application "local.pid.251" 0x157a9150
t = 124.59s Snapshot accessibility hierarchy for local.pid.251
t = 131.48s Wait for app to idle
t = 131.73s App event loop idle notification not received, will attempt to continue.
t = 131.74s App animations complete notification not received, will attempt to continue.
t = 131.83s Synthesize event
t = 132.01s Find the Application "local.pid.251" 0x157a9150
t = 132.01s Snapshot accessibility hierarchy for local.pid.251
t = 139.65s Wait for app to idle

**Comment by marekcirkos** [comment]
Snapshots are key components of XCTest framework. Unfortunately there is not much we can do.
