### ISSUE TITLE
When setting value, connection is sometimes dropped

### ISSUE THREAD

**Issue by imurchie** [facebook/WebDriverAgent#481]
WebDriverAgent sometimes drops the connection with the client. While this can happen randomly with any command, it seems to happen most on resource-constrained systems (when there is low memory, etc.) while sending a `POST` request to `/element/:uuid/value`. This is either felt as the socket hanging up (if waiting for a response) or an ECONNREFUSED error (if sending a request.

A sample of the sort of thing that is begin done (in this particular case, this is about 4 minutes into a session):
```
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/465bb6be-c916-491d-8e4c-5603f38961df/element/57588822-2EE7-4CEA-A508-073569758610/displayed] to [GET http://localhost:8100/session/3A134330-F9E1-47A8-8B58-5607AD399477/element/57588822-2EE7-4CEA-A508-073569758610/displayed] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"3A134330-F9E1-47A8-8B58-5607AD399477\",\n  \"status\" : 0\n}"

[debug] [JSONWP Proxy] Proxying [GET /element/57588822-2EE7-4CEA-A508-073569758610/attribute/type] to [GET http://localhost:8100/session/3A134330-F9E1-47A8-8B58-5607AD399477/element/57588822-2EE7-4CEA-A508-073569758610/attribute/type] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeTextField\",\n  \"sessionId\" : \"3A134330-F9E1-47A8-8B58-5607AD399477\",\n  \"status\" : 0\n}"

[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/3A134330-F9E1-47A8-8B58-5607AD399477/element] with body: {"using":"class name","value":"XCUIElementTypeKeyboard"}
2017-02-10 22:50:01:914 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"FB16F40C-F5A2-4C8F-B813-5E3CC54F12E1","type":"XCUIElementTypeKeyboard","label":null},"sessionId":"3A134330-F9E1-47A8-8B58-5607AD399477","status":0}

[debug] [JSONWP Proxy] Proxying [POST /element/57588822-2EE7-4CEA-A508-073569758610/value] to [POST http://localhost:8100/session/3A134330-F9E1-47A8-8B58-5607AD399477/element/57588822-2EE7-4CEA-A508-073569758610/value] with body: {"value":["L","a","s","t"]}
2017-02-10 22:53:16:166 - [MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
```

Any idea of why this is happening, and how to get around it, would be most appreciated!

**Comment by marekcirkos** [comment]
Is it WDA dying or maybe proxy issue?

**Comment by imurchie** [comment]
It seems like it is WDA dying. We are sending HTTP commands directly, so there is nothing between the two systems. Unfortunately, nothing comes up in the device logs when the failure happens.

**Comment by mykola-mokhnach** [comment]
@imurchie I believe it's the same problem as described [here](https://github.com/facebook/WebDriverAgent/issues/453). Just check whether the device log contains this magic string to make sure it is:

```
Error Domain=XCTestManagerErrorDomain Code=14 "Timed out waiting for key event to complete" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete
```

**Comment by marekcirkos** [comment]
It should not die. This error usually occurs after 60s and WDA is responsive afterwords. Maybe proxy has faster timeout or something?

**Comment by mykola-mokhnach** [comment]
Our proxy has default timeout set to 240 seconds, but this does not help :(

**Comment by marekcirkos** [comment]
@imurchie any luck here? I remember you were working on this, is that right?

**Comment by mykola-mokhnach** [comment]
I assume [this](https://github.com/facebook/WebDriverAgent/pull/529) PR addresses the issue

**Comment by marekcirkos** [comment]
Is is resolved?

**Comment by marekcirkos** [comment]
Can you link? 
Or even better link fork? I am curious what we are missing from your fixes.

**Comment by imurchie** [comment]
Sure: https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBXCTestDaemonsProxy.m#L19-L34

The only other change we have is that we support Xcode below 8.3, so we had to remove the recent `tap` logic, which won't compile otherwise.
