### ISSUE TITLE
Issue while installing .Scripts/bootstrap.h

### ISSUE THREAD

**Issue by kiranks4480** [facebook/WebDriverAgent#482]
Hi Team,

I am new to Node based appium testing , I have followed all the step to setup appium and I am able do proceed with automation also but installation is failing for Inspector installation and I am unable to resolve it

Launching Flow server for /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
Spawned flow server (pid=49737)
Logs will go to /private/tmp/flow/zSusrzSlocalzSlibzSnode_moduleszSappiumzSnode_moduleszSappium-xcuitest-driverzSWebDriverAgentzSInspector.log
No errors!

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js
  12:18  error  Unable to resolve path to module 'js/http'                import/no-unresolved
  13:20  error  Unable to resolve path to module 'js/screen'              import/no-unresolved
  14:31  error  Unable to resolve path to module 'js/screenshot_factory'  import/no-unresolved
  15:18  error  Unable to resolve path to module 'js/tree'                import/no-unresolved
  16:22  error  Unable to resolve path to module 'js/tree_node'           import/no-unresolved
  17:25  error  Unable to resolve path to module 'js/tree_context'        import/no-unresolved
  18:23  error  Unable to resolve path to module 'js/inspector'           import/no-unresolved
  27:14  error  Missing space before function parentheses                 space-before-function-paren
  32:20  error  Missing space before function parentheses                 space-before-function-paren
  37:18  error  Missing space before function parentheses                 space-before-function-paren
  42:13  error  Expected property shorthand                               object-shorthand
  49:12  error  Missing space before function parentheses                 space-before-function-paren
  57:9   error  Missing space before function parentheses                 space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/http.js
  13:13  error    Missing space before function parentheses            space-before-function-paren
  13:20  warning  Avoid callbacks. Prefer Async/Await                  promise/prefer-await-to-callbacks
  18:24  error    Expected parentheses around arrow function argument  arrow-parens
  20:7   warning  Avoid callbacks. Prefer Async/Await                  promise/prefer-await-to-callbacks
  25:14  error    Missing space before function parentheses            space-before-function-paren
  25:21  warning  Avoid callbacks. Prefer Async/Await                  promise/prefer-await-to-callbacks
  30:24  error    Expected parentheses around arrow function argument  arrow-parens
  32:7   warning  Avoid callbacks. Prefer Async/Await                  promise/prefer-await-to-callbacks

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/image_utils.js
  11:34  error    Missing space before function parentheses  space-before-function-paren
  11:55  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  15:40  error    Missing space before function parentheses  space-before-function-paren
  15:69  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  28:45  error    Missing space before function parentheses  space-before-function-paren
  28:79  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  41:22  error    Missing space before function parentheses  space-before-function-paren
  41:31  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  44:28  error    Missing space before function parentheses  space-before-function-paren
  45:7   warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/inspector.js
  14:22  error  Missing space before function parentheses  space-before-function-paren
  19:9   error  Missing space before function parentheses  space-before-function-paren
  34:18  error  Missing space before function parentheses  space-before-function-paren
  54:14  error  Missing space before function parentheses  space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/screen.js
  15:9   error  Missing space before function parentheses     space-before-function-paren
  32:22  error  Missing space before function parentheses     space-before-function-paren
  40:13  error  Missing space before function parentheses     space-before-function-paren
  44:19  error  Missing space before function parentheses     space-before-function-paren
  53:24  error  Missing space before function parentheses     space-before-function-paren
  66:34  error  Missing space before function parentheses     space-before-function-paren
  79:75  error  Missing space before opening brace            space-before-blocks
  80:9   error  Expected indentation of 6 spaces but found 8  indent

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/screenshot_factory.js
  10:24  error    Unable to resolve path to module 'js/image_utils'  import/no-unresolved
  12:30  error    Missing space before function parentheses          space-before-function-paren
  23:26  error    Missing space before function parentheses          space-before-function-paren
  23:60  warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks
  33:28  error    Missing space before function parentheses          space-before-function-paren
  37:22  error    Missing space before function parentheses          space-before-function-paren
  37:43  warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks
  51:34  error    Missing space before function parentheses          space-before-function-paren
  51:42  warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks
  58:5   warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/tree.js
   22:9   error  Missing space before function parentheses  space-before-function-paren
   41:16  error  Missing space before function parentheses  space-before-function-paren
   45:21  error  Missing space before function parentheses  space-before-function-paren
   51:13  error  Missing space before function parentheses  space-before-function-paren
   63:13  error  Missing space before function parentheses  space-before-function-paren
  100:14  error  Missing space before function parentheses  space-before-function-paren
  106:19  error  Missing space before function parentheses  space-before-function-paren
  112:19  error  Missing space before function parentheses  space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/tree_context.js
  11:14  error  Missing space before function parentheses  space-before-function-paren
  16:21  error  Missing space before function parentheses  space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/tree_node.js
  11:19  error  Missing space before function parentheses  space-before-function-paren
  18:23  error  Missing space before function parentheses  space-before-function-paren
  26:23  error  Missing space before function parentheses  space-before-function-paren
  36:19  error  Missing space before function parentheses  space-before-function-paren
  49:14  error  Missing space before function parentheses  space-before-function-paren

✖ 68 problems (55 errors, 13 warnings)

I am struggling to resolve this issue from past 2 days

My environment

1.Node 6.9.5
2.Appium 1.6.3
3.Mac Siera 10.2.1
4.Xcode 8.2.1

Note:-I have removed the default WDA from appium-xcuitest-driver and taken the latest one from git

I am not facing any problem with automating the applications both on Simulator and devices, muy only concern is with Inspector which I am unable to bring up and use

Currently I am using app-inspector  and it is helping me to proceed with automation but it would be of great help if this issue gets resolved and I am able to use Appium inspector from appium GUI

**Comment by marekcirkos** [comment]
Can you fetch WDA fro m github directly and check if ./Scripts/bootstrap.sh works for you?

**Comment by lujian2036** [comment]
`Validating Inspector
Launching Flow server for /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
Spawned flow server (pid=37693)
Logs will go to /private/tmp/flow/zSusrzSlocalzSlibzSnode_moduleszSappiumzSnode_moduleszSappium-xcuitest-driverzSWebDriverAgentzSInspector.log
No errors!

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js
  12:18  error  Unable to resolve path to module 'js/http'                import/no-unresolved
  13:20  error  Unable to resolve path to module 'js/screen'              import/no-unresolved
  14:31  error  Unable to resolve path to module 'js/screenshot_factory'  import/no-unresolved
  15:18  error  Unable to resolve path to module 'js/tree'                import/no-unresolved
  16:22  error  Unable to resolve path to module 'js/tree_node'           import/no-unresolved
  17:25  error  Unable to resolve path to module 'js/tree_context'        import/no-unresolved
  18:23  error  Unable to resolve path to module 'js/inspector'           import/no-unresolved
  27:14  error  Missing space before function parentheses                 space-before-function-paren
  32:20  error  Missing space before function parentheses                 space-before-function-paren
  37:18  error  Missing space before function parentheses                 space-before-function-paren
  49:12  error  Missing space before function parentheses                 space-before-function-paren
  57:9   error  Missing space before function parentheses                 space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/http.js
  13:13  error    Missing space before function parentheses  space-before-function-paren
  13:20  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  20:7   warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  25:14  error    Missing space before function parentheses  space-before-function-paren
  25:21  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  32:7   warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/image_utils.js
  11:34  error    Missing space before function parentheses  space-before-function-paren
  11:55  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  15:40  error    Missing space before function parentheses  space-before-function-paren
  15:69  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  28:45  error    Missing space before function parentheses  space-before-function-paren
  28:79  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  41:22  error    Missing space before function parentheses  space-before-function-paren
  41:31  warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks
  44:28  error    Missing space before function parentheses  space-before-function-paren
  45:7   warning  Avoid callbacks. Prefer Async/Await        promise/prefer-await-to-callbacks

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/inspector.js
  14:22  error  Missing space before function parentheses  space-before-function-paren
  19:9   error  Missing space before function parentheses  space-before-function-paren
  34:18  error  Missing space before function parentheses  space-before-function-paren
  54:14  error  Missing space before function parentheses  space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/screen.js
  15:9   error    Missing space before function parentheses     space-before-function-paren
  32:22  error    Missing space before function parentheses     space-before-function-paren
  40:13  error    Missing space before function parentheses     space-before-function-paren
  44:19  error    Missing space before function parentheses     space-before-function-paren
  53:24  error    Missing space before function parentheses     space-before-function-paren
  66:34  error    Missing space before function parentheses     space-before-function-paren
  79:75  warning  Missing space before opening brace            space-before-blocks
  80:9   error    Expected indentation of 6 spaces but found 8  indent

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/screenshot_factory.js
  10:24  error    Unable to resolve path to module 'js/image_utils'  import/no-unresolved
  12:30  error    Missing space before function parentheses          space-before-function-paren
  23:26  error    Missing space before function parentheses          space-before-function-paren
  23:60  warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks
  33:28  error    Missing space before function parentheses          space-before-function-paren
  37:22  error    Missing space before function parentheses          space-before-function-paren
  37:43  warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks
  51:34  error    Missing space before function parentheses          space-before-function-paren
  51:42  warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks
  58:5   warning  Avoid callbacks. Prefer Async/Await                promise/prefer-await-to-callbacks

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/tree.js
   22:9   error  Missing space before function parentheses  space-before-function-paren
   41:16  error  Missing space before function parentheses  space-before-function-paren
   45:21  error  Missing space before function parentheses  space-before-function-paren
   51:13  error  Missing space before function parentheses  space-before-function-paren
   63:13  error  Missing space before function parentheses  space-before-function-paren
  100:14  error  Missing space before function parentheses  space-before-function-paren
  106:19  error  Missing space before function parentheses  space-before-function-paren
  112:19  error  Missing space before function parentheses  space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/tree_context.js
  11:14  error  Missing space before function parentheses  space-before-function-paren
  16:21  error  Missing space before function parentheses  space-before-function-paren

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/tree_node.js
  11:19  error  Missing space before function parentheses  space-before-function-paren
  18:23  error  Missing space before function parentheses  space-before-function-paren
  26:23  error  Missing space before function parentheses  space-before-function-paren
  36:19  error  Missing space before function parentheses  space-before-function-paren
  49:14  error  Missing space before function parentheses  space-before-function-paren

✖ 65 problems (51 errors, 14 warnings)`
i also suffer this problem ,i fetch wad from GitHub and from appium ,both meet this

**Comment by MaxTwentythree** [comment]
Same problem here

**Comment by marekcirkos** [comment]
This is Appium issue in nesting WDA inside it. If you fetch WDA independently it will work. Please raise a ticket on Appium repo.

**Comment by bmvbab** [comment]
I tried fetching the latest WDA from their repo and I see the same issue. Did anyone else see this problem?
Im using 1.6.4 beta and the latest code from WDA

**Comment by lujian2036** [comment]
@bmvbab  i solve this problem by download WDA in a  different directory,such as /Users/mac/WebDriverAgent , then do as the manual to compile WDA ,then go to appium-xcuitest-driver directory, the full path in my matchins is /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver, then ln -s  WebDriverAgent   /Users/mac/WebDriverAgent  ,link the WebDriverAgent to /Users/mac/WebDriverAgent

**Comment by tobecrazy** [comment]
@monleylu  I try your solution but not work at all

**Comment by bmvbab** [comment]
@tobecrazy whats the version you are trying to build? I havn't seen this issue in a while.

**Comment by xlving** [comment]
@tobecrazy  hello ，hava you resolve this issue , i have met the same one , could you please provide the resolution if you have resolve it ? Thank you very much!
