### ISSUE TITLE
Issue with uiAutomator2 failing with JAVA_HOME not set

### ISSUE THREAD

**Issue by kiranks4480** [facebook/WebDriverAgent#483]
Hi Team,

I am new to Node based appium testing , I have followed all the step to setup appium and I am able do proceed with automation 

uiautomator-2 errors with JAVA_HOME not set
but I have already set the details in bash_profile and it is working well with uiautomator1
Please provide me a feasible solution to resolve this issue

**Comment by kiranks4480** [comment]
Sorry wrong forum

**Comment by marekcirkos** [comment]
You should raise your issue with Appium.
