### ISSUE TITLE
WebDriverAgent is not working for osx platform.

### ISSUE THREAD

**Issue by vkvikaskmr** [facebook/WebDriverAgent#484]
Hi,
The document says that even though osx is not supported yet but the WebDriverAgent works for osx platform. I tried running it for osx but it is not working. The idea is to automate Mac applications using FB WebdriverAgent. I am trying the following command to start it :
 
`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'platform=OSX,id=5F0026B4-84DF-539A-8DA4-5E7D2BBF1413' test 
`
I get this message : 
```
Ineligible destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
```
Please note that the "id" in my command is the hardware UUID of my Mac book pro. Kindly help me start WebDriverAgent for osx using which I can automate Mac applications.

Thanks!

**Comment by marekcirkos** [comment]
Executing iOS target on OSX will not work. You need separate binary target for OSX.

**Comment by vkvikaskmr** [comment]
Can you please throw some more light on this. I am not able to create an OSX target for WebDriverAgent by myself.

**Comment by marekcirkos** [comment]
I bet if you google for `adding OS X target to xcode project`, you will find something.

**Comment by gclouds** [comment]
@vkvikaskmr  did you get some success?

**Comment by VikasKumar190** [comment]
No not really, I started looking into other alternatives and didn't try this further.

**Comment by vkvikaskmr** [comment]
I didn't try it further. No good news from my side :(

**Comment by gclouds** [comment]
@vkvikaskmr do you have any other framework in mind. by which I can do same stuff?

**Comment by vkvikaskmr** [comment]
We started using atomac with python and that was working fine for us.
