### ISSUE TITLE
There is an error in building wda

### ISSUE THREAD

**Issue by sixleaves** [facebook/WebDriverAgent#485]
well.i use the iphone4s that 32bit cpu.when i build wda on this iphone, an error will occur.this error make me cannot communicate with wda, but it can build success.

    DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x0000000108d763cb DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x0000000108d76b09 DTDK_AMDErrorToNSError + 791
	2   DTDeviceKitBase                     0x0000000108d882f5 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 100
	3   DTDeviceKitBase                     0x0000000108d871d1 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_4 + 22
	4   DTDeviceKitBase                     0x0000000108d79317 __DTDKExecuteInSession_block_invoke + 38
	5   DTDeviceKitBase                     0x0000000108d78940 __DTDKExecuteWithConnection_block_invoke_2 + 477
	6   DTDeviceKitBase                     0x0000000108d7873c __DTDKExecuteWithConnection_block_invoke + 107
	7   libdispatch.dylib                   0x00007fffaf2b7128 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fffaf2b7d62 _dispatch_barrier_sync_f_invoke + 83
	9   DVTFoundation                       0x0000000100b5ebef DVTDispatchBarrierSync + 206
	10  DVTFoundation                       0x0000000100b3b59b -[DVTDispatchLock performLockedBlock:] + 116
	11  DTDeviceKitBase                     0x0000000108d78646 DTDKExecuteWithConnection + 223
	12  DTDeviceKitBase                     0x0000000108d792a1 DTDKExecuteInSession + 121
	13  DTDeviceKitBase                     0x0000000108d87108 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 117
	14  DVTFoundation                       0x0000000100b5df4b __DVTDispatchAsync_block_invoke + 827
	15  libdispatch.dylib                   0x00007fffaf2bff5f _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fffaf2b7128 _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fffaf2ccc10 _dispatch_continuation_pop + 533
	18  libdispatch.dylib                   0x00007fffaf2c3ea3 _dispatch_async_redirect_invoke + 734
	19  libdispatch.dylib                   0x00007fffaf2b8ee0 _dispatch_root_queue_drain + 476
	20  libdispatch.dylib                   0x00007fffaf2b8cb7 _dispatch_worker_thread3 + 99
	21  libsystem_pthread.dylib             0x00007fffaf503746 _pthread_wqthread + 1299
	22  libsystem_pthread.dylib             0x00007fffaf503221 start_wqthread + 13
    ), NSLocalizedRecoverySuggestion=Too many instances of this service are already running.,      NSLocalizedDescription=Too many instances of this service are already running.}]

**Comment by marekcirkos** [comment]
So it fails to start not build. Can you try restarting the phone and host?

**Comment by mykola-mokhnach** [comment]
Judging on several recent issue reports for Appium this seems to be a common issue for 32-bit devices and I don't think we can fix it on our side. Just run your tests on a newer 64-bit device :(

@marekcirkos I think we can add this type of error to our knowledge base.

**Comment by marekcirkos** [comment]
@mykola-mokhnach anyone can, Wiki's are open.

**Comment by marekcirkos** [comment]
Plus it is already there https://github.com/facebook/WebDriverAgent/wiki/Common-Issues#booting-wda-on-device-stops-after-set-up-and-does-not-actually-start-wda
