### ISSUE TITLE
How to 'shake' a headless simulator?

### ISSUE THREAD

**Issue by sleekweasel** [facebook/WebDriverAgent#486]
Running with a simulator window, I can use applescript to select a simulator window and send it a shake keystroke - ^#Z - but is there a way to send that to a headless emulator?

I can probably arrange for my shake-sensitive tests to run on a headed simulator, but it's going to require additional infrastructure I'd prefer to do without.

**Comment by marekcirkos** [comment]
@sleekweasel `WDA` does not support simulating shake, so I can't help you here.
