### ISSUE TITLE
WebDriverAgent.bundle: No such file or directory

### ISSUE THREAD

**Issue by cosminstirbu** [facebook/WebDriverAgent#487]
Hello,

When building the WebDriverAgentRunner I receive the following error:

WebDriverAgent.bundle: No such file or directory

The bundle is linked in the Resources group but it is missing.
I did remove it from the target but when I try to run the inspector I receive a crash.

Do I have to build the Inspector folder somehow and create a WebDriverAgent.bundle?
Can you please share some commands of how that can be done?

Thank you!

**Comment by marekcirkos** [comment]
Did you run `./Scripts/bootstrap.sh`?

**Comment by Mrgentlemangaga** [comment]
![2018-01-19 3 43 26](https://user-images.githubusercontent.com/29853841/35139764-869f4330-fd2f-11e7-86f5-00e8a100ab94.png)

**Comment by wilnicm** [comment]
Did anyone solve the above issue.  I'm running the ./Scripts/bootstrap.sh -d and i'm getting the No such file or directory message also?

**Comment by IcyW** [comment]
@Mrgentlemangaga  @wilnicm  You should run `./Scripts/bootstrap.sh -d` under the `WebDriverAgent` document.

**Comment by IcyW** [comment]
However, after running the script, I still received the following error:
`WebDriverAgent.bundle: No such file or directory`
![image](https://user-images.githubusercontent.com/16513834/53075545-69b5d900-3528-11e9-9bb2-39d6d86bfd5a.png)

![image](https://user-images.githubusercontent.com/16513834/53075583-82be8a00-3528-11e9-849c-203d6bf529cd.png)
