### ISSUE TITLE
How to use WebDriverAgent for automating OSX applications?

### ISSUE THREAD

**Issue by vkvikaskmr** [facebook/WebDriverAgent#489]
Is there a separate WebDriverAgent project that can be used for automating MacOSX applications?

**Comment by marekcirkos** [comment]
Nope. If you want to work on OSX support I'll be happy to review it.

**Comment by cosminstirbu** [comment]
I didn't, I missed exactly the most important part of the documentation.

That was stupid from my side :D.

I did run it an now everything works as expected.

Thank you!
