### ISSUE TITLE
Does webdriver Agent support communication on multiple iphones connected 

### ISSUE THREAD

**Issue by vathsalahn** [facebook/WebDriverAgent#491]
Hi ,

I am able to communicate on single iphone connected via USB through webdriver agent. Can i use 2 iphones connected to a single mac via usb to communicate simultaneously.Does 8100 port is fixed ??.If i use 2 iphones bot gets connected to same 8100 port?? Can i pass the port value dynamically while starting the webdriver agent.

**Comment by marekcirkos** [comment]
You can use `USE_PORT` env or `--port` launch argument on host app to overwrite the port.

**Comment by vathsalahn** [comment]
I am using xcodebuild to run tests ..Can u please elaborate on how to pass --port argument to xcodebuild command ..

**Comment by marekcirkos** [comment]
I think you need separate schemes for that.
