### ISSUE TITLE
FBXPath parses Unicode?

### ISSUE THREAD

**Issue by tyhcmu** [facebook/WebDriverAgent#493]
Hi,

I was using Appium v1.6.3 to test a native app, and got the following error when manipulating elements in a page containing Unicode texts:

[debug] [WebDriverAgent] Sim: Feb 21 17:00:25 MSJCIT1024873 XCTRunner[43698]: Failed to invoke libxml2>xmlTextWriterStartElement. Error code: -1
[debug] [WebDriverAgent] Sim: Feb 21 17:00:25 MSJCIT1024873 XCTRunner[43698]: Failed to generate XML presentation of a screen element

It seems like FBXPath was not able to parse elements with Unicode texts. Is it as expected? 

Thank you!

**Comment by marekcirkos** [comment]
cc: @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
what type of Unicode is it? I didn't see any problems so far with UTF-8 for example.

**Comment by tyhcmu** [comment]
Hi @mykola-mokhnach,
Sorry for the misleading information. I double checked the app source code and it is actually a special control character ETX that breaks the parsing. Closing the issue.
