### ISSUE TITLE
Application bundleID as "com.company.appname" instead of "local.pid.XXX" ?

### ISSUE THREAD

**Issue by JonGabilondoAngulo** [facebook/WebDriverAgent#494]
Hi,
property "bundleID" of FBApplication returns always an string of type "local.pid.XXX".
Is it possible to get the real bundle ID somehow ?

Thanks.

**Comment by marekcirkos** [comment]
@JonGabilondoAngulo I don't think so. Why you need it?

**Comment by JonGabilondoAngulo** [comment]
Hi
I thought it could be useful to know when an action occurred not in the application under test, e.g. the springboard.

**Comment by marekcirkos** [comment]
You can now that from WDA code. You can simply check active app against app assigned to session.
