### ISSUE TITLE
Webpack has been initialised using a configuration object that does not match the API schema

### ISSUE THREAD

**Issue by NingLu** [facebook/WebDriverAgent#495]
hi, 
i want to use webdriveragent to do ios automation test, after execute "./Scripts/bootstrap.sh", error occurs, is there anything wrong? i've installed web-pack, carthage
`./Scripts/bootstrap.sh
Fetching dependencies
Building Inspector
Creating bundle directory...
Building inspector.js...

> web-driver-inspector@1.0.0 build /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
> webpack --progress --colors

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! web-driver-inspector@1.0.0 build: `webpack --progress --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web-driver-inspector@1.0.0 build script 'webpack --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web-driver-inspector package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web-driver-inspector
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web-driver-inspector
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/npm-debug.log
Error occured during 'npm run build', please check npm build log`

================and the npm build log is ===================

info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle web-driver-inspector@1.0.0~prebuild: web-driver-inspector@1.0.0
6 silly lifecycle web-driver-inspector@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle web-driver-inspector@1.0.0~build: web-driver-inspector@1.0.0
8 verbose lifecycle web-driver-inspector@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle web-driver-inspector@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/.bin:/usr/local/lib/node_modules/appium/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/bin:/opt/subversion/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home:/Volumes/Transcend/androidSDK//tools:/Volumes/Transcend/androidSDK//platform-tools:/Users/baidu/MyApp/apache-ant-1.9.4/bin:/Volumes/Transcend/androidSDK//build-tools/19.1.0:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/baidu/Library/Android/sdk:/Users/baidu/Library/Android/sdk/platform-tools:/Users/baidu/Library/Android/sdk/tools:/Users/baidu/svn_code/xz-5.2.1:/opt/X11/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Volumes/Transcend/androidSDK//build-tools:/Volumes/Transcend/androidSDK//platform-tools:/Volumes/Transcend/androidSDK//tools:/bin:/usr/local/bin
10 verbose lifecycle web-driver-inspector@1.0.0~build: CWD: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
11 silly lifecycle web-driver-inspector@1.0.0~build: Args: [ '-c', 'webpack --progress --colors' ]
12 silly lifecycle web-driver-inspector@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle web-driver-inspector@1.0.0~build: Failed to exec build script
14 verbose stack Error: web-driver-inspector@1.0.0 build: `webpack --progress --colors`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid web-driver-inspector@1.0.0
16 verbose cwd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v6.6.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error web-driver-inspector@1.0.0 build: `webpack --progress --colors`
22 error Exit status 1
23 error Failed at the web-driver-inspector@1.0.0 build script 'webpack --progress --colors'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the web-driver-inspector package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --progress --colors
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs web-driver-inspector
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls web-driver-inspector
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
i've try to reinstall ,but it doesn't work, someone please help~

**Comment by marekcirkos** [comment]
This is Appium issue in nesting WDA inside it. If you fetch WDA independently it will work. Please raise a ticket on Appium repo.
