### ISSUE TITLE
Run WebDriverAgent without XCode

### ISSUE THREAD

**Issue by MaciejCiach** [facebook/WebDriverAgent#496]
Any chance to run WebDriverAgent without XCode ? For ex. when iPhone is connected to Windows Machine

**Comment by marekcirkos** [comment]
XCTest requires XPC connection to host. So in theory if you can mock that it could be possible. Tho there is nothing that I know of that works.

**Comment by qmfrederik** [comment]
@MaciejCiach We have a commercial solution that supports running the WebDriverAgent on Windows & Linux. Ping me at frederik.carlier@quamotion.mobi if you want to know more.

@marekcirkos I think we talked about this at the Selenium conference in London last year. Let me know if you feel this message is not appropriate, and I'll remove it.

**Comment by wangjinbo1** [comment]
@MaciejCiach Have you solved your problems,(when iPhone is connected to Windows Machine).I also face to the same problem.can you tell me how to do?
