### ISSUE TITLE
appium + WebDriverAgentRunner

### ISSUE THREAD

**Issue by lixiaoyudakeke** [facebook/WebDriverAgent#497]
when i run cd  /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=真机的udid' test  

is error
`Test Suite 'Selected tests' started at 2017-02-28 17:18:20.666
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-02-28 17:18:20.671
Test Suite 'WebDriverAgentRunner.xctest' failed at 2017-02-28 17:18:20.673.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.002) seconds
Test Suite 'WebDriverAgentLib.framework' started at 2017-02-28 17:18:20.676
Test Suite 'WebDriverAgentLib.framework' passed at 2017-02-28 17:18:20.678.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.003) seconds
Test Suite 'Selected tests' failed at 2017-02-28 17:18:20.680.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.014) seconds
Failing tests:
	-[UITestingUITests testRunner]
** TEST FAILED **
Please help answer

**Comment by marekcirkos** [comment]
@lixiaoyudakeke Did you resolve that?
