### ISSUE TITLE
dragfromtoforduration does not respect coordinate inputs

### ISSUE THREAD

**Issue by jjacquet** [facebook/WebDriverAgent#498]
I am trying to get the view in a safari browser to swipe down using the following command on a simulator:

`curl -X POST $JSON_HEADER -d "{fromX:0,fromY:60,toX:0,toY:500,duration:0.5}" $DEVICE_URL/session/$SESSION_ID/uiaTarget/0/dragfromtoforduration`

the screen scrolls up so I changed `toY:500` to `toY:-500` and still the same behavior.  I inputted `0` for all `X` and `Y` values and still the same behavior. The values are not being respected and with new entries, still the screen scrolls up. A closer look at the WebDriverAgent DTServiceHub and it reads:

` Use cached accessibility hierarchy for com.apple.mobilesafari
 Press and drag from Application 
"com.apple.mobilesafari" 0x6080000a11a0[0.00, 0.00] -> (0.0, 0.0) to Application "com.apple.mobilesafari" 0x6080000a11a0[0.00, 0.00] -> (0.0, 0.0)
Find the Application "com.apple.mobilesafari" 0x6080000a11a0
Use cached accessibility hierarchy for com.apple.mobilesafari
 Synthesize event`

You can see that its not respecting the params and passing `0x6080000a11a0[0.00, 0.00] -> (0.0, 0.0)` regardless.

Is my syntax correct?

**Comment by marekcirkos** [comment]
I think your curl command is wrong. You should quote escape all parameters.
`"{\"fromX\":\"0\",\"fromY\":\"60\",\"toX\":\"0\",\"toY\":\"500\",\"duration\":\"0.5\"}" `

**Comment by jjacquet** [comment]
That could possibly be the solution, but i am unable to confirm as I am getting the following error using my previous curl and your new approach 

`  "value" : "Unhandled endpoint: \/session\/E17C3A78-4D64-4EAA-BC73-9FD9E81286D7\/uiaTarget\/0\/dragfromtoforduration -- http:\/\/localhost:8100\/ with parameters {\n    wildcards =     (\n        \"session\/E17C3A78-4D64-4EAA-BC73-9FD9E81286D7\/uiaTarget\/0\/dragfromtoforduration\"\n    );\n}",
  "sessionId" : "E17C3A78-4D64-4EAA-BC73-9FD9E81286D7",
  "status" : 1`

How did the previous query suddenly contain an unhandled endpoint? The last session it at least returned 0 and the event worked. adding your suggestion gives the same error. I had restarted WDA to make sure listening on localhost

**Comment by marekcirkos** [comment]
We changed endpoints to be more WD spec compliant try `/wda/dragfromtoforduration` instead

**Comment by jjacquet** [comment]
You the man @marekcirkos A few things to note things:

- Using the new `wda/dragfromtoforduration ` endpoint is functioning and replaces `/uiaTarget\/0\/dragfromtoforduration`
- Escaping the parameters works, is annoying, but to be expected when working with the cUrl 
- The previous syntax for coordinate parameters `"{fromX:0,fromY:0,toX:0,toY:0,duration:0.1}" ` can be used as a hack to send the view to the top regardless os position 

I started working with `openatx/facebook-wda` in python and its brilliant in some ways and painfully slower in others. Any suggestions before getting in too deep automating iOS in a bash script/curl? Is there a framework of choice? or does it come down to `cUrl`, `Appium`, and `openatx`? 

It would be great if there was some swift bindings that I could use purely in XCTest

Thanks again
