### ISSUE TITLE
Can I send arguments to app?

### ISSUE THREAD

**Issue by hepilt** [facebook/WebDriverAgent#499]
Hi!

I can't find any links to support, so asking here: can I send to my app arguments during launch using WDA?

BR, Hepilt.

**Comment by marekcirkos** [comment]
You do this by adding `desiredCapabilities` to session start. Eg.
```
desiredCapabilities: {
    'arguments' : ['arg']
    'environment': {'env0': 'value'}
}
```

**Comment by marekcirkos** [comment]
We probably should add this to docs

**Comment by hepilt** [comment]
I've used this parameter, but app didn't receive any parameters

```
{
  "deviceName": "Abstract_Device",
  "bundleId": "org.mobile.debug",
  "app": "/tmp/some.app",
  "automationName": "XCUITest",
  "environment": {
    "scenario": "demo"
  }
}
```

**Comment by marekcirkos** [comment]
That looks correct. How are you testing it?

**Comment by hepilt** [comment]
In test app i've got all params that were send to it in start

**Comment by hepilt** [comment]
@marekcirkos any ideas?

**Comment by marekcirkos** [comment]
Let me check that over the weekend.

**Comment by marekcirkos** [comment]
@hepilt Hey I checked it and it seems to work fine. How are you checking envs? Can you also paste whole session creation request?

**Comment by marekcirkos** [comment]
@hepilt ?
