### ISSUE TITLE
Document 'double-debug' in Xcode 7 

### ISSUE THREAD

**Issue by lawrencelomax** [facebook/WebDriverAgent#5]
One of the awesome things about WDA is that allows you to connect the Debugger to the running WebDriverAgent in the ```lldb``` command line/Xcode rather than some massive UIAutomation.js scaffolding. Documenting how to do this in the `README` and the Radar for the double-debug issue under Xcode 6.

**Comment by marekcirkos** [comment]
Closing as it will be part of https://github.com/facebook/WebDriverAgent/issues/5
