### ISSUE TITLE
homescreen will fail if SpringBoard not on the top activity

### ISSUE THREAD

**Issue by adolli** [facebook/WebDriverAgent#500]
I am running an app and the screen locked. When I request to homescreen, I mean press home to unlock, I got the following outputs.
```
{
  "value" : "Error Domain=com.facebook.WebDriverAgent Code=1 \"Timeout waiting until SpringBoard is visible\" UserInfo={NSLocalizedDescription=Timeout waiting until SpringBoard is visible}",
  "sessionId" : "F0724CF5-D93C-4F57-A689-16A6FB254B11",
  "status" : 13
}
```

In spite of this output, I think there is no problem when I press home to resume my running app.

**Comment by adolli** [comment]
By the way, request to homescreen's endpoint is /wda/homescreen. Maybe the wiki should be updated.

**Comment by marekcirkos** [comment]
What do you mean by locked screen?

**Comment by adolli** [comment]
I leave my iPhone idle with an app running. The screen turns dark and auto locked after 1 min. I do the following command twice and got an "Error message" above.
`curl -X POST $JSON_HEADER -d "" $DEVICE_URL/wda/homescreen`

**Comment by marekcirkos** [comment]
Yeah, we definitely, don't handle navigating to homescreen from locked view. 
Btw. Instead of waiting 1 min you could consider using `wda/deactivateApp`.

**Comment by adolli** [comment]
Waiting for 1 min is not my initial purpose. I'm using a ci-test system and it was not able to handle all situation normally now. So each time before I start to test, I wake up the iPhone and entering the home screen.
