### ISSUE TITLE
😃  app crash when inspector runs

### ISSUE THREAD

**Issue by xudafeng** [facebook/WebDriverAgent#501]
We got app crash in some apps, when request `/inspector`.

Break point to this line: 

https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/FBApplication.m#L44

``` objc
  FBApplication *application = [FBApplication appWithPID:activeApplicationElement.processIdentifier];
  NSAssert(nil != application, @"Active application instance is not expected to be equal to nil", nil);
  [application query];

  [application resolve];  // Crashed from here, how this method worked? Can you tell me?


  return application;
```

**Comment by xudafeng** [comment]
link https://github.com/facebook/WebDriverAgent/issues/340

**Comment by xudafeng** [comment]
https://github.com/facebook/WebDriverAgent/issues/382

**Comment by marekcirkos** [comment]
`resolve` method will trigger accessibility engine to collect data about views. As I mentioned in issues you linked this is most likely application issue. It is highly probable it will also crash when accessibility is turned on. Altho accessibility does a bit more for testing.

If you cannot find problem with the app, it might be XCUITest/Accessbility problem and you should raise a ticket with Apple. Until you give me concrete example I cannot really help you here. I am sorry.
