### ISSUE TITLE
How delete cookies from real iOS Device ?

### ISSUE THREAD

**Issue by shapovalovei** [facebook/WebDriverAgent#502]
I use Appium, Appium use WebDriverAgent. 
In WebDriverAgent documentation I found endpoints for cookies 

How delete cookies from real iOS Device ?

**Comment by marekcirkos** [comment]
We do not handle cookies at all. Can you point me that endpoint?

**Comment by shapovalovei** [comment]
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/endpoints.md

<img width="1079" alt="screen shot 2017-03-06 at 15 00 34" src="https://cloud.githubusercontent.com/assets/8914951/23610995/b8e03e06-027d-11e7-922b-30af7b4b44f7.png">


What I must do ? How me clear session on real ios device ?

**Comment by shapovalovei** [comment]
any comment about that ?

**Comment by marekcirkos** [comment]
Sorry I missed your comment. This is Appium endpoint list WDA does not handle cookies. I would ask them how they map them. Maybe they use imobiledevice.

**Comment by shapovalovei** [comment]
@marekcirkos Thanks, wait for you answer

**Comment by NickAb** [comment]
@shapovalovei, Appium uses Safari Remote Debugger, see following relevant lines of code:

- https://github.com/appium/appium-xcuitest-driver/blob/ce8785daea4e72859eb7d4f4fb69b193bb1857d3/lib/commands/cookies.js#L23
- https://github.com/appium/appium-remote-debugger/blob/ff7034203b637078e7ae30c3a0f1ce20a7ad3fbf/lib/remote-debugger.js#L679
