### ISSUE TITLE
Why do “name attribute” of the element has some space in front 

### ISSUE THREAD

**Issue by lyt19871224** [facebook/WebDriverAgent#503]
hi,

some element's name attribute contains space，like “name=  超值折扣  50家”  ,four spaces in front of 超值折扣 
the commands：
curl -X POST $JSON_HEADER -d "{\"using\":\"link text\",\"value\":\"name=  超值折扣  50家\"}"  $DEVICE_URL/session/$SESSION_ID/elements

![2 pic](https://cloud.githubusercontent.com/assets/7929135/23601489/a73c74ae-0286-11e7-841a-ba2642d08252.jpg)

I don‘t know why ，my react native code  have not set any space，maybe related to the icon？

**Comment by marekcirkos** [comment]
Yep, It can be either icon or ReactNative collecting accessibilityLabel from it's subviews. As far as I remember ReactNative will set view's accessibility label as space joined accessibility labels of it's descendants.

**Comment by marekcirkos** [comment]
Closing as this is not WDA's issue
