### ISSUE TITLE
recognize elements more sophisticated

### ISSUE THREAD

**Issue by lyt19871224** [facebook/WebDriverAgent#504]
![1 pic_hd](https://cloud.githubusercontent.com/assets/7929135/23602140/dea43618-0289-11e7-9a73-e66f7e1e92ac.jpg)
it‘s a react native page.  the view contains four parts : the icon ,the超值折扣，the 50家,the 》image

But,webdriveragent recognize it like the illustrations above.
Whether webdriveragent can recognize the four element separately.

**Comment by lyt19871224** [comment]
![2606bc65c1e118a50ad65fa54d14be8b](https://cloud.githubusercontent.com/assets/7929135/23602495/cca8e204-028b-11e7-99e5-a767698b6951.jpg)
xcode accessibility can get it .

**Comment by marekcirkos** [comment]
WDA indirectly uses accessibility. However from you screenshot you can see that element you pointed has more detailed subelements (as accessibility can see it)? Unless I didn't get your point?

**Comment by lyt19871224** [comment]
I mean that  why the wda get the "超值折扣 50家" ， I want "超值折扣"  or “50家” , not the "超值折扣  50家" .

**Comment by lyt19871224** [comment]
wda only provider me the "超值折扣 50家" ,not  "超值折扣".   
curl -X POST $JSON_HEADER -d "{\"using\":\"link text\",\"value\":\"name=  超值折扣\"}"  $DEVICE_URL/session/$SESSION_ID/elements

result:
{
  "value" : [

  ],
  "sessionId" : "3D745EAD-E69B-4A04-B2E8-01C4F7EF082C",
  "status" : 0
}

**Comment by lyt19871224** [comment]
My goal is to execute the command successfully:
curl -X POST $JSON_HEADER -d "{"using":"link text","value":"name= 超值折扣"}" $DEVICE_URL/session/$SESSION_ID/elements

now exits two problems 1.the space in front 2.the level .
actually if I can get the last RCTView of "超值折扣"  which I think it  has no space , all of them will be solved.  (as you said in https://github.com/facebook/WebDriverAgent/issues/503)

**Comment by mykola-mokhnach** [comment]
@lyt19871224 Try to use location by predicate. It is still fast and allows to perform lookup by partial value, for example:

```
name contains[c] '超值折扣'
```

**Comment by marekcirkos** [comment]
Contains will not work for him as he he has bunch of elements containing '超值折扣'.
If you do exact match with space it should work. 
However I would suggest explicitly setting testID with ReactNative and using that instead default generated ones.

**Comment by lyt19871224** [comment]
Hi, the wda can recognize testId .  When setting testId, must  set  component that rn provide.  If your component  is  a  custom   component,please let the testId attribute can be  passed to the component which rn provide.

eg.
xxx.js
<customerbutton testID={'the_name_of_mybutton'}><Text></>

customerbutton.js
<TouchableOpacity    testID={this.props.testID} >

TouchableOpacity is the component that rn provide to us. customerbutton is our customer button. 
If you only set Text testid, it will not work.   should set testid in TouchableOpacity.



oh,my poor English.Wish to express clearly .
so,I think this issue can be closed.  thanks @marekcirkos  @mykola-mokhnach

**Comment by lyt19871224** [comment]
`xxx.js
<customerbutton testID={'the_name_of_mybutton'}>
   <Text>something </Text>
</>

customerbutton.js
<TouchableOpacity testID={this.props.testID}> ....
`

**Comment by lyt19871224** [comment]
customerbutton.js
`< TouchableOpacity   testID={this.props.testID} ...`
