### ISSUE TITLE
Click sometimes consumes very high memory on macs running with simulator

### ISSUE THREAD

**Issue by yaphatak** [facebook/WebDriverAgent#505]
@marekcirkos have you see this when testing internally ?

**Comment by marekcirkos** [comment]
@yaphatak Nope. Is WDA or some other process? It might be worth investigating

**Comment by yaphatak** [comment]
I am running on `10.2.1`. I see it goes [here](https://github.com/facebook/WebDriverAgent/blob/6a8281374f5976517bde5f54fb5291c231d7e452/WebDriverAgentLib/Categories/XCUIElement%2BFBTap.m#L56-L61) and then memory of AUT shoots to almost 5-6 GB. I guess nothing `WDA` can do here. But I just wanted to understand if you guys see this FB or other apps testing.
