### ISSUE TITLE
openURL deprecated

### ISSUE THREAD

**Issue by pavanbachu0604** [facebook/WebDriverAgent#506]
This issue is continuation to the Issue #7952 ` https://github.com/appium/appium/issues/7952` in Appium.

@marekcirkos I tried changing the Deployment to iOS 10.3 and I am facing above issue.

<img width="1391" alt="screen shot 2017-03-07 at 7 07 34 am" src="https://cloud.githubusercontent.com/assets/21222084/23655821/c6ab566a-0304-11e7-9c7c-cb486ba3d79f.png">

**Comment by marekcirkos** [comment]
It should not be a problem with new beta
