### ISSUE TITLE
How do I set a value of a toggle switch on an iOS sim?

### ISSUE THREAD

**Issue by jjacquet** [facebook/WebDriverAgent#508]
I want to turn off **Auto-Correction** in **General>Keyboards** on an iOS simulator. Clicking into it with cUrl is not a problem, but how do I pass the value `0` to the on/off switch?

`
curl -X POST $JSON_HEADER -d "{\"using\":\"link text\",\"value\":\"label=Auto-Capitalization\"}" $DEVICE_URL/session/$SESSION_ID/elements 
`

`
{
  "value": [
    {
      "ELEMENT": "5EB2F7C1-807D-4A7E-8401-F6F6EB87306A",
      "type": "XCUIElementTypeStaticText",
      "label": "Auto-Capitalization"
    },
    {
      "ELEMENT": "9146ED0C-0A52-4A45-9786-03699C57939C",
      "type": "XCUIElementTypeSwitch",
      "label": "Auto-Capitalization"
    },
    {
      "ELEMENT": "07ABFAB8-CB33-4868-B43F-1EB7DB60F605",
      "type": "XCUIElementTypeCell",
      "label": "Auto-Capitalization"
    }
  ],
  "sessionId": "63DB31AA-58D2-4341-824D-C77866C40622",
  "status": 0
}
`

I don't see a value in the query that I can interact with either.

**Comment by jjacquet** [comment]
I ended using `XCUIElementTypeSwitch ` with a `click` endpoint and that worked, but I would still be interested if there was an absolute way to pass a value.

**Comment by marekcirkos** [comment]
Probably we need to handle that explicitly. I'll have a look at that as it sound very useful common use case. Thanks for reporting. 

Also feel free to pop a PR for that :)
