### ISSUE TITLE
duplicate declaration of method 'pressForDuration:thenDragToCoordinate:

### ISSUE THREAD

**Issue by ashisht99x** [facebook/WebDriverAgent#509]
I get this compile time error while running the command: 

**xcodebuild -project WebDriverAgent.xcodeproj \
           -scheme WebDriverAgentRunner \
           -destination 'platform=iOS Simulator,name=iPhone 7' \
           test**

Any Help ?

**Comment by marekcirkos** [comment]
Which Xcode do you use?

**Comment by ashisht99x** [comment]
I am using Xcode 8.0

**Comment by marekcirkos** [comment]
Can you try 8.2.1?

**Comment by ashisht99x** [comment]
Tried with Xcode 8.3 Beta. It works. Thanks a lot :)

**Comment by narendra-chandratre** [comment]
Yes, Its works for me too (y)
