### ISSUE TITLE
doesn't type anything in TextField when a numeric only keyboard shown

### ISSUE THREAD

**Issue by adfghzhang** [facebook/WebDriverAgent#510]
![qq 20170308174610](https://cloud.githubusercontent.com/assets/20984179/23777764/c69e7caa-0571-11e7-8135-cc737f89057d.png)

{"using":"xpath","value":"/XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeTextField[1]"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"F6AC3976-FF6C-4E18-848E-0BD27A008EB2","type":"XCUIElementTypeTextField","label":""},"sessionId":"F16D9545-46D7-4692-93E2-79EC6E80898D","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"F6AC3976-FF6C-4E18-848E-0BD27A008EB2","type":"XCUIElementTypeTextField","label":""}
[HTTP] <-- POST /wd/hub/session/49f130d0-53b1-4d48-8783-0e3293d2a08c/element 200 452 ms - 167
[HTTP] --> POST /wd/hub/session/49f130d0-53b1-4d48-8783-0e3293d2a08c/element/F6AC3976-FF6C-4E18-848E-0BD27A008EB2/value {"id":"F6AC3976-FF6C-4E18-848E-0BD27A008EB2","value":["18696789382"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["18696789382"],"F6AC3976-FF6C-4E18-848E-0BD27A008EB2","49f130d0-53b1-4d48-8783-0e3293d2a08c"]
[XCUITest] Executing command 'setValue'
[JSONWP Proxy] Proxying [POST /element/F6AC3976-FF6C-4E18-848E-0BD27A008EB2/value] to [POST http://localhost:8100/session/F16D9545-46D7-4692-93E2-79EC6E80898D/element/F6AC3976-FF6C-4E18-848E-0BD27A008EB2/value] with body: {"value":["1","8","6","9","6","7","8","9","3","8","2"]}
[JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}","sessionId":"F16D9545-46D7-4692-93E2-79EC6E80898D","status":13}
[JSONWP Proxy] Proxying [GET /element/F6AC3976-FF6C-4E18-848E-0BD27A008EB2/attribute/type] to [GET http://localhost:8100/session/F16D9545-46D7-4692-93E2-79EC6E80898D/element/F6AC3976-FF6C-4E18-848E-0BD27A008EB2/attribute/type] with no body
[JSONWP Proxy] Got response with status 200: "{\n "value" : "XCUIElementTypeTextField",\n "sessionId" : "F16D9545-46D7-4692-93E2-79EC6E80898D",\n "status" : 0\n}"
[XCUITest] Cannot type in the text field because of UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}.

**Comment by ilk33r** [comment]
0   CoreFoundation                      0x000000010d226b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010cc8b141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d296134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010d1ad840 ___forwarding___ + 1024
	4   CoreFoundation                      0x000000010d1ad3b8 _CF_forwarding_prep_0 + 120
	5   WebDriverAgentLib                   0x000000011e1c903e __29+[FBKeyboard typeText:error:]_block_invoke + 126
	6   WebDriverAgentLib                   0x000000011e1cda65 +[FBRunLoopSpinner spinUntilCompletion:] + 149
	7   WebDriverAgentLib                   0x000000011e1c8e44 +[FBKeyboard typeText:error:] + 436
	8   WebDriverAgentLib                   0x000000011e1d762b -[XCUIElement(FBTyping) fb_typeText:error:] + 155
	9   WebDriverAgentLib                   0x000000011e1e2ef2 +[FBElementCommands handleSetValue:] + 802
	10  WebDriverAgentLib                   0x000000011e1ccb13 -[FBRoute_TargetAction mountRequest:intoResponse:] + 179
	11  WebDriverAgentLib                   0x000000011e1c4134 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548
	12  RoutingHTTPServer                   0x000000011e27bc18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
	13  RoutingHTTPServer                   0x000000011e27c4fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47

**Comment by marekcirkos** [comment]
Can you please test latest revision?

**Comment by praveen-4705** [comment]
I am still unable to enter anything when a numeric only keyboard shown

As of now I am entering the data by clicking on the Number in the Numeric Keyboard
