### ISSUE TITLE
Appium 1.6.4-beta iOS: GetScreenshot() error base-64

### ISSUE THREAD

**Issue by omsting** [facebook/WebDriverAgent#514]
## The problem

Often on iOS I get an error when I take a screenshot with Driver.GetScreenshot() or Driver.TakeScreenshot(). You can find my logs (Appium and Nunit) below in Gist, you'll see that I get an error when the screenshot is basically empty. Sometimes it works for the same test on the same device. Please tell me if you need more information.

## Environment

* Appium version: 1.6.4 beta
* WebDriver version: 3.3.0
* Desktop OS/version used to run Appium: macOS Sierra 10.12.3
* Node.js version: 3.10.10
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real device

## Link to logs

https://gist.github.com/omsting/85ac9b3d3d7e0c01ce888fc60e5b39fe#file-gistfile1-txt

**Comment by marekcirkos** [comment]
It looks like we respond with empty value. Does it fail in any particular cases?

**Comment by omsting** [comment]
Yes, as you can see in the nunit test, we get an error at GetScreenshot(), because the input is not a valid Base-64 string. And it should not return an empty value, but I don't know why it does. It works sometimes, but fails most of the time. We have around 1/3 of the tests on iOS affected by this problem and it works perfectly on Android.

**Comment by omsting** [comment]
After further testing, it appears that my screenshotting problem only happens when I run our tests on two different devices at the same time. 

Here is the commands I use to launch Appium:
/usr/local/bin/appium -p 4730 -bp 2270 --tmp /tmp/dir1 --webdriveragent-port 27730
/usr/local/bin/appium -p 4731 -bp 2271 --tmp /tmp/dir2 --webdriveragent-port 27731

**Comment by marekcirkos** [comment]
Wow, that sounds insane. Possible this is TestManager getting lost :/

**Comment by marekcirkos** [comment]
Closing as there is not much we can do
