### ISSUE TITLE
device width and height

### ISSUE THREAD

**Issue by VasilijSviridov** [facebook/WebDriverAgent#515]
Hi,

Quick one, how do I get device width and height ?

Cheers

**Comment by marekcirkos** [comment]
You mean physical ;)? If you query element type application it's frame should represent screen size.

**Comment by VasilijSviridov** [comment]
Got it, 
 "rect" : {
        "y" : 0,
        "x" : 0,
        "width" : 320,
        "height" : 568
      },
Cheers
