### ISSUE TITLE
Why UI Testing Fail When A XCTest(unit test) is running in another project?

### ISSUE THREAD

**Issue by easingboy** [facebook/WebDriverAgent#516]
when i only run webdriveragent runner, it works well.
but if i lauch another xctest(unit test) at the same time,  WDA runner does not work.
such as:

     1. visitor  localhost:8100:inspector;  error log are : 
> 2017-03-20 19:42:04.230537 XCTRunner[6648:2638287] Enqueue Failure: UI Testing Failure - Failure to determine system application: (null) <unknown> 0 1

> 2017-03-20 19:42:19.296064 XCTRunner[6648:2638287] Enqueue Failure: UI Testing Failure - Failed to get attributes within 15.0s: (
    1102

     2. when excute lauch app;
2.1 error log are:

> t =   304.42s     Launch com.xxxxx.demoApp
    t =   319.49s         Terminate <XCUIApplicationProcess: 0x1702a4f80 com.xxxxx.demoApp (341)>
2017-03-20 21:35:32.637210 XCTRunner[360:22346] Enqueue Failure: UI Testing Failure - App state for <XCUIApplicationProcess: 0x1702a4f80 com.xxxxx.demoApp (341)> is XCApplicationStateRunningInactive (2), still not XCApplicationStateNotRunning (1) <unknown> 0 1
    t =   394.86s         Waiting for accessibility to load
2017-03-20 21:36:32.922250 XCTRunner[360:22346] Enqueue Failure: UI Testing Failure - App accessibility isn't loaded <unknown> 0 1
2017-03-20 21:37:33.228715 XCTRunner[360:22346] Enqueue Failure: UI Testing Failure - '<XCUIApplicationImpl: 0x17023e920 com.tencent.imsdk.JKDemo>' App state is still not running active, state = XCApplicationStateNotRunning <unknown> 0 1

    
2.2 when only run WDA Runner ,the right log are:

> t =    96.24s     Launch com.xxxxx.demoApp
    t =    96.52s         Terminate <XCUIApplicationProcess: 0x1700bce60 com.xxxxx.demoApp (341)>
    t =    96.88s         Waiting for accessibility to load
    t =    97.27s     Find the Application "com.xxxxx.demoApp" 0x1700bc8c0
    t =    97.27s         Snapshot accessibility hierarchy for com.xxxxx.demoApp
    t =    97.93s     Find the Application "com.xxxxx.demoApp" 0x1700bc8c0
    t =    97.93s         Use cached accessibility hierarchy for com.xxxxx.demoApp
    t =    97.96s     Find the Application "com.xxxxx.demoApp" 0x1700bc8c0
    t =    97.96s         Use cached accessibility hierarchy for com.xxxxx.demoApp

Why UI Testing Fail When A XCTest(unit test) is running in another project?
is there any solution to this problem?

**Comment by marekcirkos** [comment]
All XCTests use test manager daemon so I guess there is some weird bug when test sessions are confused. Does it happen when you ran other UITests?

**Comment by marekcirkos** [comment]
@easingboy ping

**Comment by easingboy** [comment]
"Does it happen when you ran other UITests?"

it happen the same when run other UITests without WDA.
so it seems it don't matter with WDA.

**Comment by marekcirkos** [comment]
I would suggest opening issue with Apple then
