### ISSUE TITLE
TouchableOpacity does not support the testID attribute？

### ISSUE THREAD

**Issue by lyt19871224** [facebook/WebDriverAgent#517]
Hi，when I set testID to the component,some rn component seems not support.
eg.
`<TouchableOpacity  testID={'citylist'}>{this.props.some}</TouchableOpacity>`
 it won't work,wda can't get one element called citylist.

but,TouchableHighlight can .  why?

**Comment by marekcirkos** [comment]
You should ask that question on ReactNative repo. Unfortunately I cannot help you here.
