### ISSUE TITLE
 A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.2. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.

### ISSUE THREAD

**Issue by srinidhipatel** [facebook/WebDriverAgent#518]
History:
1. Installed appium 1.6.0 beta
2. Xcode 8.2
3. bootstrap.sh is not running as expected
 xxx-MacBook-Pro:WebDriverAgent xxx$ ./Scripts/bootstrap.sh -d
Fetching dependencies
xxx-MacBook-Pro:WebDriverAgent xxx$ 

inside myconfig.xcconfig file i have added
DEVELOPMENT_TEAM = <Team ID>
CODE_SIGN_IDENTITY = iPhone Developer 

**I looked many threads nothing was working out for me.. Please suggest me how to get rid of this**

Code:
capabilities.setCapability("udid","<UDID of my phone>");
			capabilities.setCapability("platformName","ios");
			capabilities.setCapability("deviceName","iPhone");
		capabilities.setCapability("xcodeConfigFile","/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/myconfig.xcconfig");
						capabilities.setCapability("bundleId","com.xxx.yyy");
			capabilities.setCapability("newCommandTimeout", 60 * 5);
			driver = new IOSDriver<WebElement>(new URL("http://"+System.getProperty("AppiumServerIp")+"/wd/hub"), capabilities);
		}

Im getting error:

[Appium] Welcome to Appium v1.6.0-beta1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":300,"bundleId":"com.linkdokter.halodoc","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/myconfig.xcconfig","udid":"879fda7542f4386931430f9c01addf15050373a4","platformName":"iOS","deviceName":"Srinidhi’s iPhone"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"newCommandTimeout":300,"bundleId":"com.linkdokter.halodoc","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/myconfig.xcconfig","udid":"879fda7542f4386931430f9c01addf15050373a4","platformName":"iOS","deviceName":"Srinidhi’s iPhone"},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1490181265312 (16:44:25 GMT+0530 (IST))
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   newCommandTimeout: 300
[Appium]   bundleId: 'com.linkdokter.halodoc'
[Appium]   xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/myconfig.xcconfig'
[Appium]   udid: '879fda7542f4386931430f9c01addf15050373a4'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'Srinidhi’s iPhone'
[debug] [iOS] IosDriver version: 1.18.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: xcodeConfigFile.
[BaseDriver] Session created with session id: e4e68963-ab20-45f8-b68d-4e50cb60c2c3
[debug] [iOS] Xcode version set to 8.2
[iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.2. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (../../lib/driver.js:131:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 { SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.2. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (../../lib/driver.js:131:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) jsonwpCode: 33 }
[HTTP] <-- POST /wd/hub/session 500 99 ms - 243

**Comment by marekcirkos** [comment]
This is clearly not WDA issue rather Appium. However did you try using "automationName": "XCUITest" instead as it asked?

**Comment by imurchie** [comment]
@srinidhipatel Please search the [Appium Issues](https://github.com/appium/appium/issues). You might also want to upgrade to a more recent version of Appium.

@marekcirkos feel free to close this.

**Comment by chinnarii** [comment]
> History:
> 
> 1. Installed appium 1.6.0 beta
> 2. Xcode 8.2
> 3. bootstrap.sh is not running as expected
>    xxx-MacBook-Pro:WebDriverAgent xxx$ ./Scripts/bootstrap.sh -d
>    Fetching dependencies
>    xxx-MacBook-Pro:WebDriverAgent xxx$
> 
> inside myconfig.xcconfig file i have added
> DEVELOPMENT_TEAM = 
> CODE_SIGN_IDENTITY = iPhone Developer
> 
> **I looked many threads nothing was working out for me.. Please suggest me how to get rid of this**
> 
> Code:
> capabilities.setCapability("udid","");
> capabilities.setCapability("platformName","ios");
> capabilities.setCapability("deviceName","iPhone");
> capabilities.setCapability("xcodeConfigFile","/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/myconfig.xcconfig");
> capabilities.setCapability("bundleId","com.xxx.yyy");
> capabilities.setCapability("newCommandTimeout", 60 * 5);
> driver = new IOSDriver(new URL("http://"+System.getProperty("AppiumServerIp")+"/wd/hub"), capabilities);
> }
> 
> Im getting error:
> 
> [Appium] Welcome to Appium v1.6.0-beta1
> [Appium] Appium REST http interface listener started on 0.0.0.0:4723
> [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":300,"bundleId":"com.linkdokter.halodoc","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/myconfig.xcconfig","udid":"879fda7542f4386931430f9c01addf15050373a4","platformName":"iOS","deviceName":"Srinidhi’s iPhone"}}
> [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"newCommandTimeout":300,"bundleId":"com.linkdokter.halodoc","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/myconfig.xcconfig","udid":"879fda7542f4386931430f9c01addf15050373a4","platformName":"iOS","deviceName":"Srinidhi’s iPhone"},null,null,null,null]
> [debug] [BaseDriver] Event 'newSessionRequested' logged at 1490181265312 (16:44:25 GMT+0530 (IST))
> [Appium] Creating new IosDriver session
> [Appium] Capabilities:
> [Appium] newCommandTimeout: 300
> [Appium] bundleId: 'com.linkdokter.halodoc'
> [Appium] xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/myconfig.xcconfig'
> [Appium] udid: '879fda7542f4386931430f9c01addf15050373a4'
> [Appium] platformName: 'iOS'
> [Appium] deviceName: 'Srinidhi’s iPhone'
> [debug] [iOS] IosDriver version: 1.18.0
> [BaseDriver] The following capabilities were provided, but are not recognized by appium: xcodeConfigFile.
> [BaseDriver] Session created with session id: e4e68963-ab20-45f8-b68d-4e50cb60c2c3
> [debug] [iOS] Xcode version set to 8.2
> [iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.2. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
> at IosDriver.createSession$ (../../lib/driver.js:131:28)
> at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
> at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
> at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
> at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> { SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.2. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
> at IosDriver.createSession$ (../../lib/driver.js:131:28)
> at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
> at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
> at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js💯21)
> at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) jsonwpCode: 33 }
> [HTTP] <-- POST /wd/hub/session 500 99 ms - 243

Hi,
I'm facing the same issue, did u get any solution for this?

Please help

**Comment by imurchie** [comment]
The solution is in the error message. Use the `automationName` desired capability and set it to `"XCUITest"`.
