### ISSUE TITLE
isVisible always returns true

### ISSUE THREAD

**Issue by imurchie** [facebook/WebDriverAgent#524]
"Always" might be hyperbole. But since https://github.com/facebook/WebDriverAgent/commit/fa1a7c5e575c54319593d0b5e033e59ccf34dfbc elements that are not visible are marked as visible, and scrolling to visible does not work (presumably because things are already "visible").

**Comment by imurchie** [comment]
I should add that this is tested looking at a table cell within a table view.

**Comment by marekcirkos** [comment]
@imurchie There is one fix waiting to land. Tho that would fix landscape issues. If you could provide PR with sample, I would be happy to work on that. 

If that is particular problematic you can use `shouldUseTestManagerForVisibilityDetection` in capabilities to switch to old behaviour.

**Comment by marekcirkos** [comment]
@imurchie Could supply more info? Inspector screenshot or something I can have a look at?

**Comment by imurchie** [comment]
This appears to be fixed now.

**Comment by adudurant** [comment]
@imurchie  Hi，I have the same  problem。So，it's very kind of you to tell me the way to  modify the code,for I have found nothing about the issue in the commits.Thanks!
