### ISSUE TITLE
Unhandled Endpoint when getting page source

### ISSUE THREAD

**Issue by da00428327** [facebook/WebDriverAgent#526]
When getting the page Source using driver.getPageSource() in Appium 1.6.3, getting as Unhandled Endpoint.

Appium Server log:
[JSONWP Proxy] Proxying [POST /source] to [POST http://localhost:8100/session/D731F61E-1F5E-4DFB-BA22-DB1A525314AC/source] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"sessionId\" : \"D731F61E-1F5E-4DFB-BA22-DB1A525314AC\",\n  \"value\" : \"Unhandled endpoint: \\/session\\/D731F61E-1F5E-4DFB-BA22-DB1A525314AC\\/source -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/D731F61E-1F5E-4DFB-BA22-DB1A525314AC\\/source\\\"\\n    );\\n}\",\n  \"status\" : 1\n}"
[HTTP]

When hit the POST request from the log "http://localhost:8100/session/D731F61E-1F5E-4DFB-BA22-DB1A525314AC/source", observed that the XML  is not properly formatted, The end tags are not closed.

![image](https://cloud.githubusercontent.com/assets/26737911/24402843/f1a88426-13d7-11e7-8c76-6e7cf7ccc282.png)

**Comment by mykola-mokhnach** [comment]
Use Appium 1.6.4-beta instead. 1.6.3 works with older WDA, which returns JSON instead of XML at /source endpoint.

**Comment by marekcirkos** [comment]
Can we close it?

**Comment by mykola-mokhnach** [comment]
At least the issue has nothing to do with WDA itself.

**Comment by da00428327** [comment]
Yes please, the issue is solved.
