### ISSUE TITLE
xcode 8.3 build error

### ISSUE THREAD

**Issue by lujun-wuhan** [facebook/WebDriverAgent#527]
While building module 'XCTest' imported from /Users/devicepass/stf/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m:10:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCTest.h:57:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIDevice.h:50:22: error: 'XCUISiriService' is partial: introduced in iOS 10.3 [-Werror,-Wunguarded-availability]
@property (readonly) XCUISiriService *siriService NS_AVAILABLE_IOS(10_3);
                     ^
While building module 'XCTest' imported from /Users/devicepass/stf/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m:10:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCTest.h:57:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIDevice.h:6:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUISiriService.h:17:12: note: 'XCUISiriService' has been explicitly marked partial here
@interface XCUISiriService : NSObject
           ^
While building module 'XCTest' imported from /Users/devicepass/stf/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m:10:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCTest.h:57:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIDevice.h:50:22: note: explicitly redeclare 'XCUISiriService' to silence this warning
@property (readonly) XCUISiriService *siriService NS_AVAILABLE_IOS(10_3);
                     ^
1 error generated.
/Users/devicepass/stf/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m:10:9: fatal error: could not build module 'XCTest'
#import <XCTest/XCTest.h>
 ~~~~~~~^
2 errors generated.

**Comment by chenqb** [comment]
the same issue like u , hope for updating

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/pull/525

**Comment by patchthecode** [comment]
I am getting a `RoutingConnection.h` not found issue on build

**Comment by pb-z** [comment]
@patchthecode If you change the Deployment Target to 10.3 on WebDriverAgentLib then you are doing wrong. 
[Here](https://github.com/facebook/WebDriverAgent/pull/525/commits/17d9b6a75f65f755c792ffbec6ede4475d85b57e) is the fix

**Comment by imurchie** [comment]
The latest release ought to fix this error and allow testing in 10.3

**Comment by patchthecode** [comment]
Thanks!

**Comment by davidschwab** [comment]
@imurchie : when is this scheduled? I just downloaded the latest Appium 1.6.4-beta.2, but still had to manually update the below file to get around the XCUISiriService build warning/error:

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig

**Comment by imurchie** [comment]
Can you provide a link to a [gist](https://gist.github.com) of the logs?

**Comment by davidschwab** [comment]
@imurchie : here you go (output of npm install and cat of ProjectSettings.xcconfig):
https://gist.github.com/davidschwab/6c58d81527588264c739fe14b44ec00e

**Comment by marekcirkos** [comment]
This has been resolve by @imurchie I believe?

**Comment by imurchie** [comment]
Yes.

**Comment by sixleaves** [comment]
i have the same error!i hasn't resolve

**Comment by sixleaves** [comment]
xcode8.3.3 cannot build

**Comment by imurchie** [comment]
@sixleaves More information is necessary. Versions, logs, etc. "Same error" is rarely diagnostically relevant.
