### ISSUE TITLE
Scroll doesn't work. WebDriver - unrecognized selector sent to instance

### ISSUE THREAD

**Issue by garkinv** [facebook/WebDriverAgent#530]
I have problems with scrolling on iOS real device
Environment:

- iOS 10.2.1
- Appium 1.6.1
- WDA 2.2.0
- xCode: 8.3
- OSX: 10.12.4

my code is:
```
HashMap<String, Object> elementDirection = new HashMap<String, Object>();
elementDirection.put("direction", "down");
elementDirection.put("location", ((RemoteWebElement) driver.findElementByName(text)).getId());
driver.executeScript("mobile: scroll", elementDirection); <---- crash is here
```

Appium log is here: [appium log](https://gist.github.com/garkinv/c26861f730b067cb75b82230337fa4de)
WDA exception in IDEA: [wda exception](https://gist.github.com/garkinv/320bd6220b588699f8c10fccc28746cb)

Additional info:
It worked before but then I tried to update to appium 1.6.4-beta and then back to 1.6.1
Sign WDA again and everything is ok. The rest of commands are working except scroll.

Please suggest something!

**Comment by mykola-mokhnach** [comment]
It will not work in Appium 1.6.1, since it does not contain all the necessary patches required by Xcode 8.3. You must use the recent beta
