### ISSUE TITLE
installing dependency failed, needs help....

### ISSUE THREAD

**Issue by sagata** [facebook/WebDriverAgent#531]
after running the command ./Script/bootstrap.sh   there is a warning, it seems the web-driver-inspector install not successfuly
and I build this project in Xcode, it happend a buildtime error said 'RoutingHTTPServer/RoutingConnection.h' file not found.  
anybody can help me ?

`npm WARN web-driver-inspector@1.0.0 No repository field.
Validating Inspector
Launching Flow server for /Users/sagata/Desktop/WebDriverAgent/Inspector
Spawned flow server (pid=1569)
Logs will go to /private/tmp/flow/zSUserszSsagatazSDesktopzSWebDriverAgentzSInspector.log
No errors!
Building Inspector...

> web-driver-inspector@1.0.0 build /Users/sagata/Desktop/WebDriverAgent/Inspector
> webpack --progress --colors

Hash: 322d2661fd8440bc9e7f  
Version: webpack 1.14.0
Time: 5429ms
       Asset    Size  Chunks             Chunk Names
inspector.js  753 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 183 hidden modules
Done
`

**Comment by mykola-mokhnach** [comment]
Execute bootstrap.sh with **-d** option first
