### ISSUE TITLE
localhost:8100/inspector is not working

### ISSUE THREAD

**Issue by prudhvialahari** [facebook/WebDriverAgent#537]
The error is shown in the screen shot

![issue](https://cloud.githubusercontent.com/assets/19347407/24644866/51cc3d9c-1933-11e7-821d-ac90b84e48ba.PNG)

But I'm able to get the source as shown the image

![issuesource](https://cloud.githubusercontent.com/assets/19347407/24645073/41785be6-1934-11e7-8cd7-d278280cb8f1.PNG)

System configuration:
Appium: 1.6.3
Xcode : 8.2.1
iOS simulator: 10.2
Using XCIUTest for automation

Please look into the issue.

**Comment by marekcirkos** [comment]
Did you run bootstrap script? It looks like code for inspector is missing

**Comment by prudhvialahari** [comment]
Yes, I ran "sh ./Scripts/bootstrap.sh -d"

**Comment by marekcirkos** [comment]
That will only fetch dependencies, but will not build inspector. Run it without any param, it will do both.

**Comment by prudhvialahari** [comment]
This the error when I try to do it without param

![issueinspector](https://cloud.githubusercontent.com/assets/19347407/24654839/224193c6-1959-11e7-9264-89561946939f.PNG)

**Comment by prudhvialahari** [comment]
I tried to pull WebDriverAgent manually and replaced existing WDA with the one I have pulled. After executing bootstrap there were no errors as such mentioned above. But now the error with inspector is something like this,

![issueinspector2](https://cloud.githubusercontent.com/assets/19347407/24655980/2c595fc4-195e-11e7-8c98-3dc79bfddd0c.PNG)

I think this is the same error as stated at the beginning of the issue.

npm v4.0.5
node v7.4.0

**Comment by marekcirkos** [comment]
This should be fixed, can you confirm?

**Comment by prudhvialahari** [comment]
Not working yet. When I try to run "sh ./ Scripts/bootstrap.sh" then it throws an error at app.js... After then I tried to access inspector then there was a blank screen and as usually​ localhost:8100/source works.

**Comment by prudhvialahari** [comment]
Am I missing some system configuration for setting up the inspector? 
What are the other ways to inspect through WDA?

**Comment by marekcirkos** [comment]
The app.js is the same you posted above or different?

**Comment by prudhvialahari** [comment]
Same..

**Comment by marekcirkos** [comment]
Make sure to try WDA independently. I have seen many issues with inspector when WDA in embedded in Appium.

**Comment by marekcirkos** [comment]
Can you try:
- removing node_modules in inspector folder?
- updating npm and node?

**Comment by prudhvialahari** [comment]
As you suggested, I have removed node_modules from inspector folder and updated node to 7.8.0 and npm to 4.2.0. bootstrap throws the same error(app.js) and the inspector screen is blank.

**Comment by marekcirkos** [comment]
Can you try fetching WDA independently and not nesting in Appium. Does the error still exists for you?

**Comment by Schnutzel** [comment]
Try to move the WebDriverAgent directory to a different directory, run the scripts, and then move it back. Something like this:

```
mv /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent ~/WebDriverAgent
cd ~/WebDriverAgent
sh Scripts/bootstrap.sh
mv ~/WebDriverAgent /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
```

**Comment by prudhvialahari** [comment]
Thanks guys, it works now.
