### ISSUE TITLE
iOS 10.3 real device: "Early unexpected exit, operation never finished bootstrapping"

### ISSUE THREAD

**Issue by imurchie** [facebook/WebDriverAgent#540]
With the update to Xcode 8.3 and iOS 10.3/10.3.1 seems to break real device support. The app is buildable and gets installed on the device (in this case, an iPhone 6s with iOS 10.3.1) but it immediately goes terminates (at least, the logs say it terminates, but the app appears to still be running on the device, and if I select it it runs fora ). 

I imagine this is Just Another Apple Problem, but hopefully there is a workaround?

Xcodebuild info: https://gist.github.com/imurchie/616fce0fb52815f4ecf5da99c554b679
System logs: https://gist.github.com/imurchie/4db144ab06ffd040c14a6d507fc1f166

**Comment by imurchie** [comment]
Not sure what changed but this is working now. Crazy.

**Comment by yxys01** [comment]
Hello guys，I met the same issue。Can you tell me how you solved the problem？

**Comment by imurchie** [comment]
Mostly... restart the device.
