### ISSUE TITLE
'RoutingHTTPServer/RouteResponse.h' file not found

### ISSUE THREAD

**Issue by lengyao88** [facebook/WebDriverAgent#543]
/Users/cly/Downloads/WebDriverAgent-master/WebDriverAgentLib/Routing/FBResponseJSONPayload.m:12:9: 'RoutingHTTPServer/RouteResponse.h' file not found

**Comment by marekcirkos** [comment]
Did you read main page and run `./Scripts/bootstrap.sh` script?

**Comment by rcastelino** [comment]
thanks @marekcirkos , I had a similar issue and running the ./Scripts/bootstrap.sh solved this.

Had done this on my previous installs but somehow forgot to do it during this instance. Thanks !
