### ISSUE TITLE
Parent

### ISSUE THREAD

**Issue by VasilijSviridov** [facebook/WebDriverAgent#544]
Is it possible to get the parent of element ? 

As example I have element [XXXX-XXXX] and I need to get its parent ID 

Cheers

**Comment by marekcirkos** [comment]
Technically it would be possible, however most likely will not give you what you want. 
Why you need this?

**Comment by VasilijSviridov** [comment]
The problem with webview I have 3 elements with different names  : A, B , C 
And by the source they all on the same X and Y coordinates , but their parent frame has actual X and Y coordinates with type "Other".
So basically I need a parent frame, but for some reason, parent doesn't have anything I could search for :/ 
My idea is to use getsource with json parser, find child and then go up to parent, but this function will use "for function" which will eat some memory and time.
Any help ?

**Comment by VasilijSviridov** [comment]
We can close this, as I found solution which is really easy, used xpath + parent in a query =)

Cheers

**Comment by HlebHalkouski** [comment]
@VasilijSviridov can you provide some examples for your solution, please?

**Comment by VasilijSviridov** [comment]
Actually it depends on your view, but yeah first I was using //parent::* which takes ages, and then I find another useful approach //XCUIElementTypeOther[XCUIElementTypeLink[@name='']]
where actual region is in XCUIElementTypeOther. It still takes about 45-60 sec but it works properly as expected. Check you host:port/inspector it should tell you which parent child approach to use.
Cheers
