### ISSUE TITLE
fb_tapWithError ignores accessibilityActivationPoint

### ISSUE THREAD

**Issue by fabb** [facebook/WebDriverAgent#545]
Accessibility elements on iOS have the property [https://developer.apple.com/reference/objectivec/nsobject/1615179-accessibilityactivationpoint#](`accessibilityActivationPoint`) for the case a VoiceOver click should **not** happen to the center of an element, but rather offset. An example use case is a UIView containing a UILabel and a UISwitch. The UIView will be made an accessibility element in order to read out the text of the label, and to provide more click area for blind users. The `accessibilityActivationPoint` will be offset in order to correctly click the switch, even though it does not sit in the middle of the UIView. This works great for VoiceOver users.

Appium, which uses the WebDriverAgent, ignores the `accessibilityActivationPoint`, and rather always clicks in the middle of an element. So for cases like the above mentioned, the switch will **not** be triggered when clicking the UIView via Appium.

**Comment by fabb** [comment]
XCUITest's `click` method works as expected.

**Comment by fabb** [comment]
Maybe the `hitPointCoordinate` property on `XCUIElement` from the private headers can be used instead?

**Comment by marekcirkos** [comment]
Resolved
