### ISSUE TITLE
[HELP]hard to understand the code for XCUIApplication

### ISSUE THREAD

**Issue by huanglik** [facebook/WebDriverAgent#551]
![image](https://cloud.githubusercontent.com/assets/3026388/25275612/c3c14d8c-26c8-11e7-883a-453209c8b3e6.png)
Anyone who can tell me what's the meaning of  these two function ?
I really can not understand why need to excute "query" and "resolve"?
  [application query];
  [application resolve];

**Comment by marekcirkos** [comment]
Is it causing any problem? In short they update information about application.
