### ISSUE TITLE
JSONWP command "runAppInBackground" returns error "Failed to find scrollable visible parent with 2 visible children"

### ISSUE THREAD

**Issue by antonys1** [facebook/WebDriverAgent#553]
Via Appium the JSONWP command "runAppInBackground" results in an error.

**WebDriverAgent error received via Appium logs:**
> [debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 "Failed to find scrollable visible parent with 2 visible children" UserInfo={NSLocalizedDescription=Failed to find scrollable visible parent with 2 visible children}","sessionId":"98821523-723A-4DE9-AFCD-80B9D9896BF4","status":13}

**Environment:**
macOS 10.12.4
Xcode 8.3.2
iOS 10.3 Simulator
Appium Server v1.6.4
Appium Java Client v5.0.0-BETA7

**Comment by marekcirkos** [comment]
Do you care about providing a bit more information? I am not familiar with Appium. What `runAppInBackground` is suppose to do? Can you add system logs? screenshot? anything?

**Comment by antonys1** [comment]
> Do you care about providing a bit more information?

Sure, for starters see [original Appium issue](https://github.com/appium/appium/issues/8323)

> I am not familiar with Appium.

Appium is an open source test automation framework for use with native, hybrid and mobile web apps. It drives iOS, Android, and Windows apps using the WebDriver protocol.

> What runAppInBackground is suppose to do?

It's supposed to send the active app to the background, a duration parameter specifies for how long until the app should eventually return to the foreground.

> Can you add system logs? screenshot? anything?

I already added the pertinent logs from Appium as pointed out by one of the Appium contributors, who decided that this was a WDA bug.

I don't think a screenshot will convey anything useful, it would just show the iOS Simulator running the active app.

I think that covers _anything_ unless you can be more specific?

**Comment by marekcirkos** [comment]
@antonys1 It is definitely WDA issue, I need to find a way to reproduce it. Does it happen sometimes or always?

**Comment by antonys1** [comment]
Always
