### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by MajdAlyaseer** [facebook/WebDriverAgent#560]
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65, however, running WebDriverAgent build in XCode succeed.

**Environment**:
Appium v1.6.4
Xcode 8.3.2
Device IOS 10.3.1

Errors log file:
https://gist.github.com/MajdAlyaseer/9c6f125f8b198a882e6a925b1c095858

**Comment by marekcirkos** [comment]
Looks like xcode build issue.

```
[Xcode] 2017-05-02 09:44:13.362 xcodebuild[8793:246398] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2017-05-02 09:44:10.998 XCTRunner[350:26411] Running tests...
[Xcode] 2017-05-02 09:44:11.007 XCTRunner[350:26411] The bundle “WebDriverAgentRunner” couldn’t be loaded because it doesn’t contain a version for the current architecture. Try installing a universal version of the bundle.
[Xcode] 2017-05-02 09:44:11.007 XCTRunner[350:26411] (dlopen_preflight(/var/containers/Bundle/Application/900E86E8-335E-4583-B7AC-878141B498C3/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): no suitable image found.  Did find:
[Xcode] 	/var/containers/Bundle/Application/900E86E8-335E-4583-B7AC-878141B498C3/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: mach-o, but wrong architecture
[Xcode] 	/private/var/containers/Bundle/Application/900E86E8-335E-4583-B7AC-878141B498C3/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: mach-o, but wrong architecture)
```

**Comment by sergd2005** [comment]
@MajdAlyaseer I noticed that you are using test-without-building option. It is outlined here 
https://gist.github.com/MajdAlyaseer/9c6f125f8b198a882e6a925b1c095858#file-gistfile1-txt-L44
It might be a reason why your binaries have wrong archs and build fails. Maybe you build your project in the past for different device with different arch.

**Comment by samuelchen2015** [comment]
@sergd2005 @marekcirkos 
I got the same issue, xcode cannot build wda into read device, I have already try clean build , and using apple ID signing

Environment:
Appium v1.6.4 release
Xcode 8.3.2
Device IOS 10.3.1

`[Xcode] 2017-05-12 09:41:13.525 xcodebuild[35782:8753619] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2017-05-12 09:41:12.162790+0800 XCTRunner[1054:187600] Running tests...
[Xcode] 2017-05-12 09:41:12.463422+0800 XCTRunner[1054:187619] Connection peer refused channel request for "dtxproxy:XCTestDriverInterface:XCTestManager_IDEInterface"; channel canceled `

**Comment by sergd2005** [comment]
Logs from xcodebuild would be usefull, I cant tell what is going on there.

**Comment by samuelchen2015** [comment]
it is ok build-for-testing, but fail for test-without-building , seems wrong with XCTestManager_IDEInterface

`test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=f28d5c6a82d6fc467b5be97085808240216f1b8e -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3
Build settings from command line:
    IPHONEOS_DEPLOYMENT_TARGET = 10.3

2017-05-12 16:02:11.139 xcodebuild[39846:9417250]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/vip/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/B831CB66-EB06-43BB-B38E-8940D88FE090/Session-WebDriverAgentRunner-2017-05-12_160211-S2TWL5.log
2017-05-12 16:02:11.139 xcodebuild[39846:9417247] [MT] IDETestOperationsObserverDebug: (835A949F-B372-45CE-AE5C-05BABB93AC6F) Beginning test session WebDriverAgentRunner-835A949F-B372-45CE-AE5C-05BABB93AC6F at 2017-05-12 16:02:11.139 with Xcode 8E2002 on target <DVTiOSDevice: 0x7f9c3c242290> {
		deviceSerialNumber:         DMPNJWYAG5VT
		identifier:                 f28d5c6a82d6fc467b5be97085808240216f1b8e
		deviceClass:                iPad
		deviceName:                 iPad
		deviceIdentifier:           f28d5c6a82d6fc467b5be97085808240216f1b8e
		productVersion:             10.3.1
		buildVersion:               14E304
		deviceSoftwareVersion:      10.3.1 (14E304)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12473597952
		deviceAvailableCapacity:    7632179200
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f9c3bf03d40 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1,
    2
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.1 (14E304))
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/_7/hnfv0lrn34328wnvkzkbp0440000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/296806e238fb279186157a92b657576c/f28d5c6a82d6fc467b5be97085808240216f1b8e/ManifestCache.plist
2017-05-12 16:02:17.444316+0800 XCTRunner[1211:231341] Running tests...
2017-05-12 16:02:17.731473+0800 XCTRunner[1211:231461] Connection peer refused channel request for "dtxproxy:XCTestDriverInterface:XCTestManager_IDEInterface"; channel canceled <DTXChannel: 0x170098e70>
2017-05-12 16:02:17.683 xcodebuild[39846:9417247] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}`

**Comment by samuelchen2015** [comment]
@sergd2005
it seems wda not working with ios10.3 device, and it is ok with ios10.2 with my device

**Comment by sergd2005** [comment]
@samuelchen2015  I am able to launch wda on 10.3. Could you please provide build logs from xcodebuild ?

**Comment by samuelchen2015** [comment]
@sergd2005 
logs in https://gist.github.com/samuelchen2015/bb611ecde2f2b6eb0db79a2f630fee50

**Comment by marekcirkos** [comment]
Can you launch any UITest on that device? This looks like xcodebuild issue.

**Comment by lshvisual** [comment]
ios 10.2 is fail to

**Comment by marekcirkos** [comment]
`Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}`

Is definitely Xcode's issue. Please raise an issue with Apple

**Comment by marekcirkos** [comment]
Closing as this is known issue https://github.com/facebook/WebDriverAgent/wiki/Common-Issues#booting-wda-on-device-stops-after-set-up-and-does-not-actually-start-wda
