### ISSUE TITLE
Appium IOS time out finding the element when API call return large number of data set

### ISSUE THREAD

**Issue by SanjayDhami** [facebook/WebDriverAgent#561]
Appium version 1.6.4
Mobile platform/version under test:
Real device or emulator/simulator: Both
Appium CLI or Appium.app|exe:
Details

IOS appium driver takes very very long time to find the element Whenever i click the link in the app that returns large set of data,

i am guessing this issue is because the API return large data set and appium ios driver is taking long time to parse and get the desired element from the DOM.

Android works fine because appium android only know what is present in the current screen regardless what api returns but iOS know every element even not displayed in the screen.

Link to Appium logs

[Xcode] 2017-04-26 17:18:21.811 XCTRunner[2724:2785096] Enqueue Failure: UI Testing Failure - Failure getting snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error -25204 getting snapshot for element {pid=2730}" UserInfo={NSLocalizedDescription=Error -25204 getting snapshot for element {pid=2730}} 0 1

[Xcode] 2017-04-26 17:18:21.929 XCTRunner[2724:2772514] Enqueue Failure: UI Testing Failure - (null) /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[Xcode] 2017-04-26 17:18:21.932 XCTRunner[2724:2772514] Failed to invoke libxml2>xmlTextWriterStartElement. Error code: -1
[Xcode] 2017-04-26 17:18:21.932 XCTRunner[2724:2772514] Failed to generate XML presentation of a screen element

And i realize that when API call return the less number of data set its pretty quick to get the element.
Any Suggestion / idea to solve this issue

And i am pretty much sure that previous version of appium like 1.5 where WDA was not integrated, it was working fine, so i believe this is something introduce by WDA integration with appium. [ May be i am wrong]

**Comment by SanjayDhami** [comment]
Thank you. Any timeline to work around on this issue.

**Comment by mykola-mokhnach** [comment]
> Error -25204 getting snapshot for element 

@SanjayDhami I suppose it might be something different. Check https://github.com/facebook/WebDriverAgent/issues/402 for the reference

**Comment by marekcirkos** [comment]
@SanjayDhami Can you check master?

**Comment by marekcirkos** [comment]
@SanjayDhami ?
