### ISSUE TITLE
Appium IOS  WDA is not able to send key value to textfield for customized keyboard

### ISSUE THREAD

**Issue by SanjayDhami** [facebook/WebDriverAgent#562]
In our native app, developer have used customized keyboard for preventing typo error. when i try to sendkey in textfield, appium throws following error

Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}

However for default keyboard it works fine.

Any help/suggestion will be highly appreciated.

Thank you

**Comment by marekcirkos** [comment]
Would it be possible of you to provide test sample in out integration test app?

**Comment by SanjayDhami** [comment]
How can i get the source code  of integration test app. 
thank you

**Comment by marekcirkos** [comment]
It is within this repo :) https://github.com/facebook/WebDriverAgent/tree/master/WebDriverAgentTests

**Comment by marekcirkos** [comment]
Any luck?
