### ISSUE TITLE
build WDA fail

### ISSUE THREAD

**Issue by hujiachun** [facebook/WebDriverAgent#564]
<img width="1003" alt="2017-05-03 16 29 10" src="https://cloud.githubusercontent.com/assets/17762932/25653043/ba2ce25a-301d-11e7-8ef8-16197c72a1c1.png">

**Comment by hujiachun** [comment]
C02SD9EYFVH5:WebDriverAgent-master test-server$ ./Scripts/bootstrap.sh
Fetching dependencies
Building Inspector
Creating bundle directory...
Fetching Inspector dependencies...
npm WARN web-driver-inspector@1.0.0 No repository field.
Validating Inspector
No errors!
Building Inspector...

> web-driver-inspector@1.0.0 build /Users/test-server/Documents/WebDriverAgent-master/Inspector
> webpack --progress --colors

Hash: 04d1f083bd932cf21402  
Version: webpack 1.15.0
Time: 2155ms
       Asset    Size  Chunks             Chunk Names
inspector.js  784 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 191 hidden modules
Done

**Comment by marekcirkos** [comment]
Can you try master? Travis is happy.

**Comment by marekcirkos** [comment]
Which Xcode are you using?
