### ISSUE TITLE
WDA interference with AVFoundation Recording of device

### ISSUE THREAD

**Issue by aprams** [facebook/WebDriverAgent#568]
The WebDriverAgent works perfectly fine by calling the REST-Endpoints.
If I do the same while running an AVCaptureSession though to record the device's screen, the WDA doesn't respond anymore and instead prints device information: 

> Alexanders-MBP:WebDriverAgent alexanderprams$ xcodebuild -project WebDriverAgent.xcodeproj            -scheme WebDriverAgentRunner            -destination 'platform=iOS,name=iPhone'            test
2017-05-04 16:16:32.304 xcodebuild[964:18051]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/alexanderprams/Library/Developer/Xcode/DerivedData/WebDriverAgent-hblrezshcmnauxfddkowblbispqv/Logs/Test/DD842929-F1F0-46B3-B819-231414311D32/Session-WebDriverAgentRunner-2017-05-04_161632-mAJuLB.log
2017-05-04 16:16:32.305 xcodebuild[964:18040] [MT] IDETestOperationsObserverDebug: (ECE67730-A4F8-4772-B105-65F32583A5B5) Beginning test session WebDriverAgentRunner-ECE67730-A4F8-4772-B105-65F32583A5B5 at 2017-05-04 16:16:32.305 with Xcode 8E1000a on target <DVTiOSDevice: 0x7f9a6e30afe0> {
		deviceSerialNumber:         <myDeviceSerial>
		identifier:                 <myDeviceID>
		deviceClass:                iPhone
		deviceName:                 iPhone
		deviceIdentifier:           <myDeviceID>
		productVersion:             10.3.1
		buildVersion:               14E304
		deviceSoftwareVersion:      10.3.1 (14E304)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        60146950144
		deviceAvailableCapacity:    33710227456
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f9a6b5f4310 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.1 (14E304))

Curl that was used: curl -i -X POST -H "Content-Type: application/json" -d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.mobilesafari\"}}" "http://192.168.0.37:8100/session" The curl command times out when using the AVCaptureSession. The debug information was printed immediately after calling curl. The exact same command does result in a successful request when not using AVFoundation.

Is there any limitation on device interaction while running WDA?

**Comment by sergd2005** [comment]
Hi @aprams - I am new to WDA and I am not sure if that`s possible to record device screen, I know it is possible to record apps screen with AVCaptureSession. I assume you are calling AVCaptureSession in your host app that is tested via WDA ?

**Comment by aprams** [comment]
Hi @sergd2005,
It is possible and it works using a short trick with CoreMediaIO. That recording program is running independently from my WDA instance. (See here on how to make the device screen itself recordable independent of any running test/app: stackoverflow.com/questions/32700632/record-iphone-ipad-screen-from-a-os-x-app-just-like-quicktime-player)
That recording application is also executed on the mac that's running the WDA instance.
Thanks for your help!

**Comment by sergd2005** [comment]
Hi @aprams, wow that's cool - let me try to reproduce your issue first. FYI I did a lot of recordings via quicktime of ios devices - one common thing that I notice ( and u can try yourself) when u start recording your debugger session quits in xcode. I ll record that issue also, maybe it is related to your problem. Thx for hint

**Comment by VasilijSviridov** [comment]
@aprams have you tried to start recording first ? and only then start WDA ?
Cheers

**Comment by qmfrederik** [comment]
When you start recording with Quicktime, the USB connection between the device and the mac is reset completely. So as @sergd2005 indicates, that will kill your debugger session in Xcode, as well as any running XCUITest session.

I don't know whether it will work, but the only way I think this could work is to start the Quicktime recording first, and then launch the WDA. You can also not stop the AV recording for as long as WDA is running, doing so will again reset the USB connection.

**Comment by sergd2005** [comment]
@qmfrederik  I agree with that suggestion. I promise to test that way with you hack @aprams as soon I ll get out from release hell ))

**Comment by aprams** [comment]
@qmfrederik Starting the recording first seems to work (I couldn't try this earlier due to the structure of the project)
Thank you for your help @qmfrederik , @sergd2005

**Comment by mstrelex** [comment]
Just an FYI - I used QT Version 10.4 (894.12), it doesn't interfere with WDA (that was started first). So apparently AVCaptureSession doing something differently.
