### ISSUE TITLE
Webview/Safari testing?

### ISSUE THREAD

**Issue by Jonahss** [facebook/WebDriverAgent#57]
I can have the appium driver connect to the Safari debugger, like we do currently with our Instruments solution.

Does Facebook currently have a different method for testing webviews/safari using XCUITest?

@mmmulani

**Comment by marekcirkos** [comment]
XCTWebDriverAgent is still work in progress. I haven't added inspector yet, but it should be fairly simple to do.

**Comment by arikon** [comment]
@marekcirkos Are you ready to accept contributions on this issue? Do you have public roadmap on it?

**Comment by Jonahss** [comment]
I'm working on just using our regular appium SafariDriver, which connects to the remote debugger. So appium will have support for WebDriverAgent along with safari.

**Comment by arikon** [comment]
@Jonahss Where to track the progress? ;)

**Comment by Jonahss** [comment]
github.com/appium/appium-webdriveragent-driver  XCUITest branch

**Comment by marekcirkos** [comment]
Good news. We can attach or launch any process with bundleID. What we need is handle, case when application launches Safari by itself.

**Comment by Jonahss** [comment]
Wow, does that mean we can launch calendar or contacts too?

**Comment by marekcirkos** [comment]
Yep :)

**Comment by Jonahss** [comment]
Awesome!

**Comment by marekcirkos** [comment]
@Jonahss I am ok to close this issue?

**Comment by Jonahss** [comment]
Ok to close.
