### ISSUE TITLE
How to start WDA Using FBSimulatorControl framework directly

### ISSUE THREAD

**Issue by thanhhtran** [facebook/WebDriverAgent#576]
Hi fb team,

Following the guide at https://github.com/facebook/WebDriverAgent/wiki/Starting-WebDriverAgent, I cannot find the file FBSimulatorInteraction+XCTest.h even in the repository of FBSimulatorControl.

Any advise or guidance would be greatly appreciated!

Regards, 
Thanh

**Comment by thanhhtran** [comment]
I can start WDA following the example in [FBSimulatorTestInjectionTests.m](https://github.com/facebook/FBSimulatorControl/blob/master/FBSimulatorControlTests/Tests/Integration/FBSimulatorTestInjectionTests.m). Closing the issue

**Comment by marekcirkos** [comment]
Thanks @thanhhtran! I updated docs :)
