### ISSUE TITLE
Cant select AlertDialog Button, When another element on the screen has the same Name.

### ISSUE THREAD

**Issue by christoff-1992** [facebook/WebDriverAgent#577]
Hi All, 

Firstly if I'm doing this incorrectly I apologies, please close this I don't want to be wasting anyones time, currently using Appium version (1.6.3, which includes appium-xcuitest-driver v2.4.2)

Currently When an Alert dialog is present with multiple Buttons eg. 'Cancel' & 'Delete' and the application also has another element in the background with the same text value in this case 'Delete'.

During the : `(BOOL)isElementObstructedByAlertView:(XCUIElement *)element alert:(XCUIElement *)alert` Check, the view is obstructed so no elements are returned.

Is this the expected behaviour? Both 'Delete' elements have different accessibilityId's in this case, but it looks to be finding the element by name.

**Eg: Screenshot of the application:**

![screen shot 2017-05-10 at 13 06 02](https://cloud.githubusercontent.com/assets/12499390/25898146/bbd81038-3582-11e7-85b3-8423023ffc94.png)

If I alter the isElementObstructedByAlertView to exclude Buttons.

`if (element.elementType == XCUIElementTypeButton) {
        return NO;
    }`

Then the button is returned and all is good, however I don't think I should be changing this method to exclude buttons.

**Comment by marekcirkos** [comment]
This should be hard to fix. When accepting alert buttons we should narrow search to subviews of alert, instead of "global" name search.

**Comment by christoff-1992** [comment]
@marekcirkos - Thanks for taking a look, sorry are you saying this is hard to fix?

**Comment by marekcirkos** [comment]
Sorry, that was misspell :) "It shouldn't" be hard to fix

**Comment by christoff-1992** [comment]
Ha well if you point me in the right direction I can take a look and open a pull request, but I can't promise time during the day it will have to be in the evenings.

**Comment by marekcirkos** [comment]
Just checked code, it should work properly. 
https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/FBAlert.m#L167

You can debug that if you have some time :)

**Comment by marekcirkos** [comment]
@christoff-1992 ?

**Comment by christoff-1992** [comment]
Hey apologies @marekcirkos, I had hoped to have some time to investigate this but need to uplift Appium to integrate the changed. Can you give me till Monday to confirm? Il be able to do this over the weekend.

**Comment by marekcirkos** [comment]
Sure, I wasn't sure you have seen my message :)
