### ISSUE TITLE
WebView clicking issue

### ISSUE THREAD

**Issue by VasilijSviridov** [facebook/WebDriverAgent#578]
Hi,
I have a webview in which there is an image with link.
When I press on that image I have a popupAlert with two buttons "OK" and "Cancel"

The build which was from 1st of February works fine, but latest build crashes when trying to click the image. I am using tap method to click image(note that build from February 1st works fine).
Same issue on real devices with versions: iOS 10.1,10.2.1,9.3.3,10.3.1
Log below:

Snapshot accessibility hierarchy for ***********
2017-05-11 08:33:06.736 XCTRunner[2949:10210813] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x159924f80
2017-05-11 08:33:06.737 XCTRunner[2949:10210813] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x159924f80'
*** First throw call stack:
(0x182606db0 0x181c6bf80 0x18260dc4c 0x18260abec 0x182508c5c 0x183a138e8 0x183a13694 0x183a13668 0x100097a58 0x1021ae16c 0x102195324 0x1021a0358 0x10218d62c 0x10218de0c 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218df84 0x10218c968 0x10218c1b8 0x1021a1598 0x102197328 0x10218f39c 0x1024763cc 0x102476b80 0x18205147c 0x182060ae8 0x18205147c 0x182056b84 0x1825bcd50 0x1825babb8 0x1824e4c50 0x182ef4cfc 0x182f4a030 0x10218e4ec 0x10217bed0 0x18260ca60 0x182504488 0x100050a30 0x10005067c 0x10008bdac 0x100050430 0x100050d80 0x10004df44 0x10004db64 0x10004dd54 0x10004df44 0x10004db64 0x10004dd54 0x10004df44 0x10004db64 0x10004dd54 0x100099a14 0x10005c8dc 0x100099894 0x100038f70 0x10008f6f8 0x1825bcf84 0x1825bc8bc 0x1825ba820 0x1824e4c50 0x183dcc088 0x1877ce088 0x100010474 0x1820828b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
2017-05-11 08:33:14.273 xcodebuild[48528:657646]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/***/Library/Developer/Xcode/DerivedData/WebDriverAgent-emghpzpphivkbcaesiqucbcxwshv/Logs/Test/C72CD832-4A2B-456B-BE21-6E3A3C8B43D4/Session-WebDriverAgentRunner-2017-05-11_083314-npkrQO.log
2017-05-11 08:33:14.273 xcodebuild[48528:652592] [MT] IDETestOperationsObserverDebug: (C262827D-07B3-4CDC-A543-86C96EDCF21C) Beginning test session WebDriverAgentRunner-C262827D-07B3-4CDC-A543-86C96EDCF21C at 2017-05-11 08:33:14.273 with Xcode 8E2002 on target <DVTiOSDevice: 0x7feab0eed0a0> {
		deviceSerialNumber:         F19QKUE1GRY8
		identifier:                 ********
		deviceClass:                iPhone
		deviceName:                 iPhone
		deviceIdentifier:           ********
		productVersion:             9.3.3
		buildVersion:               13G34
		deviceSoftwareVersion:      9.3.3 (13G34)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12565757952
		deviceAvailableCapacity:    9891880960
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7feab0ece640 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              {(
    <DTDKApplication: 0x7feab4b99040>: IntegrationApp (/private/var/containers/Bundle/Application/4A24DDFB-41B3-412B-BD21-1B84FC7F2B2F/IntegrationApp.app),
    <DTDKApplication: 0x7feab4b98de0>: WebDriverAgentRunner (/private/var/containers/Bundle/Application/53AA5E4E-8B77-4AA1-B842-BBC1BD1E98ED/WebDriverAgentRunner-Runner.app)
)}
		
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (9.3.3 (13G34))
MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/1g/9l22ywvd5158c2bxt3_fm4gc5x6c8b/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/d22bf14fd58a6e42c4407e142b42f0e8/********/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/***/Library/Developer/Xcode/DerivedData/WebDriverAgent-emghpzpphivkbcaesiqucbcxwshv/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/1g/9l22ywvd5158c2bxt3_fm4gc5x6c8b/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.hYOrQn/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/1g/9l22ywvd5158c2bxt3_fm4gc5x6c8b/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.hYOrQn/WebDriverAgentRunner-Runner.app_sparse.ipa
__MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/1g/9l22ywvd5158c2bxt3_fm4gc5x6c8b/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.hYOrQn/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/1g/9l22ywvd5158c2bxt3_fm4gc5x6c8b/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.hYOrQn/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2017-05-11 08:33:17.621 XCTRunner[2970:10214059] Running tests...
2017-05-11 08:33:18.541 XCTRunner[2970:10214059] Continuing to run tests in the background with task ID 1

Restarting after unexpected exit or crash in UITestingUITests/testRunner; summary will include totals from previous launches.

Test Suite 'Selected tests' started at 2017-05-11 08:33:19.165
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-05-11 08:33:19.166
Test Suite 'WebDriverAgentRunner.xctest' failed at 2017-05-11 08:33:19.166.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'WebDriverAgentLib.framework' started at 2017-05-11 08:33:19.167
Test Suite 'WebDriverAgentLib.framework' passed at 2017-05-11 08:33:19.167.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'Selected tests' failed at 2017-05-11 08:33:19.167.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.003) seconds
Failing tests:
	-[UITestingUITests testRunner]
** TEST FAILED **

**Comment by VasilijSviridov** [comment]
xcodebuild[51664:684222] [MT] IDETestOperationsObserverDebug: (B4E5EDB3-8207-4CF7-829B-85B048C3FF99) Failed to make test runner session:
Error Domain=DTXProxyChannel Code=1 "(null)" UserInfo={DTXProxyChannelErrorMessage=Channel disconnected}
2017-05-11 09:18:37.863 xcodebuild[51664:684222] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "The operation couldn’t be completed. (DTXProxyChannel error 1.) If you believe this error represents a bug, please attach the log file at /Users/vsv01/Library/Developer/Xcode/DerivedData/WebDriverAgent-emghpzpphivkbcaesiqucbcxwshv/Logs/Test/F1B172E2-605D-4506-BF09-1D956970D94C/Session-WebDriverAgentRunner-2017-05-11_091837-2xGN2K.log" UserInfo={NSLocalizedDescription=The operation couldn’t be completed. (DTXProxyChannel error 1.) If you believe this error represents a bug, please attach the log file at /Users/vsv01/Library/Developer/Xcode/DerivedData/WebDriverAgent-emghpzpphivkbcaesiqucbcxwshv/Logs/Test/F1B172E2-605D-4506-BF09-1D956970D94C/Session-WebDriverAgentRunner-2017-05-11_091837-2xGN2K.log}

Testing failed:
	Run test suite UITestingUITests encountered an error (The operation couldn’t be completed. (DTXProxyChannel error 1.) If you believe this error represents a bug, please attach the log file at /Users/vsv01/Library/Developer/Xcode/DerivedData/WebDriverAgent-emghpzpphivkbcaesiqucbcxwshv/Logs/Test/F1B172E2-605D-4506-BF09-1D956970D94C/Session-WebDriverAgentRunner-2017-05-11_091837-2xGN2K.log)

**Comment by marekcirkos** [comment]
Without symbolicated stack trace or reproduce steps, it would be hard to help you here

**Comment by marekcirkos** [comment]
We made few fixes on master. @VasilijSviridov can you confirm

**Comment by VasilijSviridov** [comment]
got it, give me few days to test it, won't take much time.

Thank you for help! =)

**Comment by VasilijSviridov** [comment]
Hi again, so yeah, I updated the WDA to the latest one, it is not anymore crashing as it was before, but I tested only on 1 device 10.2.1, if you could give me few more days I be able to check weather everything ok on all available iOS versions and confirm that all is good =)

**Comment by VasilijSviridov** [comment]
So yeah it is fixed for 10.* iOS versions tested on 10.1, 10.2.1,10.3.1 , but for 9.3.* same issue:

 Find the Application "********" 0x1500f7580
    t =   268.13s         Use cached accessibility hierarchy for ***********
2017-05-23 17:03:50.953 XCTRunner[558:92475] -[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x15139abb0
2017-05-23 17:03:50.954 XCTRunner[558:92475] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString objectForKey:]: unrecognized selector sent to instance 0x15139abb0'
*** First throw call stack:
(0x18287adb0 0x181edff80 0x182881c4c 0x18287ebec 0x18277cc5c 0x183c878e8 0x183c87694 0x183c87668 0x1000bfa58 0x1021fa094 0x1021e11b4 0x1021ec378 0x1021d9428 0x1021d9c08 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d9d88 0x1021d8764 0x1021d81a0 0x10220269c 0x1021e1de0 0x1021e1e88 0x1021f4634 0x1021f381c 0x1021e31b8 0x1021db1a0 0x1025063cc 0x102506b80 0x1822c547c 0x1822d4ae8 0x1822c547c 0x1822cab84 0x182830d50 0x18282ebb8 0x182758c50 0x183168cfc 0x1831be030 0x1021da2f0 0x1021c7ed0 0x182880a60 0x182778488 0x100078a30 0x10007867c 0x1000b3dac 0x100078430 0x100078d80 0x100075f44 0x100075b64 0x100075d54 0x100075f44 0x100075b64 0x100075d54 0x100075f44 0x100075b64 0x100075d54 0x1000c1a14 0x1000848dc 0x1000c1894 0x100060f70 0x1000b76f8 0x182830f84 0x1828308bc 0x18282e820 0x182758c50 0x184040088 0x187a46088 0x100030474 0x1822f68b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
2017-05-23 17:03:57.975 xcodebuild[38249:2653511]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/vsv01/Library/Developer/Xcode/DerivedData/WebDriverAgent-goaegklwdddwixboktrjulyrgtxx/Logs/Test/ADFC1D72-86D5-430B-AF26-2B37847724BB/Session-WebDriverAgentRunner-2017-05-23_170357-VakyLO.log
2017-05-23 17:03:57.975 xcodebuild[38249:2642851] [MT] IDETestOperationsObserverDebug: (0941ECD6-C49A-4891-8A4C-B82B83E9C4AC) Beginning test session WebDriverAgentRunner-0941ECD6-C49A-4891-8A4C-B82B83E9C4AC at 2017-05-23 17:03:57.975 with Xcode 8E2002 on target <DVTiOSDevice: 0x7fb0c2e55570> {
		deviceSerialNumber:         ********
		identifier:                 ********
		deviceClass:                iPhone
		deviceName:                  iPhone
		deviceIdentifier:           ********
		productVersion:             9.3.5
		buildVersion:               13G36
		deviceSoftwareVersion:      9.3.5 (13G36)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12314591232
		deviceAvailableCapacity:    6287466496
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fb0c2a77d70 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)

Restarting after unexpected exit or crash in UITestingUITests/testRunner; summary will include totals from previous launches.

Test Suite 'Selected tests' started at 2017-05-23 17:04:03.521
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-05-23 17:04:03.523
Test Suite 'WebDriverAgentRunner.xctest' failed at 2017-05-23 17:04:03.523.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'WebDriverAgentLib.framework' started at 2017-05-23 17:04:03.523
Test Suite 'WebDriverAgentLib.framework' passed at 2017-05-23 17:04:03.524.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'Selected tests' failed at 2017-05-23 17:04:03.524.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.003) seconds

**Comment by marekcirkos** [comment]
That would mean, that this is related to XCTest change. Stacktrace would be helpful here.
