### ISSUE TITLE
Tap/Drag Delay Improvements

### ISSUE THREAD

**Issue by aprams** [facebook/WebDriverAgent#579]
Taps and DragFromTo commands (via curl) both take around 1.5s to 2.5s to execute.
Is there anything I can do to speed that up?

This video for example looks multiple times faster than that, any ideas why?
https://www.youtube.com/watch?v=EatiYGFxBxY

The commands I'm using to execute the taps/drags are:

`curl -X POST $JSON_HEADER -d "{"x":"50","y":"150"}" $DEVICE_URL/session/$SESSION_ID/wda/tap/0`

`curl -X POST -H "Content-Type: application/json" -d "{fromX:100,fromY:100,toX:100,toY:180,duration:10}" http://192.168.0.37:8100/session/$SESSION_ID/wda/dragfromtoforduration`

Thank you for your help!

**Comment by marekcirkos** [comment]
Landed https://github.com/facebook/WebDriverAgent/commit/18d98e2e508b1d9003c1402edc14c908636763b2 that should help here

**Comment by marekcirkos** [comment]
@aprams Did it?

**Comment by aprams** [comment]
Sadly I could not see any improvements, these are the timestamps I get for the dragfromtoforduration command:

t =    47.14s     Find the Application "local.pid.53" 0x1700b4b20
    t =    47.14s         Snapshot accessibility hierarchy for local.pid.53

t =    47.45s     Find the Application "local.pid.53" 0x1700b4b20
    t =    47.45s         Use cached accessibility hierarchy for local.pid.53
    t =    47.45s     Find the Application "local.pid.53" 0x1700b4b20
    t =    47.45s         Use cached accessibility hierarchy for local.pid.53

t =    47.47s     Find the Application "local.pid.53" 0x1700b4b20
    t =    47.47s         Snapshot accessibility hierarchy for local.pid.53

t =    47.62s     Find the Application "local.pid.53" 0x1700b4b20
    t =    47.63s         Use cached accessibility hierarchy for local.pid.53
    t =    47.63s     Find the Application "local.pid.53" 0x1700b4b20
    t =    47.63s         Use cached accessibility hierarchy for local.pid.53
    t =    47.63s     Press and drag from Application "local.pid.53" 0x1700b4b20[0.00, 0.00] -> (300.0, 100.0) to Application "local.pid.53" 0x1700b4b20[0.00, 0.00] -> (100.0, 100.0)
    t =    47.63s         Wait for app to idle

t =    47.83s         Find the Application "local.pid.53" 0x1700b4b20
    t =    47.83s             Snapshot accessibility hierarchy for local.pid.53

t =    48.11s             Wait for app to idle

t =    48.33s         Synthesize event

t =    48.42s             Find the Application "local.pid.53" 0x1700b4b20
    t =    48.42s                 Snapshot accessibility hierarchy for local.pid.53

t =    48.57s             Find the Application "local.pid.53" 0x1700b4b20
    t =    48.57s                 Use cached accessibility hierarchy for local.pid.53

t =    49.45s         Wait for app to idle

t =    49.68s             App event loop idle notification not received, will attempt to continue.

`

**Comment by aprams** [comment]
Is there a way to simply issue the event  without any waiting or application-specific behavior? (Just issuing the "Synthesize Event" call)

**Comment by aprams** [comment]
Sorry, I tried again and it definitely works better! 
I got around 0.8s of delay, which is pretty good!
Thanks!

**Comment by codeskyblue** [comment]
@aprams From your comments and marekcirkos comments, how did you do it, to make tap faster? Waiting for your reply if you got time.

**Comment by aprams** [comment]
@codeskyblue I actually didn't do much, I just updated to the named commit. It's still not as fast as I'd like to it be, but I guess that's a XCUI limitation.
