### ISSUE TITLE
Can't clone KissXML and peertalk while bootstrapping in a reason of missing git repositories

### ISSUE THREAD

**Issue by EugeneMarrow** [facebook/WebDriverAgent#580]
Hi.
I'm trying to setup test automation environment using Appium, but I'm facing the following error:

```
 [XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  stdout: '\u001b[1mFetching dependencies\n*** Cloning KissXML\n*** Cloning peertalk\n*** Checking out KissXML at "5.0.5"\n*** Cloning KissXML\n',
  stderr: 'A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/KissXML.git /Users/macpad/Library/Caches/org.carthage.CarthageKit/dependencies/KissXML) failed with exit code 128:\nfatal: could not read Username for \'https://github.com\': terminal prompts disabled\n\n',
  code: 1 
```
I was going to clone repositories manually, as far as they supposed to be found on @marekcirkos repository list, but they aren't there.
So I found actual links for repos:
https://github.com/robbiehanson/KissXML
https://github.com/rsms/peertalk

First I've tried to clone them manually, but still, Carthage refers to:
https://github.com/marekcirkos/KissXML.git 
https://github.com/marekcirkos/peertalk.git 

so I've tried to change Cartfile and Cartfile.resolved but couldn't find peertalk version needed in Cartfile.resolved file.

Now I'm stuck and hoping you could help me on this problem.

Regards, Eugene.

**Comment by sergd2005** [comment]
Hi Eugene, from logs
Users/macpad/Library/Caches/org.carthage.CarthageKit/dependencies/KissXML) failed with exit code 128:\nfatal: could not read Username for \'https://github.com\': terminal prompts disabled\n\n',
  code: 1 }

looks like something is wrong with terminal. Try to clone any repo in terminal and see if it works.

**Comment by EugeneMarrow** [comment]
@sergd2005  Works just fine with https://github.com/rubysolo/dentaku.
From my researching, this error may be found if there are some problems with ssh connection, but still, my bet is on Carthage bootstrap trying to fetch with missing directory...

**Comment by EugeneMarrow** [comment]
@sergd2005  I'm new to git, so I wondering: as far as problem is connected with some of  @marekcirkos repos, is it possible, to connect with him via git?

**Comment by marekcirkos** [comment]
Hey, we used to have fork that supported `Carthage`. KissXML is not a dependency for a while now so I removed the repo. Using latest rev should solve problem for you.

**Comment by EugeneMarrow** [comment]
Thanks for reply.
Well, I've cloned latest revision, just as you recommended, and now there are no records about kissxml and peertalk in cartfile.
But still I'm facing almost the same error

` stdout: '\u001b[1mFetching dependencies\n*** Cloning KissXML\n*** Cloning peertalk\n*** Checking out KissXML at "5.0.5"\n*** Cloning KissXML\n',
  stderr: 'A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/KissXML.git /Users/macpad/Library/Caches/org.carthage.CarthageKit/dependencies/KissXML) failed with exit code 128:\nfatal: could not read Username for \'https://github.com\': terminal prompts disabled\n\n',
  code: 1 }
`

There is only RoutingHTTPServer subdirectory in dependencies folder, just like there is only RoutingHTTPServer record in cartfile. 
So, maybe the problem is about some cache or Appium still has those tasks to do somewhere.

Thanks a lot for you help)

**Comment by joelkaufman** [comment]
@EugeneMarrow im having the same problem, wondering if it worked at the end

**Comment by EugeneMarrow** [comment]
@joelkaufman
Yep, I've installed last up-to-date rev, and it's not a dependency anymore)

**Comment by ash197** [comment]
@EugeneMarrow I am facing the same issue, I uninstalled the carthage and re-installed it using brew . However, the same version 0.23 gets installed again. Can u please share the command or process using which u installed the revised carthage to the latest up-to-date rev.

**Comment by EugeneMarrow** [comment]
@ash197 I should git clone latest revision of WDA and copy instead Appium/WDA folder.
After that you can get kissxml and peer talk manually.

p.s. be sure to set dependencies for WDA after installing new version.

Regards

**Comment by ash197** [comment]
@EugeneMarrow thanks for the quick response , updating to latest revision of WDA worked. Can u please suggest a good inspector tool to inspect native locators of iOS app using appium 1.6.3 for iOS 10.3 device

Thanks

**Comment by EugeneMarrow** [comment]
@ash197
Glad it worked for you. For me using xcode's accessibility inspector, and appium inspector fro appium GUI is enough. You can also checkout iOS inspector(sorry,can't give a link right now, but it wouldn't be a problem to find it)
Good look)

**Comment by rikiiwang** [comment]
@EugeneMarrow 
I also met the problem below.
wang-MacBook-Pro:WebDriverAgent wang$ ./Scripts/bootstrap.sh
Fetching dependencies
*** Fetching peertalk
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** Checking out peertalk at "v1.0"
*** Fetching peertalk
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/marekcirkos/peertalk.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/*) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

I found that https://github.com/marekcirkos/peertalk.git returns 404 and doesn't exist anymore.
How can I solve that? 
WebDriverAgent.xcodeproj can not be built on real device if peertalk is not ready.
I am curious why just few people meet this issue during Appium env preparation.

Thanks a lot in advance.

**Comment by EugeneMarrow** [comment]
@rikiiwang 
HI
As already written above clone latest WDA revision, and then download peertalk via npm, then it should work just fine.
Good luck)

**Comment by RanjithHS** [comment]
I also met the problem below. ANY HELP HOW to get the latest WDA would be of great help

I have installed peertalk via nom but still the error persist. Could you please provide me few steps to overcome this.

wang-MacBook-Pro:WebDriverAgent wang$ ./Scripts/bootstrap.sh
Fetching dependencies
*** Fetching peertalk
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** Checking out peertalk at "v1.0"
*** Fetching peertalk
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/marekcirkos/peertalk.git refs/tags/:refs/tags/ +refs/heads/:refs/heads/) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by EugeneMarrow** [comment]
@RanjithHS 
Just clone it like

` git clone https://github.com/facebook/WebDriverAgent.git`

in any directory and then copy/paste it instead of WebDriverAgent directory.

After that you should bootstrap it just fine, but don forget to do signing in xcode project to fit app that you are going to test

**Comment by RanjithHS** [comment]
Thanks @EugeneMarrow 
seems to be working, but how do I code sign. I get the below error.

*** Building scheme "RoutingHTTPServer" in RoutingHTTPServer.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer/RoutingHTTPServer.xcodeproj -scheme RoutingHTTPServer -configuration Release -derivedDataPath /Users/rbei_eht1/Library/Caches/org.carthage.CarthageKit/DerivedData/RoutingHTTPServer/v1.0.1 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/dh/w9hml6wj3gj2trgljd3w3x_40000gn/T/carthage-xcodebuild.eGCJcf.log

**Comment by RanjithHS** [comment]
@EugeneMarrow

can you please help on this.

when I build WDA I am getting below error

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_XCTRunnerDaemonSession", referenced from:
      objc-class-ref in XCUIElement+FBTap.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RanjithHS** [comment]
ndefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_XCTRunnerDaemonSession", referenced from:
      objc-class-ref in XCUIElement+FBTap.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

@EugeneMarrow Any help on this please

**Comment by sushree-moharana** [comment]
Hi ,
getting this error while running the command './Scripts/bootstrap.sh -d'


HYDPCM317869D:WebDriverAgent shaik.abdulsubhan$ ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** Checking out peertalk at "v1.0"
*** Cloning peertalk
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/peertalk.git /Users/shaik.abdulsubhan/Library/Caches/org.carthage.CarthageKit/dependencies/peertalk) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
