### ISSUE TITLE
Cannot display the "Tree of Element" with new wda

### ISSUE THREAD

**Issue by phoebusliang** [facebook/WebDriverAgent#583]
xcode: 8.3.1
macOS: 10.12.4

fbsimctl: newest code
webdriveragent: newest code

![newest](https://cloud.githubusercontent.com/assets/986717/26050554/ad51f494-3991-11e7-9ee6-87a7097b7a0f.png)

**Comment by marekcirkos** [comment]
What app do you use to host WDA?

**Comment by phoebusliang** [comment]
Some default app on the simulator like com.apple.Preferences or com.apple.mobilesafari etc.

It works well if I use WDA with the old version, but nothing display with the latest code.

**Comment by marekcirkos** [comment]
This is key issue here. If you are using Safari you will not be able to see its view hierarchy. If you use Preferences, then something is wrong. It works for me tho.

Do you see any errors in system logs?

**Comment by phoebusliang** [comment]
@marekcirkos I don't think we can find the tree of elements if I use the old WDA. 
![image](https://cloud.githubusercontent.com/assets/986717/26345525/c1f996dc-3fd5-11e7-8016-2a8b3ce60a7d.png)

**Comment by marekcirkos** [comment]
So this is fixed with the new WDA?
