### ISSUE TITLE
/element crashed WebDriverAgent

### ISSUE THREAD

**Issue by saikrishna321** [facebook/WebDriverAgent#584]
Running tests using appium and when WebDriverAgent makes for /element it takes long time to perform the click action. Looking at the device logs i see WebDriverAgent runner is crashed.

PS:
when waiting for element, xcui takes around 3mins to click on it … it checks for /displayed and /enabled and /click

Device Logs::
https://gist.github.com/saikrishna321/d806417077732b662f125be9ac5f28dd

any helps on this pls

**Comment by marekcirkos** [comment]
Can you give any steps on how to reproduce it? Without any symbols it will be really hard to guess what went wrong

**Comment by saikrishna321** [comment]
Sure. let me give you working code early tomorrow

**Comment by saikrishna321** [comment]
> Can you give any steps on how to reproduce it?

@marekcirkos i'm just clicking on element, nothing other than that.

**Comment by saikrishna321** [comment]
@marekcirkos https://github.com/saikrishna321/VodQaAdvancedAppium/tree/webdriveragent_issue

clone the project and mvn clean -Dtest=GestureTest test

**Comment by marekcirkos** [comment]
Will try when I got some time

**Comment by vjmaiky** [comment]
any updates here? i`m facing this issue more and more..i have latest resources (appium/webdriver agent).

**Comment by saikrishna321** [comment]
@marekcirkos any updates ?

**Comment by marekcirkos** [comment]
@vjmaiky, @saikrishna321 sorry I did not have time to have a look at it.
