### ISSUE TITLE
[fb_scrollByVector] why can not scroll to top?

### ISSUE THREAD

**Issue by lyt19871224** [facebook/WebDriverAgent#589]
Hi,
**code**:
d(class_name="XCUIElementTypeTable",index=num).scroll(direction="up")
when I run the code above,the table can not be scrolled to top

this image is the end status
![image](https://cloud.githubusercontent.com/assets/7929135/26198210/da2de604-3bf7-11e7-940a-58e94a47bed2.png)

but I want it scroll to this status
![image](https://cloud.githubusercontent.com/assets/7929135/26198334/3c58abd4-3bf8-11e7-9a2e-7736e8153421.png)

wda exit ,i think early
![image](https://cloud.githubusercontent.com/assets/7929135/26198350/489998f4-3bf8-11e7-8182-8b901a212395.png)

**Comment by marekcirkos** [comment]
Are you saying scroll up does not work?

**Comment by lyt19871224** [comment]
scroll up  works,but not scroll to the top . I think it should scroll to appear "今天" which second image .but the fb_scrollByVector perform to return ，it only scroll to "2017年06月"  which first image.

**Comment by lyt19871224** [comment]
it is a calendar component.  wda recognize it a table.    when I  click calendar to enter the page of date choice, eg. 2017-07-01 like image.  Now I want  switch date to  today, I use scrollup ,because the date of today  is on the fist page of calendar.

**Comment by marekcirkos** [comment]
`fb_scrollByVector` let's say `1.0` will scroll by one visible page, not to the top. Would it be possible for you to provide video form that scrolling and expected scroll position? It would be easier for me to understand what is happening there. Thanks!

**Comment by lyt19871224** [comment]
hi,I have push my video to below url.  Please try to get it from the URL.   
“Iwant.mov” is the target .    The other video is scrollup debug . 
链接: https://pan.baidu.com/s/1bo1FQeb 密码: krmd

**Comment by lyt19871224** [comment]
https://youtu.be/hPZ4tN-pDJc https://youtu.be/gdr-dc3rL1g

**Comment by lyt19871224** [comment]
https://youtu.be/hPZ4tN-pDJc
 https://youtu.be/gdr-dc3rL1g

**Comment by marekcirkos** [comment]
@lyt19871224 Thank you for submitting videos. It helped a lot to understand you issue here.
I think the problem here is that those elements are considered visible through some accessibility weirdness. I guess scroll stops after next month's days are loaded. 

I think tweaking visibility checks might help, otherwise not much we can do. I am sorry.
