### ISSUE TITLE
CPU and Memory usage

### ISSUE THREAD

**Issue by qakapil** [facebook/WebDriverAgent#592]
This is not a bug but a feature request. It will be might useful If WDA can offer some API endpoints which return back the performance data of the device under test like CPU usage, memory consumption etc.

**Comment by marekcirkos** [comment]
We run in context of iOS application, so it should be possible. Feel free to pop a PR on this :)

**Comment by qakapil** [comment]
Sure, I need to learn a bit of Obj-C first though :-)
