### ISSUE TITLE
Inspector shows empty tree of elements and inspector column after upgrading to Sierra and Xcode 8.3.2 

### ISSUE THREAD

**Issue by tcstang** [facebook/WebDriverAgent#600]
Inspector was working immediately before I updated to 8.3.2. I was actually using an older version of WebDriverAgent since I hadn't updated Xcode yet. The simulators after updating went from 10.2 to 10.3 (if that matters)

**Steps performed:**

1. Upgrade to Sierra through App store
2. Upgrade Xcode through App store
3. Ensured that `xcode-select -s "/path/to/application/developer"` was pointing at the right place
4. Launched inspector through command: 
`$ xcodebuild test -project "$PROJ_PATH" -scheme WebDriverAgentRunner -destination name=$someSimulator`
5. Navigate to localhost:8100/inspector

**Resulting page:**

<img width="735" alt="screen shot 2017-05-24 at 1 41 16 pm" src="https://cloud.githubusercontent.com/assets/6655566/26424920/c6acb3c8-4087-11e7-98ba-a66141e6bccd.png">

I tried checking out different commits in WebDriverAgent, including latest commit on master from today and also good commits I've used before in April, still same thing.

**Console logs:**

```
2017-05-24 13:50:35.109 xcodebuild[34097:1895912]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/josep/Library/Developer/Xcode/DerivedData/WebDriverAgent-emqeiskngicoewdqbsxsbkvxqxwm/Logs/Test/2D8F8344-02F8-47E3-838B-1C3C67208D31/Session-WebDriverAgentRunner-2017-05-24_135035-WQ5azp.log
2017-05-24 13:50:35.110 xcodebuild[34097:1895836] [MT] IDETestOperationsObserverDebug: (D8C14BAC-64F2-40C9-8C7A-8B6D0EC2508B) Beginning test session WebDriverAgentRunner-D8C14BAC-64F2-40C9-8C7A-8B6D0EC2508B at 2017-05-24 13:50:35.110 with Xcode 8E2002 on target <DVTiPhoneSimulator: 0x7fab2bfe62b0> {
		SimDevice: SimDevice : iPhone 7 Plus (F35816EB-ADC2-44B5-8F9F-047CAC38CC2F) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus } runtime={ SimRuntime : 10.3 (14E269) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3 (14E269))
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

2017-05-24 13:50:42.434 XCTRunner[34118:1898338] Running tests...
2017-05-24 13:50:43.105 XCTRunner[34118:1898338] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-05-24 13:50:43.230
Test Suite 'WebDriverAgentLib.framework' started at 2017-05-24 13:50:43.231
Test Suite 'WebDriverAgentLib.framework' passed at 2017-05-24 13:50:43.231.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-05-24 13:50:43.232
Test Suite 'UITestingUITests' started at 2017-05-24 13:50:43.232
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-05-24 13:50:43.233
    t =     0.00s     Set Up
2017-05-24 13:50:43.237 XCTRunner[34118:1898338] Built at May 24 2017 13:29:47
2017-05-24 13:50:43.255 XCTRunner[34118:1898338] ServerURLHere->http://10.252.115.146:8100<-ServerURLHere
    t =     3.62s     Find the Application "local.pid.32751" 0x6080000b9c80
    t =     3.62s         Snapshot accessibility hierarchy for local.pid.32751
    t =    16.59s     Find the Application "local.pid.34123" 0x6080000b9920
    t =    16.59s         Snapshot accessibility hierarchy for local.pid.34123
```

**Comment by marekcirkos** [comment]
Did you check if inspector works on any other app/screen e.g. SpringBoard?
From fraction of your screenshot I can see you have a lot of cell views, `/source` might be simply slow (used for fetching view hierarchy).

**Comment by tcstang** [comment]
Yeah, it never takes this long. Doesn't look like any page is showing anything.

![screen shot 2017-05-31 at 9 50 59 am](https://cloud.githubusercontent.com/assets/6655566/26643641/d56b723c-45e6-11e7-9965-cb927d32e6f8.png)

**Comment by tcstang** [comment]
Found this:

![image](https://cloud.githubusercontent.com/assets/6655566/26743311/2d5e7df8-4796-11e7-8e30-ea14e3ba6f1d.png)

**Comment by marekcirkos** [comment]
@tcstang We resolved some issues with inspector does it work for you now?

**Comment by tcstang** [comment]
@marekcirkos It does look like it has been resolved now. Thanks!
