### ISSUE TITLE
How to Ignore Animation Effects Waiting

### ISSUE THREAD

**Issue by HoonHee** [facebook/WebDriverAgent#605]
I know about "shouldWiatForQuiescence" when I created the Session by running the app with BundleID (updated 17 days ago).

I know I can run an app through Tap.
[FBApplication fb_activeApplication] can be used to fetch and control an app
However, the imported app is waiting while processing the animation effect in the main thread.
Is there a way to handle it without delay?

The default value of "FBApplication.fb_shouldWaitForQuiescence" is NO.
Is an app running as a Tap being tested by default value?

**Comment by marekcirkos** [comment]
I am not sure what do you mean by imported app? Do you mean that tested application waits till some animatos is finished and you want to force it to skip the animation? If so it is not possible, this way you would alter tested application.
