### ISSUE TITLE
Autonomous tests

### ISSUE THREAD

**Issue by nunof** [facebook/WebDriverAgent#607]
Is it possible to build WebDriverAgent, xctests and app IPAs (under appropriate provisioning profiles of course) so that we can send them to remote group of collaborators (simple end-users) to install and execute the test (that would use local WebDriverAgent)?

Thanks

**Comment by codeskyblue** [comment]
It is not easy anyway for end users.

**Comment by nunof** [comment]
I can understand that some code needs to be developed and/or some unorthodox build undertaken. I'm available to study and have developer skills. I was mainly trying to understand if there is something that fundamentally prohibits it (e.g. even Appium use of WebDriverAgent needs to be hooked to proprietary Apple (Xcode) libs to run its magic).

So, my first question is about being possible. I take it that it is, right?

Then my second question is: can you point me in the right direction? Docs and code that I can study an what would the main building blocks be?

Thanks.

**Comment by marekcirkos** [comment]
@nunof I am not sure what is your exact question here? What is the use case you try to investigate here?

**Comment by nunof** [comment]
@marekcirkos In a nutshell I'm trying to find out if it's possible to run/control WebDriverAgent from another iOS app instead of from OS X and XCode or if there's some proprietary magic that prevents this scenario from happening without Apple's blessing... 

Assuming provisioning profiles and app(s) signing is in place.

Thanks

**Comment by marekcirkos** [comment]
It will not be possible as far as I know, test manager, WDA, and some app on OSX need to have XPC connection in order to XCUITest work
