### ISSUE TITLE
Request: To support relative path for class chain

### ISSUE THREAD

**Issue by lavi-xu** [facebook/WebDriverAgent#610]
class chain would be great replacement for xpath on xcuitest.

However currently it only supports direct path lookup like this:
//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther[6]/XCUIElementTypeOther[4]

 We would like to have relative path support, so element would be like:
-> XCUIElementTypeNavigationBar / XCUIElementTypeTextField[2]
-> XCUIElementTypeOther[2] // XCUIElementTypeButton[`name beginswith "10."`]

BR.

**Comment by lavi-xu** [comment]
FYI.

When using nest locate methods like this:
driver.find_element_by_class_name('XCUIElementTypeCell').find_element_by_ios_classchain('XCUIElementTypeButton[1]').

Its also fast (like 3 seconds) when compared to only one classchain (within 1 second).

So high recommend that people should use this method before this issue get resolved.

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/pull/612

**Comment by lavi-xu** [comment]
@mykola-mokhnach 

I tried on appium 1.7.1. It works with find_element_by_ios_classchain now.
But with find_elements_by_ios_classchain (with 's'), the result does not work as expected.

I am trying to lookup all elements that it's 2nd XCUIElementTypeStaticText after XCUIElementTypeCell:
xpath -->  '//XCUIElementTypeCell/XCUIElementTypeStaticText[2]'
class chain --> '**/XCUIElementTypeCell/XCUIElementTypeStaticText[2]'

It returns only one element, it works like xpath blow of find_element_by_xpath:
'//XCUIElementTypeStaticText[2]'

**Comment by mykola-mokhnach** [comment]
yes, you need to split such chain locator into two to find all cells first and then to find the second text element in each cell in a loop. It's going to be fast, since search scope of a single cell is quite narrow.

**Comment by lavi-xu** [comment]
Ah maybe :)

Here is the fact that there are too many XCUIElementTypeCell without name attr(it has name in uiauto) indeed, so we have to locate all of them to find correct one.

However with xpath, it just a simple one step:
'//XCUIElementTypeStaticText[@name="Name"]/following::XCUIElementTypeStaticText'
'//XCUIElementTypeStaticText[@name="Age"]/following::XCUIElementTypeStaticText'

BR.

**Comment by lavi-xu** [comment]
'**/XCUIElementTypeCell[2]/XCUIElementTypeStaticText[2]' does not work as expected for single element.

**Comment by mykola-mokhnach** [comment]
Appium@beta has the PR https://github.com/facebook/WebDriverAgent/pull/707 merged, so you can search elements based on their descendants, for example to find all cells containing at least one text edit you should write something like:

```
**/XCUIElementTypeCell[$type == 'XCUIElementTypeStaticText'$]
```
