### ISSUE TITLE
WebDriverAgent fails to build on xCode 9 -beta

### ISSUE THREAD

**Issue by NicolaRettich1** [facebook/WebDriverAgent#611]
The problem

I was trying to execute our crossplatform appium tests using xCode 9 beta and see if it still works. Unfortunately, the WebDriverAgent does not build with the new xCode version. xCode tells me that "'new' is unavailable: Use XCUIElementQuery to create XCUIElement instances." for XCUIElement+FBClassChain.m
Is there a possibility to make it run without waiting for appium to be updated?

Environment

Appium version (or git revision) that exhibits the issue: 1.6.5
Desktop OS/version used to run Appium: OSX Sierra
Node.js version (unless using Appium.app|exe): 7.8.0
Mobile platform/version under test: iOS 10.3
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI

![screen shot 2017-06-08 at 13 58 56](https://user-images.githubusercontent.com/18442286/26929270-4f647034-4c59-11e7-8e2c-32d810405c32.png)

**Comment by ketan077** [comment]
same issue for me

**Comment by ketan077** [comment]
any solution??

**Comment by NicolaRettich1** [comment]
not yet

**Comment by marekcirkos** [comment]
Resolved.

**Comment by krishan83** [comment]
i am also getting same issue , will you share how resolved it.

**Comment by fabianaapateanu** [comment]
@marekcirkos how did you solve it? :) any hints? thanks!

**Comment by garatadi** [comment]
@marekcirkos Can you please share what should be done to resolve it.

**Comment by jjing0227** [comment]
@marekcirkos can you please share your solutions for the failure? Thank you

**Comment by Maxxer1** [comment]
For all of you who can't build WebDriverAgent in Xcode 9 it's because the WebDriverAgent project isn't updated in Appium 1.21. To fix it simply clone the repo from this link https://github.com/facebook/WebDriverAgent and replace it with downloaded WebDriverAgent with Appium. 
Also run ./Scripts/bootstrap.sh in this directory.

**Comment by anandbhayre2007** [comment]
@Maxxer1: As you mentioned I replaced the WebDriverAgent and was able successfully install the web driver agent in my device, but it damaged the appium, and when I tried to open it is mac is throwing an error like can't your appium is damaged and move it to thrash.

**Comment by Maxxer1** [comment]
@anandbhayre2007 Yeah i got this error. What I have done is to perform a clean installation of Appium, open the Appium program and then when the Appium is still opened you can make changes to the WebDriverAgent file. This should work.

**Comment by deepakkg88** [comment]
@Maxxer1  I tried the solution you suggested.it worked.But I am unable to open inspector.Getting error "No session exist".But I am able to run my code.I am using appium desktop 1.2.3 with server 1.7.1, Xcode-9, iOS-11.0.1
