### ISSUE TITLE
Periodically I see this error while running tests

### ISSUE THREAD

**Issue by livastar** [facebook/WebDriverAgent#613]
[main] INFO net.serenitybdd.core.Serenity - STEP ERROR: net.serenitybdd.core.exceptions.SerenityManagedException: An unknown server-side error occurred while processing the command. Original error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

(
	0   CoreFoundation                      0x000000010cf1eb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010c983141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ce3356d -[__NSPlaceholderArray initWithObjects:count:] + 269
	3   CoreFoundation                      0x000000010ce3a2b4 +[NSArray arrayWithObjects:count:] + 52
	4   XCTest                              0x000000010c37f4f7 -[XCElementSnapshot(Hitpoint) _transformPoint:windowContextID:windowDisplayID:] + 133
	5   XCTest                              0x000000010c37f8e9 -[XCElementSnapshot(Hitpoint) hitPoint] + 386
	6   WebDriverAgentLib                   0x000000011e6a88ea -[XCElementSnapshot(FBIsVisible) fb_isVisible] + 810
	7   WebDriverAgentLib                   0x000000011e6a859a -[XCUIElement(FBIsVisible) fb_isVisible] + 154
	8   WebDriverAgentLib                   0x000000011e6bcb44 -[XCUIElement(FBScrolling) fb_scrollToVisibleWithNormalizedScrollDistance:scrollDirection:error:] + 84
	9   WebDriverAgentLib                   0x000000011e6bcadf -[XCUIElement(FBScrolling) fb_scrollToVisibleWithNormalizedScrollDistance:error:] + 79
	10  WebDriverAgentLib                   0x000000011e6bca76 -[XCUIElement(FBScrolling) fb_scrollToVisibleWithError:] + 70
	11  WebDriverAgentLib                   0x000000011e6c8c61 +[FBElementCommands handleScrollElementToVisible:withRequest:] + 177
	12  WebDriverAgentLib                   0x000000011e6c6fcf +[FBElementCommands handleScroll:] + 1807
	13  WebDriverAgentLib                   0x000000011e6ab123 -[FBRoute_TargetAction mountRequest:intoResponse:] + 179
	14  WebDriverAgentLib                   0x000000011e6a2024 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548
	15  RoutingHTTPServer                   0x000000011e744c18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
	16  RoutingHTTPServer                   0x000000011e7454fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
	17  libdispatch.dylib                   0x000000011005f792 _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x00000001100484e0 _dispatch_barrier_sync_f_slow_invoke + 292
	19  libdispatch.dylib                   0x000000011005f792 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x0000000110047247 _dispatch_main_queue_callback_4CF + 1041
	21  CoreFoundation                      0x000000010cee3909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x000000010cea9ae4 __CFRunLoopRun + 2164
	23  CoreFoundation                      0x000000010cea9016 CFRunLoopRunSpecific + 406
	24  Foundation                          0x000000010c46c600 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274
	25  Foundation                          0x000000010c46c4db -[NSRunLoop(NSRunLoop) run] + 76
	26  WebDriverAgentLib                   0x000000011e6a1003 -[FBWebServer startServing] + 211
	27  WebDriverAgentRunner                0x000000011df40254 -[UITestingUITests testRunner] + 100
	28  CoreFoundation                      0x000000010cea6c6c __invoking___ + 140
	29  CoreFoundation                      0x000000010cea6b40 -[NSInvocation invoke] + 320
	30  XCTest                              0x000000010c3378e2 __24-[XCTestCase invokeTest]_block_invoke_2 + 491
	31  XCTest                              0x000000010c375f62 -[XCTestContext performInScope:] + 190
	32  XCTest                              0x000000010c3376e4 -[XCTestCase invokeTest] + 254
	33  XCTest                              0x000000010c337fb2 -[XCTestCase performTest:] + 565
	34  XCTest                              0x000000010c335078 __27-[XCTestSuite performTest:]_block_invoke + 300
	35  XCTest                              0x000000010c334c68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	36  XCTest                              0x000000010c334e4e -[XCTestSuite performTest:] + 214
	37  XCTest                              0x000000010c335078 __27-[XCTestSuite performTest:]_block_invoke + 300
	38  XCTest                              0x000000010c334c68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	39  XCTest                              0x000000010c334e4e -[XCTestSuite performTest:] + 214
	40  XCTest                              0x000000010c335078 __27-[XCTestSuite performTest:]_block_invoke + 300
	41  XCTest                              0x000000010c334c68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29
	42  XCTest                              0x000000010c334e4e -[XCTestSuite performTest:] + 214
	43  XCTest                              0x000000010c381a86 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
	44  XCTest                              0x000000010c343f27 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 574
	45  XCTest                              0x000000010c381925 -[XCTTestRunSession runTestsAndReturnError:] + 281
	46  XCTest                              0x000000010c31fa50 -[XCTestDriver runTestsAndReturnError:] + 254
	47  XCTest                              0x000000010c37986e _XCTestMain + 559
	48  CoreFoundation                      0x000000010cec4b5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	49  CoreFoundation                      0x000000010cea9e54 __CFRunLoopDoBlocks + 356
	50  CoreFoundation                      0x000000010cea95ee __CFRunLoopRun + 894
	51  CoreFoundation                      0x000000010cea9016 CFRunLoopRunSpecific + 406
	52  GraphicsServices                    0x000000010f373a24 GSEventRunModal + 62
	53  UIKit                               0x000000010d342134 UIApplicationMain + 159
	54  XCTRunner                           0x000000010c29f88b XCTRunner + 6283
	55  libdyld.dylib                       0x00000001100a865d start + 1
	56  ???                                 0x0000000000000005 0x0 + 5
) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.65 seconds

**Comment by andreiaionitoaiesv** [comment]
Hey same issue here. But for me is reproducing everytime when I run tests in the Amazon Device Farm.

https://gist.github.com/andreiaionitoaiesv/9d2e2fce56b6d15559822b1906f6b2ee

**Comment by marekcirkos** [comment]
This is known issue that we worked around by ugly try-catch. In that case visibility is resolved as negative so that test runner has a chance to retry, so It shouldn't be a big problem for you.
