### ISSUE TITLE
New Xcode 9 Feature - firstMatch

### ISSUE THREAD

**Issue by fabb** [facebook/WebDriverAgent#614]
Xcode 9 includes method `firstMatch` for fast queries, no need for snapshots.

https://developer.apple.com/documentation/xctest/xcuielementtypequeryprovider/2902250-firstmatch
https://developer.apple.com/wwdc17/409

**Comment by VasilijSviridov** [comment]
really good idea! More performance and fast queries please, not sure how this will work with WebViews data, but lets hope at least a bit faster than it is now =)

**Comment by marekcirkos** [comment]
That definitely should help with `findElement` endpoint and when resolving elements from cache. :)

**Comment by mykola-mokhnach** [comment]
@marekcirkos I would love to add the necessary improvements it after WDA sources will be compatible with Xcode9 and iOS11 XCTest toolkit

**Comment by marekcirkos** [comment]
Diff merged
