### ISSUE TITLE
Unable to launch the quick settings on Iphone

### ISSUE THREAD

**Issue by vathsalahn** [facebook/WebDriverAgent#616]
I was trying to lunch quick settings by swiping up using co ordinates so i followed the steps mentioned below

- Launched Settings app on Iphone
- Getting the Window Size .This returns Width and Height. 
- Swipe using s.swipe(width/2,Height,width/2,0,0.5).But this is unable to launch quick settings , instead it swipes on the app screen.

Is there any other way to launch this quick settings application??

**Comment by marekcirkos** [comment]
Without any logs and responses from WDA I cannot help you here.
