### ISSUE TITLE
iOS 11 and new XCUITest. Xcode 9. XCUITest has changed API.

### ISSUE THREAD

**Issue by JonGabilondoAngulo** [facebook/WebDriverAgent#618]
Hi,
after fixing the compilation problems with Xcode 9 iOS 11 the problem go to runtime. 
For instance, there is no "appWithPID" method in XCUIApplication anymore. 
An important step for all commands is to get the current App. Now it breaks due to that missing method.
A new class dump for the private XCUITest API seems necessary and to start to find out the new way of working.
Can anyone share what are the efforts/plans to make it this WDA Agent iOS 11 compatible ?
Thanks.

+ (instancetype)appWithPID:(pid_t)processID
{
  if ([NSProcessInfo processInfo].processIdentifier == processID) {
    return nil;
  }
  FBApplication *application = [self fb_registeredApplicationWithProcessID:processID];
  if (application) {
    return application;
  }
  application = [super appWithPID:processID];
  [FBApplication fb_registerApplication:application withProcessID:processID];
  return application;
}

**Comment by VasilijSviridov** [comment]
That is true, that they changed Xcode9 XCUIT library API, but for those who wants to use Xcode8 with test packs, there is a hack how you can add support of ios11 to Xcode8 and run your test cases.
https://stackoverflow.com/questions/44381860/use-xcode-8-with-ios-11

**Comment by JonGabilondoAngulo** [comment]
I see, using Xcode 8 is embedding the ios10 XCTest.framework inside the runner. It works. Thanks.

**Comment by VasilijSviridov** [comment]
No worries, the only thing you won't be able to use new XCUIT API with new brilliant features until devs build a new runner =) but so far so good =)

Cheers

**Comment by alter-al** [comment]
Hi, 
I could not run WDA with Xcode9 Beta on iOS11.
I was copy ios11 image to Xcode8 and  launched WDA with Xcode8 on iOS11. Good. But WDA wasn't create ServerURL, because it hung up on tests:

    === BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

    Check dependencies

    writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/db/0bc6qccn54qd62hm51nkd3fc0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/050558c3bb0e832c64662ce14dab505f/f1110562a65f46c80e7ba32c50ce62af056a1c3c/ManifestCache.plist
    2017-06-14 17:01:35.483062+0300 XCTRunner[403:30062] Running tests...

Can u advice me?

**Comment by VasilijSviridov** [comment]
Looks fine on my side, and note that this is a hack how to run future DeviceSupport on Xcode 8. 
Am tested this on real iPhone 6s  iOS 11.0 device, 
If you are running via real device or emulator, I would suggest you to run [test] WDA via xcode and check any errors there.

    2017-06-14 15:28:22.647404+0100 XCTRunner[360:7608] Running tests...
        2017-06-14 15:28:24.283055+0100 XCTRunner[360:7608] Continuing to run tests in the background with task ID 1
        Test Suite 'All tests' started at 2017-06-14 15:28:25.737
        Test Suite 'WebDriverAgentRunner.xctest' started at 2017-06-14 15:28:25.738
        Test Suite 'UITestingUITests' started at 2017-06-14 15:28:25.739
        Test Case '-[UITestingUITests testRunner]' started.
        t =     0.00s     Start Test at 2017-06-14 15:28:25.740
        t =     0.00s     Set Up
        2017-06-14 15:28:25.754994+0100 XCTRunner[360:7608] Built at Jun 14 2017 11:38:17
        2017-06-14 15:28:25.785849+0100 XCTRunner[360:7608] ServerURLHere->http://**.**.**.**:***<-ServerURLHere

**Comment by alter-al** [comment]
I using real device. This is my log in Xcode8 (after 2-3min hung up on tests):

    2017-06-14 19:21:28.290300+0300 XCTRunner[404:32215] Running tests...
    thread #1: tid = 0x7dd7, 0x00000001a9c02e04 libsystem_kernel.dylib`mach_msg_trap + 8, stop reason = signal SIGSTOP
    frame #0: 0x00000001a9c02e04 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x00000001a9c02c7c libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x00000001863c2bec CoreFoundation`__CFRunLoopServiceMachPort + 196
    frame #3: 0x00000001863c06f4 CoreFoundation`__CFRunLoopRun + 1208
    frame #4: 0x00000001862db03c CoreFoundation`CFRunLoopRunSpecific + 436
    frame #5: 0x0000000187ff7fa0 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
    frame #6: 0x0000000103018394 XCTest`-[XCTestDriver _checkForTestManager] + 264
    frame #7: 0x0000000103064164 XCTest`_XCTestMain + 628
    frame #8: 0x00000001863c3074 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
    frame #9: 0x00000001863c2868 CoreFoundation`__CFRunLoopDoBlocks + 288
    frame #10: 0x00000001863c0590 CoreFoundation`__CFRunLoopRun + 852
    frame #11: 0x00000001862db03c CoreFoundation`CFRunLoopRunSpecific + 436
    frame #12: 0x0000000196b4ef94 GraphicsServices`GSEventRunModal + 100
    frame #13: 0x000000018d2a086c UIKit`UIApplicationMain + 208
    frame #14: 0x0000000102f803d4 XCTRunner`___lldb_unnamed_symbol9$$XCTRunner + 56
    frame #15: 0x00000001a9afbd1c libdyld.dylib`start + 4

    thread #5: tid = 0x7e05, 0x00000001a9c23e1c libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #0: 0x00000001a9c23e1c libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x00000001a9d231b8 libsystem_pthread.dylib`_pthread_wqthread + 876
    frame #2: 0x00000001a9d22e40 libsystem_pthread.dylib`start_wqthread + 4

    thread #8: tid = 0x7e08, 0x00000001a9c02e04 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #0: 0x00000001a9c02e04 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x00000001a9c02c7c libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x00000001863c2bec CoreFoundation`__CFRunLoopServiceMachPort + 196
    frame #3: 0x00000001863c06f4 CoreFoundation`__CFRunLoopRun + 1208
    frame #4: 0x00000001862db03c CoreFoundation`CFRunLoopRunSpecific + 436
    frame #5: 0x0000000187ff7fa0 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
    frame #6: 0x0000000188018764 Foundation`-[NSRunLoop(NSRunLoop) runUntilDate:] + 96
    frame #7: 0x000000018dd92270 UIKit`-[UIEventFetcher threadMain] + 136
    frame #8: 0x00000001880fa634 Foundation`__NSThread__start__ + 996
    frame #9: 0x00000001a9d24538 libsystem_pthread.dylib`_pthread_body + 256
    frame #10: 0x00000001a9d24438 libsystem_pthread.dylib`_pthread_start + 368
    frame #11: 0x00000001a9d22e48 libsystem_pthread.dylib`thread_start + 4

    thread #9: tid = 0x7f11, 0x00000001a9c23e1c libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #0: 0x00000001a9c23e1c libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x00000001a9d231b8 libsystem_pthread.dylib`_pthread_wqthread + 876
    frame #2: 0x00000001a9d22e40 libsystem_pthread.dylib`start_wqthread + 4


    *** If you believe this error represents a bug, please attach the log file at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/D647214C-9A39-490C-B803-E04AC58996CA/Session-WebDriverAgentRunner-2017-06-14_192114-cWv1WS.log

**Comment by alter-al** [comment]
It was in log file:

    20:30:39.182 Xcode[4512:182894] Beginning test session WebDriverAgentRunner-EEE324F0-6232-4E6F-87F1-3412F2D45702 at 2017-06-14 20:30:39.181 with Xcode 8C1002 on target 
    <DVTiOSDevice: 0x7fcf6ce9d6f0> {
		deviceSerialNumber:         C7CS9ACJHG70
		identifier:                 f1e10562a65f46c80e7ba32c50ce62af056a1c3c
		deviceClass:                iPhone
		deviceName:                 iPhone (Target)
		deviceIdentifier:           f1e10562a65f46c80e7ba32c50ce62af056a1c3c
		productVersion:             11.0
		buildVersion:               15A5278f
		deviceSoftwareVersion:      11.0 (15A5278f)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        28786896896
		deviceAvailableCapacity:    21952991232
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fcf67853510 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
    )
    applications:              {(
    <DTDKApplication: 0x7fcf67db9710>: MyTargetTestApp (/private/var/containers/Bundle/Application/61505B93-97DF-4932-9EAB-3EE9492734EF/MyTargetTestApp.app),
    <DTDKApplication: 0x7fcf6d85f990>: Battery (/private/var/containers/Bundle/Application/5B83783F-0B14-4EC3-A526-FBC82F849F37/kBatteryDoctor.app),
    <DTDKApplication: 0x7fcf64d827f0>: Delivery Club (/private/var/containers/Bundle/Application/DE9B67A1-B6F4-45B3-B75E-CEEA280FBBEF/DeliveryClub.app),
    <DTDKApplication: 0x7fcf677c2c20>: KupiVip Дети (/private/var/containers/Bundle/Application/8E2BBC54-746A-47C2-BC30-4A73093AF8B2/KupiVipKids.app),
    <DTDKApplication: 0x7fcf67104d50>: Developer Info (/private/var/containers/Bundle/Application/5E12DB12-67BE-4F15-A6D8-70E6CF4EF994/Developer Info.app),
    <DTDKApplication: 0x7fcf6d9eb630>: Money (/private/var/containers/Bundle/Application/6C38200B-A8F9-48E9-8FE3-0362806FF259/YandexMoney.app),
    <DTDKApplication: 0x7fcf64d81b90>: Новости (/private/var/containers/Bundle/Application/2D0F7FB9-43A1-452A-9510-44AE71A7672C/MailNews_Beta.app),
    <DTDKApplication: 0x7fcf64d84220>: MyTrackerTestAppDev (/private/var/containers/Bundle/Application/D0DD2FED-5548-46AE-9D1B-344548F24D18/MyTrackerTestAppDev 2.app),
    <DTDKApplication: 0x7fcf6e1a1110>: Artisto (/private/var/containers/Bundle/Application/07A2B6B6-FB66-4616-B630-46369710BB38/Artisto.app),
    <DTDKApplication: 0x7fcf64d81890>: SC Heroes (/private/var/containers/Bundle/Application/852ED164-5F75-4483-95C7-8AEDFC1DB782/scmdev.app),
    <DTDKApplication: 0x7fcf64d81b40>: maps.me beta (/private/var/containers/Bundle/Application/3913C8BB-2F58-48C7-9E73-5D2150EA7C5C/maps.me beta.app),
    <DTDKApplication: 0x7fcf6d9f7a30>: DragonML (/private/var/containers/Bundle/Application/A564F178-0234-4382-85DC-0BF3AA181FFC/DragonManiaLegends.app),
    <DTDKApplication: 0x7fcf6d9f71e0>: BeepCar (/private/var/containers/Bundle/Application/B8CCCB5C-E6F0-4B23-BBE7-D49EAB85110D/RideShare-AlphaEnterprise.app),
    <DTDKApplication: 0x7fcf6e1ab900>: VK (/private/var/containers/Bundle/Application/0A0E63B5-BBE9-47F8-99F9-11339515CE00/vkclient.app),
    <DTDKApplication: 0x7fcf6e185780>: HEALBE GoBe (/private/var/containers/Bundle/Application/47A0919B-E514-44BA-8E8B-F778BC61CF68/HEALBE GoBe.app),
    <DTDKApplication: 0x7fcf6e1ab300>: DH5 (/private/var/containers/Bundle/Application/01A6DC0C-FBA4-417B-9464-4F9A3B7C8282/DungeonHunter5.app),
    <DTDKApplication: 0x7fcf6e1a1070>: Uber (/private/var/containers/Bundle/Application/6F38AADD-479F-452F-935A-1A16C4F636E9/Helix.app),
    <DTDKApplication: 0x7fcf6d9f8870>: TestFlight (/private/var/containers/Bundle/Application/43B53066-F2E9-4909-8FFD-BB4A7A844FB8/TestFlight.app),
    <DTDKApplication: 0x7fcf67740c90>: Mail.Ru (/private/var/containers/Bundle/Application/539A6FD4-E58D-4022-B6DF-2F67FA225DBC/MRMail.app),
    <DTDKApplication: 0x7fcf64d82a00>: Mycom.Target.Unity (/private/var/containers/Bundle/Application/116E6C59-FA06-491A-A7D7-2CB30C803118/unity.app),
    <DTDKApplication: 0x7fcf64d82c80>: OK (/private/var/containers/Bundle/Application/B499163B-F0CE-4936-A3D0-436B789549E5/Odnoklassniki.app),
    <DTDKApplication: 0x7fcf6db42bd0>: My TUNE Device (/private/var/containers/Bundle/Application/6334CE0B-D446-458A-82D0-3989C596D94B/myTUNEdevice.app),
    <DTDKApplication: 0x7fcf6e1aeba0>: IntegrationApp (/private/var/containers/Bundle/Application/9CEEE9A3-38C5-4B42-AE2F-FC081E1C6A71/IntegrationApp.app),
    <DTDKApplication: 0x7fcf6e1a10c0>: Empires (/private/var/containers/Bundle/Application/DD0124BD-5A3A-45E6-AC96-47F9C4F92E26/MarchOfEmpires.app),
    <DTDKApplication: 0x7fcf6d9f7c40>: myTargetDemo (/private/var/containers/Bundle/Application/70AF4C08-5ACF-41FC-8E36-00EFF9D6477C/myTargetDemo.app),
    <DTDKApplication: 0x7fcf64d7ef90>: РосШтрафы (/private/var/containers/Bundle/Application/2752C960-C606-4F1A-B5B0-5E6FE803F85E/RosFines AppStore.app),
    <DTDKApplication: 0x7fcf64d818e0>: IntegrationApp (/private/var/containers/Bundle/Application/33F4AC30-D78F-4FF0-AB83-9DE1FE4FE1AA/IntegrationApp.app),
    <DTDKApplication: 0x7fcf67db96c0>: ЦИАН (/private/var/containers/Bundle/Application/78EBEADC-F323-434E-9A68-A5298B64CB9D/ЦИАН.app),
    <DTDKApplication: 0x7fcf6d9f8a40>: ICQ (/private/var/containers/Bundle/Application/0B01A5EB-075D-4983-A4D5-1171B0F1455E/ICQ.app),
    <DTDKApplication: 0x7fcf6db41d70>: Jungle Heat (/private/var/containers/Bundle/Application/93FEB46E-2D46-4BF9-A770-305E8394B6FD/jungleheat.app),
    <DTDKApplication: 0x7fcf6e1b21a0>: Yandex.Maps (/private/var/containers/Bundle/Application/BDFF1AB1-B3B3-4854-A52A-4ABBB0C41204/YandexMaps.app),
    <DTDKApplication: 0x7fcf6770ab80>: Green Riding Hood (/private/var/containers/Bundle/Application/604C8EA8-7A10-4719-8CF5-DB4687AA86A9/greenridinghood.app)
    )}
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
    (null)
	} (11.0 (15A5278f))
    20:30:39.182 Xcode[4512:182894] Launching with Xcode.DebuggerFoundation.Launcher.LLDB
    20:30:39.188 Xcode[4512:182894] Initializing test infrastructure.
    20:30:39.455 Xcode[4512:481741] Creating the test bundle connection.
    20:30:39.455 Xcode[4512:481741] Listening for proxy connection request from the test bundle (all platforms)
    20:30:39.455 Xcode[4512:481741] Resuming the connection.
    20:30:39.455 Xcode[4512:481741] Test connection requires daemon assistance.
    20:30:39.456 Xcode[4512:182894] Starting test session with ID EEE324F0-6232-4E6F-87F1-3412F2D45702
    20:30:39.457 Xcode[4512:182894] Checking test manager availability..., will wait up to 120s
    20:30:39.507 Xcode[4512:481488] testmanagerd handled session request.
    20:30:39.507 Xcode[4512:182894] Waiting for test process to launch.
    20:30:42.421 Xcode[4512:182894] Launch session started, setting a disallow-finish-token on the run operation.
    20:30:42.509 Xcode[4512:486346] app uninstall set - {(
    )}
    20:30:42.509 Xcode[4512:486346] app install set - {(
    <DVTFilePath:0x7fcf6aeaa3f0:'/Users/a.alterpesotskiy/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app'>
    )}
    20:30:46.050 Xcode[4512:486359] remoteExecutable setInstalledPath:/private/var/containers/Bundle/Application/43F5D4F8-5B49-4F6C-AE69-9B2FE04F0BE7/WebDriverAgentRunner-Runner.app

    20:30:46.052 Xcode[4512:486359] Updated test configuration at /var/folders/db/0bc6qccn54qd62hm51nkd3fc0000gp/T/com.apple.dt.XCTest/EEE324F0-6232-4E6F-87F1-3412F2D45702/remote-container/tmp/WebDriverAgentRunner-EEE324F0-6232-4E6F-87F1-3412F2D45702.xctestconfiguration with device paths: <XCTestConfiguration: 0x7fcf6dc144b0>
	                  testBundleURL:file:///private/var/containers/Bundle/Application/43F5D4F8-5B49-4F6C-AE69-9B2FE04F0BE7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
	         testBundleRelativePath:(null)
	              productModuleName:WebDriverAgentRunner
	                    testsToSkip:(null)
	                     testsToRun:UITestingUITests/testRunner
	             reportResultsToIDE:YES
	              sessionIdentifier:EEE324F0-6232-4E6F-87F1-3412F2D45702
	     pathToXcodeReportingSocket:(null)
	      disablePerformanceMetrics:no
	treatMissingBaselinesAsFailures:no
	                baselineFileURL:(null)
	       baselineFileRelativePath:(null)
	          targetApplicationPath:(null)
	      targetApplicationBundleID:(null)
	               reportActivities:YES
	       testsMustRunOnMainThread:YES
	         initializeForUITesting:YES
	 aggregateStatisticsBeforeCrash:{
    XCSuiteRecordsKey =     {
    };
    }

    20:30:47.802 Xcode[4512:486359] Uploaded test configuration directory from: /var/folders/db/0bc6qccn54qd62hm51nkd3fc0000gp/T/com.apple.dt.XCTest/EEE324F0-6232-4E6F-87F1-3412F2D45702/remote-container
    20:30:47.802 Xcode[4512:486359] Updated testing environment variables {
    "DTX_CONNECTION_SERVICES_PATH" = "/Developer/Library/PrivateFrameworks/DTXConnectionServices.framework";
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/43F5D4F8-5B49-4F6C-AE69-9B2FE04F0BE7/WebDriverAgentRunner-Runner.app/Frameworks:/Users/a.alterpesotskiy/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/43F5D4F8-5B49-4F6C-AE69-9B2FE04F0BE7/WebDriverAgentRunner-Runner.app/Frameworks:/Users/a.alterpesotskiy/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks";
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/5F8ABEFD-4427-443B-BE35-03EC4520F34D/tmp/WebDriverAgentRunner-EEE324F0-6232-4E6F-87F1-3412F2D45702.xctestconfiguration";
    }
    20:30:48.902 Xcode[4512:486359] Started debugserver on device. fd = 52
    20:30:51.961 Xcode[4512:182894] Adding console adaptor <IDEConsoleAdaptor: 0x7fcf6c39d820 'target'> for test session EEE324F0-6232-4E6F-87F1-3412F2D45702.
    20:30:53.529 Xcode[4512:182894] Launch session finished initial intensive file IO.
    20:30:53.529 Xcode[4512:182894] Waiting for test process to check in..., will wait up to 120s
    20:30:53.529 Xcode[4512:182894] Test process runnable PID is 435.
    20:32:54.059 Xcode[4512:182894] Clearing timeout timer while paused in the debugger. Timeout conditions may not be detected during this session.
    20:32:54.061 Xcode[4512:182894] Test process thread state:
    (lldb) 
    20:32:54.133 Xcode[4512:182894] Test process thread state:
    thread #1: tid = 0xa89b, 0x00000001a9c02e04 libsystem_kernel.dylib`mach_msg_trap + 8, stop reason = signal SIGSTOP

    20:32:54.133 Xcode[4512:182894] Test process thread state:
    frame #0: 0x00000001a9c02e04 libsystem_kernel.dylib`mach_msg_trap + 8

    20:32:54.133 Xcode[4512:182894] Test process thread state:
    frame #1: 0x00000001a9c02c7c libsystem_kernel.dylib`mach_msg + 72

    20:32:54.133 Xcode[4512:182894] Test process thread state:
    frame #2: 0x00000001863c2bec CoreFoundation`__CFRunLoopServiceMachPort + 196

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #3: 0x00000001863c06f4 CoreFoundation`__CFRunLoopRun + 1208

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #4: 0x00000001862db03c CoreFoundation`CFRunLoopRunSpecific + 436

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #5: 0x0000000187ff7fa0 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #6: 0x0000000100e9c394 XCTest`-[XCTestDriver _checkForTestManager] + 264

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #7: 0x0000000100ee8164 XCTest`_XCTestMain + 628

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #8: 0x00000001863c3074 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #9: 0x00000001863c2868 CoreFoundation`__CFRunLoopDoBlocks + 288

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #10: 0x00000001863c0590 CoreFoundation`__CFRunLoopRun + 852

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #11: 0x00000001862db03c CoreFoundation`CFRunLoopRunSpecific + 436

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #12: 0x0000000196b4ef94 GraphicsServices`GSEventRunModal + 100

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #13: 0x000000018d2a086c UIKit`UIApplicationMain + 208

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #14: 0x0000000100e083d4 XCTRunner`___lldb_unnamed_symbol9$$XCTRunner + 56

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #15: 0x00000001a9afbd1c libdyld.dylib`start + 4

    20:32:54.134 Xcode[4512:182894] Test process thread state:


    20:32:54.134 Xcode[4512:182894] Test process thread state:
    thread #5: tid = 0xa8e8, 0x00000001a9c23e1c libsystem_kernel.dylib`__workq_kernreturn + 8

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #0: 0x00000001a9c23e1c libsystem_kernel.dylib`__workq_kernreturn + 8

    20:32:54.134 Xcode[4512:182894] Test process thread state:
    frame #1: 0x00000001a9d231b8 libsystem_pthread.dylib`_pthread_wqthread + 876

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #2: 0x00000001a9d22e40 libsystem_pthread.dylib`start_wqthread + 4

    20:32:54.135 Xcode[4512:182894] Test process thread state:


    20:32:54.135 Xcode[4512:182894] Test process thread state:
    thread #8: tid = 0xa8ec, 0x00000001a9c02e04 libsystem_kernel.dylib`mach_msg_trap + 8

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #0: 0x00000001a9c02e04 libsystem_kernel.dylib`mach_msg_trap + 8

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #1: 0x00000001a9c02c7c libsystem_kernel.dylib`mach_msg + 72

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #2: 0x00000001863c2bec CoreFoundation`__CFRunLoopServiceMachPort + 196

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #3: 0x00000001863c06f4 CoreFoundation`__CFRunLoopRun + 1208

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #4: 0x00000001862db03c CoreFoundation`CFRunLoopRunSpecific + 436

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #5: 0x0000000187ff7fa0 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #6: 0x0000000188018764 Foundation`-[NSRunLoop(NSRunLoop) runUntilDate:] + 96

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #7: 0x000000018dd92270 UIKit`-[UIEventFetcher threadMain] + 136

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #8: 0x00000001880fa634 Foundation`__NSThread__start__ + 996

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #9: 0x00000001a9d24538 libsystem_pthread.dylib`_pthread_body + 256

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #10: 0x00000001a9d24438 libsystem_pthread.dylib`_pthread_start + 368

    20:32:54.135 Xcode[4512:182894] Test process thread state:
    frame #11: 0x00000001a9d22e48 libsystem_pthread.dylib`thread_start + 4

    20:32:54.172 Xcode[4512:182894] Test operation failure: Canceling tests due to timeout in Waiting for test process to check in...
    20:32:54.172 Xcode[4512:182894] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Canceling tests due to timeout in Waiting for test process to check in..." UserInfo={NSLocalizedDescription=Canceling tests due to timeout in Waiting for test process to check in...} didCancel: 1

**Comment by VasilijSviridov** [comment]
Hm,,, do you have both Xcode 8 and Xcode 9 beta ? maybe you should use switch to set the default Xcode 8 ?

**Comment by VasilijSviridov** [comment]
also could you try running not on ios11, and check weather your configuration working properly with 10* versions

**Comment by alter-al** [comment]
I solved my problem.
I updated Xcode from 8.2.1 to 8.3.3 and all will works.
Thanks.

**Comment by marekcirkos** [comment]
Fix for thishttps://github.com/facebook/WebDriverAgent/issues/639
