### ISSUE TITLE
iPhone 6 S Plus can not run XCTRunner

### ISSUE THREAD

**Issue by atulparate** [facebook/WebDriverAgent#619]
Hi,

Please find the below configuration of the machine and mobile,

Appium :-1.1.0-beta.2
MacOS :- 10.12.13(Sierra)
Iphone :- Iphone 6 S Plus (OS - 10.3.2)
Xcode :- 8.3.3

Unable to run the Appium script on iPhone 6 S getting error as XCTRunner does not have an architecture that iPhone 6 S can execute.

Please find the attached Appium log for the same.

Thanks,
Atul S Parate

 

[AppiumLogFile.zip](https://github.com/facebook/WebDriverAgent/files/1071842/AppiumLogFile.zip)

**Comment by VasilijSviridov** [comment]
@atulparate suppose you have to run xcode and wait until your new device passes symbol files within xcode, seems that the test didn't even started means it could be smth with provisioning profiles as well.  Logs: Early unexpected exit, operation never finished bootstrapping
Cheers

**Comment by marekcirkos** [comment]
@atulparate Did it help? I would also clean project, and remove app from device if it is installed.
