### ISSUE TITLE
Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Failed to make any progress while clearing text.

### ISSUE THREAD

**Issue by mmcintyre123** [facebook/WebDriverAgent#624]
I am writing automated tests for an ios mobile app using Node.js, Appium, Mocha.

Suddenly today I am having problem moving between fields on our login screen.  The failing code is as follows:

    
    return driver
        .waitForElementById('username')
        .clear()
        .sendKeys('username') //works up to here
        .waitForElementById('password')
        .clear() //this clears the username and results in the error below
    
    
    error {"message":"[element.clear()] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 \"Failed to make any progress while clearing text\" UserInfo={NSLocalizedDescription=Failed to make any progress while clearing text}","status":13,"cause":{"status":13,"value":{"message":"An unknown server-side e...

**Comment by mmcintyre123** [comment]
Duplicate of #606 and possibly #603.

**Comment by haseebzagir** [comment]
Toggle the software keyboard under Hardware > Keyboard > Software Keyboard or Cmd + K and see your textfields working like a charm.
