### ISSUE TITLE
An unknown error message 'EscrowFailure', when starting WDA tests

### ISSUE THREAD

**Issue by alter-al** [facebook/WebDriverAgent#627]
Strange Xcode error, when I am starting WDA-Runner tests:

    An unknown error message 'EscrowFailure', was received from the device.

Environment:
- iPad 4
- iOS 10.3.2
- Xcode 8.3.3
- osx Sierra

**Comment by marekcirkos** [comment]
I have never seen it. Did you manage to resolve it?
