### ISSUE TITLE
Swiping/Scrolling has no inertia

### ISSUE THREAD

**Issue by b1ueshad0w** [facebook/WebDriverAgent#629]
It's easy to perform a swiping with inertia with fingers. But I find it's no way to do so with WDA or XCTest. The scroll speed will keep unchanged and then become zero. Any ideas on this?

**Comment by mykola-mokhnach** [comment]
There is dedicated _/wda/element/:uuid/swipe_ method for swiping. Have you tried it?

**Comment by marekcirkos** [comment]
@b1ueshad0w ?
