### ISSUE TITLE
no suitable image found.  Did find

### ISSUE THREAD

**Issue by lengyao88** [facebook/WebDriverAgent#631]
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/8A16AFF1-4B0E-4DEF-A2AE-C5F4EAE26DB8/WebDriverAgentRunner-Runner.app/XCTRunner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/8A16AFF1-4B0E-4DEF-A2AE-C5F4EAE26DB8/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/8A16AFF1-4B0E-4DEF-A2AE-C5F4EAE26DB8/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/8A16AFF1-4B0E-4DEF-A2AE-C5F4EAE26DB8/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/8A16AFF1-4B0E-4DEF-A2AE-C5F4EAE26DB8/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
(lldb)

**Comment by zhuguoqiang** [comment]
@lengyao88   do you code signing  with target WebDriverAgentRuner
