### ISSUE TITLE
use iproxy 127.0.0.1 can connect iphone but ip address can't connect iphone

### ISSUE THREAD

**Issue by pluie-cloud** [facebook/WebDriverAgent#634]
use iproxy 127.0.0.1 can connect iphone but ip address can't connect iphone
when i use webdriveragent,i excute iproxy 8100 8100,i can access 127.0.0.1:8100 but can't access 10.243.242.19:8100 10.243.242.19 is my ip.

**Comment by VasilijSviridov** [comment]
I suppose you need to use it like this: 
1. Start WDA with port 8100
2. Check WDA log , it will say which IP address your device is running.
3. If you want to forward  WDA IP:PORT to localhost:PORT use iproxy: iproxy 8100 8100 UniqueDeviceId.

If you have questions about routing your IP address this is not the place to ask about routing.

**Comment by marekcirkos** [comment]
This is definitely not WDA issue, I bet is on routing. I would assume local proxy protests is not exposed to public network
