### ISSUE TITLE
Unhandled endpoint when swiping

### ISSUE THREAD

**Issue by andreiaionitoaiesv** [facebook/WebDriverAgent#637]
Appium v1.6.5
platformName: 'iOS'
platformVersion: '10.0.2'
XCUITestDriver version: 2.30.0
[XCUITest] Xcode version set to '7.3' 
[debug] [XCUITest] iOS SDK Version set to '11.0'
Appium-Python Client

So I'm trying to make a swipe to element and nothing happens. I've tried using:

```
 action = TouchAction(self)
 action.press(origin_el).move_to(destination_el).release().perform()
```
and

`self.driver.execute_script('mobile: scroll', {'name': accesibilityID, 'direction': 'down'})`

Both are failing with

self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x7f9d03117c50>
response = {'status': 500, 'value': '{"status":13,"value":{"message":"An unknown server-side error occurred while processing the ...lement/64B3C4E7-966E-4E00-8DD1-7059DE52EF0A/scroll\"\n    );\n}"},"sessionId":"9d240acd-0f99-4f76-a119-f4a524d6cc7e"}'}

In appium logs i see this:

2017-07-07 08:00:36:451 - [debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/20855DB0-87E5-4FB3-9477-244E18DD37AC/wda/element/64B3C4E7-966E-4E00-8DD1-7059DE52EF0A/scroll -- http://127.0.0.1:8100/ with parameters {\n    wildcards =     (\n        \"session/20855DB0-87E5-4FB3-9477-244E18DD37AC/wda/element/64B3C4E7-966E-4E00-8DD1-7059DE52EF0A/scroll\"\n    );\n}","sessionId":"20855DB0-87E5-4FB3-9477-244E18DD37AC","status":1}

**Comment by mykola-mokhnach** [comment]
There was a bug in WDA, which has been recently fixed. Please try Appium 1.6.6-beta, which contains the recent WDA snapshot

**Comment by andreiaionitoaiesv** [comment]
Yeah thanks. But here's the weird part. The issue described is happening in AWS Device Farm context. On my local environment I have the same setup (except Xcode which is 8.3.3). And it works. Any ideas for a workaround?

**Comment by mykola-mokhnach** [comment]
It might be than an olderer version of WebDriverAgent runner is cached on the device there, so you need to remove it manually first and then start your tests with new Appium.

**Comment by marekcirkos** [comment]
I guess this can be closed now?

**Comment by mog0202** [comment]
I have encountered the same problem, who can help me.
