### ISSUE TITLE
WDA don't work, but /status tells that everything is OK

### ISSUE THREAD

**Issue by crazyk2** [facebook/WebDriverAgent#643]
Sorry for my English.
I use Appium latest version and faced with problem when I use WDA. I use such capabilities in order to run my test case 
```capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
       capabilities.setCapability(MobileCapabilityType.APP, "/Users/user/IdeaProjects/MobileService//Messenger.app";
       capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);    
       capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, device.getVersion());
       capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, ((IOSDevice) device).getName());
       capabilities.setCapability(MobileCapabilityType.UDID, device.getUdid());  
       
       capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
       capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
       capabilities.setCapability(IOSMobileCapabilityType.USE_NEW_WDA, false);
       
       return capabilities;
```
[appium issue](https://github.com/appium/appium/issues/8818)

Its means that I don't want to reinstall my app and WDA on simulator.

And I might kill appium node and when I start new node and create new session with Appium it try to connect with already working WDA instance by sending `GET` query `Proxying [GET /status] to [GET http://localhost:8100/status] with no body` and if it received answer then it try to create session by `Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"ru.ncloudtech.messenger","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}`.

When Appium starts (or I start by command line 'xcodebuild build-for-testing test-without-building -project /Users/user/driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=444B894A-22EF-4277-91FF-384C0EEE3A93 IPHONEOS_DEPLOYMENT_TARGET=10.3') I have two process which I found with command `ps aux|grep WebDriver`
 ```
user             47227   0,0  0,4  2839308  70616   ??  Ss    5:53     0:00.95 /Users/user/Library/Developer/CoreSimulator/Devices/444B894A-22EF-4277-91FF-384C0EEE3A93/data/Containers/Bundle/Application/0A3D5744-6FF4-4D53-AFFA-3ED8BAC5A18A/WebDriverAgentRunner-Runner.app/XCTRunner -NSTreatUnknownArgumentsAsOpen NO -ApplePersistenceIgnoreState YES
user             47210   0,0  0,6  2734752 103420 s000  S+    5:53     0:02.74 /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /Users/user/driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=444B894A-22EF-4277-91FF-384C0EEE3A93 IPHONEOS_DEPLOYMENT_TARGET=10.3
```
When I kill appium node second process `/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /Users/user/driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=444B894A-22EF-4277-91FF-384C0EEE3A93 IPHONEOS_DEPLOYMENT_TARGET=10.3` is killed too. 
But it's not the problem.
 The problem is when I kill or close via `Ctrl+C` in terminal only second process WDA on device respond only on one query
```
 curl -X GET $JSON_HEADER http://localhost:8100/status
{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "10.3.1"
    },
    "ios" : {
      "simulatorVersion" : "10.3.1",
      "ip" : "10.1.14.227"
    },
    "build" : {
      "time" : "Jul 11 2017 15:31:43"
    }
  },
  "sessionId" : "EE8E002C-21B1-4E36-ACC6-ED3090DDF5B5",
  "status" : 0
```
kind of everything is OK dude, please use me further.
But if I ask for instance
```
 curl -X GET $JSON_HEADER http://localhost:8100/source
{
  "value" : "Cannot get '(null)' source of the current application",
  "sessionId" : "EE8E002C-21B1-4E36-ACC6-ED3090DDF5B5",
  "status" : 13
```
 I might to wait for the response "for ages".

or 

```
curl -X POST $JSON_HEADER http://localhost:8100/session -d "{\"desiredCapabilities\":{\"bundleId\":\"ru.ncloudtech.mssenger\",\"arguments\":[],\"environment\":{},\"shouldWaitForQuiescence\":true,\"shouldUseTestManagerForVisibilityDetection\":false,\"maxTypingFrequency\":60,\"shouldUseSingletonTestManager\":true}}"
{
  "value" : "Failed to launch ru.ncloudtech.messenger application",
  "sessionId" : "EE8E002C-21B1-4E36-ACC6-ED3090DDF5B5",
  "status" : 13
```
Thats why Appium doesn't work because it uses `GET /status` as a marker WDA is working or not on device.

[ios_logs_ok_fist_time](https://gist.github.com/crazyk2/9d2efc83ba9a5e8cdc651583de3c9991)
[ios_logs_bad_after_kill_second_process](https://gist.github.com/crazyk2/b26c3aca0f9b55aef98ae5f3ccec9364)

**Comment by marekcirkos** [comment]
1) WDA will NOT work if you kill `xcodebuild`,
2) You can use `/wda/healthcheck` to check whether it is working properly.
