### ISSUE TITLE
Is there a way to set the shouldWaitForQuiescence capability to false?

### ISSUE THREAD

**Issue by GEvanscsumb** [facebook/WebDriverAgent#644]
I'm testing an ios app through appium that was sent to me by the developers through an ipa file. Through my research, it seems that this is the capability that will wait for the app to idle before performing touch gestures. The pages I want to use the drag gesture on seem to have animations, thus the time it takes to perform the gesture itself clocks in at about 5 minutes. I've noticed this after the WDA session is created successfully:

{"desiredCapabilities":{"bundleId":"com.testapp.webdriverrun","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

Is there a way to set the value to false? I was reading the docs which said that it's set to NO by default, but I'm not sure where its value is changing.

**Comment by marekcirkos** [comment]
You just set it to false when starting session. I think this is more of a question for Appium rather than WDA. If I am wrong please re-open the issue.

**Comment by yazan990** [comment]
I have the same issus ,

 with body: {"desiredCapabilities":{"bundleId":"com.loreal.leteintparticulier","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

any idea ?

**Comment by aljones15** [comment]
it used to be possible in appium to do this, but it looks like it is not now,

**Comment by Jonahss** [comment]
appium capability is named `waitForQuiescence`. should work
