### ISSUE TITLE
Can this WebdriverAgent be signed with Apples enterprise key

### ISSUE THREAD

**Issue by vathsalahn** [facebook/WebDriverAgent#645]
I have a query ,if we can sign webdriverAgent Runner app with apples enterprise key ??

**Comment by marekcirkos** [comment]
It SHOULD work. Can't you simply try?

**Comment by yakimant** [comment]
@vathsalahn, did you succeed?

**Comment by vathsalahn** [comment]
I tried with enterprise key but i couldn't ..I was able to sign the other apps like integration app with enterprise but not webdriverAgent-Runner

**Comment by yakimant** [comment]
Same for me.
