### ISSUE TITLE
replace another iphone,and fix xcodebuild code '65'

### ISSUE THREAD

**Issue by wenshi11019** [facebook/WebDriverAgent#646]
I use appium(1.6.6.beta2) to test app with webdriveragent. I use phone A, it always thorws xcodebuild code '65'. But When I use another phone B , the server test success with the same code.

[the full failed appium logs](https://gist.github.com/wenshi11019/24f2e1e7eb98cd27c48f5ba15e75d3c2)

[the full success appium logs](https://gist.github.com/wenshi11019/aab3e8941a93e3e62a604e7414c24d3b)

**Comment by wenshi11019** [comment]
When test failed in phone A, I also use facebook/Webdriveragent to build test, and found the same exception, xcodebuild code 65

**Comment by marekcirkos** [comment]
This is xcodebuild issue, failing to start WDA. Please file a bug to Apple.
