### ISSUE TITLE
is there a way to do gesture unlock ?

### ISSUE THREAD

**Issue by jmei08** [facebook/WebDriverAgent#647]
It seems wda does not provide any api to operate gusture.

**Comment by wendywenwen** [comment]
[[FBRoute POST:@"/wda/dragfromtoforduration"] respondWithTarget:self action:@selector(handleDragCoordinate:)],  
-------------------------------------------------
from the source code, the drag operation seems only support point to point , and not support more than three points.

**Comment by marekcirkos** [comment]
@jmei08 does it work for you?

**Comment by jmei08** [comment]
I want to drag lines between more and 2 points, and i cannot find any api to do it.

**Comment by marekcirkos** [comment]
Unlock is single line drag right?

**Comment by jmei08** [comment]
There are 9 points, for example, i want to draw a line like the big 'Z' which crosses 7 points at the same time. @marekcirkos 
![image](https://user-images.githubusercontent.com/10267523/28308069-aa96f6d2-6bd7-11e7-9fd3-6d42b87bba15.png)

**Comment by marekcirkos** [comment]
Ohh. I thought you meant regular iOS unlock screen. So then, unfortunately we do not support complex gestures yet.

**Comment by mykola-mokhnach** [comment]
The patch https://github.com/facebook/WebDriverAgent/pull/740 can already do the job. I hope we can nicely polish and merge it soon
