### ISSUE TITLE
WebDriverAgent inspector showing error message as "Invalid parameter not satisfying"

### ISSUE THREAD

**Issue by irfan-appachhi** [facebook/WebDriverAgent#657]
After cloning WebDriverAgent master repo, running ./Scripts/bootstrap.sh, configuring signing identity and starting the WebDriverAgentRunner test, when I launch 192.168.1.60:8100/inspector, it prints an array which contains this message **Invalid parameter not satisfying** and in the xcode console it says 

*** Assertion failure in -[FBResponseFilePayload initWithFilePath:], /Users/xyz/Desktop/fb_webdriver_agent/WebDriverAgent/WebDriverAgentLib/Routing/FBResponseFilePayload.m:25

and the line which is throwing error is **NSParameterAssert(path);** and it is because the path is null when this line is executed

below screenshot is what shown in browser

![inspector](https://user-images.githubusercontent.com/30261605/28315746-7d51799e-6bdd-11e7-8c51-6bf3ed40ea76.png)

and below message is shown in xcode when we launch inspector

*** Assertion failure in -[FBResponseFilePayload initWithFilePath:], /Users/xyz/Desktop/fb_webdriver_agent/WebDriverAgent/WebDriverAgentLib/Routing/FBResponseFilePayload.m:25

I expect error is related to these two files 

FBResponseFilePayload.m
FBInspectorCommands.m(both have been pulled from master branch)

It is not related to Appium, I'm trying to successfully launch inspector only using WebDriverAgent

If required, you can refer stackoverflow question link I have asked

https://stackoverflow.com/questions/45158691/unable-to-launch-inspector-using-facebook-webdriveragent-library

**Comment by marekcirkos** [comment]
Did you run bootstrap script?

**Comment by irfan-appachhi** [comment]
Yes,
I ran ./Scripts/bootstrap.sh

I'm able to resolve this, but now after launching the inspector it showed only the first frame of my iOS and later it was stopped, live frames were not being streamed on the inspector

Also I was not getting the Tree List and elements blocks loaded

But I was able to run curl scripts given in the documentation

please help me resolve below queries
> What is the reason live frames of iOS are not being streamed on the browser [I'm getting script errors in the console] [Note: It is only one screenshot which is visible on the below image, it is not modifying the frames when I use the device]

![fb_inspector_error](https://user-images.githubusercontent.com/30261605/28462699-f0980cca-6e39-11e7-8435-d7d73bcc7ecc.png)

> Does WebDriverAgent allows us to control the device from the browser
> Can we perform extensive automation scripts like appium using curl commands similar to given in https://github.com/facebook/WebDriverAgent/wiki/Queries section
> Can we run multiple instances of WebDriverAgent with different ports to be able to connect multiple iOS devices.

Finally,
I'm really really thankful to you for replying to me & for providing such an awesome framework to work with, since there are very less sources for working on iOS.

**Comment by marekcirkos** [comment]
This might be fixed with https://github.com/facebook/WebDriverAgent/commit/2ed25a24ed0286b1282f4ca2afc95ceec8d89560 can you verify?

**Comment by irfan-appachhi** [comment]
It was not the issue, my issue was because bootstrap.sh was not completely running, it was throwing some ESLint error even after showing

Logs will go to /private/tmp/flow/zSUserszScnixdevzSDesktopzSwwwzSiScreenzSWebDriverAgentzSInspector.log
No errors!

After I commented `"$INSPECTOR_DIR"/node_modules/.bin/eslint js/*` line in bootstrap.sh, inspector started loading

And now after cloning the latest master, Tree & screen & inspector block have actually started loading & working, thanks for your recent commit.
