### ISSUE TITLE
Running testrunner got the error "dyld: Library not loaded: @rpath/XCTest.framework/XCTest"

### ISSUE THREAD

**Issue by Fly1991** [facebook/WebDriverAgent#664]
Env:Xcode8.3.3, ios 10.3.2

Pre:
sign the WebDriverAgent with my dev account

Description:
1.Running testrunner got the error "dyld: Library not loaded: @rpath/XCTest.framework/XCTest"

ErrorInfo:
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/2475BEE5-0F21-4D52-9936-1CB0659F70C4/WebDriverAgentRunner-Runner.app/XCTRunner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/2475BEE5-0F21-4D52-9936-1CB0659F70C4/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/2475BEE5-0F21-4D52-9936-1CB0659F70C4/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/2475BEE5-0F21-4D52-9936-1CB0659F70C4/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/2475BEE5-0F21-4D52-9936-1CB0659F70C4/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'

*** If you believe this error represents a bug, please attach the log file at /Users/yinjuanbao/Library/Developer/Xcode/DerivedData/WebDriverAgent-eogdamlycqzxgmeumzafvzprqydp/Logs/Test/DE05125D-FEEE-4C0C-9994-6DD14E84AD32/Session-WebDriverAgentRunner-2017-07-24_002320-rfTKpd.log

Part of Logs Contents:
   "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/2475BEE5-0F21-4D52-9936-1CB0659F70C4/WebDriverAgentRunner-Runner.app/Frameworks:/Users/yinjuanbao/Library/Developer/Xcode/DerivedData/WebDriverAgent-eogdamlycqzxgmeumzafvzprqydp/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks:/Developer/Library/PrivateFrameworks";
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/A764F2A8-5290-416F-B124-89AD3F41C07F/tmp/WebDriverAgentRunner-5E0675A8-ADF4-4AC7-8FB0-C67750388DD9.xctestconfiguration";
}
00:23:44.364 Xcode[447:12674] Started debugserver on device. fd = 59
00:23:44.525 Xcode[447:4467] Adding console adaptor <IDEConsoleAdaptor: 0x7fba70b41210 'target'> for test session 5E0675A8-ADF4-4AC7-8FB0-C67750388DD9.
00:23:44.905 Xcode[447:4467] Waiting for test process to check in..., will wait up to 120s
00:23:44.905 Xcode[447:4467] Test process runnable PID is 675.
00:23:46.083 Xcode[447:4467] Clearing timeout timer while paused in the debugger. Timeout conditions may not be detected during this session.
00:27:53.665 Xcode[447:4467] Test operation failure: Test operation was canceled.
00:27:53.665 Xcode[447:4467] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled." UserInfo={NSLocalizedDescription=Test operation was canceled.} didCancel: 1

**Comment by marekcirkos** [comment]
Is this device or sim? Can you try master?

**Comment by Fly1991** [comment]
device and sim all not work.
device is iPhone6,ios Version is 10.3.2;
sim is iPhone7,ios Version is 10.3;

Yes,i did try the master,but the issue is still show.

Can u give me any suggestions?thanks a lot.

**Comment by marekcirkos** [comment]
This is supper weird. XCTest should be loaded automatically, even Travis is happy. Are you sure you are not modifying WDA in anyway?

**Comment by Fly1991** [comment]
hello~
i reinstall my mac system and pull the newest wda ,then a new issue shows like:
![image](https://user-images.githubusercontent.com/2239620/28996512-8a9a5b6a-7a34-11e7-88ea-c62b414c4472.png)

the running log is not include "listening on usb..",is it right?

**Comment by marekcirkos** [comment]
This fine WDA start. We do not print USB message anymore as we do not listen on USB explicitly now. You can use `iproxy` instead

**Comment by Fly1991** [comment]
ok，thanks a lot。

**Comment by anshu1987** [comment]
Any leads over there , I am still struggling with these issues , Any hint over it.

**Comment by anandkiran2007** [comment]
Me too facing the same issue. not able to run the app in real device
