### ISSUE TITLE
Cannot show AppSwicher on Home (Springboard) on iOS 10.3.+ & iOS 11 beta

### ISSUE THREAD

**Issue by nghiadhd** [facebook/WebDriverAgent#670]
In the past, I can press home button twice to show AppSwicher and do some more actions to close all recent apps
```
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
      [[XCUIDevice sharedDevice] pressButton:XCUIDeviceButtonHome];
      [[XCUIDevice sharedDevice] pressButton:XCUIDeviceButtonHome];
});
```
However, until from iOS 10.3.+, seem the Apple doesn't allow to do that, The second event may be ignored and now I don't know to show AppSwitcherScrollView any more

I tested with Xcode 8.3.2 & Xcode 9 beta 4

Do you know how to resolve or workaround?

**Comment by renchiyansc** [comment]
same issue here

**Comment by marekcirkos** [comment]
@nghiadhd You could try adding a delay between taps as they are not sync calls.

**Comment by jochasinga** [comment]
@marekcirkos how would adding a delay between taps solve this problem, since the first one isn't synchronous and would ignore the subsequent one with or without delay?

**Comment by nghiadhd** [comment]
@marekcirkos 
I tried but still no success even with publish or private APIs.
Seem Apple has removed this feature (double home)

**Comment by jochasinga** [comment]
@nghiadhd I've been in need of this feature specifically, and trying all sort of delays didn't help. In fact, it wouldn't make any different even trying delay any more than 1s since the first press never waited.

**Comment by nghiadhd** [comment]
@jochasinga 
I work around by using force touch feature to swipe from left edge of screen to show recent apps
Unfortunately, it's removed from iOS 11 and will be added to iOS 11.1

https://9to5mac.com/2017/06/30/ios-11-3d-touch-app-switching-gesture-removed/

**Comment by daigaigai520** [comment]
> @jochasinga
> I work around by using force touch feature to swipe from left edge of screen to show recent apps

can you tell me how realize this? 
dose it need twice call force touch?
