### ISSUE TITLE
Connection to WDA timed out

### ISSUE THREAD

**Issue by KuKiSiNi77** [facebook/WebDriverAgent#671]
## detail
   https://github.com/appium/appium/issues/8882
and the next is device log,is this crash natural?
  https://gist.github.com/KuKiSiNi77/0d52021ca84ac9b661dcb1cceeb3230a#comments

**Comment by marekcirkos** [comment]
Looks like some random, SIGKILL. I will not be able to help you. unless you can provide reproducible sample. Sorry
