### ISSUE TITLE
sporadic error: __NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

### ISSUE THREAD

**Issue by ronald-veldema** [facebook/WebDriverAgent#674]
The below exception we see sporadically from our appium tests.
It looks very close to #575 which is marked closed for some reason.
Any ideas?

This is with the WDA from git so we're sure we have the latest fixes...

Cause: An unknown server-side error occurred while processing the command. Original error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]

(
	0   CoreFoundation                      0x00000001840caff8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000182b2c538 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000183fac2d8 <redacted> + 308
	3   CoreFoundation                      0x0000000183fb8030 <redacted> + 52
	4   XCTest                              0x00000001001f36bc -[XCElementSnapshot(Hitpoint) _transformPoint:windowContextID:windowDisplayID:] + 152
	5   XCTest                              0x00000001001f3ad4 -[XCElementSnapshot(Hitpoint) hitPoint] + 392
	6   XCTest                              0x00000001002044d8 -[XCUIElement(XCUIElementTouchEvents) _hitPointByAttemptingToScrollToVisibleSnapshot:] + 88
	7   XCTest                              0x00000001002064c4 __56-[XCUIElement(XCUIElementTouchEvents) pressForDuration:]_block_invoke + 56
	8   XCTest                              0x0000000100203850 __63-[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:block:]_block_invoke_2 + 248
	9   XCTest                              0x00000001001b1d2c -[XCTestCase startActivityWithTitle:block:] + 364
	10  XCTest                              0x00000001002036f0 __63-[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:block:]_block_invoke + 396
	11  XCTest                              0x00000001001b1d2c -[XCTestCase startActivityWithTitle:block:] + 364
	12  XCTest                              0x000000010020354c -[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:block:] + 368
	13  XCTest                              0x0000000100206478 -[XCUIElement(XCUIElementTouchEvents) pressForDuration:] + 132
	14  WebDriverAgentLib                   0x000000010222a9c0 +[FBElementCommands handleTouchAndHold:] + 356
	15  WebDriverAgentLib                   0x000000010220cc2c -[FBRoute_TargetAction mountRequest:intoResponse:] + 208
	16  WebDriverAgentLib                   0x00000001022051ac __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496
	17  RoutingHTTPServer                   0x00000001022b23cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
	18  RoutingHTTPServer                   0x00000001022b2b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
	19  libdispatch.dylib                   0x0000000182f829a0 <redacted> + 16
	20  libdispatch.dylib                   0x0000000182f937a8 <redacted> + 304
	21  libdispatch.dylib                   0x0000000182f829a0 <redacted> + 16
	22  libdispatch.dylib                   0x0000000182f875e8 _dispatch_main_queue_callback_4CF + 996
	23  CoreFoundation                      0x00000001840790c8 <redacted> + 12
	24  CoreFoundation                      0x0000000184076ce4 <redacted> + 1572
	25  CoreFoundation                      0x0000000183fa6da4 CFRunLoopRunSpecific + 424
	26  Foundation                          0x0000000184ac0d74 <redacted> + 304
	27  Foundation                          0x0000000184b156c4 <redacted> + 88
	28  WebDriverAgentLib                   0x00000001022042fc -[FBWebServer startServing] + 260
	29  WebDriverAgentRunner                0x00000001021f3ed4 -[UITestingUITests testRunner] + 80
	30  CoreFoundation                      0x00000001840d0e80 <redacted> + 144
	31  CoreFoundation                      0x0000000183fc62c4 <redacted> + 292
	32  XCTest                              0x00000001001aca30 __24-[XCTestCase invokeTest]_block_invoke.237 + 48
	33  XCTest                              0x00000001001f0aac -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 56
	34  XCTest                              0x00000001001ac67c __24-[XCTestCase invokeTest]_block_invoke_2 + 564
	35  XCTest                              0x00000001001e7dac -[XCTestContext performInScope:] + 208
	36  XCTest                              0x00000001001ac430 -[XCTestCase invokeTest] + 268
	37  XCTest                              0x00000001001acd80 -[XCTestCase performTest:] + 536
	38  XCTest                              0x00000001001a9f44 __27-[XCTestSuite performTest:]_block_invoke + 240
	39  XCTest                              0x00000001001a9b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	40  XCTest                              0x00000001001a9d54 -[XCTestSuite performTest:] + 200
	41  XCTest                              0x00000001001a9f44 __27-[XCTestSuite performTest:]_block_invoke + 240
	42  XCTest                              0x00000001001a9b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	43  XCTest                              0x00000001001a9d54 -[XCTestSuite performTest:] + 200
	44  XCTest                              0x00000001001a9f44 __27-[XCTestSuite performTest:]_block_invoke + 240
	45  XCTest                              0x00000001001a9b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	46  XCTest                              0x00000001001a9d54 -[XCTestSuite performTest:] + 200
	47  XCTest                              0x00000001001f5a14 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 44
	48  XCTest                              0x00000001001b88dc -[XCTestObservationCenter _observeTestExecutionForBlock:] + 520
	49  XCTest                              0x00000001001f5894 -[XCTTestRunSession runTestsAndReturnError:] + 292
	50  XCTest                              0x0000000100194f70 -[XCTestDriver runTestsAndReturnError:] + 252
	51  XCTest                              0x00000001001eb6f8 _XCTestMain + 548
	52  CoreFoundation                      0x000000018407930c <redacted> + 20
	53  CoreFoundation                      0x0000000184078b28 <redacted> + 288
	54  CoreFoundation                      0x0000000184076998 <redacted> + 728
	55  CoreFoundation                      0x0000000183fa6da4 CFRunLoopRunSpecific + 424
	56  GraphicsServices                    0x0000000185a10074 GSEventRunModal + 100
	57  UIKit                               0x000000018a25a058 UIApplicationMain + 208
	58  XCTRunner                           0x00000001000b0474 XCTRunner + 33908
	59  libdyld.dylib                       0x0000000182fb559c <redacted> + 4
) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8.66 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'UFMSs-Mac-mini.local', ip: '169.254.140.122', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_65'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/mini-node/BFixing/bin/bFixing_DEV.ipa, networkConnectionEnabled=false, noReset=true, bundleId=com.bshg.bfixing.smp2.d.debug, databaseEnabled=false, deviceName=iPad Air, usePrebuiltWDA=null, platform=MAC, webDriverAgentUrl=http://localhost:8080, appium-version=1.6.3, maxTypingFrequency=60, newCommandTimeout=180, platformVersion=10.3, webStorageEnabled=false, locationContextEnabled=false, name=appTest, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=b355b22141049c65222b07dd8716f6ec79c510f9, autoAcceptAlerts=false}]
Session ID: 55e918e2-09aa-43f0-8de4-6fba2527dd34

**Comment by mykola-mokhnach** [comment]
This happens because older Appium releases contain older WDA snapshots. Try to use 1.6.6-beta if you want to have the newest and the greatest snapshot.

**Comment by rsveldema** [comment]
- alas this happens with the latest version from WDA git, so unfortunately it is not that easy....
- happens sporadically and very similar to the other bug, I figure this is a regression somewhere?

**Comment by mykola-mokhnach** [comment]
This exception happens in the internal XCTest's _pressForDuration_ method, which means we cannot fix it.

@marekcirkos can we, probably, create the same workaround for long tap as we did for the simple tap and catch that annoying exception?

**Comment by marekcirkos** [comment]
@mykola-mokhnach Yep.
