### ISSUE TITLE
WDA doesnt close when test fails.

### ISSUE THREAD

**Issue by SamyQAZ** [facebook/WebDriverAgent#676]
# The problem
Screen goes black and WDA doesnt close somehow on test failure. It leads to fail next all test until manually go to device home page/ kill WDA.

# Environment
Appium version: v1.6.5
Desktop OS/version used to run Appium: MacOS Sierra(10.12.5)
Node.js version (unless using Appium.app|exe): v7.10.0
Mobile platform/version under test: iphone 5(10.3.2)
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: Appium CLI
appium-xcuitest-driver: 2.40.0

# Link to Appium logs
Here is the [link to logs!](https://gist.github.com/SamyQAZ/099fc935c996ff52ffd542b702172c96)

**Comment by marekcirkos** [comment]
This is aPpium issue not taking care of killing WDA. You can consider using `/killAll` endpoint that stops WDA and tested application
