### ISSUE TITLE
Return the error 2 visible children even though only one element exists with the identifier

### ISSUE THREAD

**Issue by sebinjqburst** [facebook/WebDriverAgent#680]
While performing scroll, I get "Failed to find scrollable visible parent with 2 visible children\" error. But only one element with the identifier is present there. I have accessed the screen 1 at first (I perform some scrolling here) and then went to some other screen, say screen 2. Later, when I came back to screen 1 and try to scroll to some element on the screen, it returns this error. I tried scrolling to the same element in the first attempt, that is without switching between the screens and it was successful.

## Appium logs

[debug] [XCUITest] Found matching gesture: scroll
[debug] [JSONWP Proxy] Proxying [POST /wda/element/4A4E80AE-54B8-4CD4-912C-98D3AB445858/scroll] to [POST http://localhost:8100/session/8EA8B88F-CD11-4F01-A0AB-C8FE4EBA7E3E/wda/element/4A4E80AE-54B8-4CD4-912C-98D3AB445858/scroll] with body: {"toVisible":true}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Failed to find scrollable visible parent with 2 visible children\" UserInfo={NSLocalizedDescription=Failed to find scrollable visible parent with 2 visible children}","sessionId":"8EA8B88F-CD11-4F01-A0AB-C8FE4EBA7E3E","status":13}

**Comment by marekcirkos** [comment]
I am not sure I understand. Error reports that view you are trying to scroll does not contain at least two subviews. It has nothing to do with finding that scroll view. Am I missing something?

**Comment by sebinjqburst** [comment]
@marekcirkos What I understood from the log is that it returns two elements with the same id on trying to scroll to an element with the id. But in fact, there is only one with the same id. I am not sure whether my understanding is right, but I am unable to do a scroll.

**Comment by marekcirkos** [comment]
Is one of those elements by any chance not visible (has isDisplayed set to no)? I that case you should interact with visible one. I noticed that XCTest sometimes may duplicate elements. but mark duplicates as not visible.

**Comment by sebinjqburst** [comment]
@marekcirkos Most of the cases, as the elements to which I want to scroll are below the current screen view, both the elements(that is the original and the duplicated) will be having the visibility false. So how can I get differentiate them with isDisplayed? Is there some other way to distinguish them so that I could interact with the original one?

**Comment by Akulavenkatesh** [comment]
My issue got fixed, I did these:

* npm i appium-webdriveragent-driver
* Downloaded https://github.com/facebook/WebDriverAgent and then ran ./Scripts/bootstrap.sh
* Deleted webdriver agent app from my simulator and reran the test case
