### ISSUE TITLE
WebDriver/Appium cannot find all cells added to UITableViewCell

### ISSUE THREAD

**Issue by MRameshiOS** [facebook/WebDriverAgent#681]
I have a tableview, It enabled accessibility identifier, and It contains 700+ cells. But appium is not finding all cell. It finding only 500 cells. Main problem It is not finding visible cells identifiers. tableview contains default cell and default label.

**Comment by marekcirkos** [comment]
Unfortunately this is XCTest limitation. Not much we can do about it.
All I can advise is to not depend on invisible elements.
