### ISSUE TITLE
integrity checksum failed when using sha1!

### ISSUE THREAD

**Issue by yxys01** [facebook/WebDriverAgent#683]
$ ./Scripts/bootstrap.sh 

Fetching dependencies
Building Inspector
Creating bundle directory...
Fetching Inspector dependencies...
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN web-driver-inspector@1.0.0 No repository field.

npm ERR! code EINTEGRITY
npm ERR! sha1-OuCW1AHJacyLV5glP7gjgeLQI3o= integrity checksum failed when using sha1: wanted sha1-OuCW1AHJacyLV5glP7gjgeLQI3o= but got sha1-dS3H+XH1lXpJvOj6SXK4Vt3+rrQ=. (370341 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2017-08-08T07_10_27_787Z-debug.log

**Comment by yxys01** [comment]
Solution
In WebDriverAgent/Inspector/webpack.config.js 

...
loaders: [
{ test: /.js?$/, loaders: ['babel-loader'], exclude: /node_modules/ },
{ test: /.css?$/, loader: 'style-loader!css-loader' },
]
...
Change to

...
loaders: [
{ test: /.js?$/, loaders: ['babel-loader'] },
{ test: /.css?$/, loader: 'style-loader!css-loader' },
]
...
Delete  ', exclude: /node_modules/'

**Comment by marekcirkos** [comment]
Create a diff?
