### ISSUE TITLE
Appium/TableViewCell issues: can't get the cell

### ISSUE THREAD

**Issue by KarenXuan** [facebook/WebDriverAgent#684]
I am using Appium for iOS automation test, in one page there is a tableView, in the tableView there is some cells, I can see the cells in the page, and I can get the cell info use Appium.app in inspect elements as XCUIElementTypeCell, but in the code, I can't find the cells, no matter I use by.xpath or by.classname or other function, and I use getPageSource to printf all the page elements, there is only XCUIElementTypeTable but no XCUIElementTypeCell, why there is no XCUIElementTypeCell in the page source?

**Comment by marekcirkos** [comment]
Without some screenshots and inspector info I will not be able to help you. Feel free to repent it

**Comment by lanzelot1989** [comment]
@marekcirkos I added a screenshot to illustrate how this looks on our side.
![no-access-to-table-cells](https://user-images.githubusercontent.com/773651/33423269-9fc041e6-d5b8-11e7-9813-13363ff449e2.png)

The table element writes "list" or "Emtpy list" in other instances. We use the WebDriverAgent that comes with Appium 1.7.1.

Any help would be greatly appreciated.

**Comment by mykola-mokhnach** [comment]
Do you see the same output if the app is inspected via built-in Xcode accessibility inspector?

**Comment by lanzelot1989** [comment]
Hi @mykola-mokhnach, yes I can still target the individual StaticText entries in the cells via the Accessiblity Inspector that comes with XCode.

**Comment by JasonJue** [comment]
![image](https://user-images.githubusercontent.com/18206935/33543502-3bf7f908-d912-11e7-84d3-c935771eefd2.png)
I met the same problem.

**Comment by mykola-mokhnach** [comment]
@lanzelot1989 Can you also try to query all the descendants of the table element above, like `driver.findElement(tableLocator).findElements(By.className("XCUIElementTypeAny"))`. Do you get any elements in the response?

**Comment by JasonJue** [comment]
@mykola-mokhnach I met the same problem. Try it in your way, return the still XCUIElementTypeTable element object

**Comment by lanzelot1989** [comment]
@mykola-mokhnach: I am not able to access the elements as you described, 
I think that my problem is related to what has been discussed [here](https://forums.xamarin.com/discussion/104986/appium-tests-ios-children-of-a-xcuielementtypetable-do-not-show-also-the-table-has-elements). 

I will ask our devs to incorporate this.

**Comment by mykola-mokhnach** [comment]
You could also check https://github.com/appium/appium/issues/6517 ;)

**Comment by mykola-mokhnach** [comment]
This PR might also improve some stuff there:
https://github.com/facebook/WebDriverAgent/commit/23091efe08710681acac35e95b4d414d780d998a

**Comment by srafiqa** [comment]
Hey,  I am using appium v1.9.0 (Desktop app) for IOS native app automation with Appium XCUITEST . I am  also facing issues with pages which contains UITable views. The inspector is not recognise the elements even after developers set the accessibility. Please help if anyone found the solution for this issue.
