### ISSUE TITLE
XCUITest enabled property for ImageView returns always true

### ISSUE THREAD

**Issue by morpheus554** [facebook/WebDriverAgent#685]
Hi,

I have image for which I got userInterdactionEnabled set to false. Is there a way using WDA and Appium to check if value set on UIImageView using setUserInteractionEnabled is true or false? I tried XCUIelement.IsWDEnabled, but it returns always true for UIImageView.

In more details issue is described on appium side, but rejected.
https://github.com/appium/appium/issues/8996

Best regards,
Greg

**Comment by marekcirkos** [comment]
There is now way to check `userInterdactionEnabled`, our enabled has different meaning.
