### ISSUE TITLE
How to POST a scheme to WDAServer

### ISSUE THREAD

**Issue by YoungL92** [facebook/WebDriverAgent#686]
I find some code in WebDriverAgentLib/Conmands/FBSessionCommands.m

[[FBRoute POST:@"/url"] respondWithTarget:self action:@selector(handleOpenURL:)]
...
+ (id<FBResponsePayload>)handleOpenURL:(FBRouteRequest *)request
{
  NSString *urlString = request.arguments[@"url"];
  if (!urlString) {
    return FBResponseWithStatus(FBCommandStatusInvalidArgument, urlString);
  }
  NSURL *url = [NSURL URLWithString:urlString];
  if (!url) {
    return FBResponseWithStatus(
      FBCommandStatusInvalidArgument,
      [NSString stringWithFormat:@"%@ is not a valid URL", url]
    );
  }
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wdeprecated-declarations"
  if (![[UIApplication sharedApplication] openURL:url]) {
    return FBResponseWithErrorFormat(@"Failed to open %@", url);
  }
  #pragma clang diagnostic pop
  return FBResponseWithOK();
}

And I want to konw, can we use WDA open a new app by scheme just like Safari(tel://xxxxxx).
If we can, how?

**Comment by YoungL92** [comment]
@marekcirkos Can you answer this？

**Comment by codeskyblue** [comment]
+1 want to know

**Comment by marekcirkos** [comment]
Send a POST request on `[WDA_address]/(session_id)/url` with `url` set to URL?
