### ISSUE TITLE
Can 'WebDriverAgent' work in a enviroment without Xcode? just like a App in our Phone

### ISSUE THREAD

**Issue by lancelot9527** [facebook/WebDriverAgent#689]
forgive my poor English

**Comment by myzle** [comment]
then, how to install it?

**Comment by nghiadhd** [comment]
Actually, we can invoke WebDriverAgent (WDA) via lockdown protocol (Ref libimobiledevice tools)
I see one guy can do it is Seetest (experitest). They support Mac & Windows and remember that Xcode only support on Mac, that's magical

**Comment by marekcirkos** [comment]
Or you can use `FBSimulatorControl`

**Comment by NickAb** [comment]
1. Build WebDriverAgent once:
```
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'generic/platform=iOS' build-for-testing
```
2. Run WebDriverAgent as needed using fbsimctl:
```
fbsimctl --json $DEVICE_UDID launch_xctest $WDA_RR_PATH/PlugIns/WebDriverAgentRunner.xctest com.apple.Preferences --port 10000 -- listen
```

Where `$DEVICE_UDID` is a udid of simulator you want to run web driver on, `$WDA_RR_PATH` is an absolute path to `WebDriverAgentRunner-Runner.app` that you build in step 1.
