### ISSUE TITLE
Run XCUITest bundle via WebDriverAgent

### ISSUE THREAD

**Issue by bootstraponline** [facebook/WebDriverAgent#69]
Many companies are investing in using XCUITest directly because that's Apple's official recommendation for UI Testing. It'd be great to have an endpoint in WebDriverAgent that accepts a zip of XCUITests and returns a base64 encoded zip file with the contents of the run.

On Android, running Instrumentation tests from the command line is easy with [spoon](https://github.com/square/spoon). I haven't found an equivalent way to easily run XCUITests without someone manually using XCode. Would [xctool](https://github.com/facebook/xctool) enable people to run XCUITests programmatically?

Amazon supports this via uploading a zipped [XCTest bundle](http://docs.aws.amazon.com/devicefarm/latest/developerguide/test-types-ios-xctest.html). It's not clear how they run the bundle once it's uploaded.

Adding XCUITest bundle support would enable all existing automation providers that offer appium to execute XCUITests. That'd be a big win for customers who currently don't have many options when selecting device clouds with XCUITest support.

/cc @jlipps @Jonahss

**Comment by bootstraponline** [comment]
It looks like [fastlane/scan](https://github.com/fastlane/scan) would work for running the XCUITests directly (instead of via a WebDriver abstraction).

**Comment by Jonahss** [comment]
Though useful for people who want to use XCUITest, I don't think it has much bearing on WebDriverAgent or Appium. Appium exists as a way to test on iOS and Android devices using the JSON Wire Protocol.

**Comment by jlipps** [comment]
@Jonahss this could be an interesting way for people to put custom non-JSONWP drivers inside our JSONWP session architecture. I wouldn't imagine it would be the norm, but imagine for example people who have a bunch of XCUITests who want to run them on Sauce, either during a migration to JSONWP-based tests or in lieu of that.

**Comment by bootstraponline** [comment]
Ok, closing in favor of Sauce implementing support directly in their cloud.
