### ISSUE TITLE
How to  use "[[FBRoute POST:@"/url"] respondWithTarget:self action:@selector(handleOpenURL:)]"

### ISSUE THREAD

**Issue by YoungL92** [facebook/WebDriverAgent#691]
In WebDriverAgentLib/Conmands/FBSessionCommands.m

[[FBRoute POST:@"/url"] respondWithTarget:self action:@selector(handleOpenURL:)]

How to use this?

**Comment by marekcirkos** [comment]
Duplicate of https://github.com/facebook/WebDriverAgent/issues/686
