### ISSUE TITLE
Crash when taking a screenshot

### ISSUE THREAD

**Issue by nghiadhd** [facebook/WebDriverAgent#692]
I run on iPad - iOS 11 Beta 7 with Xcode Beta 6
And when I take a screenshot, WDA has crashed
I debug and see seem Apple has removed "screenshot" of XCUIScreen
I tried to dump XCTest.frameworks and see we can use alternative API is

`[[XCUIScreen mainScreen] screenshotDataForQuality:2 rect:CGRectMake(0, 0, width, height)]`
 to take screenshot however seem we should handle orientation portrait & landscape manually

**Comment by jmei08** [comment]
hi, is there anyway to resolve this problem?

**Comment by marekcirkos** [comment]
Does it still crash on non-beta version?

**Comment by nghiadhd** [comment]
Yes, it's. However, it only occurs on one iPad 12.9 inch Gen 2

Below is my workaround. Unfortunately, the Xcode 9 has performance issue with WebDriverAgent
The time to get source tree takes more  5-10x than Xcode 8
 so now I revert and run with Xcode 8

```
- (NSData *)fb_screenshot
{
  if (NSClassFromString(@"XCUIScreen")) {
    CGSize screenSize = [[FBSpringboardApplication fb_springboard] fb_getDeviceResolution];
    int32_t value = 0;
    size_t length = sizeof(value);
    sysctlbyname("hw.cputype", &value, &length, NULL, 0);

    if (value == CPU_TYPE_ARM) {
      return [[[XCUIScreen mainScreen] screenshot] PNGRepresentation];
    }

    return [[XCUIScreen mainScreen] screenshotDataForQuality:1 rect:CGRectMake(0, 0, screenSize.width, screenSize.height)];
  }

  return [[XCAXClient_iOS sharedClient] screenshotData];
}
```

**Comment by marekcirkos** [comment]
Can you pop an PR?

**Comment by mykola-mokhnach** [comment]
I did a PR: https://github.com/facebook/WebDriverAgent/pull/766
