### ISSUE TITLE
Page source differs from iOS simulator and real device

### ISSUE THREAD

**Issue by jamesvanhorn** [facebook/WebDriverAgent#694]
Getting page source (through Appium) returns only visible elements for the iOS simulator. For a real device, it returns the full page, including elements present on the page, but currently not visible. The value of simpleIsVisibleCheck doesn't have any affect. Sim and real device are both iOS 10.3. Same environment otherwise.

**Comment by marekcirkos** [comment]
I do not think we can do much here, since reporting elements is done on Apple side. :/
