### ISSUE TITLE
XCUITest WebDriverAgent stop connection after swipe

### ISSUE THREAD

**Issue by rutin31** [facebook/WebDriverAgent#698]
I run C# test on iphone real device
I have to get OTP code from notification msg. After success swipe function and find element by xpath I got exception on Visual studio:
A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL 
The status of the exception was KeepAliveFailure, and the message was: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.

Appium logs for findelement after swipe

debug] [XCUITest] Connection to WDA timed out

[debug] [iProxy] recv failed: Operation not permitted
Appium version 1.6.5
Desktop OS/version macOS Sierra 10.12.5
Node.js version v8.1.0
Mobile platform/version 10.1.1
Real device

**Comment by marekcirkos** [comment]
Seems like WDA crashed. Can you provide a stack trace or some more information and reopen this issue?
