### ISSUE TITLE
Problems with commands on Xcode 8.3+

### ISSUE THREAD

**Issue by Faraen** [facebook/WebDriverAgent#701]
I'm using appium for my tests, and have noticed that when using Xcode 8.3+ with my tests, I often get this error message: “Remote end closed connection without response”. I wouldn't have a problem with that error if it meant that the action i wanted to make just didn't work, but this error show ups randomly regardless of whether the action i was making happened or not. That means that when I try to use the tap command, and i receive this error, I am not sure if the tap did actually occur or not. this happened to me for few commands, like tap by x and y coordinates, using driver.close command or when getting device dimensions. The only fix i have found as of today is downgrading from Xcode 8.3 to Xcode 8.2, but than i lose support of iOS 10.3+. I would post appium logs, but they don't seem to show anything interesting at all.

**Comment by marekcirkos** [comment]
This is Xcode 8.x know issue starting XCTest. Not much on WDA side we can do
