### ISSUE TITLE
Something  may improve

### ISSUE THREAD

**Issue by adudurant** [facebook/WebDriverAgent#704]
When use the inspector to get the screen of iPhone, I  find all of the buttons in the browser.It means that the buttons that  visible and invisible all can be  clicked. What's more,when to click ,the invisible buttons,there is no response while the visible there are the right responses

**Comment by adudurant** [comment]
https://github.com/facebook/WebDriverAgent/issues/524 
I wonder that this issue  had been solved or  it is the same problem I mention  in the  my issue.
Anyone could help?

**Comment by adudurant** [comment]
Well，it turns out that  the UIView  leads to this problem. Anyone has a try?How to solve  the problem?

**Comment by adudurant** [comment]
Actually,   when using  the apple system's  nativeController  to push view there is no problem ，for it is the system view navigation. However, if there  are  custom requirements ，we have to write  the  mainController to add some page or view ,and add a subview,The problem arises！  what's more they both Inherit from UIview。

**Comment by marekcirkos** [comment]
I am not sure exactly what is the problem here?

**Comment by adudurant** [comment]
@marekcirkos   thanks, I will  show you the problem more  comprehensive later.
