### ISSUE TITLE
when  isVisible  or  isWDVisible  used，the WDA crash

### ISSUE THREAD

**Issue by adudurant** [facebook/WebDriverAgent#713]
As the title，when I use the isWDVisible  attributes，the WDA  always crash。 I wonder the implementation is  something wrong？

**Comment by adudurant** [comment]
There is a  implementation of this  method  by swift。But it is very unstable。Who can help find the bug or 
 improve it？ 

 func isWDVisible() -> Bool {
        if self.frame.isEmpty || self.visibleFrame.isEmpty {
            return false
        }
        
        let app: XCElementSnapshot? = _rootElement() as! XCElementSnapshot?
        let screenSize: CGSize? = MathUtils.adjustDimensionsForApplication((app?.frame.size)!, (XCUIDevice.shared().orientation))
        let screenFrame  = CGRect(x: CGFloat(0), y: CGFloat(0), width: CGFloat((screenSize?.width)!), height: CGFloat((screenSize?.height)!))
        let rectIntersects: Bool = visibleFrame.intersects(screenFrame)
        let isActionable: Bool? = app?.frame.contains(hitPoint)
        return rectIntersects && isActionable!
    }

**Comment by marekcirkos** [comment]
Does our WDA crash?

**Comment by adudurant** [comment]
@marekcirkos    Unfortunately, Yes.  The  Viewcontroler  in app is  customer  may lead to the crash.
