### ISSUE TITLE
xcodebuild build error in Xcode9

### ISSUE THREAD

**Issue by lujun-wuhan** [facebook/WebDriverAgent#715]
WebDriverAgentLib does not support provisioning profiles. WebDriverAgentLib does not support provisioning profiles, but provisioning profile xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

How to set cert and provisioning profile ?

**Comment by marekcirkos** [comment]
Google is your friend. https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ConfiguringYourApp/ConfiguringYourApp.html#//apple_ref/doc/uid/TP40012582-CH28-SW1
