### ISSUE TITLE
wda crashed when screenshot on xcode9+ios11

### ISSUE THREAD

**Issue by jmei08** [facebook/WebDriverAgent#717]
The environment:
  xcode 9.0(9A235) GM
  iphone7p ios11(15A372) GM

The problem:
**1. webdriveragent crashed when do screenshot**
**2. get page source is extremly slow** 

@mykola-mokhnach Please take a look at these problem. Thanks a lot.

**Comment by shynkevich-alex** [comment]
the same with second issue

**Comment by marekcirkos** [comment]
Can you provide more information? Stacktrace, logs etc?

**Comment by cschabetsberger-micro-focus** [comment]
I think I am having the same issue. It seems that the "/screenshot" call leads WDA to crash on the device if the whole call takes longer than ~ 7 seconds. This seems only to happen on devices with large screens (i.e. like on an iPad Pro).

When I debugged this, the crash was in fb_screenshot when executing:
`return (NSData *)[xcScreen valueForKeyPath:@"mainScreen.screenshot.PNGRepresentation"];`

The executing thread receives a SIGKILL after a few seconds.

**Comment by jmei08** [comment]
@cschabetsberger-micro-focus Is there anyway to resolve this problem? It happens on iPhone 7Plus.

**Comment by jmei08** [comment]
@marekcirkos It crashed in the fb_screenshot function with iPhone 7Plus
<img width="669" alt="111" src="https://user-images.githubusercontent.com/10267523/32086495-362c0a6e-bb08-11e7-9ec3-6fd03f037f00.png">

**Comment by jmei08** [comment]
@marekcirkos It crashed in the fb_screenshot function with iPhone 7Plus.
- (NSData *)fb_screenshot
{
  id xcScreen = NSClassFromString(@"XCUIScreen");
  if (xcScreen) {
    return (NSData *)[xcScreen valueForKeyPath:@"mainScreen.screenshot.PNGRepresentation"];
  }
  return [[XCAXClient_iOS sharedClient] screenshotData];
}

**Comment by cschabetsberger-micro-focus** [comment]
@jmei08 I have not found any workaround for this yet. The old approach `[XCAXClient_iOS sharedClient] screenshotData` cannot be used anymore for iOS 11 and the new approach seems to be buggy. So right now I have no idea how this could be solved for iOS 11, but maybe somebody of the WDA devs has?

**Comment by mykola-mokhnach** [comment]
@cschabetsberger-micro-focus Try the solution proposed by @nghiadhd

https://github.com/facebook/WebDriverAgent/issues/692

**Comment by cschabetsberger-micro-focus** [comment]
@mykola-mokhnach I tried the proposed [PR](https://github.com/facebook/WebDriverAgent/pull/766) on my iPad Pro but it still seems to crash in the line `res = (NSData *)[mainScreen valueForKeyPath:@"screenshot.PNGRepresentation"];` (i.e. I receive a SIGKILL after a few seconds)

**Comment by mykola-mokhnach** [comment]
@cschabetsberger-micro-focus Thanks for trying it. Can you please add the full stacktrace?

**Comment by cschabetsberger-micro-focus** [comment]
@mykola-mokhnach no problem, I copied the stacktrace when I received the SIGKILL:
`
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001814b8bc4 in mach_msg_trap ()
#1	0x00000001814b8a3c in mach_msg ()
#2	0x0000000181967ce4 in __CFRunLoopServiceMachPort ()
#3	0x00000001819658b0 in __CFRunLoopRun ()
#4	0x00000001818862d8 in CFRunLoopRunSpecific ()
#5	0x0000000102ac6c38 in -[XCTWaiter waitForExpectations:timeout:enforceOrder:] ()
#6	0x0000000102ac8fe8 in +[XCTWaiter waitForActivity:timeout:block:] ()
#7	0x0000000102a9d524 in -[XCUIScreen _modernScreenshotDataForQuality:rect:error:] ()
#8	0x0000000102a9d98c in -[XCUIScreen screenshotDataForQuality:rect:error:] ()
#9	0x0000000102a9d1e4 in -[XCUIScreen screenshot] ()
#10	0x00000001822adf70 in -[NSObject(NSKeyValueCoding) valueForKey:] ()
#11	0x00000001822addf8 in -[NSObject(NSKeyValueCoding) valueForKeyPath:] ()
#12	0x000000010458728c in __38-[XCUIDevice(FBHelpers) fb_screenshot]_block_invoke at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m:54
#13	0x0000000181345048 in _dispatch_client_callout ()
#14	0x0000000181348710 in dispatch_once_f$VARIANT$mp ()
#15	0x0000000104586dd4 in _dispatch_once [inlined] at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/dispatch/once.h:84
#16	0x0000000104586db8 in -[XCUIDevice(FBHelpers) fb_screenshot] at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m:53
#17	0x000000010456af14 in +[FBScreenshotCommands handleGetScreenshot:] at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Commands/FBScreenshotCommands.m:32
#18	0x0000000104576fb4 in -[FBRoute_TargetAction mountRequest:intoResponse:] at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBRoute.m:42
#19	0x000000010456f324 in __37-[FBWebServer registerRouteHandlers:]_block_invoke at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:161
#20	0x000000010461e3cc in -[RoutingHTTPServer handleRoute:withRequest:response:] at /Users/marko/Projects/RoutingHTTPServer/Source/RoutingHTTPServer.m:189
#21	0x000000010461eb80 in __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke at /Users/marko/Projects/RoutingHTTPServer/Source/RoutingHTTPServer.m:255
#22	0x0000000181345048 in _dispatch_client_callout ()
#23	0x00000001813532a0 in _dispatch_sync_thread_bound_invoke ()
#24	0x0000000181345048 in _dispatch_client_callout ()
#25	0x0000000181351b74 in _dispatch_main_queue_callback_4CF$VARIANT$mp ()
#26	0x0000000181967f20 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#27	0x0000000181965afc in __CFRunLoopRun ()
#28	0x00000001818862d8 in CFRunLoopRunSpecific ()
#29	0x00000001822ae6e4 in -[NSRunLoop(NSRunLoop) runMode:beforeDate:] ()
#30	0x000000010456e344 in -[FBWebServer startServing] at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:76
#31	0x000000010455bbe4 in -[UITestingUITests testRunner] at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m:37
#32	0x00000001819c76a0 in __invoking___ ()
#33	0x00000001818a6820 in -[NSInvocation invoke] ()
#34	0x0000000102a880a8 in __24-[XCTestCase invokeTest]_block_invoke.275 ()
#35	0x0000000102ad4f08 in -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] ()
#36	0x0000000102a87e58 in __24-[XCTestCase invokeTest]_block_invoke ()
#37	0x0000000102acd780 in -[XCUITestContext performInScope:] ()
#38	0x0000000102a87ba0 in -[XCTestCase invokeTest] ()
#39	0x0000000102a88c78 in __26-[XCTestCase performTest:]_block_invoke.382 ()
#40	0x0000000102ad2778 in +[XCTContext runInContextForTestCase:block:] ()
#41	0x0000000102a88674 in -[XCTestCase performTest:] ()
#42	0x0000000102a84868 in __27-[XCTestSuite performTest:]_block_invoke ()
#43	0x0000000102a84290 in -[XCTestSuite _performProtectedSectionForTest:testSection:] ()
#44	0x0000000102a844a0 in -[XCTestSuite performTest:] ()
#45	0x0000000102a84868 in __27-[XCTestSuite performTest:]_block_invoke ()
#46	0x0000000102a84290 in -[XCTestSuite _performProtectedSectionForTest:testSection:] ()
#47	0x0000000102a844a0 in -[XCTestSuite performTest:] ()
#48	0x0000000102a84868 in __27-[XCTestSuite performTest:]_block_invoke ()
#49	0x0000000102a84290 in -[XCTestSuite _performProtectedSectionForTest:testSection:] ()
#50	0x0000000102a844a0 in -[XCTestSuite performTest:] ()
#51	0x0000000102adbf5c in __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke ()
#52	0x0000000102a973e8 in -[XCTestObservationCenter _observeTestExecutionForBlock:] ()
#53	0x0000000102adbdd8 in -[XCTTestRunSession runTestsAndReturnError:] ()
#54	0x0000000102a73ed0 in -[XCTestDriver runTestsAndReturnError:] ()
#55	0x0000000102ad1920 in _XCTestMain ()
#56	0x000000018196816c in __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ ()
#57	0x0000000181967a3c in __CFRunLoopDoBlocks ()
#58	0x000000018196574c in __CFRunLoopRun ()
#59	0x00000001818862d8 in CFRunLoopRunSpecific ()
#60	0x0000000183717f84 in GSEventRunModal ()
#61	0x000000018ae33880 in UIApplicationMain ()
#62	0x000000010268c430 in _mh_execute_header ()
#63	0x00000001813aa56c in start ()
`

**Comment by mykola-mokhnach** [comment]
Cool, I've added some fixes there, can you please try now @cschabetsberger-micro-focus ?

**Comment by nghiadhd** [comment]
@cschabetsberger-micro-focus  "screenshot.PNGRepresentation" doesn't work on iPad Pro
You should switch to use JPEG instead

[[XCUIScreen mainScreen] screenshotDataForQuality:1 rect:CGRectMake(0, 0, screenSize.width, screenSize.height)];

https://developer.apple.com/documentation/xctest/xctattachment.imagequality

**Comment by mykola-mokhnach** [comment]
@nghiadhd Is there a reliable way to check if high quality (value zero) is supported on the current device?

**Comment by mykola-mokhnach** [comment]
@cschabetsberger-micro-focus does the current implementation work for you? If everything is OK then we could merge this code to Appium fork ASAP.

**Comment by marekcirkos** [comment]
I merged that PR. Is there still a problem there?

**Comment by jmei08** [comment]
@mykola-mokhnach It doesn't crash after updating to the latest version of wda. But snapshot accessibility hierarchy for app takes a very long time and cannot return any elements with "Error copying attribute -25202"

**Comment by mykola-mokhnach** [comment]
Regarding page source - try to use /source endpoint with format=description argument to get fast page source representation (this is different from the default XML, bit still ok for internal debugging purposes). Read https://github.com/mykola-mokhnach/appium/blob/38e2791dae203258dad3f33bc012963ad30ad2d2/docs/en/writing-running-appium/ios/ios-xctest-source.md if you use Appium

**Comment by cschabetsberger-micro-focus** [comment]
@mykola-mokhnach sorry for the delay. I tested the PR but unfortunately it still seems to crash (with the new code, in the line `[invocation getReturnValue:&result]`) with SIGKILL on the iPad Pro.

When this happens, variables are set as follows:
quality = 0
screenRect = 0, 0, 768, 1024

The stacktrace is as follows:
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001814b8bc4 in mach_msg_trap ()
#1	0x00000001814b8a3c in mach_msg ()
#2	0x0000000181967ce4 in __CFRunLoopServiceMachPort ()
#3	0x00000001819658b0 in __CFRunLoopRun ()
#4	0x00000001818862d8 in CFRunLoopRunSpecific ()
#5	0x0000000102652c38 in -[XCTWaiter waitForExpectations:timeout:enforceOrder:] ()
#6	0x0000000102654fe8 in +[XCTWaiter waitForActivity:timeout:block:] ()
#7	0x0000000102629524 in -[XCUIScreen _modernScreenshotDataForQuality:rect:error:] ()
#8	0x000000010262998c in -[XCUIScreen screenshotDataForQuality:rect:error:] ()
#9	0x00000001819c76a0 in __invoking___ ()
#10	0x00000001818a6820 in -[NSInvocation invoke] ()
#11	0x0000000102e3b2f4 in -[XCUIDevice(FBHelpers) fb_screenshotWithError:] at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m:72
#12	0x0000000102e1f194 in +[FBScreenshotCommands handleGetScreenshot:] at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Commands/FBScreenshotCommands.m:33
#13	0x0000000102e2b2a4 in -[FBRoute_TargetAction mountRequest:intoResponse:] at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBRoute.m:42
#14	0x0000000102e23614 in __37-[FBWebServer registerRouteHandlers:]_block_invoke at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:161
#15	0x0000000102ed23cc in -[RoutingHTTPServer handleRoute:withRequest:response:] at /Users/marko/Projects/RoutingHTTPServer/Source/RoutingHTTPServer.m:189
#16	0x0000000102ed2b80 in __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke at /Users/marko/Projects/RoutingHTTPServer/Source/RoutingHTTPServer.m:255
#17	0x0000000181345048 in _dispatch_client_callout ()
#18	0x00000001813532a0 in _dispatch_sync_thread_bound_invoke ()
#19	0x0000000181345048 in _dispatch_client_callout ()
#20	0x0000000181351b74 in _dispatch_main_queue_callback_4CF$VARIANT$mp ()
#21	0x0000000181967f20 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#22	0x0000000181965afc in __CFRunLoopRun ()
#23	0x00000001818862d8 in CFRunLoopRunSpecific ()
#24	0x00000001822ae6e4 in -[NSRunLoop(NSRunLoop) runMode:beforeDate:] ()
#25	0x0000000102e22634 in -[FBWebServer startServing] at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBWebServer.m:76
#26	0x0000000102e0fbe4 in -[UITestingUITests testRunner] at /tmp/Appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m:37
#27	0x00000001819c76a0 in __invoking___ ()
#28	0x00000001818a6820 in -[NSInvocation invoke] ()
#29	0x00000001026140a8 in __24-[XCTestCase invokeTest]_block_invoke.275 ()
#30	0x0000000102660f08 in -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] ()
#31	0x0000000102613e58 in __24-[XCTestCase invokeTest]_block_invoke ()
#32	0x0000000102659780 in -[XCUITestContext performInScope:] ()
#33	0x0000000102613ba0 in -[XCTestCase invokeTest] ()
#34	0x0000000102614c78 in __26-[XCTestCase performTest:]_block_invoke.382 ()
#35	0x000000010265e778 in +[XCTContext runInContextForTestCase:block:] ()
#36	0x0000000102614674 in -[XCTestCase performTest:] ()
#37	0x0000000102610868 in __27-[XCTestSuite performTest:]_block_invoke ()
#38	0x0000000102610290 in -[XCTestSuite _performProtectedSectionForTest:testSection:] ()
#39	0x00000001026104a0 in -[XCTestSuite performTest:] ()
#40	0x0000000102610868 in __27-[XCTestSuite performTest:]_block_invoke ()
#41	0x0000000102610290 in -[XCTestSuite _performProtectedSectionForTest:testSection:] ()
#42	0x00000001026104a0 in -[XCTestSuite performTest:] ()
#43	0x0000000102610868 in __27-[XCTestSuite performTest:]_block_invoke ()
#44	0x0000000102610290 in -[XCTestSuite _performProtectedSectionForTest:testSection:] ()
#45	0x00000001026104a0 in -[XCTestSuite performTest:] ()
#46	0x0000000102667f5c in __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke ()
#47	0x00000001026233e8 in -[XCTestObservationCenter _observeTestExecutionForBlock:] ()
#48	0x0000000102667dd8 in -[XCTTestRunSession runTestsAndReturnError:] ()
#49	0x00000001025ffed0 in -[XCTestDriver runTestsAndReturnError:] ()
#50	0x000000010265d920 in _XCTestMain ()
#51	0x000000018196816c in __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ ()
#52	0x0000000181967a3c in __CFRunLoopDoBlocks ()
#53	0x000000018196574c in __CFRunLoopRun ()
#54	0x00000001818862d8 in CFRunLoopRunSpecific ()
#55	0x0000000183717f84 in GSEventRunModal ()
#56	0x000000018ae33880 in UIApplicationMain ()
#57	0x000000010222c430 in _mh_execute_header ()
#58	0x00000001813aa56c in start ()

Please let me know if there is anything else I could try.

**Comment by mykola-mokhnach** [comment]
Thanks for checking. Can you say what is the returned value for [[mainScreen valueForKey:@"scale"] doubleValue] on ipad?

**Comment by cschabetsberger-micro-focus** [comment]
The scale is exactly 2. If I change the condition to `[[mainScreen valueForKey:@"scale"] doubleValue] >= 2.0 ? 1: 0` it works (i.e. it does not crash and it returns an image).

**Comment by mykola-mokhnach** [comment]
Good, change the condition there from 
``` NSUInteger quality = [[mainScreen valueForKey:@"scale"] doubleValue] > 2.0 ? 1 : 0;
```

to 

```NSUInteger quality = ([[mainScreen valueForKey:@"scale"] doubleValue] > 2.0 || ([UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad)) ? 1 : 0;
```

**Comment by cschabetsberger-micro-focus** [comment]
I tried that change too and it also seems to work.

**Comment by mykola-mokhnach** [comment]
That's good, but I think it would be safer to always use lower quality [by default](https://github.com/facebook/WebDriverAgent/pull/787). I don't think that JPEG representation of the screenshot is so bad.

**Comment by mykola-mokhnach** [comment]
The endpoint still does return PNG, but converted from JPEG, which means that some small details there might not be looking so precisely. But this is more about how Apple itself implemented it. Lower quality is anyway better than a crash :-P

**Comment by cschabetsberger-micro-focus** [comment]
Fully agreed, I just wanted to point that possible issue out :-)
