### ISSUE TITLE
Not able to build project on real device - Error Failed to write value for key AutomationDisableFauxCollectionCells

### ISSUE THREAD

**Issue by lareddy** [facebook/WebDriverAgent#718]
Hi, When I am trying to build project on iOS real device (iPad Air), I am getting below error.
Can anyone help me with this issue? I went through other thread similar to this issue where they have issue with iPhones in China. But this is iPad in USA. I am stuck with this, need immediate help please,

Failed to write value for key AutomationDisableFauxCollectionCells in CFPrefsPlistSource<0x178119980> (Domain: com.apple.Accessibility, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null)): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access, switching to read-only
2017-09-15 22:42:28.691394-0500 XCTRunner[231:6432] Built at Sep 15 2017 22:06:37
2017-09-15 22:42:28.719845-0500 XCTRunner[231:6432] ServerURLHere->http://192.168.1.113:8100<-ServerURLHere

**Comment by marekcirkos** [comment]
Please update WDA and remove it from device. Wd do not use AutomationDisableFauxCollectionCells anymore
