### ISSUE TITLE
Why "Kill showFakeCollectionViewCells"

### ISSUE THREAD

**Issue by bearxc** [facebook/WebDriverAgent#721]
On latest WDA, When  I scroll on collectionview , inspector can not detect those new visible components any more, only old visible ones are available on inspector.  I have to roll back "Kill showFakeCollectionViewCells" to make it work.

Also, once we remove fake cell support, all invisible components would be gone, it is impossible to scroll collection view through predicate query, because of  none existence exception. We have to manually scroll  right/left/up/down  and then check on screen ?

**Comment by marekcirkos** [comment]
There are to major issues with it:
- Performance is a disaster on newer iOS versions
- It is not super reliable on reporting all offscreen views, It is way better to depend on visible elements.
