### ISSUE TITLE
tap is not working on appium 1.6.5

### ISSUE THREAD

**Issue by vutukuriswathi** [facebook/WebDriverAgent#722]
Problem:
Tap is not working.

I tried the below two ways but nothing is working.

  Dimension size = TestBase.driver.manage().window().getSize();
 JavascriptExecutor js = (JavascriptExecutor) TestBase.driver;
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("x",size.getWidth() / 2);
        params.put("y",size.getHeight() / 2);
        js.executeScript("mobile:tap",params);

or 

TestBase.driver.tap(1, size.getWidth() / 2, size.getHeight() / 2, 1);

Getting 200 status in appium logs but it is not tapping on the real device.

Environment:
ios Device:10.0
appium:1.6.5
appium java client :4.0.0
Macos:10.11.6

Appium logs:
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile:tap",[{"x":368,"y":207}],"bed304e4-6dbb-4591-ac15-4bae486db779"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [POST /wda/tap/0] to [POST http://localhost:8100/session/9B375DC5-E988-4FE4-BE33-032374194D0E/wda/tap/0] with body: {"x":368,"y":207}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"9B375DC5-E988-4FE4-BE33-032374194D0E","status":0}
[debug] [MJSONWP] Responding to client with driver.execute() result: {}
[HTTP] <-- POST /wd/hub/session/bed304e4-6dbb-4591-ac15-4bae486db779/execute 200 364505 ms - 74 
[HTTP] --> POST /wd/hub/session/bed304e4-6dbb-4591-ac15-4bae486db779/timeouts {"type":"implicit","ms":0}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",0,"bed304e4-6dbb-4591-ac15-4bae486db779"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/bed304e4-6dbb-4591-ac15-4bae486db779/timeouts 200 2 ms - 76 
[HTTP] --> GET /wd/hub/session/bed304e4-6dbb-4591-ac15-4bae486db779/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["bed304e4-6dbb-4591-ac15-4bae486db779"]
[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/bed304e4-6dbb-4591-ac15-4bae486db779/context 200 1 ms - 84 
[HTTP] --> POST /wd/hub/session/bed304e4-6dbb-4591-ac15-4bae486db779/elements {"using":"id","value":"playBtn"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["id","playBtn","bed304e4-6dbb-4591-ac15-4bae486db779"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/9B375DC5-E988-4FE4-BE33-032374194D0E/elements] with body: {"using":"id","value":"playBtn"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"9B375DC5-E988-4FE4-BE33-032374194D0E","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/bed304e4-6dbb-4591-ac15-4bae486db779/elements 200 975 ms - 74 
[HTTP] --> GET /wd/hub/session/bed304e4-6dbb-4591-ac15-4bae486db779/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["bed304e4-6dbb-4591-ac15-4bae486db779"]
[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"

**Comment by clergyman** [comment]
Which version of xcode is that?
There are extensive problems with freshly released xcode 9.
In me case, neither element.click nor Appium::TouchAction.new.tap(element.location.to_h).perform
would for some elements, so I had to revert back to xcode 8.3.3 so things get fixed back

Looks like some usual problems with accessibility when new xcode is released.

**Comment by vutukuriswathi** [comment]
I am using xcode 8.2.1 but still tap is not working for me.

**Comment by marekcirkos** [comment]
What if you wait a bit just before tap?
