### ISSUE TITLE
Failed to fetch hit point for ***

### ISSUE THREAD

**Issue by lingtingSir** [facebook/WebDriverAgent#723]
XCElementSnapshot (FBHitPoint)   When the page elements in the outside of the screen, call the [self fb_hitPoint] method will appear memory usage surge problem, performance is a serious problem, the Logs:Failed to fetch hit point for * *, is there a better solution?

**Comment by lingtingSir** [comment]
XCElementSnapshot (FBIsVisible)  fb_isVisible: Internal call self.visibleFrame .There are serious performance problems. Is there any way to solve it?

**Comment by marekcirkos** [comment]
Duplicate of https://github.com/facebook/WebDriverAgent/issues/639
