### ISSUE TITLE
The hitPoint  brings crash !!!!!!

### ISSUE THREAD

**Issue by adudurant** [facebook/WebDriverAgent#727]
As the title,  when getting  the hitPoint attribute, the program may crash. As the following
code, try to catch the exception.However, it may not work well, for it's  an assertion.So,I wonder  if we could implement the attribute outside by ourselves. The apple has not opened the source code, who could help or solve the crash problem?

#import "XCElementSnapshot+FBHitPoint.h"
#import "FBLogger.h"

@implementation XCElementSnapshot (FBHitPoint)

- (CGPoint)fb_hitPoint
{
  @try {
    return [self hitPoint];
  } @catch (NSException *e) {
    [FBLogger logFmt:@"Failed to fetch hit point for %@ - %@", self.debugDescription, e.reason];
    return CGPointMake(-1, -1); // Same what XCTest does
  }
}

@end

**Comment by antiarchit** [comment]
> As the title, when getting the hitPoint attribute, the program may crash. As the following
code, try to catch the exception.

What's the error you get? Can you provide logs or the error message you got? What assertion is getting the `hitPoint` failing?

**Comment by adudurant** [comment]
![gitgitgit0](https://user-images.githubusercontent.com/9434109/31376716-6e454dd0-add8-11e7-9a03-a11bdcc660f8.png)

**Comment by adudurant** [comment]
@antiarchit

**Comment by adudurant** [comment]
@antiarchit Looking forward to your help.Tks!

**Comment by antiarchit** [comment]
I suspect it's because you're calling it on an [`XCAccessibilityElement`](https://github.com/facebook/WebDriverAgent/blob/master/PrivateHeaders/XCTest/XCAccessibilityElement.h), which doesn't have a `hitPoint` property.

**Comment by rajfidel** [comment]
@adudurant Can you please provide the Appium logs?

**Comment by adudurant** [comment]
@antiarchit @rajfidel   I  promise that the hitPoint  is used property. Wait for a while,I will show the detail.

**Comment by adudurant** [comment]
@antiarchit @rajfidel
The code as following,
 
func isWDVisible() -> Bool {
if self.frame.isEmpty || self.visibleFrame.isEmpty {
return false
}
let app: XCElementSnapshot? = _rootElement() as! XCElementSnapshot?
let screenSize: CGSize? = MathUtils.adjustDimensionsForApplication((app?.frame.size)!, (XCUIDevice.shared().orientation))
let screenFrame = CGRect(x: CGFloat(0), y: CGFloat(0), width: CGFloat((screenSize?.width)!), height: CGFloat((screenSize?.height)!))
let rectIntersects: Bool = visibleFrame.intersects(screenFrame)
let isActionable: Bool? = app?.frame.contains(hitPoint)
return rectIntersects && isActionable!
}


app?.frame.contains(hitPoint)   carsh !!!   XCElementSnapshot.hitpoint!

**Comment by adudurant** [comment]
@antiarchit @rajfidel   the log between the server and client  is so simple that I  use xcode to get the message. It tells me that the hitpoint could't get...

**Comment by antiarchit** [comment]
I still don't follow the code. Where is `hitpoint` defined? Where does this code exist? Is it in an extension?

**Comment by adudurant** [comment]
https://github.com/macacajs/XCTestWD/blob/master/XCTestWD/XCTestWDUITests/server/models/extensions/XCTestWDAccessibility.swift     Line 413

**Comment by marekcirkos** [comment]
Mate, this your WDA re-written in swift, which is absolutely fine. However reporting bugs in your code on this repo is not really cool.
