### ISSUE TITLE
[xcode 9] WebdriverAgentLib build failure: 'new' is unavailable: Use XCUIElementQuery to create XCUIElement instances.

### ISSUE THREAD

**Issue by pkulkarnii** [facebook/WebDriverAgent#728]
Recently upgraded(21/09/2017) xcode from 8.3 to xcode 9. Since then unable to build the WebDriverAgent.xcodeproj.
Appium version: 1.7.0

**Issue**: Error in WebDriverAgentLib. Error message: 'new' is unavailable: Use XCUIElementQuery to create XCUIElement instances.
![screen shot 2017-09-22 at 1 26 41 pm](https://user-images.githubusercontent.com/31199545/30728161-7296b344-9f99-11e7-8368-fa8ac1efe90f.png)

**Comment by lolotoms** [comment]
Hi,

I follow instructions here => https://github.com/facebook/WebDriverAgent/issues/611

but it failed to build again with other errors

**Comment by pkulkarnii** [comment]
This fixed the issue for me. 

```
For all of you who can't build WebDriverAgent in Xcode 9 it's because the WebDriverAgent project isn't updated in Appium 1.21. To fix it simply clone the repo from this link https://github.com/facebook/WebDriverAgent and replace it with downloaded WebDriverAgent with Appium.
Also run ./Scripts/bootstrap.sh in this directory.
```

**Comment by anandbhayre2007** [comment]
@pkulkarnii: As you mentioned I replaced the WebDriverAgent and was able to successfully install the web driver agent in my device, but it damaged the appium, and when I tried to open it mac was throwing an error like can't your appium is damaged and move it to thrash. I am using appium GUI.

**Comment by Shrikant07** [comment]
@pkulkarnii Thanks for suggestion. This helped me to solved my issue.
