### ISSUE TITLE
/source command returns incorrect hierarchy

### ISSUE THREAD

**Issue by cschabetsberger-micro-focus** [facebook/WebDriverAgent#733]
We have an internal app that has a simple login form. When requesting the pageSource from this app, we are getting the following:

`
<AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="InsuranceMobile" label="InsuranceMobile" enabled="true" visible="true" x="0" y="0" width="320" height="568">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="320" height="568">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="568">
      <XCUIElementTypeNavigationBar type="XCUIElementTypeNavigationBar" name="Login" enabled="true" visible="true" x="0" y="20" width="320" height="44">
        <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Login" name="Login" label="Login" enabled="true" visible="true" x="138" y="28" width="44" height="27"/>
        <XCUIElementTypeButton type="XCUIElementTypeButton" name="Add" label="Add" enabled="true" visible="true" x="275" y="26" width="41" height="30"/>
      </XCUIElementTypeNavigationBar>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="568">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="568">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="568">
            <XCUIElementTypeImage type="XCUIElementTypeImage" name="header" enabled="true" visible="true" x="0" y="64" width="320" height="66"/>
            <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="Email" label="" enabled="true" visible="true" x="20" y="150" width="280" height="40">
              <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="Email" label="" enabled="true" visible="true" x="20" y="150" width="280" height="40"/>
            </XCUIElementTypeTextField>
            <XCUIElementTypeSecureTextField type="XCUIElementTypeSecureTextField" value="Password" enabled="true" visible="true" x="20" y="200" width="280" height="40">
              <XCUIElementTypeSecureTextField type="XCUIElementTypeSecureTextField" value="Password" enabled="true" visible="true" x="20" y="200" width="280" height="40"/>
            </XCUIElementTypeSecureTextField>
            <XCUIElementTypeButton type="XCUIElementTypeButton" name="Login" label="Login" enabled="true" visible="true" x="20" y="250" width="280" height="30"/>
            <XCUIElementTypeButton type="XCUIElementTypeButton" name="" label="" enabled="true" visible="true" x="20" y="300" width="280" height="55"/>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="320" height="568">
    <XCUIElementTypeStatusBar type="XCUIElementTypeStatusBar" enabled="true" visible="true" x="0" y="0" width="320" height="20">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="20"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="320" height="20">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="6" y="0" width="39" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" value="SSID" name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" enabled="true" visible="true" x="50" y="0" width="15" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="10:43 AM" label="10:43 AM" enabled="true" visible="true" x="134" y="0" width="57" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="-100% battery power" label="-100% battery power" enabled="true" visible="true" x="280" y="0" width="35" height="20"/>
      </XCUIElementTypeOther>
    </XCUIElementTypeStatusBar>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>
`

As you can see, the hierarchy contains, for example, XCUIElementTypeTextField which has a child XCUIElementTypeTextField with the same attributes. When I then do a find via xpath with an absolute locator 

`
//XCUIElementTypeApplication[@name='InsuranceMobile']/XCUIElementTypeWindow[@name='']/XCUIElementTypeOther[@name='']/XCUIElementTypeOther[@name='']/XCUIElementTypeOther[@name='']/XCUIElementTypeOther[@name='']/XCUIElementTypeTextField[@name='']/XCUIElementTypeTextField[@name='']
`

it does not work, because the most inner XCUIElementTypeTextField cannot be found. If I change the locator to 

`
//XCUIElementTypeApplication[@name='InsuranceMobile']/XCUIElementTypeWindow[@name='']/XCUIElementTypeOther[@name='']/XCUIElementTypeOther[@name='']/XCUIElementTypeOther[@name='']/XCUIElementTypeOther[@name='']/XCUIElementTypeTextField[@name='']
`

it works correctly. For me this looks like that XCUIElementTypeTextField should not have a child XCUIElementTypeTextField. There are also other elements, for example, XCUIElementTypeSecureTextField with the same issue.

**Update:** I forgot to mention my environment:
* Appium 1.7
* iPhone 5s Simulator with iOS 11
* Xcode 9
* Updated to the latest version of WDA

**Comment by marekcirkos** [comment]
I cannot really work with this until you will give me some app sample.
