### ISSUE TITLE
With 1.7.1 not able to tap on the assistive touch window using coordinates

### ISSUE THREAD

**Issue by manoj0384** [facebook/WebDriverAgent#736]
To navigate to he widgets and other apps from the test I was using assistive touch to go to the home screen and then navigate to the desired app or widgets. This was working fine till I upgraded appium to 1.7.1 from 1.6.5.

Steps to reproduce, on iphone version >= 6

1. Enable assistive touch
2. keep the touch window over the time label in your in portrait mode
3. Launch any testable app through appium. Assistive touch window will be visible on top (coordinates on iphone plus y = 30, x = 207).
4. Try to tap on this coordinates through driver eg. iosdriver.Tap(1, 30, 207)
5. With appium 1.6.5 it opens the assitive touch window but with 1.7.1 it clicks on the element underneath.

**Comment by marekcirkos** [comment]
@mykola-mokhnach Any ideas?

**Comment by mykola-mokhnach** [comment]
I wouldn't rely on hardcoded coordinate values in any case :)

**Comment by marekcirkos** [comment]
@mykola-mokhnach Good point ;)

**Comment by manoj0384** [comment]
Hi Guys, hard coded coordinates, is different. But my question here is, with appium 1.6.5 I am able to click on the assistive touch element by coordinates but with latest appium it is considering it  as an transparent object and clicking anything underneath that. Do you have any idea why?

**Comment by zcnst** [comment]
I have the same issue...
I was able to click on the assistive touch until I updated Xcode from 8.3.3 to 9.2

**Comment by Ip2507** [comment]
hi is there any way to automate tapping  assistive touch , from there devices , app switch buttons ??
