### ISSUE TITLE
WebDriverAgent Crashing on iOS 11 simulator

### ISSUE THREAD

**Issue by shanthi2016** [facebook/WebDriverAgent#738]
WebDriverAgent gets crashed when trying to run the test on iOS 11.

The app gets installed and then the Webdriveragent is unable to install and it keeps on crashing.
Webdriveragent runner build was successful in xcode 9.

Environment:
Appium version (or git revision) that exhibits the issue: 1.7.1
Last Appium version that did not exhibit the issue (if applicable): 1.6.4
Desktop OS/version used to run Appium: Mac OS 10.12.6
Node.js version (unless using Appium.app|exe):6.10.2
Mobile platform/version under test: 11.0
Real device or emulator/simulator: Simulator
Appium CLI or Appium.app|exe: Both

Please find attached logs:
https://gist.github.com/shanthi2016/773f6c891cc83b44ff83431eadff337e

And here are simulator system logs:
https://gist.github.com/shanthi2016/8a68e23a9be70430ac3194c61d215f59

**Comment by ashwinibaisutrave** [comment]
I'am facing the similar issue .My application is getting installed but its not launching  on the simulator 
iOS 11
Simulator -iPhone 7 Plus
Appium version -1.7.1
Xcode 9
Mac OS 10.12.6
No errors displayed just stuck

**Comment by shanthi2016** [comment]
Still facing the same issue,does anyone have a solution for this crash issue.

**Comment by shanthi2016** [comment]
@mykola-mokhnach:  Is there a solution for this one, can't run tests on iOS 11

**Comment by marekcirkos** [comment]
"Service could not initialize" I assume some random xcodebuild error. Does it happen consistently for you?
