### ISSUE TITLE
Unable to start WDA manually after building and deploying the app to phone

### ISSUE THREAD

**Issue by kiran-z** [facebook/WebDriverAgent#747]
xcodebuild  -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=3f6****4  IPHONEOS_DEPLOYMENT_TARGET=10.3 clean build

I build the app using above command. And installed the .app on phone using 
ios-deploy --bundle /path/to/.appfile

Then when I tap on the app icon it crashes. doesn't start the server.

http://localhost:8100/status is not accessible on device.

How do I start the distributed wda without using xcode?

**Comment by marekcirkos** [comment]
Simple taping the app will not work. You need to execute it through xcodebuilt or appium, which I assume will use xcodebuild
