### ISSUE TITLE
Not able to Run in real device

### ISSUE THREAD

**Issue by nishithcitc** [facebook/WebDriverAgent#75]
I tried to install application in real device but I am getting below error :

ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/PrivateFrameworks'
ld: framework not found UIAutomation
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Let me know If I am doing anything wrong.
Please help me to fix this issue.

**Comment by marekcirkos** [comment]
I think you try to run tests on UIAWebDriverAgent which does NOT support testing on devices.
Try using XCTWebDriverAgent, but running XCTUITestRunner tests

**Comment by nishithcitc** [comment]
But I can't run XCTWebDriverAgent in device. I want to make automation in my application using UIAutomation command or XCTUITest. Please suggest me is it possible?

**Comment by marekcirkos** [comment]
I just tried running XCTWebDriverAgent on device and it works properly. Could you in detail say how you try to run it and what is the error? 

according to automation it depends what you want to automate. Automating you app should be definitely possible, tho XCTWebDriverAgent does NOT support system apps, yet.

**Comment by nishithcitc** [comment]
I am executing test case from this file (FBWebDriverAlertTests.m). But not working for me on device.
Can you please add me on Skype or Hangout ? I need your help.

**Comment by marekcirkos** [comment]
1) `FBWebDriverAlertTests.m` is proper test forUIAutomation which will not run on device.
2) Running `UITestingUITests.m` will start XCTWebDriverAgent which is what you want. You can tell if it was successful if you can see blue screen and `ServerURLHere->http://[SOME_URL]<-ServerURLHere` on console view.

Can you tell we what is the error message when you run `UITestingUITests.m` or link video so that I can help you?

**Comment by marekcirkos** [comment]
@nishithcitc any progress?

**Comment by marekcirkos** [comment]
Long silence, closing.
