### ISSUE TITLE
WDA "xcodebuild failed with code 65" when running from Jenkins

### ISSUE THREAD

**Issue by vjmaiky** [facebook/WebDriverAgent#751]
Appium 1.7.0
Node 8.5.0
npm 5.3.0
iOS real device - iPhone 7 with iOS 11, xcode 9

Description:
I have a local project (where i start appium from code); when i run it locally with intelij works perfectly. If i run it from jenkins (using exactly the same code), setup crashes when is trying to install WebDriverAgent app. It install my ipa but not the WDA. What i'm missing?

[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

Log: https://gist.github.com/vjmaiky/02bc08df4c00cfaa70f641d023849824

@mykola-mokhnach any thoughts?

**Comment by mykola-mokhnach** [comment]
It's not an issue. It's just about WDA source is not signed. Try to use _keychainPath_/_keychainPassword_ capabilities to let jenkins agent to use keychain.

**Comment by vjmaiky** [comment]
strange; on the others machine where i use the exact code base with jenkins i don`t have any paths set; i have a supposition that has something to do with from which account from mac machine i run the jobs; i'll check tomorrow; thanks

**Comment by vjmaiky** [comment]
I added:
        caps.setCapability("keychainPath", "/Users/admin/Library/Keychains/login.keychain-db");
        caps.setCapability("keychainPassword", "password");

Now i get: 

[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "Command" security -in unlock-keychain -p oscar200 /Users/admin/Library/Keychains/login.keychain-db 'exited with code 195'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md . Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
        at XCUITestDriver.quitAndUninstall $ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:386:13)
        at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
        at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
        at generatorFunctionPrototype.prototype. (anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
        at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
        at <anonymous>
        at process._tickCallback (internal / process / next_tick.js: 188: 7)

**Comment by vjmaiky** [comment]
@mykola-mokhnach any thoughts? i'm able to build manually from xcode, aso integration app i'm able to deploy it from xcode to device...

**Comment by vjmaiky** [comment]
i managed to resolve it; it was related to mac accounts; even if i had the certificates installed on admin they where not available for jenkins agent; still i gave jenkins agent the path to keychains but still it wasn't able to use them; the solution was to install profiles also on jenkins agent and after that it worked perfectly. Thanks anyway.

**Comment by MathuMarques** [comment]
Hey @vjmaiky I have just the same issue of you, with the WDA, can you show me how to deal with that thing?
