### ISSUE TITLE
Cannot get source tree of WebView on iOS 11

### ISSUE THREAD

**Issue by mrhhsg** [facebook/WebDriverAgent#755]
<img width="1571" alt="webview" src="https://user-images.githubusercontent.com/1179834/31573977-50e539c6-b0f8-11e7-9303-fbfefa2af5b6.png">

**Comment by marekcirkos** [comment]
I have seen this, I suspect this is, because Apple changed making all Views accessible by default to NO. You can try changing that in code.

**Comment by marekcirkos** [comment]
Duplicate of https://github.com/facebook/WebDriverAgent/issues/639
