### ISSUE TITLE
About versions for iOS automation

### ISSUE THREAD

**Issue by Drashti92** [facebook/WebDriverAgent#757]
Hey all,Does WebDriverAgent works for iOS 11.0.1,XCODE 9 and APPIUM 1.7.0 ??? IN my case I am not able to run automation. Getting this error:
error: [MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:381:13)

**Comment by VTINFOJames** [comment]
The Full Manual Configuration instructions for signing the WebDriverAgent in the link you posted worked for me. I am using iOS 11, Appium 1.7.1 and Xcode 9. However, I found that I had to individually sign and build to my test devices the Integration App, the WebDriverAgentRunner, and the WebDriverAgentLib in Xcode.

**Comment by Drashti92** [comment]
WebDriverAgent was builded properly. But running that three commands of exporting Device_url variable and than doing curl shows cant connect to 8100. also while running automation shows server side error.

**Comment by marekcirkos** [comment]
@Drashti92 This is question for Appium. Until you provide more information on WDA errors. I will not be able to help you here.

**Comment by chanugithub** [comment]
@marekcirkos I posted similar issue https://github.com/facebook/WebDriverAgent/issues/792

I am also unable to install through WDA with my code and also by command line (xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=my udid no' clean build test), here is the gist https://gist.github.com/chanugithub/bf952a3fa61db43333997e7177ec37be
 please throw some light on us

**Comment by chanugithub** [comment]
@marekcirkos Finally i was able to find the solution, it was actually Apple certificates in key chain access which now i set to 'system default' and previously it was in 'Always trust' mode, are you able to resolve it, another thing is it display failed in logs but able to install WDA and run the app
