### ISSUE TITLE
Implicit conversion from nullable pointer 'FBApplication *_Nullable' to non-nullable pointer type...

### ISSUE THREAD

**Issue by hongjojjay** [facebook/WebDriverAgent#760]
I use Xcode 8.2.1 to build WebDriverAgentLib, but build error with this below:
Implicit conversion from nullable pointer 'FBApplication *_Nullable' to non-nullable pointer type 'FBApplication *_Nonnull'

This error occured on this position:
- (FBApplication *)application
{
...
...
return [FBApplication fb_activeApplication] ?: self.testApplication;
}

**Comment by zhangqinghe** [comment]
I have same problem.
