### ISSUE TITLE
Unable to find elements in XCUIElementTypeCollectionView in iOS 11

### ISSUE THREAD

**Issue by mauriparra** [facebook/WebDriverAgent#761]
## The problem

In iOS 11, all the elements that are in a XCUIElementTypeCollectionView, I can found it with appium if the element is showed in the screen. This problem not happens in iOS 10.3 using the same appium version

## iOS 10.3.1
![ios 10_3](https://user-images.githubusercontent.com/24278482/31947787-bf69e500-b89a-11e7-803f-dfa7614ce70d.png)

## iOS 11
![ios 11](https://user-images.githubusercontent.com/24278482/31947812-cfc6ae56-b89a-11e7-95af-4707d3ae7449.png)

## Environment

Appium version (or git revision) that exhibits the issue: 1.7.1
Desktop OS/version used to run Appium: Mac OS Sierra 10.12.6
Node.js version (unless using Appium.app|exe): 4.1.2
Mobile platform/version under test: iOS 11
Real device or emulator/simulator: Iphone 6 simulator
Appium CLI or Appium.app|exe: both

![captura de pantalla 2017-10-24 a la s 9 08 26 a m](https://user-images.githubusercontent.com/24278482/31947862-f3563940-b89a-11e7-8061-a390897c4981.png)

**Comment by HenryLecobee** [comment]
I recently had the same issue and found it was something to do with my real device. So a factory reset of the iPhone fixed it for me.

**Comment by marekcirkos** [comment]
You might also need to explicitly mark them as accessible. Apple changed default accessibility values.
