### ISSUE TITLE
WDARunner trying to run on port 0 instead of 8100

### ISSUE THREAD

**Issue by aristeia** [facebook/WebDriverAgent#762]
After building the version of  WDA found in Appium 1.7.1 or 1.7.2-beta with Xcode 9 on High Sierra, I get the following for the WDA server address:
```
WebDriverAgentRunner-Runner[3875:20544] ServerURLHere->http://172.16.253.184:0<-ServerURLHere
```
172.16.253.184 is the ip for the local machine on its network
This has never happened to me in past versions of WDA or with Xcode 8. What could be causing it?

**Comment by aristeia** [comment]
temporary workaround is here: https://github.com/facebook/WebDriverAgent/issues/661#issuecomment-338900334

**Comment by cuhavp** [comment]
Hi,
I faced this issue happen again:

Test Suite 'All tests' started at 2017-11-02 13:12:11.432
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-11-02 13:12:11.435
Test Suite 'UITestingUITests' started at 2017-11-02 13:12:11.436
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2017-11-02 13:12:11.440
    t =     0.01s Set Up
2017-11-02 13:12:11.468262+0700 WebDriverAgentRunner-Runner[448:236553] Built at Nov  2 2017 13:11:54
2017-11-02 13:12:11.520087+0700 WebDriverAgentRunner-Runner[448:236553] ServerURLHere->http://192.168.2.3:0<-ServerURLHere
