### ISSUE TITLE
Connection peer refused channel request for

### ISSUE THREAD

**Issue by lujun-wuhan** [facebook/WebDriverAgent#769]
Connection peer refused channel request for "dtxproxy:XCTestDriverInterface:XCTestManager_IDEInterface"; channel canceled <DTXChannel: 0x1c40ad3e0>

https://stackoverflow.com/questions/43171020/unit-testing-ios-dtxproxychannel-error-1

Is there another way to pass the code?

**Comment by marekcirkos** [comment]
This is Xcode's issue launching test, not much we can do.
