### ISSUE TITLE
how can I drag without releasing ？

### ISSUE THREAD

**Issue by tianshanfz** [facebook/WebDriverAgent#775]
Is there any way to manipulate a  joystick by WDA ?
I 'm not able to  find any API in "XCEventGenerator.h" to simulate such action like "touchhold and move "  yet.

**Comment by mykola-mokhnach** [comment]
Check if https://github.com/facebook/WebDriverAgent/pull/740 works for you

**Comment by tianshanfz** [comment]
@mykola-mokhnach  Thanks, it does help. What if I want  to simulate the touchdown , touchmove and touchup event respectively ?  I tried it with multipile "XCPointerEventPath"s  but failed.

**Comment by mykola-mokhnach** [comment]
Describe the action, that you need, and pass the resulting JSON to /actions endpoint with this PR included. More information at https://github.com/jlipps/simple-wd-spec#perform-actions
