### ISSUE TITLE
Using inspector  on Xcode9, iOS9, 10 failed to execute tap

### ISSUE THREAD

**Issue by butterflyingdog** [facebook/WebDriverAgent#778]
## I used inspector on Xcode9, ios9,10, when I tap a icon or a button in the inspector webpage, then xcode9 gave the followsing errors, but xcode8 with ios9,10 will not fail, xcode9 with ios11 also will not fail.
**the errors is followed, and  "local.pid.16257" means the springboard, and the app is not crash **
 _

> t =   401.88s Get all elements bound by index for: Elements matching predicate 'wdLabel == "Share" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
>     t =   556.57s Find the Application "local.pid.16257" 0x6000002a1440
> 2017-11-06 09:33:52.717 WebDriverAgentRunner-Runner[16615:21900019] Enqueue Failure: Application local.pid.16257 is not running /Users/icbc/Documents/GIT/facebook/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
>     t =   556.57s Find the Application "local.pid.16257" 0x6000002a1440
> 2017-11-06 09:33:52.720 WebDriverAgentRunner-Runner[16615:21900019] Enqueue Failure: Application local.pid.16257 is not running /Users/icbc/Documents/GIT/facebook/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
>     t =   557.75s Find the Application "local.pid.16257" 0x6000002a1440
> 2017-11-06 09:33:53.895 WebDriverAgentRunner-Runner[16615:21900019] Enqueue Failure: Application local.pid.16257 is not running /Users/icbc/Documents/GIT/facebook/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
>     t =   557.75s Find the Application "local.pid.16257" 0x6000002a1440
> 2017-11-06 09:33:53.897 WebDriverAgentRunner-Runner[16615:21900019] Enqueue Failure: Application local.pid.16257 is not running /Users/icbc/Documents/GIT/facebook/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
>     t =   571.30s Find the Application "local.pid.16257" 0x6000002a1440
> 2017-11-06 09:34:07.445 WebDriverAgentRunner-Runner[16615:21900019] Enqueue Failure: Application local.pid.16257 is not running /Users/icbc/Documents/GIT/facebook/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
>     t =   571.30s Get all elements bound by index for: Elements matching predicate 'wdLabel == "Safari" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'

_

**Comment by Catrinacen** [comment]
I came across the same issue on iOS9/10+Xcode9, dose anyone have any ideas?

**Comment by Catrinacen** [comment]
iOS9/10+Xcode9.2, when using inspector or get "/screenshot" API, we came across below errors:

> 2017-12-22 14:09:53.196 WebDriverAgentRunner-Runner[310:50178] Enqueue Failure: Application local.pid.54 is not running /***/ios-wda/WebDriverAgentRunner/UITestingUITests.m 37 1
2017-12-22 14:09:53.201 WebDriverAgentRunner-Runner[310:50178] *** Assertion failure in -[XCUIScreen _screenshotDataForQuality:rect:error:], /Library/Caches/com.apple.xbs/Sources/XCTest_iOS/XCTest-13764/Sources/UITesting/XCUIScreen.m:230

**Comment by jqqqqqqqqqq** [comment]
Exactly the same issue.

**Comment by liyuankunbix** [comment]
Watching. Exactly the same issue.

**Comment by marekcirkos** [comment]
Same problem as in https://github.com/facebook/WebDriverAgent/issues/845
