### ISSUE TITLE
Very slow response in Safari when web content is large

### ISSUE THREAD

**Issue by vinodvpatil** [facebook/WebDriverAgent#780]
Tap and dragfromtoforduration endpoints take more time to do action on safari when the web content is large(e.g. news.google.com).

Is it because page snapshot is big and finding elements take time ?

Is it possible to get less source instead of full page source ?

**Comment by marekcirkos** [comment]
This is because, we are querying all elements and then trying to resolve all properties and visibility on them. Visibility is specially expensive.
