### ISSUE TITLE
Facebook WDA stops responding to CURL commands after certain operations.

### ISSUE THREAD

**Issue by arunku2x** [facebook/WebDriverAgent#781]
I am currently evaluating Facebook WDA for iOS Automation. There is an issue I am facing with Facebook WDA while checking its stability. I am running a test involving following steps.

Test Steps
-------------
- Run settings application.
- Click Bluetooth Static Text.
- Check State of Bluetooth Switch.
- Toggle Bluetooth Switch.
- Check state of Bluetooth Switch again.
- Compares Bluetooth Switch state before and after changing it. In case it doesn't change then fail the test.
- All above operations are performed in a loop. Facebook WDA is launched on the iPhone using fbsimctl (installed from HEAD). All interactions with Facebook WDA is performed using CURL commands captured at https://github.com/facebook/webdriveragent/wiki/queries.

Observations
----------------
- Facebook WDA works fine till 12th iteration. After this it stops responding to CURL commands.
-  It doesn't responds to even CURL command used for closing the application.

Setup Details
---------------
- iPhone 6S Plus, iOS version 11.0.2
- MAC OS High Sierra 10.13.1
- Xcode 9.1
- Built latest source code of Facebook WDA using XCode 9.1 and installed it on iPhone.
- Installed FBSIMCTL from HEAD using brew.

**Comment by marekcirkos** [comment]
Can you provide any system logs?
