### ISSUE TITLE
XCUIScreen  Abnormal

### ISSUE THREAD

**Issue by lingtingSir** [facebook/WebDriverAgent#784]
WebDriverAgentRunner-Runner[30101:1074487] *** Assertion failure in -[XCUIScreen _screenshotDataForQuality:rect:error:], /Library/Caches/com.apple.xbs/Sources/XCTest_Sim/XCTest-13201/Sources/UITesting/XCUIScreen.m:230

**Comment by mykola-mokhnach** [comment]
Can you please provide more context on this failure?
