### ISSUE TITLE
Locating files with Xpath takes a long time

### ISSUE THREAD

**Issue by cooperisduhace** [facebook/WebDriverAgent#785]
Hi,

Currently we have a hard time on automating our project as locating Xpath locators is taking its sweet time to find. It takes about 3-4 mins just to locate an element. We are automating an IOS Hybrid app.

Is there any way to make this faster? Using accessibility_id is much faster but most of our locators are not viable to use accessibility_id as most of our labels are dynamically changed.

We tried following instructions from this issue https://github.com/facebook/WebDriverAgent/issues/372 but with no success.

# Sample Xpaths:
xpath=//XCUIElementTypeStaticText[contains(@value,'Pick Up') and not(contains(@value,'Prepare')) and not(contains(@value,'Awaiting'))]
xpath=//XCUIElementTypeStaticText[contains(@value,'Completed')]

**Comment by mykola-mokhnach** [comment]
try to replace your queries with predicates/class chains: https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance

**Comment by cooperisduhace** [comment]
How should i do this on robot-framework? When I use POSTMAN to locate my element it returns this:
![image](https://user-images.githubusercontent.com/15809861/32540236-0924adfc-c4a7-11e7-89ca-389236e63603.png)

But when I run my tests it says:
```Keyword 'AppiumLibrary.Tap' failed after retrying for 4 minutes. The last error was: ValueError: Element locator '**/XCUIElementTypeStaticText[`value BEGINSWITH 'Pick Up'`]' did not match any elements.```

I also tried adding class_path=**/XCUIElementTypeStaticText[`value BEGINSWITH 'Pick Up'`] for the locator and still to no avail.

# Code
```
Suite Teardown    Close Application
Force Tags        SFLogin    High
Resource          ../../../Resources/SFKeywords.tsv

*** Test Cases ***
User Should Be Logged In With Valid Credentials
    Open Application And Log In    ${SFUsername}    ${SFPassword}
    Click    **/XCUIElementTypeStaticText[`value BEGINSWITH 'Pick Up'`]
```

**Comment by marekcirkos** [comment]
xpath is slow and will be slow. There is no way to optimise it for perf. You should consider moving out from xpath
