### ISSUE TITLE
fb_isvisible method to achieve a problem in iOS10.2

### ISSUE THREAD

**Issue by lingtingSir** [facebook/WebDriverAgent#786]
iOS10.2 version When pop-up or mask view or full-screen pop-up window, the underlying UI elements are usually not visible, Currently isvisible is True, is there any good way to identify pop-up view

**Comment by marekcirkos** [comment]
What do you mean by `Currently isvisible`? I am not sure what do you state as an issue here?

**Comment by antiarchit** [comment]
Closing since insufficient data. Feel free to re-open or create a new issue with some more data so we can investigate.
