### ISSUE TITLE
WebDriverAgent fails on iOS11.1 device

### ISSUE THREAD

**Issue by funkyvisions** [facebook/WebDriverAgent#789]
## The problem

I'm running Appium.  I get "Could not write to device error" when it tries to install WDA on a real iOS 11.1 device.  It works fine on an iOS 10.3 device.

## Environment

* Appium 1.7.1
* MacOS Sierra 10.13.1, Xcode 9
* Node 8.6.0
* iOS 11.1

## Details

When I run (or appium runs)

xcodebuild build-for-testing test-without-building -project /Users/daviesd/workspace/wms-circ-app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=a3ce98efdcb051d96ec2b652bcdf4022869beb38 -xcconfig /var/folders/j9/t3_mfb994192rsywfpfhpcgh578d_j/T/2017109-70564-1tvshsa.62so/appium-temp.xcconfig

I see 

 NSLocalizedRecoverySuggestion=Could not write to the device., NSLocalizedFailureReason=Could not write to the device.}
2017-11-09 11:17:15.557 xcodebuild[70755:11901569] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Here's the link to my appium log:

https://gist.github.com/funkyvisions/665069d51a7c09f7d3dc4155c1b4f52d

Here's another log that I just got the reports "App installation failed"

https://gist.github.com/funkyvisions/cbe3ae4fa05b391018aa7e14265af04b

**Comment by gu-wei** [comment]
same issue:
add log:
Wei-Dev-Mac:~ weigu$ xcodebuild build-for-testing test-without-building -project /Users/weigu/src/git/appium/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=f2eb6fac5437b05356a69ba128a7895c0124537c IPHONEOS_DEPLOYMENT_TARGET=11.0 -xcconfig /Users/weigu/src/git/appium/.vscode/wda.xcconfig
Build settings from command line:
    IPHONEOS_DEPLOYMENT_TARGET = 11.0

Build settings from configuration file '/Users/weigu/src/git/appium/.vscode/wda.xcconfig':
    BUILD_PRODUCTS_DIR = $(SRCROOT)/build/$(SDKROOT)/$CONFIGURATION
    CODE_SIGN_IDENTITY = iPhone Developer
    CONFIGURATION_BUILD_DIR = $(SRCROOT)/build/$(SDKROOT)/$CONFIGURATION
    DEVELOPMENT_TEAM = UBF8T346G9
    DSTROOT = $(SRCROOT)/build/$(SDKROOT)/$CONFIGURATION/build.dst
    IPHONE_DEPLOYMENT_TARGET = 10.0
    OBJROOT = $(SRCROOT)/build/$(SDKROOT)/$CONFIGURATION/build.obj
    PROJECT_TEMP_DIR = $(SRCROOT)/build/$(SDKROOT)/$CONFIGURATION/$(PROJECT_NAME).build
    SDKROOT = iphoneos
    SHARED_PRECOMPS_DIR = $(SRCROOT)/build/$(SDKROOT)/$CONFIGURATION/build.pch
    SYMROOT = $(SRCROOT)/build/$(SDKROOT)/$CONFIGURATION/build.sym

=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

** TEST BUILD SUCCEEDED **

2017-11-10 15:36:08.589 xcodebuild[54461:6772282]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/xz/4mg39ybs31907gx3tcyy926h0000gp/T/com.apple.dt.XCTest/IDETestRunSession-77D4F45D-6CBB-44B4-8595-BC1529A06B69/WebDriverAgentRunner-38171DEC-DE45-4080-AC2A-9B625916903B/Session-WebDriverAgentRunner-2017-11-10_153608-P7utRm.log
2017-11-10 15:36:08.590 xcodebuild[54461:6772230] [MT] IDETestOperationsObserverDebug: (A49B7B43-3831-46BA-9CC1-A022FD6022A0) Beginning test session WebDriverAgentRunner-A49B7B43-3831-46BA-9CC1-A022FD6022A0 at 2017-11-10 15:36:08.589 with Xcode 9B55 on target <DVTiOSDevice: 0x7f82c1de3650> {
		deviceSerialNumber:         F72SHPSQHG6W
		identifier:                 f2eb6fac5437b05356a69ba128a7895c0124537c
		deviceClass:                iPhone
		deviceName:                 iPhone
		deviceIdentifier:           f2eb6fac5437b05356a69ba128a7895c0124537c
		productVersion:             11.1.1
		buildVersion:               15B150
		deviceSoftwareVersion:      11.1.1 (15B150)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        28578009088
		deviceAvailableCapacity:    21951717376
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f82c1d946e0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		connected:                 yes
		isWirelessEnabled:         no
		connectionType:            direct
		} (11.1.1 (15B150))
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xz/4mg39ybs31907gx3tcyy926h0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/842d8a783618ef0224468eb217944707/f2eb6fac5437b05356a69ba128a7895c0124537c/ManifestCache.plist
2017-11-10 15:38:17.623 xcodebuild[54461:6772230] Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner" UserInfo={NSLocalizedDescription=Unable to launch com.apple.test.WebDriverAgentRunner-Runner, NSUnderlyingError=0x7f82ce1320f0 {Error Domain=DTXMessage Code=1 "(null)" UserInfo={DTXExceptionKey=Background launch requested, but this app cannot run in the background (see UIApplicationExitsOnSuspend or 'Background Modes' in Xcode).}}}
2017-11-10 15:38:17.623 xcodebuild[54461:6772230] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
** TEST EXECUTE FAILED **

**Comment by chanugithub** [comment]
yes same issue webdriver agent runner is unable to install in xcode 9.1/ios 11.1 but weird thing is the logs are saying code signing issue :(

Got this error when selected webdriver agent runner in xcode and doing Product/Test

dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/901DB988-6057-4DE3-91CF-CC8EEE670A6D/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/901DB988-6057-4DE3-91CF-CC8EEE670A6D/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/901DB988-6057-4DE3-91CF-CC8EEE670A6D/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/901DB988-6057-4DE3-91CF-CC8EEE670A6D/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/901DB988-6057-4DE3-91CF-CC8EEE670A6D/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
(lldb) bt
* thread #1, stop reason = signal SIGABRT
  * frame #0: 0x0000000102a16f1c dyld`__abort_with_payload + 8
    frame #1: 0x0000000102a166f4 dyld`abort_with_payload_wrapper_internal + 100
    frame #2: 0x0000000102a16720 dyld`abort_with_payload + 12
    frame #3: 0x00000001029ec498 dyld`dyld::halt(char const*) + 312
    frame #4: 0x00000001029ef714 dyld`dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 7376
    frame #5: 0x00000001029e921c dyld`_dyld_start + 68

**Comment by chanugithub** [comment]
funkyvisions Finally i was able to find the solution, it was actually Apple certificates in key chain access which now i set to 'system default' and previously it was in 'Always trust' mode

**Comment by marekcirkos** [comment]
Can you add some info in Wiki's common issues ?

**Comment by chanugithub** [comment]
@marekcirkos sure can you send me link for wiki so that i would add some info

**Comment by funkyvisions** [comment]
Sorry, just saw this.  I will check.

**Comment by funkyvisions** [comment]
@chanugithub all of mine were set to "system default" already.  still doesn't work for me.
