### ISSUE TITLE
Linking WebDriverAgent.framework in non-Test target

### ISSUE THREAD

**Issue by pratimas** [facebook/WebDriverAgent#790]
Hi, I am trying to using WebDriverAgent.framework in my application.
It builds successfully, but while running It says 

dyld: Library not loaded: @rpath/XCTest.framework/XCTest referenced from WebDriverAgentLib.framework/WebDriverAgentLib Reason: image not found

Can you plz help me o resolve the issue?
Is WebDriverAgent.framework only works with test-target ?
 Is there any way around I can use XCTest.framework in non-test target ?

Thank you.

**Comment by marekcirkos** [comment]
WDA is based on XCTest framework. Why do you want to even link it to regular app?
