### ISSUE TITLE
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65"

### ISSUE THREAD

**Issue by chanugithub** [facebook/WebDriverAgent#792]
Hello, @mykola-mokhnach @imurchie @marekcirkos 

I am trying to automate native ios app and having very hard time launching the webdriver agent and could not get single clue why it is failing. Unable to find whether any of my configuration got messed up or permission issue. I had cross check with my iOS developer that code sign provisional profiles are correct in my xcode. I uninstalled and installed appium and its dependencies several times but always failing in versions V1.6.5/V1.7.1/V1.7.2-beta
My co-worker had same setup as mine but he was able to launch the app.
Here are my desired capabilities and setup
iOS 11.1/xcode 9.1/Appium V1.7.2-beta/Mac 10.12.6

	cap.setCapability("platformName", "iOS");
			cap.setCapability("platformVersion", "11.1");
			cap.setCapability("deviceName", "iPhone 7 Plus");
			cap.setCapability("automationName", "XCUITest");
			cap.setCapability("udid", "given correct device udid number");
			cap.setCapability("bundleid", "com.facebook.WebDriverAgentLib");
			cap.setCapability("showIOSLog", true);
			// cap.setCapability("autoWebview", "true");
			cap.setCapability("clearSystemFiles", "true");
			cap.setCapability("useNewWDA", "true");
			cap.setCapability("noReset", "true");
			cap.setCapability("startIWDP", "true");
			cap.setCapability("showXcodeLog", "true");
			cap.setCapability("xcodeSigningId", "iPhone Developer");
			cap.setCapability("xcodeOrgId", "----------");
			
The regular errors i found in logs are 
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
 [IOS_SYSLOG_ROW] Nov 14 13:43:51 orbs-iPhone installd(Security)[46] <Notice>:  [leaf CheckIntermediateMarkerOid CheckLeafMarkerOid]
[Xcode] 2017-11-14 13:43:51.127 xcodebuild[74653:3785821]  iPhoneConnect: installApplicationBundleAtPath:withOptions:andError:withCallback: failed with {
[Xcode]     NSLocalizedDescription = "Unable to install \"WebDriverAgentRunner-Runner\"";
[Xcode]     NSLocalizedRecoverySuggestion = "The certificate used to sign \"WebDriverAgentRunner-Runner\" has either expired or has been revoked. An updated certificate is required to sign and install the application.";
[Xcode] }
[Xcode] 
[iOSLog] [IOS_SYSLOG_ROW] Nov 14 13:43:51 orbs-iPhone installd(MobileSystemServices)[46] <Notice>: 0x16f507000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 147: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.1cM1sO/extracted/WebDriverAgentRunner-Runner.app : 0xe8008018 (The identity used to sign the executable is no longer valid.)
[iOSLog] [IOS_SYSLOG_ROW] Nov 14 13:43:51 orbs-iPhone installd(MobileSystemServices)[46] <Notice>: 0x16f507000 -[MIInstaller performInstallationWithError:]: Verification stage failed
[debug] [XCUITest] 'pgrep -nif xcodebuild.*18e20052fc6d9a7676a519e63cbbcb62fe818fb8' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Cannot find xcodebuild's process id, so unable to retrieve DerivedData folder path
[XCUITest] No WebDriverAgent derived data available, so unable to clear system files
[debug] [iOSLog] Stopping iOS log capture

This is the error when i type this command line
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=udid' test 
then this the error
[webdriver agent console info.txt]
https://gist.github.com/chanugithub/bf952a3fa61db43333997e7177ec37be

Actual error in eclipse logs
https://gist.github.com/chanugithub/b60d33aa0931287fa976a730ce082cf4

Appium Doctor logs in case if i messed up with env variable
https://gist.github.com/chanugithub/c2af8b6b45084f66588bf7c04fb7f94f

**Comment by chanugithub** [comment]
@mykola-mokhnach Can you once verify the above issue and give me any feedback as you work exclusively on iOS

**Comment by chanugithub** [comment]
Finally i was able to find the solution, it was actually Apple certificates in key chain access which now i set to 'system default' and previously it was in 'Always trust' mode

**Comment by deepRaghwa** [comment]
Thanks a ton @chanugithub . this was exactly the same issue in my case as well. One of the Apple certificate was set to "Always trust" in the Keychain Access. Reverted it back to "System Default" and all works fine now. Thanks a lot once again.

**Comment by chanugithub** [comment]
@deepRaghwa Glad you got this fixed from my approach

**Comment by ShanmukhaArun** [comment]
Hi Guys, i have the issue related to dis. 

- First For Provision profile what is the BundleId do i need to provide, The iPhone Developers have provided the provisioning profile with "com.zoll.navigatorapp", i am updating the build settings as "com.zoll.WebDriverAgentRunner". is this the right way to do?.

- second thing is i am not able to launch the app, webDriver will install in real device but app is not launching.

Can anybody please help me on this.

**Comment by siddhantraut** [comment]
Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.


{

  "platformName": "iOS",
  "platformVersion": "11.0.3",
  "app": "Users/admin/Automation/xyz.ipa”,
  "deviceName": "iPhone 8",
  "noReset": true,
  "udid": “3123hh3o4hoh4hohoh31h312h12o31XXXXXXXX”,
  "automationName": "XCUITest",
  "xcodeOrgId": " ABCDEFGH”,
  "xcodeSigningId": “iPhone Developer”
}


Xcode 9.2
Appium Desktop: 1.3.1

When using certificate : "User system default"

still have problem....

**Comment by ssmalan94** [comment]
@chanugithub How did you changed that Keychain?

**Comment by ashishyadav2020** [comment]
@chanugithub  Could you please be specific which certificate to modify in Keychain?
@ssmalan94  Did you resolve it?

**Comment by ashishyadav2020** [comment]
Ah ok. But for me I need to test against iOS12(beta), which requires latest Xcode (10 beta 5). And there was known issue with Xcode v10 with Appium (Regex) and it was fixed in Appium Desktop v1.6.3.

**Comment by ssmalan94** [comment]
@ashishyadav2020  ohh....then you have to wait for another fix... I've tried with all steps.

**Comment by chanugithub** [comment]
@ssmalan94 @ashishyadav2020  i solved by below steps, if still it happens then you have to dig more 

In Mac,

Go to Keychain access
right click on iPhone developer (or your iphone developer ID)
click on 'get info'
click on 'Trust' arrow mark
Observe the first option (when using this certificate: Use 'System Defaults')
it should be 'System Defaults', it should not be 'Always Trust' or 'never trust'
All other certificates in 'Login' and 'System' etc should be 'System Defaults'

**Comment by ashishyadav2020** [comment]
@chanugithub Thanks for detailed steps.

I found these were already set to 'System Default' on my system. I need to investigate more on this.
