### ISSUE TITLE
Iphone X iOS 11 waiting for connection [debug] [iProxy] Number of available devices == 1 [debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100 #9626

### ISSUE THREAD

**Issue by Kitty2014** [facebook/WebDriverAgent#793]
The problem

waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100 shown when running iOS11

Environment

Appium version (or git revision) that exhibits the issue: v1.7.2-beta
Last Appium version that did not exhibit the issue (if applicable): -
Desktop OS/version used to run Appium: 10.12.6 (16G1023)
Node.js version (unless using Appium.app|exe): v8.4.0
Mobile platform/version under test: iPhone X iOS 11.0.1 and 11.2
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI
Xcode version set to 'Version 9.2 beta (9C32c)'

Details

iOS10.3.3 normally but fail with iOS11

**Comment by Kitty2014** [comment]
App run in background but  session  does not replace ,[debug] [iProxy] waiting for connection
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection
[debug] [iProxy] Number of available devices == 1
[debug] [iProxy] Requesting connecion to device handle == 1 (serial: 6b5dc9ce1d3846893ff756459eb2b7133938bbcb), port 8100
[debug] [iProxy] accepted connection, fd = 4
[debug] [iProxy] waiting for connection

**Comment by marekcirkos** [comment]
Do you have any system logs or Xcode logs? Those log do not tell me much

**Comment by Kitty2014** [comment]
@marekcirkos  sorry to reply you so late
this maybe iOS  11early daily version  which Interrupt mechanism, in recently iOS version works OK
