### ISSUE TITLE
Screenshots slow after removal of Peertalk

### ISSUE THREAD

**Issue by mike-seagull** [facebook/WebDriverAgent#795]
Ever since Peertalk was removed, calling the 'screenshot' endpoint seems slower (from 40ms to 300ms). Unfortunately, I cannot verify that because @marekcirkos 's fork of Peertalk was removed. Is there any place that I can get a copy of the fork to further test this out?

**Comment by marekcirkos** [comment]
This definitely is unrelated. Peertalk was used only as a proxy. We removed it because there are simpler solutions https://github.com/facebook/WebDriverAgent/wiki/USB-support
