### ISSUE TITLE
WebDriverAgent failing because of system alert that is open before starting the appium test

### ISSUE THREAD

**Issue by danielMayberg** [facebook/WebDriverAgent#799]
environment: appium+ruby+mac+iphone 6(real device)
this error occurs when I have an system alert open prior to starting a test, example: OS update message or enter password for itunes account. the error I get from webdriver is: Error Domain=IDETestOperationsObserverErrorDomain Code=13 "Failed to background test runner"

any workaround to deal with this issue? if I manually close the alert my test works fine.

thanks

(added screenshot of this)
![screen shot 2017-11-21 at 3 00 47 pm](https://user-images.githubusercontent.com/23641475/33073894-f4f9398a-cecc-11e7-97dc-ecb47dbed6d8.png)

**Comment by marekcirkos** [comment]
This is Xcode issue.

**Comment by danielMayberg** [comment]
you could be a little more informative..this issue makes working with webdriver a nightmare
