### ISSUE TITLE
[Question] Is there a way to automatic (CLI) re-sign WDA after free license expired?

### ISSUE THREAD

**Issue by lavi-xu** [facebook/WebDriverAgent#800]
We follow the steps to compile WDA Agent for appium with checked automatic code-sign.  And it works great.

However, the sign license we used is using a free Apple account which will be required to re-checkout license after 6 days in Xcode.

Normal we re-sign wda agent in xcode manually, I wanna know is there command line to automatic re-sign WDA for CI?

Thanks,

BR.

**Comment by marekcirkos** [comment]
Simple rebuild will resign it right?

**Comment by lavi-xu** [comment]
Yes, Just launch Xcode once, it will rebuild with resign.

However is there a way to do this over command line? 
So that these steps could be integrated to CI (over command line).

BRs.

**Comment by marekcirkos** [comment]
`xcodebuild` should the same.
