### ISSUE TITLE
XCUITest] Failed to create WDA session. Retrying...

### ISSUE THREAD

**Issue by zusmani-mbo-com** [facebook/WebDriverAgent#801]
Hi All,
I am getting similar error when trying to launch the app, even though I have not specified the bundle ID.I am running this on bitrise mac. box
Also , I have attached the ios logs

https://gist.github.com/zusmani-mbo-com/3dd2f3069ecfa0137bdbbc02f7fbedae
I have also looked at this issue, can not get it working still, It does not work manually 

Appium version 1.7.1
Desktop OS IOS:
Mobile platform/version under test:
emulator/simulator:
Appium CLI :

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/issues/802

**Comment by shubhamj-cuelogic** [comment]
This issue is not resolved.. I am still getting same for appium version v1.3.2(appium-desktop-1.3.2-mac.zip) for IOS automation

**Comment by anandkiran2007** [comment]
Me too facing the same issue

**Comment by anandkiran2007** [comment]
any help is much appreciated

**Comment by Pr60** [comment]
I'm also facing this issue. Please find the logs here: 
https://gist.github.com/Pr60/728fe3474b1a1c0321d7bcf251e2fad9

Environment:
Desktop OS/version used to run Appium: Mac OSX High Sierra
Node.js version : 8.11.1
npm version: 5.6.0
Appium CLI: 1.8

**Comment by PatwalRohit** [comment]
I'm facing the same issue.No luck.

[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1533118394675 (15:43:14 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.ionicframework.appiumtest992994","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"The application under test with bundle id 'com.ionicframework.appiumtest992994' is not running, possibly crashed","sessionId":"77C648D9-ECBF-4E24-8946-DCAA02FE77E9","status":889}

Desktop OS/version used to run Appium: Mac OS High Sierra (10.13.4)
Node.js version : 8.11.2
npm version: 6.2.0
Appium CLI: 1.8.1
