### ISSUE TITLE
[XCUITest] Failed to create WDA session. Retrying...

### ISSUE THREAD

**Issue by zusmani-mbo-com** [facebook/WebDriverAgent#802]
Hi All,
I am getting similar error when trying to launch the app, even though I have not specified the bundle ID.I am running this on bitrise mac. box
Also , I have attached the ios logs

https://gist.github.com/zusmani-mbo-com/3dd2f3069ecfa0137bdbbc02f7fbedae
I have also looked at this issue, can not get it working still.It does not work manually too.
#8373

Appium version 1.7.1
Desktop OS IOS:
Mobile platform/version under test:
emulator/simulator:
Appium CLI :

**Comment by Bose27** [comment]
Hi I am facing the same issue with the appium desktop app 1.4
PFA log.
[appium-server-log0330.txt](https://github.com/facebook/WebDriverAgent/files/1864545/appium-server-log0330.txt)

**Comment by marekcirkos** [comment]
`Failed to launch com.go.abclocal.kabcapp` does the app crash? Do you use correct bundle id here?
