### ISSUE TITLE
Create WebDriverAgent .ipa and use it without Xcode 

### ISSUE THREAD

**Issue by JasmeetDeveloper** [facebook/WebDriverAgent#803]
Can I create WebDriverAgent .ipa and use it without Xcode, currently I have built .ipa but the connection does not seem to work .

Any help or guidance?

**Comment by JasmeetDeveloper** [comment]
Any help ?

**Comment by csusheep** [comment]
U Cannot

**Comment by JasmeetDeveloper** [comment]
Please check this issue : It says its possible but don't know how  

https://github.com/facebook/WebDriverAgent/issues/496

**Comment by marekcirkos** [comment]
Maybe contact guy that said it is possible?

**Comment by oldstone** [comment]
> Can I create WebDriverAgent .ipa and use it without Xcode, currently I have built .ipa but the connection does not seem to work .
> 
> Any help or guidance?

Can you please provide instructions on how to create WDA ipa file?
