### ISSUE TITLE
Locators not found while testing on iOS 11 for App which is built using Xcode 8

### ISSUE THREAD

**Issue by VenkateshPS** [facebook/WebDriverAgent#805]
Locators not found while testing on iOS 11 for App which is built using Xcode 8, is this a known issue.

On iOS 11 label="Compose New Message" is not shown, when I do driver.getPageSource, though the Image is present on UI.

Please look into the Attached locatorsourcecomparison.txt

[locatorsourcecomparison.txt](https://github.com/facebook/WebDriverAgent/files/1517323/locatorsourcecomparison.txt)

**Comment by marekcirkos** [comment]
What is your search query?

**Comment by marekcirkos** [comment]
We do not support anything below Xcode 9
