### ISSUE TITLE
Not getting "Listening on USB" when running WebDriverAgentRunner test

### ISSUE THREAD

**Issue by rpjesivac** [facebook/WebDriverAgent#807]
Hi,

I am trying to setup appium to work for testing iOS devices and I can go trough installation, signing, and building everything successfully but when I run the last test I don't get "Listening on USB" message.

I did noticed that when tests start the port of ServerURL is 0 and not 8100 and I am not sure why that is happening?

Here is just the last couple of lines of test but full log is attached.

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/b1/10pd17vj6wnd_smk4wcmxbm00000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/dcba334e6702d57f1cb07a0e3223d02d/bf07b43c4cb47cb4522ce2edb31197a6ff5f7b05/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/mesqa/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/b1/10pd17vj6wnd_smk4wcmxbm00000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.dvtedW/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
dst_ipa: /var/folders/b1/10pd17vj6wnd_smk4wcmxbm00000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.dvtedW/WebDriverAgentRunner-Runner.app_sparse.ipa
MDMDirectoryDiff_block_invoke:1473 calling writeDictToFile with: /var/folders/b1/10pd17vj6wnd_smk4wcmxbm00000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.dvtedW/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/b1/10pd17vj6wnd_smk4wcmxbm00000gq/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.dvtedW/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2017-11-30 10:40:56.348883-0500 XCTRunner[354:101620] Running tests...
2017-11-30 10:40:56.413297-0500 XCTRunner[354:101620] Continuing to run tests in the background with task ID 1
2017-11-30 10:40:57.652890-0500 XCTRunner[354:101620] Continuing to run tests in the background with task ID 2
Test Suite 'All tests' started at 2017-11-30 10:40:58.702
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-11-30 10:40:58.705
Test Suite 'UITestingUITests' started at 2017-11-30 10:40:58.706
Test Case '-[UITestingUITests testRunner]' started.
t =     0.00s     Start Test at 2017-11-30 10:40:58.707
t =     0.01s     Set Up
2017-11-30 10:40:58.723790-0500 XCTRunner[354:101620] Built at Nov 29 2017 15:30:10
2017-11-30 10:40:58.755890-0500 XCTRunner[354:101620] ServerURLHere->http://10.234.74.142:0<-ServerURLHere

Also, if I run CURL command to test it I get connection refused on port 8100.

C1MR10FNG944:~ mesqa$ curl -X GET -H "Content-Type: application/json;charset=UTF-8, accept:application/json" http://10.234.74.142:8100/status
curl: (7) Failed to connect to 10.234.74.142 port 8100: Connection refused

Any suggestion on how to complete this successfully?

Thanks

[RunLogs.txt](https://github.com/facebook/WebDriverAgent/files/1518473/RunLogs.txt)

**Comment by sorccu** [comment]
Doesn't exist anymore. See 5428e03808a5bffa2d550424769f0559f0505220.

**Comment by marekcirkos** [comment]
This diff is unrelated. I suspect your port is already in use, can you try changing the port to different one?
