### ISSUE TITLE
Running WDA on iOS 11 real device, request always timeout

### ISSUE THREAD

**Issue by liuxuan30** [facebook/WebDriverAgent#808]
So I am new to WDA and just download and executed `./Scripts/bootstrap.sh` on latest master branch with official Xcode 9 latest and iPhone 7 + iOS 11.1.2

It build and launched fine, I can see my server URL 
```
Runner[2675:912531] ServerURLHere->http://192.168.1.52:8100<-ServerURLHere
```
however when trying to `GET http://192.168.1.52:8100`, it always timeout. If I open safari on iPhone 7, it returns json message, so it's fine on device.

My iPhone and mac are in same local network, and the universal clipboard is working as well, so it should not be local network connection issue, but I just don't know why I can't get any response on my mac.

Can anyone help? Thanks!

**Comment by marekcirkos** [comment]
Can you at least ping that ip from mac? Maybe your router is blocking connections?

Anyway, if you can connect your devices via USB you can always you usb proxy instead

**Comment by liuxuan30** [comment]
No, the ip is pingable. If I use iproxy, the server will respond. So I think it's the server or something wrong?

**Comment by marekcirkos** [comment]
That would suggest routing issues.

**Comment by liuxuan30** [comment]
yes I just found that.  But why..? It's super weird.

**Comment by Pylipala** [comment]
Exactly the same behavior here, visit `http://192.168.0.101:8100/` on iPhone is OK with json response. Visit the same URL on Mac which is connected to the same wifi network, it always timeout.

**Comment by Shunzi007** [comment]
I meet the same issue.

**Comment by PandaraWen** [comment]
Same issue here, the ip is pingable but request from my mac and other iPhone would always go into timeout.

**Comment by 308823810** [comment]
I am also facing the same issue.
_XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply contained error: Error Domain=DTXProxyChannel Code=1 "(null)" UserInfo={DTXProxyChannelErrorMessage=Channel disconnected}

**Comment by 308823810** [comment]
About  Error Domain=DTXProxyChannel Code=1 "(null)" UserInfo={DTXProxyChannelErrorMessage=Channel disconnected} , Surprisingly, to fix this, just replugged my iPhone to another port  !!!!

**Comment by liuxuan30** [comment]
@marciok I came across this post: https://www.reddit.com/r/apple/comments/69k1j8/the_chinese_iphones_let_you_choose_which_apps_can/
Saying Chinese phones will have option for the internet access.

To quote one message:
>Cydia, for example, won't be able to access internet because it's not allowed to, but it would never show a pop-up asking for permission, and won't be in app list

Will this be the same issue as WDA? I don't remember if WDA popup the window and ask for permit, and right now I didn't have phone to test yet.

**Comment by chfism** [comment]
@308823810 replugging the iPhones works for me too.

**Comment by marekcirkos** [comment]
I remember that, there was an issue with phones in China, and simple solution for that is using usb proxy to connect to WDA.

**Comment by liuxuan30** [comment]
@marekcirkos I would keep this open, as we might find the possible reason, and we need to confirm if it's directly related, or just irrelevant.

**Comment by harlentan** [comment]
> @marekcirkos I meet the same issue too,but I found a rule,when I disable the iphone's wifi,wda-runner will be ok,when I open the iphone's wifi,wda-runner will go into timeout and return error:"XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply contained error: Error Domain=DTXProxyChannel Code=1 "(null)" UserInfo={DTXProxyChannelErrorMessage=Channel disconnected}". a few days ago,i run the command idevice_id -l,it return two same ideviceid when I connect the iphone via usb with wifi on,but when I close iphone's wifi,it return only one ideviceid.so I suspect that the problem is related to the network,but I don't know how to solve.


I have the same issue. It will be ok if I disable the wifi.

how to fix it ?

**Comment by Jitu1888** [comment]
@marekcirkos How to enable the Wifi, we need it for Automation?
We can't use USB port as it is occupied by our product. I will really appreciate if you help me on this.

Thanks
Jitu

**Comment by Jitu1888** [comment]
@marekcirkos @harlentan In which file I need to enable the Wifi proxy? Please let me know I will try it locally.

**Comment by harlentan** [comment]
> @marekcirkos @harlentan In which file I need to enable the Wifi proxy? Please let me know I will try it locally.

iTunes -> find your device -> enable wifi sync

wifi connection for automation test is unstable.

**Comment by Jitu1888** [comment]
@harlentan Still the same error [XCUITest] Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

**Comment by Jitu1888** [comment]
@marekcirkos Please help me out....Please
