### ISSUE TITLE
Unable to close app via XCUITests

### ISSUE THREAD

**Issue by kaleposhobios** [facebook/WebDriverAgent#81]
Hi,

I'm trying to kill the app. I tried the following:
    curl -X DELETE -H "Content-Type: application/json" -d "{\"session\":\"29E17024-0123-4FA7-A019-22FE8248463E\"}" http://10.0.0.71:8100

    curl -X DELETE http://0.0.0.71:8100/session/29E17024-0123-4FA7-A019-22FE8248463E/

Neither of these work. Am I doing something wrong? Or am I misunderstanding what should be happening with this endpoint? Thank you!

**Comment by marekcirkos** [comment]
If you haven't made typo in ip while pasting  `curl -X DELETE http://10.0.0.71:8100/session/29E17024-0123-4FA7-A019-22FE8248463E/` should work. What is the response?

**Comment by kaleposhobios** [comment]
I'm sorry, my error. It works now.
