### ISSUE TITLE
Cannot locate indexed element when the first tree view does not have such element.

### ISSUE THREAD

**Issue by lavi-xu** [facebook/WebDriverAgent#812]
Here it's tree view:
XCUIElementTypeScrollView
-> XCUIElementTypeTable (1)
-->  XCUIElementTypeCell
--->   XCUIElementTypeStaticText  [1]
--->   XCUIElementTypeStaticText  [2]
-> XCUIElementTypeTable (2)
-->  XCUIElementTypeCell
--->   XCUIElementTypeStaticText  [1] ---- here 1
--->   XCUIElementTypeStaticText  [2]
--->   XCUIElementTypeStaticText  [3]  ---- here 2

It cannot locate element with xpath like "//XCUIElementTypeStaticText[3]". What we expected is to located 3rd XCUIElementTypeStaticText   ( here 1)

or xpath like "//XCUIElementTypeCell/XCUIElementTypeStaticText[3]". What we expected is to located 3rd XCUIElementTypeStaticText   ( here 2)

**Comment by marekcirkos** [comment]
@mykola-mokhnach any idea?

My personal advice, don't use 'xpath' and depend on identifiers instead.

**Comment by mykola-mokhnach** [comment]
Yep, I've also suggested the same in the linked Appium issue. Also, the locator itself is not very readable and is not easy to understand
