### ISSUE TITLE
Can WebDriverAgent support the operation App with alibaba/weex elements？

### ISSUE THREAD

**Issue by NeowuqiLee** [facebook/WebDriverAgent#817]
Weex element develop by vue.js，I can search the elements，but can not interact with it。

**Comment by marekcirkos** [comment]
Do you have any errors, logs or code sample?

**Comment by NeowuqiLee** [comment]
t = 72225.52s     Snapshot accessibility hierarchy for app with pid 543
    t = 72225.60s     Find: Descendants matching type StaticText
    t = 72225.60s     Find: Elements matching predicate 'wdName == "让分" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
    t = 72225.63s Find the Application "com.ZhongCai500" 0x1c6ada400
    t = 72225.63s     Snapshot accessibility hierarchy for app with pid 543
    t = 72225.68s Get all elements bound by index for: Elements matching predicate 'wdName == "让分" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
    t = 72225.68s     Snapshot accessibility hierarchy for app with pid 543
    t = 72225.75s     Find: Descendants matching type StaticText
    t = 72225.76s     Find: Elements matching predicate 'wdName == "让分" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
    t = 72225.79s Find the Application "com.ZhongCai500" 0x1c6ada400
