### ISSUE TITLE
Sending createSession command to WDA - No session start

### ISSUE THREAD

**Issue by haithngn** [facebook/WebDriverAgent#819]
Hi there,

I'm facing with this issue, Appium could not start new Simulator session there are the log.

P/S: After once launch from xcode, appium work fine.

`Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.0\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.0\",\n      \"ip\" : \"192.168.1.3\"\n    },\n    \"build\" : {\n      \"time\" : \"Dec  9 2017 09:33:11\"\n    }\n  },\n  \"sessionId\" : \"19B4C373-3957-4D68-B957-DCF80B4C49B8\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.floware.universalflo.dev","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.floware.universalflo.dev application","sessionId":"19B4C373-3957-4D68-B957-DCF80B4C49B8","status":13}
[debug] [XCUITest] Failed to create WDA session. Retrying...`

**Comment by marekcirkos** [comment]
It failed, because app launch failed. Unless you provide some more logs, I cannot help much
