### ISSUE TITLE
Have we support webview context?

### ISSUE THREAD

**Issue by xudafeng** [facebook/WebDriverAgent#82]
```bash
{
  "value": "Unhandled endpoint: /session/5918AD27-DC17-4135-A311-00DE4B4BAE11/context -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/5918AD27-DC17-4135-A311-00DE4B4BAE11/context\"\n    );\n}",
  "sessionId": "5918AD27-DC17-4135-A311-00DE4B4BAE11",
  "status": 1
}
```

By the way, according to the [de-facto standard spec-draft](https://code.google.com/p/selenium/source/browse/spec-draft.md?repo=mobile), server should response with result status `501` not `implemented`, thanks team!

**Comment by ziczhu** [comment]
+1, cant agree any more.

**Comment by Jonahss** [comment]
appium-xcuitest-driver wraps facebook/webdriveragent and connect to the safari debugger port for automating safari and webviews.
