### ISSUE TITLE
Unknown type name 'XCUIScreen'

### ISSUE THREAD

**Issue by pluie-cloud** [facebook/WebDriverAgent#821]
xcode 8
error ： 
/Users/root2/Downloads/WebDriverAgent-master/WebDriverAgentLib/Categories/XCUIElement+FBUtilities.m:147:3: Unknown type name 'XCUIScreen'; did you mean 'UIScreen'?

**Comment by lavi-xu** [comment]
You have to use xcode 9+

**Comment by pluie-cloud** [comment]
I see,thx
