### ISSUE TITLE
[Question] about performance of xml format.

### ISSUE THREAD

**Issue by lavi-xu** [facebook/WebDriverAgent#822]
I did a try on using json format to return for appium pagesource, it quite fast [ios 11.2 with xcode 9.2).

It's kinda confusion why it produces such difference performance on XML and JSON format.
Is it possible that when user asks pagesource XML format, we first load UI tree with json format, after it full loaded we then covert this json to XML format one time and returns to appium?

Or better we should ask appium to convert json to xml on their side?

BRs.

**Comment by marekcirkos** [comment]
It would better to fix it on WDA side. We are open for PRs, so feel free to work on this.
