### ISSUE TITLE
cannot find interface declaration for 'XCUIScreen'.

### ISSUE THREAD

**Issue by qwertyI** [facebook/WebDriverAgent#825]
Hi, I'm new in WDA. 

I use `git clone https://github.com/facebook/WebDriverAgent.git` to download the newest code. And then use `./Scripts/bootstrap.sh` to init the code. 
But while I want to build the project, Xcode told me 
`cannot find interface declaration for 'XCUIScreen', do you mean 'UIScreen'?` 
and other issues like the ScreenShoot:
![image](https://user-images.githubusercontent.com/8364623/34137234-ba7f8046-e4a4-11e7-99c6-efddc65d6219.png)

Xcode: 8.3.3

can anyone save me time?

best wishes!

**Comment by jmei08** [comment]
update to xcode9

**Comment by sparda2** [comment]
Having exactly the same error as @qwertyI.  Did updating to xcode 9 fixed it for you?

**Comment by keshavwy** [comment]
@qwertyI , @jmei08 

Didn't work for me to even after upgrading to Xcode 9.4.1
