### ISSUE TITLE
Code Sign Error

### ISSUE THREAD

**Issue by yinyijie** [facebook/WebDriverAgent#830]
I follow the instruction for installing WDA, but failed in the final step for "start WebDriverAgentRunner test" . Does anyone know what the cause of the error was?

CodeSign /Users/tony/Library/Developer/Xcode/DerivedData/WebDriverAgent-echihzyuhxzrfyahcmsyeyorsdfn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework
    cd /Users/tony/GitHub/WebDriverAgent
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Developer: ycf_surpass@163.com (Q2QL232HC3)"

    /usr/bin/codesign --force --sign B91F53AF482A5B6112D2C99916B80B8B48D87F1D --deep --preserve-metadata=identifier,entitlements,flags --timestamp=none /Users/tony/Library/Developer/Xcode/DerivedData/WebDriverAgent-echihzyuhxzrfyahcmsyeyorsdfn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework

/Users/tony/Library/Developer/Xcode/DerivedData/WebDriverAgent-echihzyuhxzrfyahcmsyeyorsdfn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework: replacing existing signature
/Users/tony/Library/Developer/Xcode/DerivedData/WebDriverAgent-echihzyuhxzrfyahcmsyeyorsdfn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/XCTAutomationSupport.framework: unknown error -1=ffffffffffffffff
Command /usr/bin/codesign failed with exit code 1

**Comment by kwailamchan** [comment]
I encountered the same issue when clicking "production -> test".

**Comment by kwailamchan** [comment]
Try to configure code sign in general and build settings for WebDriverAgentLib and WebDriverAgentRunner, then re-ran, it worked.

References:
- [ iOS 真机如何安装 WebDriverAgent](https://testerhome.com/topics/7220)
- [Code signing is required for product type Unit Test Bundle in SDK iOS 8.0
](https://stackoverflow.com/questions/26109851/code-signing-is-required-for-product-type-unit-test-bundle-in-sdk-ios-8-0)

**Comment by yinyijie** [comment]
Fixed for reboot the laptop.
