### ISSUE TITLE
How to get a Python PIL object of screenshot?

### ISSUE THREAD

**Issue by livc** [facebook/WebDriverAgent#832]
I can get screenshot with wda and save it, read it with PIL. But it wastes time a lot. So I want to get PIL image object directly with wda, can I reach it?

Thanks.

**Comment by antiarchit** [comment]
WebDriverAgent tries to conform to the WebDriver spec, and I don't think it makes sense to have native support for a Python library within the project, even if it's possible. 

You can fork and try to implement it on your own though.
