### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by tornesschopper** [facebook/WebDriverAgent#839]
Env: Xcode 9.2
        iOS 11.2.2
        iPhone8 Plus

dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/9C2A48A2-53D4-41D3-81B1-E44791EEEA4D/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/9C2A48A2-53D4-41D3-81B1-E44791EEEA4D/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/9C2A48A2-53D4-41D3-81B1-E44791EEEA4D/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/9C2A48A2-53D4-41D3-81B1-E44791EEEA4D/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: code signing blocked mmap() of '/private/var/containers/Bundle/Application/9C2A48A2-53D4-41D3-81B1-E44791EEEA4D/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'

**Comment by marekcirkos** [comment]
This looks like issue with XCode here. Did you resolve it?

**Comment by aray0322** [comment]
@tornesschopper , did you fixed this issue?  I am facing the same issue here.

**Comment by 789dry** [comment]
@tornesschopper , did you fix this issue? I am facing the same issue here.

**Comment by ModiYesha** [comment]
@tornesschopper How did you solve the issue with xcode ? I am going through the same issue
