### ISSUE TITLE
How can I solve the following questions?

### ISSUE THREAD

**Issue by vivibro** [facebook/WebDriverAgent#842]
shenenweideMacBook-Pro:WebDriverAgent-master 2 vi-vibro$ ./Scripts/bootstrap.sh
Fetching dependencies
Please make sure that you have Carthage installed (https://github.com/Carthage/Carthage)
Note: We are expecting that carthage installed in /usr/local/bin/

**Comment by marekcirkos** [comment]
Visit https://github.com/Carthage/Carthage page and installing, might be a good idea

**Comment by vivibro** [comment]
Thank you sincerely
