### ISSUE TITLE
In iOS version 11.2.2, Test Failed

### ISSUE THREAD

**Issue by xiongbingyang** [facebook/WebDriverAgent#843]
In iOS version 11.2.2, Test Failed.But In iOS 11.2.1 it is successful,have you happened.

**Comment by SanlinBlackball** [comment]
if you made it ,could you tell me how to solve it ?

**Comment by xiongbingyang** [comment]
No,I do not konw how to solve it, I also have the problem

**Comment by BarnyZhao** [comment]
i have the same problem,it build success,but test failed,iOS 11.2.2

**Comment by BarnyZhao** [comment]
2018-01-15 10:16:58.756370+0800 WebDriverAgentRunner-Runner[249:5915] +[CATransaction synchronize] called within transaction
2018-01-15 10:16:58.879512+0800 WebDriverAgentRunner-Runner[249:5915] Running tests...
2018-01-15 10:17:53.396128+0800 WebDriverAgentRunner-Runner[249:6615] Connection peer refused channel request for "dtxproxy:XCTestDriverInterface:XCTestManager_IDEInterface"; channel canceled <DTXChannel: 0x1d00bce60>
Failed to run tests: The operation couldn’t be completed. (DTXProxyChannel error 1.)
Dumping buffered debug messages:
====================
10:16:58.887 WebDriverAgentRunner-Runner[249:5915] Linked XCTest.framework from /var/containers/Bundle/Application/9042B1C8-A796-4EBF-B0DE-5FCD7BA1BB8E/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest, built with Xcode 0920(9C34c), modified on Monday, 15 January 2018 at 10:04:42 AM China Standard Time
XCTest.framework bundle version: 13764
10:16:58.888 WebDriverAgentRunner-Runner[249:5915] System uptime: 58
10:16:58.888 WebDriverAgentRunner-Runner[249:5915] Process arguments: (
    "/var/containers/Bundle/Application/9042B1C8-A796-4EBF-B0DE-5FCD7BA1BB8E/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner",
    "-NSTreatUnknownArgumentsAsOpen",
    NO,
    "-ApplePersistenceIgnoreState",
    YES
)
10:16:58.888 WebDriverAgentRunner-Runner[249:5915] Process environment: {
    "CFFIXED_USER_HOME" = "/private/var/mobile/Containers/Data/Application/EFBD02E2-D9D0-4A3C-8703-93DE6FEB96DF";
    CLASSIC = 1;
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/9042B1C8-A796-4EBF-B0DE-5FCD7BA1BB8E/WebDriverAgentRunner-Runner.app/Frameworks:/Users/Barney/Library/Developer/Xcode/DerivedData/WebDriverAgent-dlsriqlfwsfcpjewodrfympgeabr/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks:/Developer/Library/PrivateFrameworks";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/9042B1C8-A796-4EBF-B0DE-5FCD7BA1BB8E/WebDriverAgentRunner-Runner.app/Frameworks:/Users/Barney/Library/Developer/Xcode/DerivedData/WebDriverAgent-dlsriqlfwsfcpjewodrfympgeabr/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks:/Developer/Library/PrivateFrameworks";
    HOME = "/private/var/mobile/Containers/Data/Application/EFBD02E2-D9D0-4A3C-8703-93DE6FEB96DF";
    LOGNAME = mobile;
    "MTC_CRASH_ON_REPORT" = 1;
    NSUnbufferedIO = YES;
    "OS_ACTIVITY_DT_MODE" = YES;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin";
    SHELL = "/bin/sh";
    TMPDIR = "/private/var/mobile/Containers/Data/Application/EFBD02E2-D9D0-4A3C-8703-93DE6FEB96DF/tmp/";
    USER = mobile;
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/EFBD02E2-D9D0-4A3C-8703-93DE6FEB96DF/tmp/WebDriverAgentRunner-097385FE-2C30-4DE7-9586-70B2317CA05A.xctestconfiguration";
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0xb73][70]";
    "__CF_USER_TEXT_ENCODING" = "0x1F5:0:0";
}
10:16:58.888 WebDriverAgentRunner-Runner[249:5915] App Sandbox active: YES
10:16:58.888 WebDriverAgentRunner-Runner[249:5915] Loading test bundle at: file:///private/var/containers/Bundle/Application/9042B1C8-A796-4EBF-B0DE-5FCD7BA1BB8E/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
10:16:59.051 WebDriverAgentRunner-Runner[249:5915] Finished loading test bundle
10:16:59.052 WebDriverAgentRunner-Runner[249:5915] Readying IDE session
10:16:59.057 WebDriverAgentRunner-Runner[249:5915] <XCTWaiter: 0x1c000c820, state: XCTWaiterStateInProgress> entering wait loop for 5.00s with expectations: (
    "Exchange protocol versions with daemon"
)
10:16:59.066 WebDriverAgentRunner-Runner[249:6040] Got daemon protocol version 18
10:16:59.067 WebDriverAgentRunner-Runner[249:6040] <XCTWaiter: 0x1c000c820, state: XCTWaiterStateSucceeded>: cancelWaiting
10:16:59.067 WebDriverAgentRunner-Runner[249:5915] <XCTWaiter: 0x1c000c820, state: XCTWaiterStateSucceeded> done waiting
10:16:59.067 WebDriverAgentRunner-Runner[249:5915] <XCTWaiter: 0x1c000c820, state: XCTWaiterStateSucceeded> cleaning up Exchange protocol versions with daemon
10:16:59.067 WebDriverAgentRunner-Runner[249:5915] Requesting IDE connection transport
10:16:59.068 WebDriverAgentRunner-Runner[249:5915] <XCTWaiter: 0x1c800a0d0, state: XCTWaiterStateInProgress> entering wait loop for 60.00s with expectations: (
    "Transport for IDE session acquired"
)
10:16:59.070 WebDriverAgentRunner-Runner[249:6040] Creating transport with received transport data
10:16:59.071 WebDriverAgentRunner-Runner[249:6044] <XCTWaiter: 0x1c800a0d0, state: XCTWaiterStateSucceeded>: cancelWaiting
10:16:59.071 WebDriverAgentRunner-Runner[249:5915] <XCTWaiter: 0x1c800a0d0, state: XCTWaiterStateSucceeded> done waiting
10:16:59.071 WebDriverAgentRunner-Runner[249:5915] <XCTWaiter: 0x1c800a0d0, state: XCTWaiterStateSucceeded> cleaning up Transport for IDE session acquired
10:16:59.071 WebDriverAgentRunner-Runner[249:5915] Creating connection with transport <DTXFileDescriptorTransport: 0x1d00f4500>
10:16:59.072 WebDriverAgentRunner-Runner[249:5915] Creating the proxy channel with connection <DTXConnection 0x1d01e1d00 : x1>
10:16:59.072 WebDriverAgentRunner-Runner[249:5915] Messaging IDE proxy - _XCT_testBundleReadyWithProtocolVersion:25 minimumVersion:8
10:16:59.073 WebDriverAgentRunner-Runner[249:5915] <XCTWaiter: 0x1d400a520, state: XCTWaiterStateInProgress> entering wait loop for 60.00s with expectations: (
    "IDE session ready for test plan"
)
10:17:53.396 WebDriverAgentRunner-Runner[249:6616] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply contained error: Error Domain=DTXProxyChannel Code=1 "(null)" UserInfo={DTXProxyChannelErrorMessage=Channel disconnected}
10:17:53.397 WebDriverAgentRunner-Runner[249:6617] <XCTWaiter: 0x1d400a520, state: XCTWaiterStateSucceeded>: cancelWaiting
10:17:53.397 WebDriverAgentRunner-Runner[249:5915] <XCTWaiter: 0x1d400a520, state: XCTWaiterStateSucceeded> done waiting
10:17:53.398 WebDriverAgentRunner-Runner[249:5915] <XCTWaiter: 0x1d400a520, state: XCTWaiterStateSucceeded> cleaning up IDE session ready for test plan
====================

**Comment by LiuYibin** [comment]
Same problem after I upgraded to iOS 11.2.2

**Comment by SuperChenSSS** [comment]
I encounter this problem too... Could you fix this?

**Comment by izzyliao** [comment]
Try this solution：Check the xcode version，Please upgrade to the latest version：Xcode 9.2

**Comment by marekcirkos** [comment]
This must be Xcode issue, as it didn't even started executing WDA
