### ISSUE TITLE
tap on wrong location, if x is larger than screen size

### ISSUE THREAD

**Issue by wsyzxcn** [facebook/WebDriverAgent#844]
I am using WebDriverAgent with xcode9 to do some automate test. The target app is a game, so tap events can only based on tap on exactly coordinate.Tap on element workaround is not available here.But when i using ``/wda/tap/:uuid ``endpoint for this purpose, it sometimes click on the wrong location sometimes it's the right location.I take a notepad app to reveal the real coordinates it clicked, and the result shows below:
Some fact about the device:
- iPhone 7 real device
- window size is  375x667, get from ``/window/size/`` endpoint
- screenshot image size: 750x1334

 ![Image](https://github.com/wsyzxcn/picturehub/blob/master/pics/IMG_00472.PNG)
https://github.com/wsyzxcn/picturehub/blob/master/pics/IMG_00472.PNG
see, this is an horizontal oriented page, when I click on (374, 10), it appears 374 is distance to the left of the screen. however if I click on (375, 10), 375 is scaled to fit window size of 450x1334, and the orientation of axis also changed, so (375, 10) locate at 187 to the bottom size, and 10 to the left side.  It seems like if x coordinate larger then window width which is 375, it changes its behavior, the reference axis to locate the coordinate changed.

**Comment by olinzzz30** [comment]
I have the same problem here, this only happens in the horizontal oriented game. I think this is a positioning issue.

**Comment by marekcirkos** [comment]
Yeah, We had exactly same problem with scrolling. Whenever touch event was requested with x or y off the screen, for some reason it was silently "replaced" with x,y divided by 2. I am pretty sure this is Apple's bug or some legacy code from retina not retina times. 

We could check on WDA side whether touch goes off the screen and throw an error or move it to the edge of the screen.

Feel free to pop an request
