### ISSUE TITLE
WebDriverAgentLib.h not found

### ISSUE THREAD

**Issue by JamesXu007222** [facebook/WebDriverAgent#847]
/Users/xujiaheng/WebDriverAgent/WebDriverAgentLib/Utilities/FBXCodeCompatibility.h:10:9: 'WebDriverAgentLib/WebDriverAgentLib.h' file not found when i try to run test
<img width="1022" alt="2018-01-16 9 23 10" src="https://user-images.githubusercontent.com/35492889/34991144-7a7f83b8-fb03-11e7-8fa6-7e4575333fa8.png">

**Comment by marekcirkos** [comment]
Did you resolved it? Did you modify the code or project in someway?

**Comment by JamesXu007222** [comment]
i downloaded a new one and it is still has the same problem…

**Comment by JamesXu007222** [comment]
it seems like there is a file called RoutingConnection.h that is missing

**Comment by marekcirkos** [comment]
Did you run bootstrap script?
