### ISSUE TITLE
Unable to build the wedriveragent project.xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test

### ISSUE THREAD

**Issue by SubaRajaram09** [facebook/WebDriverAgent#849]
Unable to build using this command : xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test. Below are the logs at the end.

CodeSign /Users/subarajaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
    cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
    
Signing Identity:     "iPhone Developer: Long Shi (UEM96UF2Z4)"
Provisioning Profile: "dev-au.com.commbank.wildcard"
                      (3ab47228-5b20-4755-addb-6fa537450447)

    /usr/bin/codesign --force --sign 612621621B8953E8D1A272FC70343822D780B3F6 --deep --entitlements /Users/subarajaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/WebDriverAgentRunner.xctest.xcent --timestamp=none /Users/subarajaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
/Users/subarajaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app: replacing existing signature

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/x2/gndcqf4d47v07bfvf894s2l40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/f40557f2ec6daf93216a339024f23c6a/3df785473d472fbcdfcd11b9c572bb3498fa3f39/ManifestCache.plist
2018-01-18 12:44:49.735099+1100 WebDriverAgentRunner-Runner[356:64131] +[CATransaction synchronize] called within transaction
2018-01-18 12:44:49.755977+1100 WebDriverAgentRunner-Runner[356:64131] Running tests...
2018-01-18 12:44:49.797666+1100 WebDriverAgentRunner-Runner[356:64131] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2018-01-18 12:44:49.797711+1100 WebDriverAgentRunner-Runner[356:64131] (dlopen_preflight(/var/containers/Bundle/Application/A03F7C3A-7E15-482D-AADF-B2875161E9D3/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
  Referenced from: /private/var/containers/Bundle/Application/A03F7C3A-7E15-482D-AADF-B2875161E9D3/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/A03F7C3A-7E15-482D-AADF-B2875161E9D3/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/A03F7C3A-7E15-482D-AADF-B2875161E9D3/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
)
2018-01-18 12:44:49.249 xcodebuild[759:25078] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
** TEST FAILED **

**Comment by SubaRajaram09** [comment]
https://gist.github.com/SubaRajaram09/d7eb0e73de4a36716873fb10f3c19e19.

guys above is the gist link to my logs.. please look into it and let me know what is wrong..

**Comment by marekcirkos** [comment]
This is Xcode issue. My guess is you are trying to run simulator build on device

**Comment by oprilepin** [comment]
Hi, the same error I got, but for emulator it is built good, but for real connected device I got error above. So, where I can find project for real device? Thx
