### ISSUE TITLE
Can I customize the duration of drag action?

### ISSUE THREAD

**Issue by lukapool** [facebook/WebDriverAgent#851]
I want to set the duration of drag action from START point to END point after START point had pressed.
But I only cstiomize the duration of pressing START point in the method below. I want to make the swipe action much faster.

`- (void)pressForDuration:(NSTimeInterval)duration thenDragToCoordinate:(XCUICoordinate *)otherCoordinate;`

**Comment by marekcirkos** [comment]
You can always create custom event with described touch events. Have a look on how scrolling is done and pop a PR :)
