### ISSUE TITLE
Can not scroll to element outside the screen

### ISSUE THREAD

**Issue by sanlengjingvv** [facebook/WebDriverAgent#853]
## The problem
screen size is `{"width":414,"height":736}`, element location is `{"x":167,"y":740}`
```
execute('mobile: scroll', {element: element.value.ELEMENT, 'toVisible': true})
```

**expect:**  
swipe up like `execute('mobile: scroll', {direction: 'down’})`

**actual:**  
swipe down like `execute('mobile: scroll', {direction: 'up'})`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 1.3.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 11.2.2
* Real device or emulator/simulator: Real device, iPhone 7 Plus
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs
https://gist.github.com/sanlengjingvv/3ed727fdd59b6f21f97b550df9fdff8f

## Code To Reproduce Issue [ Good To Have ]
```javascript
// WebdriverIO
describe('scroll', function() {
    it('scroll to element', function() {
        var element = browser.element('.//XCUIElementTypeCell[6]/descendant::XCUIElementTypeStaticText[3]')
        console.log(element.getLocation())
        console.log(browser.windowHandleSize())        
        browser.execute('mobile: scroll', {element: element.value.ELEMENT, 'toVisible': true})
    })
})
```

**Comment by marekcirkos** [comment]
What is the problem? It does not scroll or ...? Can you provide more information here?

**Comment by sanlengjingvv** [comment]
When I scroll to the element marked in this picture, actual behavior is Pull-to-refresh
![img_94c2e4f7feb5-1](https://user-images.githubusercontent.com/6478615/36641579-a60b9976-1a6c-11e8-9896-2e50ef13e658.jpeg)
![img_0078531a88be-1](https://user-images.githubusercontent.com/6478615/36641582-abe067d2-1a6c-11e8-950a-4695fe461e06.jpeg)
