### ISSUE TITLE
iPad Located touch and Hold is not corrected

### ISSUE THREAD

**Issue by swccc** [facebook/WebDriverAgent#855]
Device : iPad Air2
Version : iOS 11.1.1
xCode : 9.1

1. iPad Located Landscape
2. iPad touchAndHold
3. Comamnd 
  "curl -X POST $JSON_HEADER -d '{"duration":0.05,"x":900,"y":300}' $DEVICE_URL/session/F422C19F-73DE-45D0-9F38-A26EBD44BF23/wda/touchAndHold"

result :
size : 1024,768
SUCCESS
touch X : 100,200,300,400,500,600,700,710,720,730,740,750,760 
ERROR
touch X : 900 
 I See touch x point is: 140..

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/issues/856

**Comment by marekcirkos** [comment]
Duplicate
