### ISSUE TITLE
support start app by URL Scheme?

### ISSUE THREAD

**Issue by wrsuifeng** [facebook/WebDriverAgent#858]
We want to open the specific view by url scheme. Have these api?

**Comment by marekcirkos** [comment]
What do you mean exactly? We already handle `/url` POST request

**Comment by mykola-mokhnach** [comment]
I assume the problem lies in https://forums.developer.apple.com/thread/25355

**Comment by marekcirkos** [comment]
Thank you @mykola-mokhnach, not much we can do here, then.

**Comment by mykola-mokhnach** [comment]
@marekcirkos You can check https://github.com/appium/WebDriverAgent/pull/49 if such workaround is interesting for you.
