### ISSUE TITLE
In Appium automation, WDA giving ""Error Domain=XCTDaemonErrorDomain Code=14 \"Timed out waiting for key event to complete\" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete}","status":13" error so send_keys() method is not able to send characters from string.

### ISSUE THREAD

**Issue by amoldhamapurkar** [facebook/WebDriverAgent#860]
Description:
1. In real IOS device when iam trying to send string using Appium sever then many times getting above issue.
2. It looks like WDA is not working properly. It is becoming to slow after executing few test cases. 
Below are the appium logs for same.
 [JSONWP Proxy] Proxying [POST /element/17CE66BB-4FB9-4A50-8AC5-47358C33E4DE/clear] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element/17CE66BB-4FB9-4A50-8AC5-47358C33E4DE/clear] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"status\" : 0,\n  \"id\" : \"17CE66BB-4FB9-4A50-8AC5-47358C33E4DE\",\n  \"sessionId\" : \"645EB25A-A111-4A1F-8583-62B7E99069BC\",\n  \"value\" : \"\"\n}"
[MJSONWP] Responding to client with driver.clear() result: null
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/17CE66BB-4FB9-4A50-8AC5-47358C33E4DE/clear 200 2897 ms - 76 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/17CE66BB-4FB9-4A50-8AC5-47358C33E4DE/value {"sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","id":"17CE66BB-4FB9-4A50-8AC5-47358C33E4DE","value":["I","O","S","_","A","u","t","o","_","0","0","2"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["I","O","S","_","A","u","t","o","_","0","0","2"],"17CE66BB-4FB9-4A50-8AC5-47358C33E4DE","8a4195cc-8e16-4640-8e09-77be1f6bbfa7"]
[XCUITest] Executing command 'setValue'
[JSONWP Proxy] Proxying [POST /element/17CE66BB-4FB9-4A50-8AC5-47358C33E4DE/value] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element/17CE66BB-4FB9-4A50-8AC5-47358C33E4DE/value] with body: {"value":["I","O","S","_","A","u","t","o","_","0","0","2"]}
[JSONWP Proxy] Got response with status 200: {"status":0,"id":"17CE66BB-4FB9-4A50-8AC5-47358C33E4DE","sessionId":"645EB25A-A111-4A1F-8583-62B7E99069BC","value":""}
[MJSONWP] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/17CE66BB-4FB9-4A50-8AC5-47358C33E4DE/value 200 21565 ms - 76 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element {"using":"id","sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","value":"Done"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Done","8a4195cc-8e16-4640-8e09-77be1f6bbfa7"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element] with body: {"using":"id","value":"Done"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"645EB25A-A111-4A1F-8583-62B7E99069BC","value":{"ELEMENT":"6C365F08-B0AC-4FDE-8314-D4F5AB35A09C"},"status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"6C365F08-B0AC-4FDE-8314-D4F5AB35A09C"}
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element 200 2261 ms - 122 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/6C365F08-B0AC-4FDE-8314-D4F5AB35A09C/click {"sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","id":"6C365F08-B0AC-4FDE-8314-D4F5AB35A09C"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/6C365F08-B0AC-4FDE-8314-D4F5AB35A09C/click] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element/6C365F08-B0AC-4FDE-8314-D4F5AB35A09C/click] with body: {"sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","id":"6C365F08-B0AC-4FDE-8314-D4F5AB35A09C"}
[JSONWP Proxy] Got response with status 200: {"status":0,"id":"6C365F08-B0AC-4FDE-8314-D4F5AB35A09C","sessionId":"645EB25A-A111-4A1F-8583-62B7E99069BC","value":""}
[JSONWP Proxy] Replacing sessionId 645EB25A-A111-4A1F-8583-62B7E99069BC with 8a4195cc-8e16-4640-8e09-77be1f6bbfa7
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/6C365F08-B0AC-4FDE-8314-D4F5AB35A09C/click 200 7781 ms - 118 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element {"using":"id","sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","value":"Contact Name IOS_Auto_002, Contact presence Available, Contact avatar Default Avatar, , "}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Contact Name IOS_Auto_002, Contact presence Available, Contact avatar Default Avatar, , ","8a4195cc-8e16-4640-8e09-77be1f6bbfa7"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element] with body: {"using":"id","value":"Contact Name IOS_Auto_002, Contact presence Available, Contact avatar Default Avatar, , "}
[JSONWP Proxy] Got response with status 200: {"sessionId":"645EB25A-A111-4A1F-8583-62B7E99069BC","value":{"using":"id","value":"Contact Name IOS_Auto_002, Contact presence Available, Contact avatar Default Avatar, , ","description":"unable to find an element"},"status":7}
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element 500 1746 ms - 164 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element {"using":"id","sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","value":"Contact Name IOS_Auto_002, Contact presence Offline, Contact avatar Default Avatar, , "}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Contact Name IOS_Auto_002, Contact presence Offline, Contact avatar Default Avatar, , ","8a4195cc-8e16-4640-8e09-77be1f6bbfa7"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element] with body: {"using":"id","value":"Contact Name IOS_Auto_002, Contact presence Offline, Contact avatar Default Avatar, , "}
[JSONWP Proxy] Got response with status 200: {"sessionId":"645EB25A-A111-4A1F-8583-62B7E99069BC","value":{"using":"id","value":"Contact Name IOS_Auto_002, Contact presence Offline, Contact avatar Default Avatar, , ","description":"unable to find an element"},"status":7}
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element 500 1795 ms - 164 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element {"using":"id","sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","value":"Contact Name IOS_Auto_002, Contact presence Do Not Disturb, Contact avatar Default Avatar, , "}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Contact Name IOS_Auto_002, Contact presence Do Not Disturb, Contact avatar Default Avatar, , ","8a4195cc-8e16-4640-8e09-77be1f6bbfa7"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element] with body: {"using":"id","value":"Contact Name IOS_Auto_002, Contact presence Do Not Disturb, Contact avatar Default Avatar, , "}
[JSONWP Proxy] Got response with status 200: {"sessionId":"645EB25A-A111-4A1F-8583-62B7E99069BC","value":{"using":"id","value":"Contact Name IOS_Auto_002, Contact presence Do Not Disturb, Contact avatar Default Avatar, , ","description":"unable to find an element"},"status":7}
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element 500 1778 ms - 164 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element {"using":"id","sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","value":"Clear"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Clear","8a4195cc-8e16-4640-8e09-77be1f6bbfa7"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element] with body: {"using":"id","value":"Clear"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"645EB25A-A111-4A1F-8583-62B7E99069BC","value":{"ELEMENT":"7DE17392-61AC-44C2-9F14-C22705C44968"},"status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"7DE17392-61AC-44C2-9F14-C22705C44968"}
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element 200 1796 ms - 122 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/7DE17392-61AC-44C2-9F14-C22705C44968/click {"sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","id":"7DE17392-61AC-44C2-9F14-C22705C44968"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/7DE17392-61AC-44C2-9F14-C22705C44968/click] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element/7DE17392-61AC-44C2-9F14-C22705C44968/click] with body: {"sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","id":"7DE17392-61AC-44C2-9F14-C22705C44968"}
[JSONWP Proxy] Got response with status 200: {"status":0,"id":"7DE17392-61AC-44C2-9F14-C22705C44968","sessionId":"645EB25A-A111-4A1F-8583-62B7E99069BC","value":""}
[JSONWP Proxy] Replacing sessionId 645EB25A-A111-4A1F-8583-62B7E99069BC with 8a4195cc-8e16-4640-8e09-77be1f6bbfa7
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/7DE17392-61AC-44C2-9F14-C22705C44968/click 200 6219 ms - 118 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element {"using":"id","sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","value":"Search"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Search","8a4195cc-8e16-4640-8e09-77be1f6bbfa7"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element] with body: {"using":"id","value":"Search"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"645EB25A-A111-4A1F-8583-62B7E99069BC","value":{"ELEMENT":"DEB07643-7A08-488C-84D2-2DB8F0F57CE6"},"status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"DEB07643-7A08-488C-84D2-2DB8F0F57CE6"}
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element 200 1826 ms - 122 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/DEB07643-7A08-488C-84D2-2DB8F0F57CE6/clear {"sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","id":"DEB07643-7A08-488C-84D2-2DB8F0F57CE6"}
[MJSONWP] Calling AppiumDriver.clear() with args: ["DEB07643-7A08-488C-84D2-2DB8F0F57CE6","8a4195cc-8e16-4640-8e09-77be1f6bbfa7"]
[XCUITest] Executing command 'clear'
[JSONWP Proxy] Proxying [POST /element/DEB07643-7A08-488C-84D2-2DB8F0F57CE6/clear] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element/DEB07643-7A08-488C-84D2-2DB8F0F57CE6/clear] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"status\" : 0,\n  \"id\" : \"DEB07643-7A08-488C-84D2-2DB8F0F57CE6\",\n  \"sessionId\" : \"645EB25A-A111-4A1F-8583-62B7E99069BC\",\n  \"value\" : \"\"\n}"
[MJSONWP] Responding to client with driver.clear() result: null
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/DEB07643-7A08-488C-84D2-2DB8F0F57CE6/clear 200 2936 ms - 76 
[HTTP] --> POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/DEB07643-7A08-488C-84D2-2DB8F0F57CE6/value {"sessionId":"8a4195cc-8e16-4640-8e09-77be1f6bbfa7","id":"DEB07643-7A08-488C-84D2-2DB8F0F57CE6","value":["I","O","S","_","A","u","t","o","_","0","0","3"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["I","O","S","_","A","u","t","o","_","0","0","3"],"DEB07643-7A08-488C-84D2-2DB8F0F57CE6","8a4195cc-8e16-4640-8e09-77be1f6bbfa7"]
[XCUITest] Executing command 'setValue'
[JSONWP Proxy] Proxying [POST /element/DEB07643-7A08-488C-84D2-2DB8F0F57CE6/value] to [POST http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element/DEB07643-7A08-488C-84D2-2DB8F0F57CE6/value] with body: {"value":["I","O","S","_","A","u","t","o","_","0","0","3"]}
[JSONWP Proxy] Got response with status 200: {"sessionId":"645EB25A-A111-4A1F-8583-62B7E99069BC","value":"Error Domain=XCTDaemonErrorDomain Code=14 \"Timed out waiting for key event to complete\" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete}","status":13}
[JSONWP Proxy] Proxying [GET /element/DEB07643-7A08-488C-84D2-2DB8F0F57CE6/attribute/type] to [GET http://localhost:8100/session/645EB25A-A111-4A1F-8583-62B7E99069BC/element/DEB07643-7A08-488C-84D2-2DB8F0F57CE6/attribute/type] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"sessionId\" : \"645EB25A-A111-4A1F-8583-62B7E99069BC\",\n  \"value\" : \"XCUIElementTypeSearchField\",\n  \"status\" : 0\n}"
[HTTP] <-- POST /wd/hub/session/8a4195cc-8e16-4640-8e09-77be1f6bbfa7/element/DEB07643-7A08-488C-84D2-2DB8F0F57CE6/value 500 27048 ms - 338 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[BaseDriver] Shutting down because we waited 6000 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 6000 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session a580cf8f-1bcd-4240-9be3-795b8577618f from our master session list
[XCUITest] Cannot find a match for DerivedData folder path from lsof. Trying to access logs
[XCUITest] Cannot find a match for xcodebuild log file. No derived data folder will be found
[XCUITest] No WebDriverAgent derived data available, so unable to set permissions on WDA attachments folder
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture

**Comment by marekcirkos** [comment]
`Timed out waiting for key event to complete` it is XCUITest issue that is reported when we detected that typing went wrong. Unfortunately not much we can do on WDA level. However you could try handling that on client level, by clearing field and retrying.

**Comment by amoldhamapurkar** [comment]
Thanks @marekcirkos. But still it is giving problem. Anyway i handle this issue with different way.
