### ISSUE TITLE
When buidding WDA in Xcode, I got a one question about : 'WebDriverAgentLib/XCUIElement.h' file not found

### ISSUE THREAD

**Issue by HJNVR** [facebook/WebDriverAgent#862]
<img width="1440" alt="2018-01-30 8 13 23" src="https://user-images.githubusercontent.com/34841349/35600134-5fba3396-05fa-11e8-93dc-77ca750e1cdc.png">

Did I miss something like I forget to download the file ?

**Comment by shivakrishnach31** [comment]
@HJNVR - Run below commands in the WebDriverAgent location and try to build WebDriverAgent from Xcode.

```
mkdir -p Resources/WebDriverAgent.bundle
./Scripts/bootstrap.sh -d
```

**Comment by marekcirkos** [comment]
xccproject related warnings look relevant to your problem
