### ISSUE TITLE
Unable to launch app due to WDA crash

### ISSUE THREAD

**Issue by shanthi2016** [facebook/WebDriverAgent#864]
I am trying to run tests on an iOS simulator(11.2 or 10.3 or any) with Appium desktop 1.7.1 .
Appium installs the app and WDA, but the app is not launching.

Came to know from Appium issues page that this is due to WDA crash.

Environment
Appium version (or git revision) that exhibits the issue: 1.7.1
Last Appium version that did not exhibit the issue (if applicable):NA
Desktop OS/version used to run Appium: Mac OS 10.12.6
Node.js version (unless using Appium.app|exe):6.10.2
Mobile platform/version under test: 11.2,11.0 and 10.3
Real device or emulator/simulator: Both
Appium CLI or Appium.app|exe: .app

Appium logs:
https://gist.github.com/shanthi2016/c143b4f4238ed00d88a7663a5acf6a97

Device logs:
https://gist.github.com/shanthi2016/25565148038e1404219f0eebe14548fe

Could you please help me with this issue

**Comment by marekcirkos** [comment]
Do you have crashreport for it? I can't really say what went wrong

**Comment by eguptax** [comment]
I am also facing this issue please help.

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/15/k070p35d7rv9pl3nqjjdr9wh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/715314eb79dc3a67733c024940454ffe/fdf88c0911312812011f2188eb3f7953a24a54f6/ManifestCache.plist

Got Unknown status 3 from FB_AMDeviceListenerCallback
2018-02-14 17:12:01.362 xcodebuild[40577:101144]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/15/k070p35d7rv9pl3nqjjdr9wh0000gn/T/com.apple.dt.XCTest/IDETestRunSession-86571D00-CED6-4165-83AA-A8BA6C2FFDC6/WebDriverAgentRunner-5AB00CBD-D0AA-4B61-953B-8A5F4FD42998/Session-WebDriverAgentRunner-2018-02-14_171201-1WNGXe.log

2018-02-14 17:12:01.363 xcodebuild[40577:100809] [MT] IDETestOperationsObserverDebug: (1A0068D9-9D04-40D3-AED3-17CFD21F2DCD) Beginning test session WebDriverAgentRunner-1A0068D9-9D04-40D3-AED3-17CFD21F2DCD at 2018-02-14 17:12:01.363 with Xcode 9C40b on target <DVTiOSDevice: 0x7fe049ee1d50> {
		deviceSerialNumber:         F71V4XDMHG7J
		identifier:                 fdf88c0911312812011f2188eb3f7953a24a54f6
		deviceClass:                iPhone
		deviceName:                 Karl’s iPhone
		deviceIdentifier:           fdf88c0911312812011f2188eb3f7953a24a54f6
		productVersion:             11.2.5
		buildVersion:               15D60
		deviceSoftwareVersion:      11.2.5 (15D60)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        28526850048
		deviceAvailableCapacity:    22254178304
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fe049eac5b0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              {(
    <DTDKApplication: 0x7fe04a2acc70>: Clips (/private/var/containers/Bundle/Application/6FC143D6-A52C-4B18-B9BC-A93965C30CFB/Clips.app),
    <DTDKApplication: 0x7fe04a2ad050>: GarageBand (/private/var/containers/Bundle/Application/6C2BC70D-EB91-452F-B8E6-4391C19488F6/MobileGarageBand.app),
    <DTDKApplication: 0x7fe04a2ad260>: iTunes U (/private/var/containers/Bundle/Application/E174F7B4-E40F-47EF-9159-9F9A1E941C7F/iTunesU.app),
    <DTDKApplication: 0x7fe04a2ac650>: DeleteContactsApp (/private/var/containers/Bundle/Application/F859008F-A21F-45B4-851E-62B18AF38AF5/DeleteContactsApp.app),
    <DTDKApplication: 0x7fe04a2ad470>: Pages (/private/var/containers/Bundle/Application/6BD2DC65-995B-47A6-A95F-E69F211AE1B2/Pages.app),
    <DTDKApplication: 0x7fe04a2ad680>: Numbers (/private/var/containers/Bundle/Application/D97EF146-2A61-4E42-B5C7-118E2AACED5D/Numbers.app),
    <DTDKApplication: 0x7fe04a2adaa0>: WebDriverAgentRunner-Runner (/private/var/containers/Bundle/Application/C88A9244-D1D9-4CBE-BBFD-615348E71593/WebDriverAgentRunner-Runner.app),
    <DTDKApplication: 0x7fe04a2ad890>: iMovie (/private/var/containers/Bundle/Application/F0A9D392-48D5-45F6-8811-E1E03BE53838/iMovie.app),
    <DTDKApplication: 0x7fe04a2ace40>: Keynote (/private/var/containers/Bundle/Application/1F47B0DC-C179-460E-AEEB-CD39FB8ACFCC/Keynote.app)
)}
		provisioningProfiles:      {(
    <DTDKProvisioningProfile 0x7fe049fa7cf0: UUID: aaa379ca-04c5-4b78-b467-ab7f44234b4c, name: iOS Team Ad Hoc Provisioning Profile: *, team: Z9FFXSRKVC (Himanshu Nigam), platform: iOS>,
    <DTDKProvisioningProfile 0x7fe049fbd8c0: UUID: 0cda2acd-0b48-4dec-82e4-fe00d9e84777, name: com.facebook.WebdriverAgentRunner, team: Z9FFXSRKVC (Himanshu Nigam), platform: iOS>,
    <DTDKProvisioningProfile 0x7fe049fc3ca0: UUID: 9b74b61c-2fc5-463e-96fc-054b7cdda13e, name: com.facebook.WebdriverAgentRunner, team: Z9FFXSRKVC (Himanshu Nigam), platform: iOS>,
    <DTDKProvisioningProfile 0x7fe049fc1560: UUID: 7b63d03b-6b2b-4601-a3cb-586a8b9d1f94, name: iOS Team Provisioning Profile: com.intel.superlight, team: 97JBTLBAJ7 (Recon Instruments Inc), platform: iOS>,
    <DTDKProvisioningProfile 0x7fe049ec0680: UUID: 818e8841-5fd6-46c8-85b4-e28206e6cfed, name: com.intel.superlight Distribution, team: 97JBTLBAJ7 (Recon Instruments Inc), platform: iOS>,
    <DTDKProvisioningProfile 0x7fe04768c960: UUID: 98e52ab5-2a7c-4aca-9d56-a3d20e1e04dd, name: iOS Team Provisioning Profile: *, team: Z9FFXSRKVC (Himanshu Nigam), platform: iOS>
)}
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		connected:                 yes
		isWirelessEnabled:         no
		connectionType:            direct
		} (11.2.5 (15D60))

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/15/k070p35d7rv9pl3nqjjdr9wh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/715314eb79dc3a67733c024940454ffe/fdf88c0911312812011f2188eb3f7953a24a54f6/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/nic_user/execution-config/ReferenceAppFiles/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/15/k070p35d7rv9pl3nqjjdr9wh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.OLJdUL/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/15/k070p35d7rv9pl3nqjjdr9wh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.OLJdUL/WebDriverAgentRunner-Runner.app_sparse.ipa

MDMDirectoryDiff_block_invoke:1473 calling writeDictToFile with: /var/folders/15/k070p35d7rv9pl3nqjjdr9wh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.OLJdUL/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/15/k070p35d7rv9pl3nqjjdr9wh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.OLJdUL/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

** TEST EXECUTE FAILED **

**Comment by marekcirkos** [comment]
This is not crash report, just logs from XCUITest process.
