### ISSUE TITLE
If the speed is so slow due to the method "pinch"?

### ISSUE THREAD

**Issue by yaosum** [facebook/WebDriverAgent#865]
I used the "pinch" method to pinch or zoom, but the automation is running pretty slow. I wonder if the pinch method causes automation so slow. Or beause it's running under landscape? 

Here is how I use this method.

pinch: self.w.execute_script("mobile: pinch", {"scale": 1.5, "velocity": 1.1})
zoom: self.w.execute_script("mobile: pinch", {"scale": 0.5, "velocity": -0.1})

**Comment by marekcirkos** [comment]
Can you tell me which WDA endpoint is used here, with what parameters?
