### ISSUE TITLE
WDA is failing while scrolling on the iPhone screen

### ISSUE THREAD

**Issue by eguptax** [facebook/WebDriverAgent#866]
Sometimes while scrolling on the iPhone screen I am getting an issue - Got Unknown status 3 from FB_AMDeviceListenerCallback 
Please find the logs below as well

t =    68.79s Find the Application "com.apple.Preferences" 0x1c40cd040
    t =    68.79s     Snapshot accessibility hierarchy for app with pid 1409
    t =    68.82s Find the Application "com.apple.Preferences" 0x1c40cd040
    t =    68.82s     Snapshot accessibility hierarchy for app with pid 1409
    t =    68.86s Get all elements bound by index for: Elements matching predicate 'wdName == "Device Management" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
    t =    68.88s     Snapshot accessibility hierarchy for app with pid 1409
    t =    68.94s     Find: Descendants matching type Any
    t =    68.94s     Find: Elements matching predicate 'wdName == "Device Management" AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
    t =    69.36s Find the Application "com.apple.Preferences" 0x1c40cd040
    t =    69.36s     Snapshot accessibility hierarchy for app with pid 1409
    t =    69.39s Get all elements bound by index for: Descendants matching type Table
    t =    69.40s     Snapshot accessibility hierarchy for app with pid 1409
    t =    69.43s     Find: Descendants matching type Table
    t =    69.86s Find the Table
    t =    69.86s     Snapshot accessibility hierarchy for app with pid 1409
    t =    69.92s     Find: Descendants matching type Table
    t =    69.92s     Find: Element at index 0
    t =    69.92s Get all elements bound by index for: Elements matching predicate '"Device Management" IN identifiers'
    t =    69.94s     Snapshot accessibility hierarchy for app with pid 1409
    t =    69.98s     Find: Descendants matching type Table
    t =    69.98s     Find: Element at index 0
    t =    69.99s     Find: Descendants matching type Any
    t =    69.99s     Find: Elements matching predicate '"Device Management" IN identifiers'
    t =    69.99s Snapshot accessibility hierarchy for app with pid 1409
    t =    70.03s Find: Descendants matching type Table
    t =    70.04s Find: Element at index 0
    t =    70.04s Find: Descendants matching type Any
    t =    70.04s Find: Elements matching predicate '"Device Management" IN identifiers'
    t =    70.04s Find: Element at index 1
    t =    70.04s Find the "Device Management" Any
    t =    70.04s     Snapshot accessibility hierarchy for app with pid 1409
    t =    70.08s     Find: Descendants matching type Table
    t =    70.09s     Find: Element at index 0
    t =    70.09s     Find: Descendants matching type Any
    t =    70.09s     Find: Elements matching predicate '"Device Management" IN identifiers'
    t =    70.09s     Find: Element at index 1
    t =    70.09s Find the "Device Management" StaticText
    t =    70.09s     Snapshot accessibility hierarchy for app with pid 1409
    t =    70.14s     Find: Descendants matching type Table
    t =    70.14s     Find: Element at index 0
    t =    70.14s     Find: Descendants matching type Any
    t =    70.14s     Find: Elements matching predicate '"Device Management" IN identifiers'
    t =    70.14s     Find: Element at index 1
    t =    70.20s Find the "Device Management" StaticText
    t =    70.20s     Snapshot accessibility hierarchy for app with pid 1409
    t =    70.25s     Find: Descendants matching type Table
    t =    70.25s     Find: Element at index 0
    t =    70.25s     Find: Descendants matching type Any
    t =    70.25s     Find: Elements matching predicate '"Device Management" IN identifiers'
    t =    70.25s     Find: Element at index 1
    t =    70.28s Snapshot accessibility hierarchy for app with pid 1409
    t =    70.32s Snapshot accessibility hierarchy for app with pid 1409
    t =    70.37s Snapshot accessibility hierarchy for app with pid 1409
    t =    70.41s Snapshot accessibility hierarchy for app with pid 1409
    t =    70.45s Snapshot accessibility hierarchy for app with pid 1409
    t =    70.49s Snapshot accessibility hierarchy for app with pid 1409
    t =    70.53s Snapshot accessibility hierarchy for app with pid 1409
    t =    70.57s Snapshot accessibility hierarchy for app with pid 1409
    t =    70.62s Snapshot accessibility hierarchy for app with pid 1409
    t =    70.69s Find the "Device Management" StaticText
    t =    70.69s     Snapshot accessibility hierarchy for app with pid 1409
    t =    70.75s     Find: Descendants matching type Table
    t =    70.75s   
Got Unknown status 3 from FB_AMDeviceListenerCallback
2018-02-14 12:50:57.520 xcodebuild[2532:22961]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/15/k070p35d7rv9pl3nqjjdr9wh0000gn/T/com.apple.dt.XCTest/IDETestRunSession-2986F73D-6CA0-4DCF-972C-667E45ABF710/WebDriverAgentRunner-1ECC4A4D-B5E7-4F10-A77D-67CAA872D24F/Session-WebDriverAgentRunner-2018-02-14_125057-da2sXi.log

**Comment by marekcirkos** [comment]
`FB_AMDeviceListenerCallback` is from `FBSimulatorControl` right? Tis is unrelated to WDA
