### ISSUE TITLE
Not Able to launch the WebDriverAgent

### ISSUE THREAD

**Issue by ifti1234** [facebook/WebDriverAgent#880]
when ever I am trying to launch the WebDriverAgent it closes unexpectedly and failed the process..
here are the logs 

2018-03-04 12:04:33.169 xcodebuild[28581:448855]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/9n/fv0hf0bs0l931r0_jpkk91856nvc21/T/com.apple.dt.XCTest/IDETestRunSession-9BC00064-C87C-47C7-AA58-5405CA8320E0/WebDriverAgentRunner-A17BB7CC-CE18-49BE-81E6-13885F034ED6/Session-WebDriverAgentRunner-2018-03-04_120433-nEfx6B.log
2018-03-04 12:04:33.170 xcodebuild[28581:448842] [MT] IDETestOperationsObserverDebug: (F451F599-0F8E-4118-8816-7418DA87980E) Beginning test session WebDriverAgentRunner-F451F599-0F8E-4118-8816-7418DA87980E at 2018-03-04 12:04:33.170 with Xcode 9B55 on target <DVTiOSDevice: 0x7fa318715170> {
		deviceSerialNumber:         F2LNJ76YG5QV
		identifier:                 cc17330157611c13238b31cfc3d84191c938dcee
		deviceClass:                iPhone
		deviceName:                 M036
		deviceIdentifier:           cc17330157611c13238b31cfc3d84191c938dcee
		productVersion:             11.0.3
		buildVersion:               15A432
		deviceSoftwareVersion:      11.0.3 (15A432)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        60508483584
		deviceAvailableCapacity:    54484017152
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fa31351b990 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		connected:                 yes
		isWirelessEnabled:         no
		connectionType:            direct
		} (11.0.3 (15A432))
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

ProcessProductPackaging /Users/iftikhar/Library/MobileDevice/Provisioning\ Profiles/abbd03c6-a708-4f9c-87ab-d84a757733a6.mobileprovision /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/../embedded.mobileprovision
    cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export PATH="/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/Users/iftikhar/Library/Android/sdk/platform-tools:/Users/iftikhar/Library/Android/sdk/tools:/Users/iftikhar/Library/Android/sdk/tools/bin"
    builtin-productPackagingUtility /Users/iftikhar/Library/MobileDevice/Provisioning\ Profiles/abbd03c6-a708-4f9c-87ab-d84a757733a6.mobileprovision -o /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/embedded.mobileprovision

ProcessProductPackaging /Users/iftikhar/Library/MobileDevice/Provisioning\ Profiles/abbd03c6-a708-4f9c-87ab-d84a757733a6.mobileprovision /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/../embedded.mobileprovision
    cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export PATH="/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/Users/iftikhar/Library/Android/sdk/platform-tools:/Users/iftikhar/Library/Android/sdk/tools:/Users/iftikhar/Library/Android/sdk/tools/bin"
    builtin-productPackagingUtility /Users/iftikhar/Library/MobileDevice/Provisioning\ Profiles/abbd03c6-a708-4f9c-87ab-d84a757733a6.mobileprovision -o /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/embedded.mobileprovision

Touch /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
    cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export PATH="/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/Users/iftikhar/Library/Android/sdk/platform-tools:/Users/iftikhar/Library/Android/sdk/tools:/Users/iftikhar/Library/Android/sdk/tools/bin"
    /usr/bin/touch -c /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest

CodeSign /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
    cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export CODESIGN_ALLOCATE=/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/Users/iftikhar/Library/Android/sdk/platform-tools:/Users/iftikhar/Library/Android/sdk/tools:/Users/iftikhar/Library/Android/sdk/tools/bin"
    
Signing Identity:     "iPhone Developer: fousiya@farabi.ae (FHMXHJGDQ8)"
Provisioning Profile: "iOS Team Provisioning Profile: com.facebook.WebDriverAgentRunnerQAAT"
                      (abbd03c6-a708-4f9c-87ab-d84a757733a6)

    /usr/bin/codesign --force --sign 44F3ACAF5DDF10A896422CE0CE607BE4F0E81A41 --deep --entitlements /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/WebDriverAgentRunner.xctest.xcent --timestamp=none /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
/Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest: replacing existing signature

CodeSign /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
    cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export CODESIGN_ALLOCATE=/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/iftikhar/Desktop/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/Users/iftikhar/Library/Android/sdk/platform-tools:/Users/iftikhar/Library/Android/sdk/tools:/Users/iftikhar/Library/Android/sdk/tools/bin"
    
Signing Identity:     "iPhone Developer: fousiya@farabi.ae (FHMXHJGDQ8)"
Provisioning Profile: "iOS Team Provisioning Profile: com.facebook.WebDriverAgentRunnerQAAT"
                      (abbd03c6-a708-4f9c-87ab-d84a757733a6)

    /usr/bin/codesign --force --sign 44F3ACAF5DDF10A896422CE0CE607BE4F0E81A41 --deep --entitlements /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/WebDriverAgentRunner.xctest.xcent --timestamp=none /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
/Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app: replacing existing signature

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/9n/fv0hf0bs0l931r0_jpkk91856nvc21/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/63b15ddac4b5ed3ae045bbfe488ae523/cc17330157611c13238b31cfc3d84191c938dcee/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/iftikhar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/9n/fv0hf0bs0l931r0_jpkk91856nvc21/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.NOW0Fz/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/9n/fv0hf0bs0l931r0_jpkk91856nvc21/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.NOW0Fz/WebDriverAgentRunner-Runner.app_sparse.ipa
MDMDirectoryDiff_block_invoke:1473 calling writeDictToFile with: /var/folders/9n/fv0hf0bs0l931r0_jpkk91856nvc21/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.NOW0Fz/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/9n/fv0hf0bs0l931r0_jpkk91856nvc21/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.NOW0Fz/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2018-03-04 12:04:42.569443+0400 WebDriverAgentRunner-Runner[381:29224] +[CATransaction synchronize] called within transaction
2018-03-04 12:04:42.653390+0400 WebDriverAgentRunner-Runner[381:29224] Running tests...
2018-03-04 12:04:42.852370+0400 WebDriverAgentRunner-Runner[381:29224] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2018-03-04 12:04:42.852561+0400 WebDriverAgentRunner-Runner[381:29224] (dlopen_preflight(/var/containers/Bundle/Application/75695178-23B1-41D7-8D1D-02EBB88E72A9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
  Referenced from: /private/var/containers/Bundle/Application/75695178-23B1-41D7-8D1D-02EBB88E72A9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/75695178-23B1-41D7-8D1D-02EBB88E72A9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer: required code signature missing for '/private/var/containers/Bundle/Application/75695178-23B1-41D7-8D1D-02EBB88E72A9/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework/RoutingHTTPServer'
)
2018-03-04 12:04:42.926 xcodebuild[28581:448842] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
** TEST FAILED **

**Comment by marekcirkos** [comment]
`Reason: no suitable image found. Did find:` - this is codesign issue, you need to setup it up correctly
