### ISSUE TITLE
missing reference module.modulemap

### ISSUE THREAD

**Issue by stigmata1** [facebook/WebDriverAgent#886]
New to xCode and WebdriverAgent. While trying to build WebdriverAgentRunner, I noticed the reference to the Folder Module was missing(refer the attached screenshot). I've tried installing Appium a couple of times, but never managed to find the reference to this folder. Appreciate any tips

Appium version 1.7.2

<img width="1404" alt="screen shot 2018-03-12 at 2 20 58 am" src="https://user-images.githubusercontent.com/37269864/37255167-aee06dc0-259c-11e8-88af-42a5c7b50ccc.png"

**Comment by marekcirkos** [comment]
This file is generated with `Scripts/bootstrap.sh`, probably Appium setup is not correct
