### ISSUE TITLE
Unable to run  Automation on iOS 11.3 and Xcode 9.2

### ISSUE THREAD

**Issue by VenkateshPS** [facebook/WebDriverAgent#889]
<img width="1227" alt="screen shot 2018-03-16 at 11 05 37 am" src="https://user-images.githubusercontent.com/11774683/37505482-1d66d4c0-290b-11e8-9387-6b57c26027a3.png">

This iPhone 6 is running iOS 11.3 (15E5211a), which may not be supported by this version of Xcode.

Appium version Appium v1.6.6-beta.4

**Comment by pluie-cloud** [comment]
you must update your xcode to 9.3

**Comment by ledinhphuong** [comment]
You should upgrade to Xcode 9.3 which can recognize `iOS 11.3`
