### ISSUE TITLE
Add support for JsonWireProtocol "element/:id/location_in_view"

### ISSUE THREAD

**Issue by kaleposhobios** [facebook/WebDriverAgent#89]
In addition to the "/session/:sessionId/element/:id/location" JsonWireProcotol method that is supported by WebDriverAgent, it would be nice to also support the /element/:id/location_in_view" method.

As per the docs, this method scrolls the element into view then returns its location: https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/element/:id/location_in_view

**Comment by marekcirkos** [comment]
Should be fairly simple to implement.

**Comment by marekcirkos** [comment]
merged
