### ISSUE TITLE
"wda/touch/perform" endpoint is not working

### ISSUE THREAD

**Issue by CPPAlien** [facebook/WebDriverAgent#890]
The response is correct, but the action is not working on the phone

curl -X POST $JSON_HEADER -d "{\"actions\":[{\"action\":\"tap\", \"options\":{\"x\":\"487\",\"y\":\"619\"}}]}" $DEVICE_URL/session/$SESSION_ID/wda/touch/perform
{
  "sessionId" : "650520A9-A0B2-4981-9869-BD651785D24C",
  "value" : {

  },
  "status" : 0
}%

**Comment by mykola-mokhnach** [comment]
Facebook WDA does not implement `wda/touch/perform` endpoint

**Comment by CPPAlien** [comment]
So why Appium use wda/touch/perform ? 
I open an issue on Appium repo too
https://github.com/appium/appium/issues/10374

**Comment by mykola-mokhnach** [comment]
because this is an experimental implementation, which is only available in appium and needs more extensive testing

**Comment by pchois** [comment]
I'm having the same problem, is there a workaround for iOS?

**Comment by marekcirkos** [comment]
As @mykola-mokhnach said we do not support it
