### ISSUE TITLE
Page source only fo visible elements

### ISSUE THREAD

**Issue by rutin31** [facebook/WebDriverAgent#892]
Hi, is there any way to get page source only for visible elements ?
Now I get XML with all elements on page : for example:
![image](https://user-images.githubusercontent.com/31386296/37700222-58cc5d64-2cf3-11e8-87eb-f563af2296d2.png)

<XCUIElementTypeToolbar height="667" width="308" y="0" x="67" visible="false" enabled="true" type="XCUIElementTypeToolbar">
-<XCUIElementTypeOther height="667" width="308" y="0" x="67" visible="false" enabled="true" type="XCUIElementTypeOther">
<XCUIElementTypeOther height="667" width="308" y="0" x="67" visible="false" enabled="true" type="XCUIElementTypeOther"/>
</XCUIElementTypeOther>
</XCUIElementTypeToolbar>
-<XCUIElementTypeOther height="667" width="308" y="0" x="67" visible="true" enabled="true" type="XCUIElementTypeOther">

**Comment by antiarchit** [comment]
Getting page source only for visible elements is not a part of the [WebDriver spec](https://www.w3.org/TR/webdriver/#getting-page-source). 

What's the use case though? I wonder if whatever you want can be done externally on the XML.

**Comment by rutin31** [comment]
Full source calibrates the performance and makes it difficult to construct a function isElementExist

**Comment by antiarchit** [comment]
Not sure I fully follow, elements could exist and still be not visible, right?

**Comment by rutin31** [comment]
Yes,
For example, I have a contact page that includes more than 100 entries. XML that I receive -for all content and not just the elements currently displayed on the screen

**Comment by marekcirkos** [comment]
We are definitely not changing this.
@rutin31 Can't you just filter them out?
