### ISSUE TITLE
Methods sendKey throws WebDriverException

### ISSUE THREAD

**Issue by dmersiyanov** [facebook/WebDriverAgent#898]
## The problem

Methods sendKey and setValue don't send value to text inputs in iOS native app. It's just skips inputs and and throw following exception:

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error Domain=XCTDaemonErrorDomain Code=14 "Timed out after waiting 1.0s for KeyEventCompleted after sending event for 'd'." UserInfo={NSLocalizedDescription=Timed out after waiting 1.0s for KeyEventCompleted after sending event for 'd'.} (WARNING: The server did not provide any stacktrace information)

Also can be reproduced on appium desktop 1.4.1. I've tried to add click and clear methods before sendKeys but it didn't help.

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.2.7
* Desktop OS/version used to run Appium: MacOS High Sierra 10.13.3
* Mobile platform/version under test: iOS 11.2
* Real device or emulator/simulator: Simulator iPhone 7
* Appium CLI or Appium.app|exe: 1.7.1

## Code To Reproduce Issue [ Good To Have ]

MobileElement emailTextField = (MobileElement) driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"App\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeTable/XCUIElementTypeCell[2]/XCUIElementTypeTextField");

MobileElement passTextField = (MobileElement)                                                                         driver.findElementByXPath("//XCUIElementTypeApplication[@name=\"App\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeTable/XCUIElementTypeCell[3]/XCUIElementTypeSecureTextField");

emailTextField.sendKeys("dmersiyanov@mail.ru");
passTextField.sendKeys("123");

driver.findElementByXPath("//XCUIElementTypeButton[@name=\"Sign in\"]").click();

**Comment by marekcirkos** [comment]
This is known XCTest issue. I do not have any known workaround except for clearing field and retrying
