### ISSUE TITLE
Session doesn't start on iOS 11.2 - Xcode 9.2 

### ISSUE THREAD

**Issue by lucialuzuriaga** [facebook/WebDriverAgent#899]
Original issue here: https://github.com/appium/appium/issues/10433

## The problem

I've been testing without issues for several months on my app. Build target up to now had been iOS 10.3 and built using Xcode 8. After the app finally switched to iOS 11.2 SDK and Xcode 9, WebDriver Agent Runner fails to start a session. App is installed, Runner is installed, but the tests never run. This is 100% reproducible using Appium Desktop 1.4.0, and partially reproducible with Appium CLI 1.7.2. If I close and restart Appium many times or delete both app and runner, it may get to work once, and then stop working again on the next test run. 

I built the WebdriverAgent project with Xcode 9.2 without issues. I didn't perform ANY changes to my setup asides from changing the .app file building it with Xcode 9.2. After encountering this, I reinstalled Appium CLI, Appium Desktop, updated all my Homebrew packages, but the problem persists. I could install the app on the simulator, using xcrun command, without problems. I can manually install and execute the application on the simulator. This is done via command line, using Titanium Framework.

## Environment

* Appium version: Appium Desktop 1.4.0, Appium 1.7.2.
* Last Appium version that did not exhibit the issue (if applicable): Same version
* Desktop OS/version used to run Appium: Mac Mini - OSX 10.13.3 High Sierra
* Node.js version: v8.9.4
* Mobile platform/version under test: iOS Simulator (iPhone 6s)
* Real device or emulator/simulator: iOS Simulator (iPhone 6s)

## Capabilities
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("deviceName", "iPhone 6s");
        capabilities.setCapability("platformVersion", "11.2");
        capabilities.setCapability("app", "/Users/***/Downloads/***.app");
        capabilities.setCapability("orientation", "PORTRAIT");
        capabilities.setCapability("automationName", "XCUITest"); (This line was added after the issue started happening - didn't use it with previous Xcode version)
        capabilities.setCapability("appiumVersion", "1.7.2");

## Link to Appium logs

With Xcode and iOS logs included: https://gist.github.com/lucialuzuriaga/30993b2c9cb7663febd04117f66eca2b

**Comment by marekcirkos** [comment]
@lucialuzuriaga is it still an issue?
