### ISSUE TITLE
IOS11.3 Screenshot size different from window/size

### ISSUE THREAD

**Issue by pluie-cloud** [facebook/WebDriverAgent#901]
IOS 11.3  Ipad
OS 10.13.4 
API window/size GET        "width" : 1024, "height" : 768
BUT API screenshot GET  "width" : 768, "height" : 1024
everything is ok in IOS 10

**Comment by pluie-cloud** [comment]
@marekcirkos

**Comment by marekcirkos** [comment]
@pluie-cloud Can you tell me which one is correct? Is it possible that you inspect landscape orientation of the app, and screenshot is not rotated?

**Comment by pluie-cloud** [comment]
API window/size GET "width" : 1024, "height" : 768   this is correct;

**Comment by marekcirkos** [comment]
@pluie-cloud So image is just not rotated?
