### ISSUE TITLE
WDA crashes when try to identify elements from the screen xcode9.2+iOS 11.2.1

### ISSUE THREAD

**Issue by nikolaynezdolii** [facebook/WebDriverAgent#907]
crash reproduced only on the one screen of the app
[Session-WebDriverAgentRunner-2018-04-05_191616-QTWaNB.log](https://github.com/facebook/WebDriverAgent/files/1880834/Session-WebDriverAgentRunner-2018-04-05_191616-QTWaNB.log)

**Comment by marekcirkos** [comment]
There is no crash message in the log?
