### ISSUE TITLE
homescreen request failed in iOS 11.3

### ISSUE THREAD

**Issue by suyuchen123** [facebook/WebDriverAgent#910]
I try use homescreen request with Xcode 9.2 and iOS 11.3, and will reply "NSLocalizedDescription=Timeout waiting until SpringBoard is visible" 

it seems dock item goes into “程序坞” in chinese lang system, 
any idea there is more general way of judge if success back to homescreen

**Comment by marekcirkos** [comment]
IT looks like we fail to validate that we made it to springboard (homescreen). Did it work when you look at device?

**Comment by ZhaoxuepingSwag** [comment]
have you solved the problem yet? I met this issue too.
