### ISSUE TITLE
Using appium 1.7.2 - crash in UITestingUITests/testRunner after executing findElement

### ISSUE THREAD

**Issue by githubdilip** [facebook/WebDriverAgent#911]
Using appium 1.7.2 for iOS native app automation. Once the script is executing findElement the test get fail with below error. Issue happens in once particular page alone: 

XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 30000 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/8AC2F43E-67B9-4DB4-B92B-CF7F4B70A757/element] with body: {"using":"xpath","value":"//XCUIElementTypeStaticText[contains(@label,'NativeAutomation_2018-04-10_14:50:45')]//following-sibling::XCUIElementTypeButton[1]"}
[XCUITest] Log file for xcodebuild test: /var/folders/b6/pljv07_x56j_8vvvs4xxmhs40000gr/T/com.apple.dt.XCTest/IDETestRunSession-C1B15F0A-585F-45DB-BB3D-BE793DA775CB/WebDriverAgentRunner-C7B3D7D6-0158-4133-8611-1EBFF77FD994/Session-WebDriverAgentRunner-2018-04-10_145503-bRLeFL.log
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[HTTP] <-- POST /wd/hub/session/2baa2f8c-98aa-4f62-bb9b-a9caa5efbfee/element 500 58243 ms - 164 
[Xcode]  0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   465.18s     Find the Button
[Xcode]     t =   465.18s         Snapshot accessibility hierarchy for com.xxxxxx.xxxx
[Xcode]     t =   465.95s         Find: Descendants matching type Button
[Xcode]     t =   465.96s         Find: Elements matching predicate 'wdUID IN {375} AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0)'
[Xcode]     t =   465.96s         Find: Element at index 0
[Xcode]     t =   466.07s     Find the "Cases" Button
[Xcode]     t =   466.07s         Snapshot accessibility hierarchy for com.xxxxxx.xxxx

[Xcode] 2018-04-10 14:54:54.139547+0530 XCTRunner[320:38834] Enqueue Failure: Failed to get snapshot within 15.0s /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-04-10 14:55:09.842139+0530 XCTRunner[329:41389] Running tests...
[Xcode] 2018-04-10 14:55:11.134706+0530 XCTRunner[329:41389] Continuing to run tests in the background with task ID 1
[Xcode] 
[Xcode] Restarting after unexpected exit or crash in UITestingUITests/testRunner; summary will include totals from previous launches.

**Comment by marekcirkos** [comment]
Did the app deadlock?

**Comment by DhivyaS19** [comment]
hi, am also getting this issue. Please find the logs,

Restarting after unexpected exit or crash in UITestingUITests/testSocketRunner; summary will include totals from previous launches.

Test Suite 'Selected tests' started at 2019-05-07 14:58:30.836
Test Suite 'WebDriverAgentRunner.xctest' started at 2019-05-07 14:58:30.836
Test Suite 'WebDriverAgentRunner.xctest' failed at 2019-05-07 14:58:30.837.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'WebDriverAgentLib.framework' started at 2019-05-07 14:58:30.837
Test Suite 'WebDriverAgentLib.framework' passed at 2019-05-07 14:58:30.838.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'Selected tests' failed at 2019-05-07 14:58:30.838.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.003) seconds

Please let me know if anyone have solution for this issue.
