### ISSUE TITLE
Could WebDriverAgent connect device via WiFi?

### ISSUE THREAD

**Issue by tianyig** [facebook/WebDriverAgent#926]
I noticed that Xcode9 and iOS10 support wireless debug,  when test wireless debug, all things fine, but when I run WebDriverAgent via wifi, it occurs error as blow:

20:18:39.827 WebDriverAgentRunner-Runner[554:18545] <XCTWaiter: 0x1c000e470, state: XCTWaiterStateSucceeded> cleaning up Transport for IDE session acquired
20:18:39.827 WebDriverAgentRunner-Runner[554:18545] Creating connection with transport <DTXFileDescriptorTransport: 0x1c00f1a80>
20:18:39.828 WebDriverAgentRunner-Runner[554:18545] Creating the proxy channel with connection <DTXConnection 0x1c41f8a00 : x1>
20:18:39.828 WebDriverAgentRunner-Runner[554:18545] Creating future for 'IDE session ready for test plan' with timeout 60.00
20:18:39.829 WebDriverAgentRunner-Runner[554:18545] Messaging IDE proxy - _XCT_testBundleReadyWithProtocolVersion:25 minimumVersion:8
20:18:39.829 WebDriverAgentRunner-Runner[554:18545] <XCTWaiter: 0x1c400e760, state: XCTWaiterStateInProgress> entering wait loop for 60.00s with expectations: (
    "IDE session ready for test plan"
)
20:18:57.946 WebDriverAgentRunner-Runner[554:18717] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply contained error: Error Domain=DTXProxyChannel Code=1 "(null)" UserInfo={DTXProxyChannelErrorMessage=Channel disconnected}
20:18:57.947 WebDriverAgentRunner-Runner[554:18717] <XCTWaiter: 0x1c400e760, state: XCTWaiterStateSucceeded>: cancelWaiting
20:18:57.948 WebDriverAgentRunner-Runner[554:18545] <XCTWaiter: 0x1c400e760, state: XCTWaiterStateSucceeded> done waiting
20:18:57.948 WebDriverAgentRunner-Runner[554:18545] <XCTWaiter: 0x1c400e760, state: XCTWaiterStateSucceeded> cleaning up IDE session ready for test plan
====================

**Comment by marekcirkos** [comment]
This is xcode related issue, sorry cannot help you here
