### ISSUE TITLE
Appium server does not take screenshot for 1 screen only i.e map integrated with list view

### ISSUE THREAD

**Issue by grpratap69** [facebook/WebDriverAgent#935]
<img width="876" alt="screen shot 2018-05-29 at 12 30 29 pm" src="https://user-images.githubusercontent.com/37795475/40646715-a36bcd2a-6347-11e8-9254-ab51dcc5b314.png">
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[HTTP] --> GET /wd/hub/session/7f1c8604-8524-452e-a1a2-24f6820f1767/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["7f1c8604-8524-452e-a1a2-24f6820f1767"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/BEA5520D-5658-4D15-BE50-7EE321DC1841/source] with no body

Logs for current screen starts from this line .... [XCUITest] Connection to WDA timed out....progress bar displayed all the time

**Comment by grpratap69** [comment]
Below are additional logs...



 t =  1004.17s Find the Application "com.mbrdi.travelbook.iOS.iPhone-ece-pDev" 0x1c3edf800
[Xcode]     t =  1004.17s     Snapshot accessibility hierarchy for app with pid 2687
[Xcode]     t =  1010.14s Snapshot accessibility hierarchy for app with pid 2687
[Xcode]     t =  1014.87s Snapshot accessibility hierarchy for app with pid 2687
[Xcode] 2018-05-29 14:01:24.538793+0530 WebDriverAgentRunner-Runner[2682:1838849] Enqueue Failure: Failure fetching attributes for element  pid: 2687, elementOrHash.elementID: 4840791120.67: Error Domain=XCTDaemonErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
[Xcode] 2018-05-29 14:01:24.540936+0530 WebDriverAgentRunner-Runner[2682:1838849] Failed to fetch hit point for StaticText, 0x1c4983670, traits: 8589934656, {{5.0, 70.0}, {370.0, 41.0}}, label: 'HERE SDK for iOS Evaluation Package expires on 2018/07/10' - *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]
[Xcode]     t =  1015.83s Snapshot accessibility hierarchy for app with pid 2687
[Xcode]     t =  1016.67s Snapshot accessibility hierarchy for app with pid 2687
[Xcode]     t =  1017.62s Snapshot ac

**Comment by marekcirkos** [comment]
Not WDA related
