### ISSUE TITLE
Getting -->Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".

### ISSUE THREAD

**Issue by ManjuAsthuthe** [facebook/WebDriverAgent#937]

**Comment by jacattau** [comment]
Are you resigning your .ipa file?  Have you followed the URL it gives you to sign the webdriveragent?

This typically means your .ipa file or your webdriveragent is not signed correctly.  You should follow the link it provides you (https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) and work that out.
