### ISSUE TITLE
browserName: null returned from current session capabilities when using Xcode 8

### ISSUE THREAD

**Issue by Dan-Maor** [facebook/WebDriverAgent#939]
Removing query & resolve from fb_activeApplication causes the label property of the application to not be resolved, and thus returns null instead of the application label when working with Xcode 8.

This may also affect other places in the code.

**Comment by mykola-mokhnach** [comment]
Xcode8 is not supported by Facebook WDA

**Comment by Dan-Maor** [comment]
I see, figured it was a WebDriverAgent related issue so I've opened it here.
Should I post this issue in the Appium repo?

**Comment by mykola-mokhnach** [comment]
Yes, it would be more useful

**Comment by mykola-mokhnach** [comment]
Or you can create a PR

**Comment by Dan-Maor** [comment]
OK, will do.
Closing this issue since it's not relevant for Facebook.
