### ISSUE TITLE
WebDriver agent is failing to build in real devices when the alert pop-up for updating IOS is present in the screen

### ISSUE THREAD

**Issue by ptsiakos77** [facebook/WebDriverAgent#940]
When a native alert is present on the screen (for example prompt for update IOS version) the WDA is failing to build with 65 error code. 
Is there any way to overcome this?
Due to this problem entire runs are skipped when an new IOS version is available.

**Comment by mykola-mokhnach** [comment]
We were asking Apple guys about how to workaround such problem during WWDC session and they have no solution for this. So, in order to prevent update alerts we just put the test phones into a separate network where IP addresses of Apple update servers are blocked on the router level }:-)

**Comment by ptsiakos77** [comment]
Thanks a lot mykola, 
actually we are proceeding with this solution,
I was just thinking it there was an alternative way to do this

**Comment by marekcirkos** [comment]
You could also try to provision device and prohibit system updates  :)
