### ISSUE TITLE
java.io.IOException: unexpected end of stream 

### ISSUE THREAD

**Issue by derunewige** [facebook/WebDriverAgent#942]
Occasionally appium tests fail with 

`org.openqa.selenium.WebDriverException: java.io.IOException: unexpected end of stream on okhttp3.Address@e4e50464 `

when executing javascript for scrolling

```
JavascriptExecutor js = this.appiumDriver;

Map<String, Object> params = new HashMap<>();
params.put("element", targetElement.getId());
params.put("toVisible", "true");
if (searchStrategy.equals(ScrollSearchStrategy.UP)) {
	params.put("direction", "up");
}

js.executeScript("mobile: scroll", params);
```

Appium v1.8.1
java-client 6.0.0
iOS 11.4 iPhone 8
iOS 11.4 iPhone 6s+
iOS 10.3.3 iPhone 5c

Edit:
In one specific case I have a page where I try to scroll to the bottom of the page to find an element. The element is found in the dom tree with visibility false. I call the mobile:scroll command to scroll to that element. It actually scrolls to the bottom of the page. In the dom tree the visibilty changes to true.
BUT the command keeps scrolling, won't stop and blocks the execution of the following code. 

In the server logs I see the error code
`2018-06-13 09:07:58:325 - [debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Failed to perform scroll with visible cell due to max scroll count reached\" UserInfo={NSLocalizedDescription=Failed to perform scroll with visible cell due to max scroll count reached}","sessionId":"6BC5CFD4-F309-409E-BF39-C153E0485E66","status":13}`

but in the IDE I get the error 
`Caused by: org.openqa.selenium.WebDriverException: java.io.IOException: unexpected end of stream on okhttp3.Address@f39847cb`

So actually, could there be two different errors? 
One, that it keeps scrolling though the element is visible.
Second, the "max scroll count reached" error is not handled right and causes the "unexpected end of stream"  error?

server logs: [gist](https://gist.github.com/derunewige/dac29129de8d6cd95135826c1665e3d6)

I am searching for the textfield with the string "PLZ" in it

![scrollingerror](https://user-images.githubusercontent.com/6079062/41344997-c240e43a-6f02-11e8-8022-b6767a667bb2.gif)

**Comment by derunewige** [comment]
After the update to appium java client 6.1.0 it tries to scroll to the element. fails with max scroll count reached but does not throw the end of stream exception anymore
Further it makes an retry and then finds the element immediately without any scrolling. 
So actually the test does not fail anymore, but is very very slow because of the 25 tries to scroll to the element.  

btw - is there any way to set the max scroll count to a custom value?

**Comment by marekcirkos** [comment]
It is Appium related issue, not WDA.
