### ISSUE TITLE
Opening View Controller is extremely slow on Appium

### ISSUE THREAD

**Issue by randhirkumarcse** [facebook/WebDriverAgent#944]
In my app, instantiating and pushing view controller is extremely slow means it's taking 5+ minutes. Tested on simulator only.

**Environment**
Appium version (or git revision) that exhibits the issue: 1.8.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: 10.13.4
Node.js version (unless using Appium.app|exe): v8.11.2
Mobile platform/version under test: iOS 11.3
Real device or emulator/simulator: Simulator iPhone 6
Appium CLI or Appium.app|exe: Appium.app

**Capabilities:**
"platformName": "iOS", "platformVersion": "11.3", "deviceName": "iPhone 6", "automationName": "XCUITest", "app": "/Users/xxx/Documents/Downloads/iOSApp.app", "autoAcceptAlerts": true, "autoDismissAlerts": true, "autoGrantPermissions": true, "databaseEnabled": true

Code To Reproduce Issue [ Good To Have ]
```
@IBAction fileprivate func locationButtonTapped(_ sender: UIButton)
    {
        if (mSelectLocationVC == nil)
        {
            mSelectLocationVC = self.storyboard?.instantiateViewController(withIdentifier: "SelectLocationViewController") as? SelectLocationViewController
            mSelectLocationVC?.delegate = self
        }         self.navigationController?.pushViewController(mSelectLocationVC!, animated: true)
}
```

Few more details for SelectLocationViewController are:
Settings elements in viewDidLoad and database call in viewWillAppear. 
There is no API/server call.

**Comment by marekcirkos** [comment]
WDA does not run as part of your  app so I am not sure how would it influence your app?
