### ISSUE TITLE
It's too slow to swipe/scroll up on a video

### ISSUE THREAD

**Issue by Chenneyfang** [facebook/WebDriverAgent#953]
model:iPhone 7,
os: iOS 7,

My app is full of one videos ,and  every one video is full of the screen. Users Can swipe/scroll every video up,and then you will see the next video. But I use webdriveragent,it harldly swipe/scroll up.

**Comment by wsndy163** [comment]
https://github.com/wsndy163/WebDriverAgent
修复swipe引起的卡顿问题
