### ISSUE TITLE
dyld fatal error

### ISSUE THREAD

**Issue by sapieneptus** [facebook/WebDriverAgent#96]
Running `UITestingUITests`, iPhone6, iOS 9.2, Xcode 7.2

"Stub Apps" appears to install but then immediately crashes with `dyld_fatal_error` : 

```
dyld: could not load inserted library '/private/var/mobile/Containers/Data/Application/B8DD9504-DE4C-4418-8D5E-3B492DDCA07E/tmp/IDEBundleInjection.framework/IDEBundleInjection' because no suitable image found.  Did find:
	/private/var/mobile/Containers/Data/Application/B8DD9504-DE4C-4418-8D5E-3B492DDCA07E/tmp/IDEBundleInjection.framework/IDEBundleInjection: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Data/Application/B8DD9504-DE4C-4418-8D5E-3B492DDCA07E/tmp/IDEBundleInjection.framework/IDEBundleInjection'
```

The same setup works with Xcode 7.3 Beta (the version released two days ago). By that I mean, the app will at least launch and the server will start / be able to receive commands.

**Comment by marekcirkos** [comment]
Wow! First time I see this. Did you run it via xcodebuild or Xcode?

**Comment by sapieneptus** [comment]
This was via Xcode. I can try via `xcodebuild` instead.

**Comment by marekcirkos** [comment]
Running with Xcode is better ;).
I created PR (https://github.com/facebook/WebDriverAgent/pull/98), that recreates XCTUITestRunner as proper XCUITest target and switched all XCT targets to iOS 9.2. Please check it out and tell me if it helps.

**Comment by marekcirkos** [comment]
Btw keep in mind that screen will not turn blue, but stay black or switch to dashboard. So check logs :)

**Comment by sapieneptus** [comment]
Well, with that branch, I no longer get the `dyld` issue :) App still doesn't make it past the launch screen, but I'll pick this up in #97 .
