### ISSUE TITLE
    " driver.navigate().to(scheme)"  not work in real device（iOS）

### ISSUE THREAD

**Issue by ghsy0519** [facebook/WebDriverAgent#963]
driver.navigate().to(scheme); this method work in simulator .but not work  in real device ,I try click webdriveragent app in my iphone (webdriveragent foreground) before this method run ,then it will be work .but default case is webDriverAgentRunner-Runner run tests in the background. so how can i slove this problem

**Comment by ghsy0519** [comment]
somebody can help me?

**Comment by marekcirkos** [comment]
Not WDA related
