### ISSUE TITLE
WDA pops error in Xcode Version 10.0 beta 4 (10L213o)

### ISSUE THREAD

**Issue by xiaoyaoamiao** [facebook/WebDriverAgent#968]
Ld /Users/miaog001/Library/Developer/Xcode/DerivedData/WebDriverAgent-drvvqzbpgvdnqmelknazwmmdefay/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/WebDriverAgentLib normal x86_64 (in target: WebDriverAgentLib)
    cd /Users/miaog001/Desktop/WebDriverAgent
    export IPHONEOS_DEPLOYMENT_TARGET=9.3
    /Users/miaog001/Downloads/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Users/miaog001/Downloads/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk -L/Users/miaog001/Library/Developer/Xcode/DerivedData/WebDriverAgent-drvvqzbpgvdnqmelknazwmmdefay/Build/Products/Debug-iphonesimulator -F/Users/miaog001/Library/Developer/Xcode/DerivedData/WebDriverAgent-drvvqzbpgvdnqmelknazwmmdefay/Build/Products/Debug-iphonesimulator -F/Users/miaog001/Downloads/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -F/Users/miaog001/Desktop/WebDriverAgent/Carthage/Build/iOS -F/Users/miaog001/Desktop/WebDriverAgent/Carthage/Build/Mac -filelist /Users/miaog001/Library/Developer/Xcode/DerivedData/WebDriverAgent-drvvqzbpgvdnqmelknazwmmdefay/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/x86_64/WebDriverAgentLib.LinkFileList -install_name @rpath/WebDriverAgentLib.framework/WebDriverAgentLib -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mios-simulator-version-min=9.3 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/miaog001/Library/Developer/Xcode/DerivedData/WebDriverAgent-drvvqzbpgvdnqmelknazwmmdefay/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/x86_64/WebDriverAgentLib_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -lxml2 -framework RoutingHTTPServer -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/miaog001/Library/Developer/Xcode/DerivedData/WebDriverAgent-drvvqzbpgvdnqmelknazwmmdefay/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/x86_64/WebDriverAgentLib_dependency_info.dat -o /Users/miaog001/Library/Developer/Xcode/DerivedData/WebDriverAgent-drvvqzbpgvdnqmelknazwmmdefay/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/WebDriverAgentLib

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_XCElementSnapshot", referenced from:
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBIsVisible in XCUIElement+FBIsVisible.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBUID in XCUIElement+FBUID.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_WebDriverAttributes in XCUIElement+FBWebDriverAttributes.o
      objc-class-ref in XCUIElement+FBWebDriverAttributes.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBAccessibility in XCUIElement+FBAccessibility.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBScrolling in XCUIElement+FBScrolling.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBHitPoint in XCElementSnapshot+FBHitPoint.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is there have solution to resolve it? 
Thank you very much.

**Comment by Dan-Maor** [comment]
From what I can see it's still in XCTAutomationSupport framework. It happened with XCDeviceEvent when Xcode 9 came out, even though it's still in the framework as well.

An ugly workaround can be just to ignore it in linking time (tested) by adding the following to the linker flags:
-Wl,-U,"_OBJC_CLASS_$_XCElementSnapshot"

Not bitcode compatible, ugly, but it works.

**Comment by mykola-mokhnach** [comment]
yep, I can observe it in XCTest headers dump, that XCElementSnapshot class is still used, however is not exposed anywhere. Only some extensions of it are visible though

**Comment by DanMPerfecto** [comment]
Still relevant for Beta 5.

**Comment by Dan-Maor** [comment]
Still relevant for Beta 5.

**Comment by rjaros87** [comment]
@Dan-Maor where I could add above flags? I try to add to `Other Linker Flags` but it throws the same error as above.
I'm using Xcode 10 beta5.

**Comment by Dan-Maor** [comment]
@rjaros87 
Technically it's a single entry, make sure to copy it as it is (with the commas).
Also - try cleaning the project first.

**Comment by rjaros87** [comment]
```
2018-07-31 10:58:20:627 - [Xcode] Undefined symbols for architecture arm64:
2018-07-31 10:58:20:627 - [Xcode]   "_OBJC_CLASS_$_XCElementSnapshot", referenced from:
2018-07-31 10:58:20:627 - [Xcode] 
2018-07-31 10:58:20:628 - [Xcode]       l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBIsVisible in XCUIElement+FBIsVisible.o
2018-07-31 10:58:20:628 - [Xcode]       l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBUID in XCUIElement+FBUID.o
2018-07-31 10:58:20:628 - [Xcode]       l_OBJC_$_CATEGORY_XCElementSnapshot_$_WebDriverAttributes in XCUIElement+FBWebDriverAttributes.o
2018-07-31 10:58:20:628 - [Xcode]       l_OBJC_CLASSLIST_REFERENCES_$_ in XCUIElement+FBWebDriverAttributes.o
2018-07-31 10:58:20:628 - [Xcode] 
2018-07-31 10:58:20:629 - [Xcode]       l_OBJC_CLASSLIST_REFERENCES_$_.71 in XCUIElement+FBUtilities.o
2018-07-31 10:58:20:629 - [Xcode]       l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBAccessibility in XCUIElement+FBAccessibility.o
2018-07-31 10:58:20:629 - [Xcode]       l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBScrolling in XCUIElement+FBScrolling.o
2018-07-31 10:58:20:629 - [Xcode]       ...
2018-07-31 10:58:20:630 - [Xcode] 
2018-07-31 10:58:20:630 - [Xcode] ld: symbol(s) not found for architecture arm64
2018-07-31 10:58:20:630 - [Xcode] 
2018-07-31 10:58:20:633 - [Xcode] clang: error: 
2018-07-31 10:58:20:635 - [Xcode] 
2018-07-31 10:58:20:635 - [Xcode] linker command failed with exit code 1 (use -v to see invocation)
```
I'm using Xcode 10 beta 5.
Works with flags: `-Wl,-U,"_OBJC_CLASS_$_XCElementSnapshot"`

**Comment by Dan-Maor** [comment]
Oops, that's what I thought I've written, Github changed the first '_' to italic.

**Comment by huowenxuan** [comment]
@rjaros87 go to File->Project Setting，change the build system to Legacy Build System. Then add to Other Linker Flags...

**Comment by marekcirkos** [comment]
https://github.com/facebook/WebDriverAgent/commit/c4da863b9c8d6d076ba74bf1ff58b47ef56dd2fa
