### ISSUE TITLE
iphoneX appium1.8.1 webdriveragent启动抛异常Early unexpected exit, operation never finished bootstrapping - no restart will be attempted

### ISSUE THREAD

**Issue by linyan0321** [facebook/WebDriverAgent#981]
webdriver启动的命令如下
xcodebuild -project /Users/linyan/tool_ly/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=94535e0c4eeb7f1ebf00c53116a1e211ca3cf117' test

iphoneX ：ios11.4   appium：1.8.1
启动一直抛错误：Early unexpected exit, operation never finished bootstrapping - no restart will be attempted
重启电脑并且插拔一下手机的USB就有可能会好，执行几次之后又会继续出现

log：：：：
2018-08-23 19:34:05.218 xcodebuild[5197:491729]  DTDeviceKit: deviceType from 94535e0c4eeb7f1ebf00c53116a1e211ca3cf117 was NULL
2018-08-23 19:34:05.252 xcodebuild[5197:491730]  DTDeviceKit: deviceType from 94535e0c4eeb7f1ebf00c53116a1e211ca3cf117 was NULL
2018-08-23 19:34:05.364 xcodebuild[5197:491729]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/38/d6j_4rt56kqbsrj8p3tb1njh0000gn/T/com.apple.dt.XCTest/IDETestRunSession-E412E00B-2533-4540-890D-51655F129AD2/WebDriverAgentRunner-16BFD976-B080-4E93-A3A0-BA3B75823DFD/Session-WebDriverAgentRunner-2018-08-23_193405-DzRBM1.log
2018-08-23 19:34:05.365 xcodebuild[5197:491682] [MT] IDETestOperationsObserverDebug: (CA35E25C-5591-45A6-9F82-0B8AA4AE6357) Beginning test session WebDriverAgentRunner-CA35E25C-5591-45A6-9F82-0B8AA4AE6357 at 2018-08-23 19:34:05.365 with Xcode 9F2000 on target <DVTiOSDevice: 0x7f861b423aa0> {
		deviceSerialNumber:         DNQVN05GJCLF
		identifier:                 94535e0c4eeb7f1ebf00c53116a1e211ca3cf117
		deviceClass:                iPhone
		deviceName:                 iphone x
		deviceIdentifier:           94535e0c4eeb7f1ebf00c53116a1e211ca3cf117
		productVersion:             11.4.1
		buildVersion:               15G77
		deviceSoftwareVersion:      11.4.1 (15G77)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        60271497216
		deviceAvailableCapacity:    52132139008
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f861aeb3560 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		connected:                 yes
		isWirelessEnabled:         no
		connectionType:            direct
		} (11.4.1 (15G77))
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/38/d6j_4rt56kqbsrj8p3tb1njh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/976a18e3b6ced48ad255314c202e6514/94535e0c4eeb7f1ebf00c53116a1e211ca3cf117/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/linyan/Library/Developer/Xcode/DerivedData/WebDriverAgent-dgwmvnuvojrimgbmkjvembfewogn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/38/d6j_4rt56kqbsrj8p3tb1njh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.y7j0EI/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/38/d6j_4rt56kqbsrj8p3tb1njh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.y7j0EI/WebDriverAgentRunner-Runner.app_sparse.ipa
MDMDirectoryDiff_block_invoke:1473 calling writeDictToFile with: /var/folders/38/d6j_4rt56kqbsrj8p3tb1njh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.y7j0EI/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/38/d6j_4rt56kqbsrj8p3tb1njh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.y7j0EI/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
2018-08-23 19:34:08.989434+0800 WebDriverAgentRunner-Runner[12971:1250836] +[CATransaction synchronize] called within transaction
2018-08-23 19:34:09.015196+0800 WebDriverAgentRunner-Runner[12971:1250836] Running tests...
Dumping buffered debug messages:
====================
19:34:09.018 WebDriverAgentRunner-Runner[12971:1250836] Linked XCTest.framework from /var/containers/Bundle/Application/120B352F-6CA5-42DB-BBFF-1BD346A09380/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest, built with Xcode 0940(9F1027a), modified on 2018年8月18日 星期六 中国标准时间 上午10:13:52
XCTest.framework bundle version: 14100
19:34:09.019 WebDriverAgentRunner-Runner[12971:1250836] System uptime: 2天 4:36:31
19:34:09.019 WebDriverAgentRunner-Runner[12971:1250836] Process arguments: (
    "/var/containers/Bundle/Application/120B352F-6CA5-42DB-BBFF-1BD346A09380/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner",
    "-NSTreatUnknownArgumentsAsOpen",
    NO,
    "-ApplePersistenceIgnoreState",
    YES
)
19:34:09.020 WebDriverAgentRunner-Runner[12971:1250836] Process environment: {
    "CFFIXED_USER_HOME" = "/private/var/mobile/Containers/Data/Application/4C46ACAE-0AC0-4CB8-BF92-4E726934CCE5";
    CLASSIC = 1;
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/120B352F-6CA5-42DB-BBFF-1BD346A09380/WebDriverAgentRunner-Runner.app/Frameworks:/Users/linyan/Library/Developer/Xcode/DerivedData/WebDriverAgent-dgwmvnuvojrimgbmkjvembfewogn/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks:/Developer/Library/PrivateFrameworks";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/120B352F-6CA5-42DB-BBFF-1BD346A09380/WebDriverAgentRunner-Runner.app/Frameworks:/Users/linyan/Library/Developer/Xcode/DerivedData/WebDriverAgent-dgwmvnuvojrimgbmkjvembfewogn/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks:/Developer/Library/PrivateFrameworks";
    HOME = "/private/var/mobile/Containers/Data/Application/4C46ACAE-0AC0-4CB8-BF92-4E726934CCE5";
    LOGNAME = mobile;
    "MTC_CRASH_ON_REPORT" = 1;
    NSUnbufferedIO = YES;
    "OS_ACTIVITY_DT_MODE" = YES;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin";
    SHELL = "/bin/sh";
    "SQLITE_ENABLE_THREAD_ASSERTIONS" = 1;
    TMPDIR = "/private/var/mobile/Containers/Data/Application/4C46ACAE-0AC0-4CB8-BF92-4E726934CCE5/tmp/";
    USER = mobile;
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/4C46ACAE-0AC0-4CB8-BF92-4E726934CCE5/tmp/WebDriverAgentRunner-CA35E25C-5591-45A6-9F82-0B8AA4AE6357.xctestconfiguration";
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0x10ca][69]";
    "__CF_USER_TEXT_ENCODING" = "0x1F5:0:0";
}
19:34:09.020 WebDriverAgentRunner-Runner[12971:1250836] App Sandbox active: YES
19:34:09.020 WebDriverAgentRunner-Runner[12971:1250836] Loading test bundle at: file:///private/var/containers/Bundle/Application/120B352F-6CA5-42DB-BBFF-1BD346A09380/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
19:34:09.033 WebDriverAgentRunner-Runner[12971:1250836] Finished loading test bundle
19:34:09.033 WebDriverAgentRunner-Runner[12971:1250836] Readying IDE session
19:34:09.034 WebDriverAgentRunner-Runner[12971:1250836] Creating future for 'Exchange protocol versions with daemon' with timeout 15.00
19:34:09.035 WebDriverAgentRunner-Runner[12971:1250836] <XCTWaiter: 0x1d401bf20, state: XCTWaiterStateInProgress> entering wait loop for 15.00s with expectations: (
    "Exchange protocol versions with daemon"
)
19:34:09.036 WebDriverAgentRunner-Runner[12971:1250836] <XCTWaiter: 0x1d401bf20, state: XCTWaiterStateSucceeded> done waiting
19:34:09.036 WebDriverAgentRunner-Runner[12971:1250862] <XCTWaiter: 0x1d401bf20, state: XCTWaiterStateSucceeded>: cancelWaiting
19:34:09.036 WebDriverAgentRunner-Runner[12971:1250836] <XCTWaiter: 0x1d401bf20, state: XCTWaiterStateSucceeded> cleaning up Exchange protocol versions with daemon
19:34:09.037 WebDriverAgentRunner-Runner[12971:1250836] Got daemon protocol version 22
19:34:09.037 WebDriverAgentRunner-Runner[12971:1250836] Requesting IDE connection transport
19:34:09.037 WebDriverAgentRunner-Runner[12971:1250836] <XCTWaiter: 0x1d0019320, state: XCTWaiterStateInProgress> entering wait loop for 60.00s with expectations: (
    "Transport for IDE session acquired"
)
19:35:09.038 WebDriverAgentRunner-Runner[12971:1250836] <XCTWaiter: 0x1d0019320, state: XCTWaiterStateInProgress> done waiting
19:35:09.039 WebDriverAgentRunner-Runner[12971:1250836] <XCTWaiter: 0x1d0019320, state: XCTWaiterStateFailed> reporting timed out failure with Transport for IDE session acquired
19:35:09.039 WebDriverAgentRunner-Runner[12971:1250836] <XCTWaiter: 0x1d0019320, state: XCTWaiterStateFailed> cleaning up Transport for IDE session acquired
====================
2018-08-23 19:35:09.051 xcodebuild[5197:491682] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Early unexpected exit, operation never finished bootstrapping - no restart will be attempted

**Comment by marekcirkos** [comment]
This is Xcode issue on starting XCTest. Nothing WDA specific, sorry :/
