### ISSUE TITLE
iOS 12 beta 9, Xcode 10.0 beta 6 Unable to build the WebdriverAgent getting error -  linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by chandanijain9** [facebook/WebDriverAgent#985]
Getting this error while building 
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_XCElementSnapshot", referenced from:
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBIsVisible in XCUIElement+FBIsVisible.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBUID in XCUIElement+FBUID.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_WebDriverAttributes in XCUIElement+FBWebDriverAttributes.o
      objc-class-ref in XCUIElement+FBWebDriverAttributes.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBAccessibility in XCUIElement+FBAccessibility.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBScrolling in XCUIElement+FBScrolling.o
      l_OBJC_$_CATEGORY_XCElementSnapshot_$_FBHitPoint in XCElementSnapshot+FBHitPoint.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by marekcirkos** [comment]
That should be resolved. Did you try master?

**Comment by chandanijain9** [comment]
Tried with master.It is working ..
Thanks @marekcirkos
