### ISSUE TITLE
What about using private api to find elements and operate elements?

### ISSUE THREAD

**Issue by Chenneyfang** [facebook/WebDriverAgent#988]
I know that, the private api can operate elements ,and it can be use to find elements, why not using it ?
In some case ,it may be  fastest than private api. For example,it hardly to scorll the feed page of the  app named TikTok, but  i use the private api  named "- (double)pressAtPoint:(CGPoint)arg1 forDuration:(double)arg2 liftAtPoint:(CGPoint)arg3 velocity:(double)arg4 orientation:(UIInterfaceOrientation)arg5 name:(NSString *)arg6 handler:(XCEventGeneratorHandler)arg7" to scroll  TikTok, it seems to be very fast.

**Comment by Chenneyfang** [comment]
Now, i try to use private api to find elements, something wrong happened. When i use the command "application.lastSnapshot" to get the snaps of the app, it seems to give back some elements, not all the elements. In Debug model, i use the command "po application", it print all the elements. And the i use "application.lastSnapshot" , all the elements will be printed.
I am interested in the way of using private api to find elements, who can help me ?

**Comment by marekcirkos** [comment]
We already use private API you mentioned :)
