### ISSUE TITLE
iPhoneXs_ios12.0 doesn’t support any of WebDriverAgentLib.framework’s architectures. You can add iPhoneXs_ios12.0’s arm64e architecture to WebDriverAgentLib.framework’s Architectures build setting.

### ISSUE THREAD

**Issue by yuzhidi** [facebook/WebDriverAgent#994]
iPhoneXs_ios12.0 doesn’t support any of WebDriverAgentLib.framework’s architectures. You can add iPhoneXs_ios12.0’s arm64e architecture to WebDriverAgentLib.framework’s Architectures build setting.

Xcode Version 9.3 (9E145)

how can I fix this issue?
![iphonexs_ios12 0_is_not_valid_for_testing](https://user-images.githubusercontent.com/6584807/45874674-11877900-bdc8-11e8-8ead-ea23629220aa.png)
![wda_project_config](https://user-images.githubusercontent.com/6584807/45874722-324fce80-bdc8-11e8-8510-74c329e901a1.png)

**Comment by fr0l** [comment]
Are you using Xcode 10 ? ( I can not reproduce the issue)
